function m(b,a,c,d){b.l.pb(b.tb,a,c,d)}function n(b,a,c,d){b.l.da?m(b,a,c,d):b.l.Re()._OnMessageFromDOM({type:"event",component:b.tb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.l.B(b.tb,a,c)}function v(b,a){for(const [c,d]of a)p(b,c,d)}function w(b){b.Wb||(b.l.zc(b.he),b.Wb=!0)}window.Ca=class{constructor(b,a){this.l=b;this.tb=a;this.Wb=!1;this.he=()=>this.Sa()}nd(){}Sa(){}};
window.Ef=class{constructor(){this.jd=-1}j(){-1!==this.jd&&(self.clearTimeout(this.jd),this.jd=-1)}};"use strict";function aa(b,a){p(b,"get-element",c=>{const d=x(b,c.elementId);return a(d,c)})}function x(b,a){b=b.Xa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Ub}
window.rd=class extends self.Ca{constructor(b,a){super(b,a);this.Xa=new Map;this.rb=!0;v(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=x(this,c);this.rb&&d.parentElement.removeChild(d);this.Xa.delete(c)}],["set-visible",c=>{if(this.rb){var d=this.Xa.get(c.elementId),e=d.Ub;d.Rd?e.style.display=c.isVisible?"":"none":d.kf=!!c.isVisible}}],["update-position",c=>{if(this.rb){var d=this.Xa.get(c.elementId),e=d.Ub,f=this.l;e.style.left=c.left+"px";e.style.top=
c.top+"px";e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.qf=g;g=f.td(g);g!==d.Ia&&(e.remove(),f.sc(g).appendChild(e),d.Ia=g,f.Lc());c=c.htmlZIndex;c!==d.Tc&&(d.Tc=c,f.Lc());d.Rd||(d.Rd=!0,d.kf&&(e.style.display=""))}}],["update-state",c=>{x(this,c.elementId);throw Error("required override");}],["focus",c=>this.Ic(c)],["set-css-style",c=>{const d=x(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,
c):d.style[e]=c}],["set-attribute",c=>{x(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{x(this,c.elementId).removeAttribute(c.name)}]]);aa(this,c=>c)}Ic(b){var a=x(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const ba=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent);let ca=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.uf?new Promise(c=>{const d="c3_resolve_"+ca;++ca;self[d]=c;a.textContent=b.yf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function da(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let B=new Audio;
const ea={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function fa(b){b=await ha(b);return(new TextDecoder("utf-8")).decode(b)}
function ha(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const D=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,H=new Map;let ia=0;const ja=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ja.push(b)};const ka=new Set(["cordova","playable-ad","instant-games"]);let la=!1;
window.pa=class b{constructor(a){this.da=a.Af;this.ya=null;this.aa="";this.fb=a.xf;this.Jb={};this.Za=this.va=null;this.Wa=[];this.ma=null;this.Vd=!0;this.M=[];this.cd=[];this.dd=!1;this.ie=()=>this.Pe();this.Vc=!1;this.Od=0;this.yb=null;this.eb=-1;this.pf=()=>this.$e();this.Gb=new Set;this.kd=null;this.je=[];this.u=a.ke;this.Xb="file"===location.protocol.substr(0,4);if("playable-ad"===this.u||"instant-games"===this.u)this.da=!1;if("cordova"===this.u&&this.da&&y){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.da=!1)}this.oa()?self.chrome.webview.addEventListener("message",c=>this.Ed(c.data)):"macos-wkwebview"===this.u&&(self.C3WrapperOnMessage=c=>this.Ed(c));this.$b=this.sa=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.df(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Ve());this.B("runtime","cordova-fetch-local-file",c=>this.We(c));this.B("runtime","create-job-worker",()=>this.Xe());this.B("runtime","send-wrapper-extension-message",c=>this.cf(c));"cordova"===this.u?document.addEventListener("deviceready",()=>this.Cd(a)):this.Cd(a)}j(){this.Ac();this.ya&&(this.ya=this.ya.onmessage=null);this.va&&(this.va.terminate(),this.va=null);this.Za&&(this.Za.j(),this.Za=null);for(const {canvas:a,
ib:c}of this.M)a.remove(),c.remove();this.M.length=0}ud(){return this.M[0].canvas}td(a){return Math.min(a,this.M.length-1)}sc(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].ib}Fe(){return ba&&"cordova"===this.u}nb(){const a=navigator.userAgent;return ba&&ka.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}De(){return y}vd(){return y&&ka.has(this.u)}xd(){return"windows-webview2"===this.u||!!("preview"===this.u&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}oa(){return this.xd()||"xbox-uwp-webview2"===this.u}async Cd(a){this.da&&!await da()&&(this.da=!1);"macos-wkwebview"===this.u?this.Ga({type:"ready"}):this.oa()&&(this.ff(),this.je=(await this.Ue()).registeredComponentIds);if("playable-ad"===this.u){this.sa=self.c3_base64files;this.$b={};await this.Me();for(let d=0,e=a.hb.length;d<e;++d){var c=a.hb[d];this.$b.hasOwnProperty(c)?a.hb[d]={uf:!0,yf:this.$b[c]}:this.sa.hasOwnProperty(c)&&(a.hb[d]=URL.createObjectURL(this.sa[c]))}a.oc=
[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.zc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.wf?this.aa=a.wf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Cf&&(this.Jb=a.Cf);c=new MessageChannel;this.ya=c.port1;this.ya.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ze(d));this.yb=
new self.Ge(this);await oa(this.yb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.da?await this.Te(a,c.port2):await this.Se(a,c.port2)}Cc(a){a=this.Jb.hasOwnProperty(a)?this.Jb[a]:a.endsWith("/workermain.js")&&this.Jb.hasOwnProperty("workermain.js")?this.Jb["workermain.js"]:"playable-ad"===
this.u&&this.sa.hasOwnProperty(a)?this.sa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async qc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.Xb)return a=await this.Kb(d.tf?a:this.fb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}qa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}Bd(a){var c=this.aa,d=location.href,e=this.qa(),f=this.ga(),g=window.devicePixelRatio,h=b.mb(),k=a.If,l=window.cr_previewImageBlobs||this.sa,q=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,t=window.cr_swClientId||"";a=a.ke;var u=(new URLSearchParams(self.location.search)).has("debug"),A=this.yb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:q,previewProjectFileSWUrls:r,swClientId:t,exportType:a,isDebug:u,ife:!!self.Hf,jobScheduler:{inputPort:A.Uc,outputPort:A.bd,maxNumWorkers:A.lf},supportedAudioFormats:ea,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.fb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.fb+"opus.wasm.wasm",isFileProtocol:this.Xb,isiOSCordova:this.Fe(),isiOSWebView:this.nb(),isWindowsWebView2:this.xd(),isAnyWebView2Wrapper:this.oa(),wrapperComponentIds:this.je,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Te(a,c){const d=this.Cc(a.Bf);"preview"===this.u?(this.va=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,q)=>{const r=t=>{this.va.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():q()};this.va.addEventListener("message",r);this.va.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.va=await this.qc(d,this.aa,{type:"module",name:"Runtime",tf:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,ib:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.oc||[],k=a.hb;h=await Promise.all(h.map(l=>this.Ta(l)));k=await Promise.all(k.map(l=>this.Ta(l)));if("cordova"===this.u)for(let l=0,q=a.nc.length;l<q;++l){const r=
a.nc[l],t=r[0];if(t===a.ld||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Ta(t)}this.va.postMessage(Object.assign(this.Bd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.nc,mainProjectScript:a.ld,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...qa(this.yb)]);this.Wa=F.map(l=>new l(this));this.Ad();ra(e);sa(g);ta(this.ma);self.c3_callFunction=(l,q)=>{var r=this.ma;return r.l.yd(r.tb,"js-invoke-function",
{name:l,params:q})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.pb("runtime","go-to-last-error-script"))}async Se(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,ib:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Wa=F.map(h=>new h(this));this.Ad();ra(d);sa(e);e=a.hb.map(h=>"string"===
typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.oc)){var f=[...a.oc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Ta(h)));await Promise.all(e.map(h=>z(h)));e=self.C3_ProjectScriptsStatus;f=a.ld;const g=a.nc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Ta(k),await z(k),"preview"!==this.u||e[h]||this.Gd(h,"main script did not run to completion")}catch(l){this.Gd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Ta(k),await z(k);"preview"===this.u&&"object"!==typeof self.Df.Ff?(this.Pb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Bd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:ja}),ta(this.ma),this.Dd(),this.Za=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Za,
a))}Gd(a,c){this.Pb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Dd(){this.Pb()}Pb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Xe(){const a=await ua(this.yb);return{outputPort:a,transferables:[a]}}df(a){if(!this.Vc){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,ib:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Vd&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Vd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,ib:q}=this.M.pop();q.remove();this.da&&!d?this.cd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,q=c-this.M.length;l<q;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.da?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,ra(c),sa(d),this.M.push({canvas:c,ib:d});for(const l of this.Wa)if(l instanceof window.rd&&l.rb)for(const q of l.Xa.values())e=l.l.td(q.qf),f=q.Ia,-1!==e&&-1!==f&&e!==f&&(f=q.Ub,f.remove(),l.l.sc(e).appendChild(f),q.Ia=e);this.Lc();return{addedCanvases:a,transferables:k}}Ve(){for(const a of this.cd)a.remove();this.cd.length=0}Lc(){this.dd||(this.dd=!0,this.zc(this.ie))}Pe(){this.Fd(this.ie);
this.dd=!1;let a=[];for(var c of this.Wa)if(c instanceof window.rd){var d=c.rb?[...c.Xa.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.Ia,l=h.Ia;return k!==l?k-l:g.Tc-h.Tc});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.Ia!==c&&(this.zd(c,a.slice(d,e)),c=g.Ia,d=e)}d<e&&this.zd(c,a.slice(d,e))}zd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Ub);var d=new Set(c);a=this.sc(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Re(){if(this.da)throw Error("not available in worker mode");return this.Za}pb(a,c,d,e,f){this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}yd(a,c,d,e,f){const g=ia++,h=new Promise((k,l)=>{H.set(g,{resolve:k,reject:l})});this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.Ye(a);if("result"===c)this.af(a);else if("runtime-ready"===c)this.bf();else if("alert-error"===c)this.Pb(),alert(a.message);else if("creating-runtime"===c)this.Dd();else throw Error(`unknown message '${c}'`);}Ye(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Ob(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Ob(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Ob(f,!1,""+h)}):this.Ob(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Ob(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.ya.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}af(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}B(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));
if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Pa(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}Ad(){for(const a of this.Wa)if("runtime"===a.tb){this.ma=a;return}throw Error("cannot find runtime DOM handler");}Ze(a){this.pb("debugger","message",a)}bf(){for(const a of this.Wa)a.nd()}static mb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||la)}static Qb(a){la=!!a}zc(a){this.Gb.add(a);
this.Kc()}Fd(a){this.Gb.delete(a);0===this.Gb.size&&this.Ac()}Kc(){-1===this.eb&&0<this.Gb.size&&(this.eb=requestAnimationFrame(this.pf))}Ac(){-1!==this.eb&&(cancelAnimationFrame(this.eb),this.eb=-1)}$e(){this.eb=-1;for(const a of this.Gb)a();this.Kc()}Fa(a){this.ma.Fa(a)}Ra(a){this.ma.Ra(a)}Jc(){this.ma.Jc()}Nb(a){this.ma.Nb(a)}Ee(){return!!ea["audio/webm; codecs=opus"]}async gf(a){a=await this.yd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ie(a){this.Vc=!0;this.Od=
a}Ce(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}wd(a){return!this.Ce(a)}async Ta(a){return"cordova"===this.u&&(a.startsWith("file:")||this.Xb&&this.wd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Kb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async We(a){const c=a.filename;switch(a.as){case "text":return await this.Be(c);case "buffer":return await this.Kb(c);default:throw Error("unsupported type");
}}qd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Be(a){a=await this.qd(a);return await fa(a)}Bc(){if(D.length&&!(8<=E)){E++;var a=D.shift();this.Ne(a.filename,a.zf,a.sf)}}Kb(a){return new Promise((c,d)=>{D.push({filename:a,zf:e=>{E--;this.Bc();c(e)},sf:e=>{E--;this.Bc();d(e)}});this.Bc()})}async Ne(a,c,d){try{const e=await this.qd(a),f=await ha(e);c(f)}catch(e){d(e)}}Ed(a){if("entered-fullscreen"===
a)b.Qb(!0),I(this.ma);else if("exited-fullscreen"===a)b.Qb(!1),I(this.ma);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.kd(a),this.kd=null):"extension-message"===c?this.pb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}cf(a){this.Ga({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Ga(a){this.oa()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.u&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}ff(){window.moveTo=(a,c)=>{this.Ga({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ga({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Ue(){return this.oa()?new Promise(a=>{this.kd=a;this.Ga({type:"wrapper-init"})}):Promise.resolve()}async Me(){const a=[];for(const [c,d]of Object.entries(this.sa))a.push(this.Le(c,d));
await Promise.all(a)}async Le(a,c){if("object"===typeof c)this.sa[a]=new Blob([c.str],{type:c.type}),this.$b[a]=c.str;else{let d=await this.Qe(c);d||(d=this.Oe(c));this.sa[a]=d}}async Qe(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Oe(a){a=this.ef(a);return this.Ke(a.data,
a.vf)}ef(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{vf:a,data:d}}Ke(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const J=self.pa,va=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},wa={dispatchUserScriptEvent:!0},xa={dispatchRuntimeEvent:!0};function ya(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function za(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function L(b){b=URL.createObjectURL(b);try{return await za(b)}finally{URL.revokeObjectURL(b)}}function Aa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ba(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await L(b);var d=await Aa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await L(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await L(b)}
function Da(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ea=new Set(["input","textarea","datalist","select"]),Fa=new Set(["canvas","body","html"]);function M(b){b.target.tagName&&Fa.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ga(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Ha(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await L(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ba(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ia=!1;document.addEventListener("pause",()=>Ia=!0);document.addEventListener("resume",()=>Ia=!1);function ra(b){b.addEventListener("selectstart",M);b.addEventListener("gesturehold",M);b.addEventListener("pointerdown",M)}function sa(b){b.addEventListener("selectstart",Ga);b.addEventListener("gesturehold",Ga);b.addEventListener("touchstart",Ga)}function ta(b){b.Nd=!0;b.Yc=b.l.qa();b.zb=b.l.ga()}
function I(b){if(!b.ka){var a=J.mb();a&&"any"!==b.gd&&Ja(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ga()})}}async function Ka(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function La(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ma(b){return await self.C3_GetSvgImageSize(b.blob)}function Na(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Oa(b){self.setTimeout(()=>{b.Md=!0},1E3);"cordova"===b.l.u?(document.addEventListener("pause",()=>Pa(b,!0)),document.addEventListener("resume",()=>Pa(b,!1))):document.addEventListener("visibilitychange",()=>Pa(b,"hidden"===document.visibilityState));b.dc=!("hidden"!==document.visibilityState&&!Ia);return{isSuspended:b.dc}}
function Qa(b){b.Id||(b.Id=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Ra(b){b.Hd||(b.Hd=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Sa(b){await ya(b.url)}
function Ta(b,a){b.Pd=a.message;-1===b.Pc&&(b.Pc=setTimeout(()=>{b.Pc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Pd)},250))}function Ua(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:J.mb(),innerWidth:b.qa(),innerHeight:b.ga()})}
function Pa(b,a){b.dc!==a&&((b.dc=a)?b.l.Ac():b.l.Kc(),m(b,"visibilitychange",{hidden:a}),!a&&b.l.nb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Va(b,a,c){"Backspace"===c.key&&M(c);if(b.l.oa()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.ka||(d=va.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K))}
function N(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Ba,pageX:c.pageX,pageY:c.pageY+b.Ba,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function O(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.$c);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Ba,pageX:c.pageX,pageY:c.pageY+b.Ba,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&
(b.$c=c.buttons)}}function Wa(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Ba=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Ba=a))}}
function Xa(b,a,c,d){const e=b.qa(),f=b.ga();b.gb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.mb()}):10>d&&Ya(b,e,f,d+1)}function Ya(b,a,c,d){-1!==b.gb&&clearTimeout(b.gb);b.gb=setTimeout(()=>Xa(b,a,c,d),48)}
function Ja(b){b=b.gd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Za(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.Pa(class extends self.Ca{constructor(b){super(b,"runtime");this.Nd=!1;this.gb=-1;this.gd="any";this.dc=this.Hd=this.Id=!1;this.kc=document.createElement("div");this.kc.className="c3-screen-reader-text";this.kc.setAttribute("aria-live","polite");document.body.appendChild(this.kc);this.Ka=null;this.ka=!1;this.Pd="";this.Pc=-1;this.Md=!1;this.Yc=b.qa();this.zb=b.ga();this.Ba=this.Ib=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ka(c));b.B("runtime","raster-svg-image",c=>La(c));b.B("runtime","get-svg-image-size",c=>Ma(c));b.B("runtime","set-target-orientation",c=>{this.gd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Na(c));b.B("runtime","go-to-script",c=>Na(c));b.B("runtime","before-start-ticking",()=>Oa(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ka||(this.Ka=document.createElement("div"),this.Ka.id="inspectOutline",document.body.appendChild(this.Ka));var d=this.Ka;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ka&&(this.Ka.style.display="none")});b.B("runtime","enable-device-orientation",()=>Qa(this));b.B("runtime","enable-device-motion",()=>Ra(this));b.B("runtime","add-stylesheet",c=>Sa(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>this.Fc(c));b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.kc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.l.ud().style.display="";this.l.Ie(c.duration)});b.B("runtime","export-to-video-progress",c=>Ta(this,c));b.B("runtime","exported-to-video",c=>{window.rf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.rf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Da(d)||c.preventDefault()});window.addEventListener("selectstart",M);window.addEventListener("gesturehold",M);window.addEventListener("touchstart",M,{passive:!1});window.addEventListener("pointerdown",M,{passive:!1});this.$c=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ha,{passive:!1});window.addEventListener("wheel",Ha,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Nd){var c=this.qa();var d=this.ga();if(this.l.vd()){if(this.Md){if(this.Yc===
c&&d<this.zb){this.Ib=this.zb-d;Wa(this,this.zb,this.Ib);c=void 0;break a}0<this.Ib&&(this.Ib=0,Wa(this,d,this.Ib))}this.Yc=c;this.zb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.mb()});this.l.nb()&&(-1!==this.gb&&clearTimeout(this.gb),Xa(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",()=>
I(this));window.addEventListener("fullscreenerror",c=>Ua(this,c));window.addEventListener("webkitfullscreenerror",c=>Ua(this,c));window.addEventListener("mozfullscreenerror",c=>Ua(this,c));if(b.nb()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):Da(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.$a=new Set;this.bc=new WeakSet;this.xa=!1}nd(){window.addEventListener("focus",()=>{m(this,"window-focus",null,xa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},xa);this.$c=0});window.addEventListener("focusin",a=>{a=a.target;(Ea.has(a.tagName.toLowerCase())||Da(a))&&m(this,"keyboard-blur",null,xa)});window.addEventListener("keydown",a=>Va(this,"keydown",a));window.addEventListener("keyup",a=>Va(this,"keyup",a));window.addEventListener("mousedown",a=>N(this,"mousedown",a,wa));window.addEventListener("mousemove",a=>N(this,"mousemove",a,wa));window.addEventListener("mouseup",a=>N(this,"mouseup",a,wa));window.addEventListener("dblclick",
a=>N(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Ba,pageX:a.pageX,pageY:a.pageY+this.Ba,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Za(a.target)&&document.activeElement&&!Za(document.activeElement)&&document.activeElement.blur();O(this,"pointerdown",a)});this.l.da&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{O(this,"pointermove",a)}):window.addEventListener("pointermove",a=>O(this,"pointermove",a));window.addEventListener("pointerup",a=>O(this,"pointerup",a));window.addEventListener("pointercancel",a=>O(this,"pointercancel",a));const b=()=>this.Jc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.l.De()&&!this.l.vd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Wa(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.l.nb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}qa(){return this.l.qa()}ga(){return this.l.ga()}Jc(){var b=[...this.$a];this.$a.clear();if(!this.xa)for(const a of b)(b=a.play())&&b.catch(()=>{this.bc.has(a)||this.$a.add(a)})}Fa(b){if("function"!==
typeof b.play)throw Error("missing play function");this.bc.delete(b);let a;try{a=b.play()}catch(c){this.$a.add(b);return}a&&a.catch(()=>{this.bc.has(b)||this.$a.add(b)})}Ra(b){this.$a.delete(b);this.bc.add(b)}Nb(b){this.xa=!!b}Fc(b){alert(b.message)}});"use strict";
async function oa(b){if(b.hf)throw Error("already initialised");b.hf=!0;var a=b.za.Cc(("playable-ad"===b.za.u?b.za.fb:"")+"dispatchworker.js");b.Oc=await b.za.qc(a,b.sb,{name:"DispatchWorker"});a=new MessageChannel;b.Uc=a.port1;b.Oc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.bd=await ua(b)}function qa(b){return[b.Uc,b.bd]}
async function ua(b){const a=b.Wd.length;var c=b.za.Cc(("playable-ad"===b.za.u?b.za.fb:"")+"jobworker.js");c=await b.za.qc(c,b.sb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Oc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Wd.push(c);return e.port1}
self.Ge=class{constructor(b){this.za=b;this.sb=b.aa;this.sb="preview"===b.u?this.sb+"workers/":this.sb+b.fb;this.lf=Math.min(navigator.hardwareConcurrency||2,16);this.Oc=null;this.Wd=[];this.bd=this.Uc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.pa({Af:!1,Bf:"workermain.js",hb:["scripts/c3runtime.js"],nc:[],ld:"",xf:"scripts/",oc:[],ke:"html5"}));"use strict";
async function $a(b,a){a=a.type;let c=!0;0===a?c=await ab():1===a&&(c=await bb());m(b,"permission-result",{type:a,result:c})}async function ab(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function bb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.pa.Pa(class extends self.Ca{constructor(b){super(b,"touch");p(this,"request-permission",a=>$a(this,a))}});"use strict";function cb(){}
function db(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(b,"sw-message",a.data))}
function eb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.pa.Pa(class extends self.Ca{constructor(b){super(b,"browser");this.u="";v(this,[["get-initial-state",a=>this.Hc(a)],["ready-for-sw-messages",()=>db(this)],["alert",a=>this.Fc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ic(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>eb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||this.l.oa()?window.open(c,"_blank"):this.Gf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.l.oa()||"macos-wkwebview"===this.u)self.pa.Qb(!0),this.l.Ga({type:"set-fullscreen",
fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(cb)}}],["exit-fullscreen",
()=>{if(this.l.oa()||"macos-wkwebview"===this.u)self.pa.Qb(!1),this.l.Ga({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(cb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=
a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",
e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{m(this,"backbutton")})}Hc(b){this.u=b.exportType;
return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}Fc(b){alert(b.message)}Ic(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
"use strict";function fb(b){return new Promise((a,c)=>{b.getInsetTop(a,c)})}function gb(b){return new Promise((a,c)=>{b.getInsetRight(a,c)})}function hb(b){return new Promise((a,c)=>{b.getInsetBottom(a,c)})}function ib(b){return new Promise((a,c)=>{b.getInsetLeft(a,c)})}
async function kb(b){if(!b.Ma)try{b.Ma=await navigator.wakeLock.request("screen"),b.Ma.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Ma=null;m(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),m(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),m(b,"wake-lock-error")}}
async function lb(b){const a=await mb();m(b,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function mb(){var b=self.AndroidNotch;if(b)try{return await Promise.all([fb(b),gb(b),hb(b),ib(b)])}catch(c){return console.error("[Construct] Failed to get Android safe area inset: ",c),[0,0,0,0]}else{var a=document.body;b=a.style;b.setProperty("--temp-sai-top","env(safe-area-inset-top)");b.setProperty("--temp-sai-right","env(safe-area-inset-right)");b.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");b.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);return isFinite(c)?c:0});b.removeProperty("--temp-sai-top");b.removeProperty("--temp-sai-right");b.removeProperty("--temp-sai-bottom");b.removeProperty("--temp-sai-left");return a}}
self.pa.Pa(class extends self.Ca{constructor(b){super(b,"platform-info");v(this,[["get-initial-state",()=>this.Hc()],["request-wake-lock",()=>kb(this)],["release-wake-lock",()=>{this.Ma&&(this.Ma.release(),this.Ma=null)}]]);window.addEventListener("resize",()=>lb(this));this.Ma=null}async Hc(){const b=await mb();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:b,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==
typeof nw}}});"use strict";self.pa.Pa(class extends self.Ca{constructor(b){super(b,"mouse");v(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.l.ud().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";const nb=180/Math.PI;
async function ob(b,a){if(a.isiOSCordova||a.isSafari)b.fc=!0;b.hd=a.timeScaleMode;b.ae=["equalpower","HRTF","soundfield"][a.panningModel];b.Ld=["linear","inverse","exponential"][a.distanceModel];b.be=a.refDistance;b.$d=a.maxDistance;b.de=a.rolloffFactor;if(b.l.Vc)b.fc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.l.Od)});else{var c={latencyHint:a.latencyHint};b.ge||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");pb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&pb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Va=b.g.createGain();b.Va.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ba);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function qb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,q=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Xd=g.slice(0);rb(b,g);try{b.R=await sb(b,c,d,e,g,f);if(q){Q(b.R,!0);var u=b.R,A=q.innerAngle,ma=q.outerAngle,na=q.outerGain;if(u.xb){tb(u,q.x,q.y,q.z,q.angle);var C=self.jb.Je;u.ta[0]!==C(A)&&
(u.ta[0]=C(A),u.F.coneInnerAngle=C(A));u.ta[1]!==C(ma)&&(u.ta[1]=C(ma),u.F.coneOuterAngle=C(ma));u.ta[2]!==na&&(u.ta[2]=na,u.F.coneOuterGain=na)}q.hasOwnProperty("uid")&&(b.R.ra=q.uid)}else"number"===typeof r&&0!==r?(R(b.R,!0),ub(b.R,r)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,l,t)}catch(Gb){console.error("[Construct] Audio: error starting playback: ",Gb);return}finally{c=g.join(" ");d=b.Fb.get(c);if(!d)throw Error("expected pending tag");d.md--;0===d.md&&(d.resolve(),b.Fb.delete(c))}w(b)}
async function vb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await wb(b,c);for(const h of S(b,c))if(!h.wa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.v.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Oa=d;h.Ya=g;h.fe=a}T(b)}async function xb(b,a){const c=a.tags;a=a.rate;await wb(b,c);for(const d of S(b,c))d.la!==a&&(d.la=a,d.Ha())}async function yb(b,a){const c=a.tags;a=a.pos;await wb(b,c);for(const d of S(b,c))d.wc(a)}
async function zb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await sb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function Ab(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function Bb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.qe(b,...e);else if("delay"===c)d=new self.oe(b,...e);else if("convolution"===c){var g=d=new self.ne(b,f.ha,...e),h=a.bufferType;g.Jd=a.bufferOriginalUrl;g.Kd=h}else if("flanger"===c)d=
new self.re(b,...e);else if("phaser"===c)d=new self.te(b,...e);else if("gain"===c)d=new self.se(b,...e);else if("stereopan"===c)d=new self.ve(b,...e);else if("tremolo"===c)d=new self.we(b,...e);else if("ringmod"===c)d=new self.ue(b,...e);else if("distortion"===c)d=new self.pe(b,...e);else if("compressor"===c)d=new self.me(b,...e);else if("analyser"===c)d=new self.le(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Ud=l.length;d.fd=
h;l.push(d);Cb(g,h)}Db(b)}
async function Eb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Da()&&1===c||!e.Da()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ja.values())for(const g of f)g.j();b.ja.clear();b.lc=a.timeScale;b.Qc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ba[e]=d[e];b.g.listener.setOrientation(...b.ba)}b.xa=a.isSilent;b.l.Nb(b.xa);b.ac=a.masterVolume;b.Va.gain.value=
b.ac;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>Bb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Fb(b,f,c)));T(b)}
async function Hb(b,a){try{const c=b.g.suspend(a.time);b.Td?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.l.pb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Ib(d)),b.Td=!0);await c}catch(c){Ib(c)}}
function pb(b){b.Vb||(b.Sc=!1,window.addEventListener("pointerup",b.Aa,!0),window.addEventListener("touchend",b.Aa,!0),window.addEventListener("click",b.Aa,!0),window.addEventListener("keydown",b.Aa,!0),b.Vb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ia)if(g.lb()===c)return await Jb(g),g;if(f)return null;if(e&&(b.fc||b.Sd)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Da()?g.j():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.ge;e&&f&&(b.Sd=!0);c=!e||b.fc||f?new self.ze(b,a,c,d,e,f):new self.xe(b,a,c,d,e);b.ia.push(c);await Jb(c);b.Zd.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.Zd.add(a));return c}
function Kb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Lb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function Cb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of Mb(b,a))d=c,e=f.ca||f.F||f.G,e.disconnect(),e.connect(d);b.La&&b.Zc===a&&(b.La.disconnect(),b.La.connect(c))}
function*Mb(b,a){if(a)for(const c of b.H)Kb(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Nb(b,a,c){return c?b.l.gf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Ob(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(Kb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function sb(b,a,c,d,e,f){for(const g of b.H)if(g.lb()===c&&(g.pc()||f))return g.na=e,g;a=await P(b,a,c,d,f);e="html5"===a.Mc?new self.ye(a.v,a,e):new self.Ae(a.v,a,e);b.H.push(e);return e}
function rb(b,a){a=a.join(" ");let c=b.Fb.get(a);if(!c){let d=null;c={md:0,promise:new Promise(e=>d=e),resolve:d};b.Fb.set(a,c)}c.md++}function wb(b,a){return(b=b.Fb.get((0===a.length?b.Xd:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Ua.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Pb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function Db(b){b.Wc||(b.Wc=!0,Promise.resolve().then(()=>Qb(b)))}
function Qb(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.kb());m(b,"fxstate",{fxstate:a});b.Wc=!1}
async function Fb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await sb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.bb[0]=f[0],b.bb[1]=f[1],b.bb[2]=f[2],f=d.orient,b.ab[0]=f[0],b.ab[1]=f[1],b.ab[2]=f[2],e.setPosition(...b.bb),e.setOrientation(...b.ab),b.ta[0]=d.cia,b.ta[1]=d.coa,b.ta[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.ra=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),ub(b,d));c.Play(k,l,q,0);a.isPlaying||c.ob();c.Ec(a)}}}function Ib(b){console.error("[Audio] Offline rendering error: ",b)}
self.jb=class extends self.Ca{constructor(b){super(b,"audio");this.Va=this.g=null;this.Vb=this.Sc=!1;this.Aa=()=>{if(!this.Sc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Vb&&(this.Sc=!0,window.removeEventListener("pointerup",this.Aa,!0),window.removeEventListener("touchend",this.Aa,!0),window.removeEventListener("click",this.Aa,!0),window.removeEventListener("keydown",
this.Aa,!0),this.Vb=!1)}};this.ia=[];this.H=[];this.R=null;this.Xd=[];this.Zd=new Set;this.Yd=-1;this.Fb=new Map;this.ac=1;this.xa=!1;this.hd=0;this.lc=1;this.Qc=0;this.ae="HRTF";this.Ld="inverse";this.be=600;this.$d=1E4;this.de=1;this.$=[0,0,0];this.ba=[0,0,-1,0,1,0];this.Sd=this.fc=!1;this.ge=this.l.Ee();this.ja=new Map;this.Ua=new Set;this.Td=this.Wc=!1;this.Zc="";this.La=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.La&&this.La.disconnect();this.Zc=c.toLowerCase();this.La=this.g.createMediaStreamSource(a);
this.La.connect(Lb(this,this.Zc))};this.Tb=null;self.C3Audio_GetOutputStream=()=>{this.Tb||(this.Tb=this.g.createMediaStreamDestination(),this.Va.connect(this.Tb));return this.Tb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>ob(this,a)],["play",a=>qb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ea()}],["stop-all",()=>{for(const a of this.H)a.Ea()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.ob():d.Mb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>vb(this,a)],["set-master-volume",a=>{this.ac=a.vol;this.Va.gain.value=this.ac}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Rb(d,a)}],["set-silent",a=>{this.xa=a.isSilent;this.l.Nb(this.xa);for(const c of this.H)c.Rb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.xc(a)}],["set-playback-rate",a=>xb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),ub(d,a)}],["seek",a=>yb(this,a)],["preload",a=>zb(this,a)],["unload",a=>Ab(this,a)],["unload-all",()=>{for(const a of this.ia)a.j();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.yc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Bb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Db(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ja.delete(a);Cb(this,a)}}],["tick",a=>{this.lc=a.timeScale;this.Qc=a.gameTime;this.Yd=a.tickCount;if(0!==this.hd)for(var c of this.H)c.Ha();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ba[0]!==
c[0]||this.ba[1]!==c[1]||this.ba[2]!==c[2]||this.ba[3]!==c[3]||this.ba[4]!==c[4]||this.ba[5]!==c[5])){for(let d=0;6>d;++d)this.ba[d]=c[d];this.g.listener.setOrientation(...this.ba)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.ra===a&&tb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Eb(this,a)],["offline-render-audio",a=>Hb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Va}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Lb(){return this.xa}Fa(b){this.l.Fa(b)}Ra(b){this.l.Ra(b)}Sa(){for(var b of this.Ua)b.Sa();
b=this.g.currentTime;for(var a of this.H)a.Sa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.kb());m(this,"state",{tickCount:this.Yd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ua].map(c=>({tag:c.fd,index:c.Ud,peak:c.cb,rms:c.ce,binCount:c.m.frequencyBinCount,freqBins:c.Qd}))});0===a.length&&0===this.Ua.size&&this.Wb&&(this.l.Fd(this.he),this.Wb=!1)}static Je(b){return b*nb}static sd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static He(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.pa.Pa(self.jb);"use strict";function Jb(b){b.Zb||(b.Zb=b.Dc());return b.Zb}self.od=class{constructor(b,a,c,d,e){this.v=b;this.nf=a;this.Na=c;this.T=d;this.jf=e;this.Mc="";this.Zb=null}j(){this.Zb=this.v=null}Dc(){}V(){return this.v.V()}tc(){return this.nf}lb(){return this.Na}rc(){return this.T}Da(){return this.jf}fa(){}};"use strict";
self.xe=class extends self.od{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Mc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Ab=this.Bb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Eb=this.V().createGain();this.Db=null;this.L.addEventListener("canplay",()=>{this.Bb&&(this.Bb(),this.Ab=this.Bb=null);!this.Db&&this.L&&(this.Db=this.V().createMediaElementSource(this.L),this.Db.connect(this.Eb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Na}' error: `,f);this.Ab&&(this.Ab(f),this.Ab=this.Bb=null)})}j(){Ob(this.v,this);this.Eb.disconnect();this.Eb=null;this.Db.disconnect();this.Db=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Dc(){return new Promise((b,a)=>{this.Bb=b;this.Ab=a;this.L.src=this.Na})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Sb(b){if(b.Ja)return b.Ja;var a=b.v.l;if("cordova"===a.u&&a.wd(b.Na)&&a.Xb)b.Ja=await a.Kb(b.Na);else{a=await fetch(b.Na);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ja=await a.arrayBuffer()}}async function Tb(b){if(b.ha)return b.ha;b.ha=await Nb(b.v,b.Ja,b.mf);b.Ja=null}
self.ze=class extends self.od{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Mc="webaudio";this.ha=this.Ja=null;this.mf=!!f}j(){Ob(this.v,this);this.ha=this.Ja=null;super.j()}async Dc(){try{await Sb(this),await Tb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Na}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Ub=0;
function Q(b,a){a=!!a;b.xb!==a&&(b.xb=a,b.xb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.v.ae,b.F.distanceModel=b.v.Ld,b.F.refDistance=b.v.be,b.F.maxDistance=b.v.$d,b.F.rolloffFactor=b.v.de),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function R(b,a){a=!!a;b.Yb!==a&&(b.Yb=a,b.Yb?(Q(b,!1),b.ca=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ca),b.ca.connect(b.ea())):(b.ca.disconnect(),b.ca=null,b.G.disconnect(),b.G.connect(b.ea())))}function ub(b,a){b.Yb&&b.ed!==a&&(b.ca.pan.value=a,b.ed=a)}function U(b,a){b.Oa=a;b.G.gain.cancelScheduledValues(0);b.Ya=-1;b.G.gain.value=b.uc()}function Rb(b,a){a=!!a;b.wa!==a&&(b.wa=a,b.Rb())}
function tb(b,a,c,d,e){if(b.xb){var f=b.bb,g=b.ab,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Xc?b.v.Qc:performance.now()/1E3}
self.pd=class{constructor(b,a,c){this.v=b;this.P=a;this.na=c;this.Sb=Ub++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.xb=!1;this.bb=[0,0,0];this.ab=[0,0,0];this.ta=[0,0,0];this.ca=null;this.Yb=!1;this.ed=0;this.I=!0;this.Y=this.ua=this.J=!1;this.Oa=1;this.wa=!1;this.la=1;b=this.v.hd;this.Xc=1===b&&!this.Da()||2===b;this.Ya=this.ra=-1;this.fe=!1}j(){this.P=this.v=null;this.F&&(this.F.disconnect(),this.F=null);this.ca&&(this.ca.disconnect(),this.ca=null);this.G.disconnect();
this.G=null}V(){return this.v.V()}ea(){return Lb(this.v,0<this.na.length?this.na[0]:"")}tc(){return this.P.tc()}lb(){return this.P.lb()}rc(){return this.P.rc()}Da(){return this.P.Da()}O(){}pc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Qa(){}fa(){return this.P.fa()}Play(){}Ea(){}ob(){}Mb(){}Sa(b){-1!==this.Ya&&b>=this.Ya&&(this.Ya=-1,this.fe&&this.Ea(),Pb(this.v,"fade-ended",this.na,this.Sb))}uc(){const b=this.Oa;return isFinite(b)?b:0}Lb(){return this.v.Lb()}Rb(){}xc(){}Ha(){}wc(){}yc(){}vc(){}kb(){var b=
this.Sb,a=this.na,c=this.fa(),d=-1===this.Ya?this.Oa:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.bb,orient:this.ab,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ra}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Qa(),playbackRate:this.la,uid:this.ra,bufferOriginalUrl:this.tc(),bufferUrl:"",bufferType:this.rc(),isMusic:this.Da(),isLooping:this.Y,isMuted:this.wa,resumePosition:this.vc(),pan:f,stereoPan:this.ca?
this.ed:null}}Ec(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Ha());Rb(this,b.isMuted)}};"use strict";
self.ye=class extends self.pd{constructor(b,a,c){super(b,a,c);this.P.Eb.connect(this.G);this.P.onended=()=>this.Gc()}j(){this.Ea();this.P.Eb.disconnect();super.j()}W(){return this.P.W()}Gc(){this.I=!0;this.ra=-1;Pb(this.v,"ended",this.na,this.Sb)}O(){return this.W().ended}pc(){return this.I?!0:this.O()}Qa(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);this.wa=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.lb()}' to position '${c}': `,e)}this.v.Fa(d);this.J=this.I=!1;this.Y=b;this.la=1}Ea(){const b=this.W();b.paused||b.pause();this.v.Ra(b);this.I=!0;this.J=!1;this.ra=-1}ob(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.v.Ra(b);this.J=!0}}Mb(){!this.J||this.I||this.O()||(this.v.Fa(this.W()),this.J=!1)}Rb(){this.W().muted=this.wa||this.Lb()}xc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ha(){let b=this.la;this.Xc&&(b*=this.v.lc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}wc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}vc(){return this.Qa()}yc(b){b?this.IsPlaying()?(this.W().pause(),this.ua=!0):this.ua=!1:this.ua&&(this.v.Fa(this.W()),this.ua=!1)}};"use strict";
function W(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.qb=null}
self.Ae=class extends self.pd{constructor(b,a,c){super(b,a,c);this.s=null;this.cc=d=>this.Gc(d);this.Rc=!0;this.qb=null;this.S=this.ec=this.hc=0;this.ad=1}j(){this.Ea();W(this);this.cc=null;super.j()}Gc(b){this.J||this.ua||b.target!==this.qb||(this.I=this.Rc=!0,this.ra=-1,W(this),Pb(this.v,"ended",this.na,this.Sb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Rc}pc(){return!this.s||this.I?!0:this.O()}Qa(){let b;b=this.J?this.S:this.ec+(V(this)-this.hc)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.wa=!1;this.ad=1;U(this,a);W(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ha;this.s.connect(this.G);this.qb=this.s;this.s.onended=this.cc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Rc=!1;this.Y=b;this.la=1;this.hc=V(this);this.ec=c}Ea(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.ra=-1}ob(){this.J||this.I||this.O()||(this.S=this.Qa(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Mb(){!this.J||this.I||this.O()||(W(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.cc,this.s.loop=this.Y,U(this,this.Oa),this.Ha(),this.s.start(0,this.S),this.hc=V(this),this.ec=this.S,this.J=!1)}uc(){return super.uc()*this.ad}Rb(){this.ad=this.wa||this.Lb()?0:1;U(this,this.Oa)}xc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ha(){let b=this.la;this.Xc&&(b*=this.v.lc);this.s&&(this.s.playbackRate.value=b)}wc(b){this.I||this.O()||(this.J?this.S=b:(this.ob(),
this.S=b,this.Mb()))}vc(){return this.S}yc(b){b?this.IsPlaying()?(this.ua=!0,this.S=this.Qa(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.ua=!1:this.ua&&(W(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.cc,this.s.loop=this.Y,U(this,this.Oa),this.Ha(),this.s.start(0,this.S),this.hc=V(this),this.ec=this.S,this.ua=!1)}Ec(b){super.Ec(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.v=b;this.g=b.V();this.Ud=-1;this.T=this.fd="";this.o=null}j(){this.g=null}N(){}U(){}kb(){return{type:this.T,tag:this.fd,params:this.o}}}
self.qe=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.A=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}j(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.oe=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.Cb=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.vb=X(this);this.vb.gain.value=c;this.A.connect(this.Cb);this.A.connect(this.h);this.Cb.connect(this.i);this.Cb.connect(this.X);this.X.connect(this.vb);this.vb.connect(this.Cb)}j(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.Cb.disconnect();
this.X.disconnect();this.vb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.jb.sd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);Y(this,this.vb.gain,e(a),c,d);break;case 5:this.o[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.ne=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Kd=this.Jd="";this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.ub=this.g.createConvolver();this.ub.normalize=c;this.ub.buffer=a;this.A.connect(this.ub);this.A.connect(this.h);this.ub.connect(this.i)}j(){this.A.disconnect();this.ub.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}kb(){const b=super.kb();b.bufferOriginalUrl=this.Jd;b.bufferUrl="";b.bufferType=this.Kd;return b}};
self.re=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.A=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.wb=X(this);this.wb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=X(this);this.K.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.wb);this.wb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.A.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.wb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;Y(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;Y(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,Y(this,this.wb.gain,a/100,c,d)}}};
self.te=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.A=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=X(this);this.K.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.A.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;Y(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,Y(this,this.C.frequency,a,c,d)}}};self.se=class extends Z{constructor(b,a){super(b);this.T="gain";this.o=[a];this.m=X(this);this.m.gain.value=a}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){const e=self.jb.sd;switch(b){case 4:this.o[0]=e(a),Y(this,this.m.gain,e(a),c,d)}}};
self.ve=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.m=this.g.createStereoPanner();this.m.pan.value=a}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,Y(this,this.m.pan,a,c,d)}}};
self.we=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.m=X(this);this.m.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=X(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.m.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;Y(this,this.m.gain,1-a/2,c,d);Y(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.ue=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.A=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Hb=X(this);this.Hb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Hb.gain);this.C.start(0);this.A.connect(this.Hb);this.A.connect(this.h);this.Hb.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Hb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.pe=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.A=X(this);this.jc=X(this);this.ic=X(this);b=d;.01>b&&(b=.01);this.jc.gain.value=b;this.ic.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.mc=this.g.createWaveShaper();this.Nc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Nc[32768+e]=f,this.Nc[32768-
e-1]=-f;this.mc.curve=this.Nc;this.A.connect(this.jc);this.A.connect(this.h);this.jc.connect(this.mc);this.mc.connect(this.ic);this.ic.connect(this.i)}j(){this.A.disconnect();this.jc.disconnect();this.mc.disconnect();this.ic.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.me=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};
self.le=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.Qd=new Float32Array(this.m.frequencyBinCount);this.ee=new Uint8Array(a);this.ce=this.cb=0;b=this.v;b.Ua.add(this);T(b)}j(){this.v.Ua.delete(this);this.m.disconnect();super.j()}Sa(){this.m.getFloatFrequencyData(this.Qd);this.m.getByteTimeDomainData(this.ee);const b=this.m.fftSize;let a=this.cb=0;for(var c=0;c<b;++c){let d=(this.ee[c]-
128)/128;0>d&&(d=-d);this.cb<d&&(this.cb=d);a+=d*d}c=self.jb.He;this.cb=c(this.cb);this.ce=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};
