function m(c,a,b,d){c.h.ga(c.X,a,b,d)}function r(c,a,b,d){c.h.m?m(c,a,b,d):c.h.Hb()._OnMessageFromDOM({type:"event",component:c.X,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function t(c,a,b){c.h.i(c.X,a,b)}function u(c,a){for(const [b,d]of a)t(c,b,d)}window.S=class{constructor(c,a){this.h=c;this.X=a}qa(){}};window.sc=class{constructor(){}};"use strict";function aa(c,a){t(c,"get-element",b=>{const d=v(c,b.elementId);return a(d,b)})}
function v(c,a){c=c.L.get(a);if(!c)throw Error(`no element with id ${a}`);return c.ka}
window.Ra=class extends self.S{constructor(c,a){super(c,a);this.L=new Map;this.V=!0;u(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{b=b.elementId;const d=v(this,b);this.V&&d.parentElement.removeChild(d);this.L.delete(b)}],["set-visible",b=>{if(this.V){var d=this.L.get(b.elementId),e=d.ka;d.kb?e.style.display=b.isVisible?"":"none":d.$b=!!b.isVisible}}],["update-position",b=>{if(this.V){var d=this.L.get(b.elementId),e=d.ka,f=this.h;e.style.left=b.left+"px";e.style.top=b.top+
"px";e.style.width=b.width+"px";e.style.height=b.height+"px";var h=b.fontSize;null!==h&&(e.style.fontSize=h+"em");h=b.htmlIndex;d.dc=h;h=f.Sa(h);h!==d.G&&(e.remove(),f.fa(h).appendChild(e),d.G=h,f.Aa());b=b.htmlZIndex;b!==d.Da&&(d.Da=b,f.Aa());d.kb||(d.kb=!0,d.$b&&(e.style.display=""))}}],["update-state",b=>{v(this,b.elementId);throw Error("required override");}],["focus",b=>this.xa(b)],["set-css-style",b=>{const d=v(this,b.elementId),e=b.prop;b=b.val;e.startsWith("--")?d.style.setProperty(e,b):d.style[e]=
b}],["set-attribute",b=>{v(this,b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{v(this,b.elementId).removeAttribute(b.name)}]]);aa(this,b=>b)}xa(c){var a=v(this,c.elementId);c.focus?a.focus():a.blur()}};"use strict";const w=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent),ba=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let y=0;
function z(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.ic?new Promise(b=>{const d="c3_resolve_"+y;++y;self[d]=b;a.textContent=c.mc+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((b,d)=>{a.onload=b;a.onerror=d;a.src=c;document.head.appendChild(a)})}
async function ca(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let c=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){c=!0}}),b=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return c&&b}catch(c){return console.warn("Error feature detecting worker mode: ",c),!1}}let A=new Audio;
const da={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ea(c){c=await fa(c);return(new TextDecoder("utf-8")).decode(c)}
function fa(c){return new Promise((a,b)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsArrayBuffer(c)})}const B=[];let C=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let ha=0;const ia=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");ia.push(c)};const ja=new Set(["cordova","playable-ad","instant-games"]);let ka=!1;
window.D=class c{constructor(a){this.m=a.oc;this.$=null;this.l="";this.N=a.lc;this.ca={};this.Ha=this.P=null;this.K=[];this.I=null;this.mb=!0;this.j=[];this.La=[];this.Ma=!1;this.ob=()=>this.Fb();this.lb=!1;this.Y=null;this.M=-1;this.cc=()=>this.Qb();this.aa=new Set;this.Oa=null;this.pb=[];this.g=a.qb;this.Fa="file"===location.protocol.substr(0,4);if("playable-ad"===this.g||"instant-games"===this.g)this.m=!1;ba&&(this.m=!1);if("cordova"===this.g&&this.m&&x){const b=/Chrome\/(\d+)/i.exec(navigator.userAgent);
b&&90<=parseInt(b[1],10)||(this.m=!1)}this.u()?self.chrome.webview.addEventListener("message",b=>this.bb(b.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=b=>this.bb(b));this.la=this.A=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.i("canvas","update-size",b=>this.Ub(b));this.i("canvas","set-html-layer-count",
b=>this._OnSetHTMLLayerCount(b));this.i("canvas","cleanup-html-layers",()=>this.Lb());this.i("runtime","cordova-fetch-local-file",b=>this.Mb(b));this.i("runtime","create-job-worker",()=>this.Nb());this.i("runtime","send-wrapper-extension-message",b=>this.Tb(b));"cordova"===this.g?document.addEventListener("deviceready",()=>this.$a(a)):this.$a(a)}sb(){return this.j[0].canvas}Sa(a){return Math.min(a,this.j.length-1)}fa(a){if(0>a||a>=this.j.length)throw new RangeError("invalid canvas layer");return this.j[a].da}_GetHTMLWrapElement(a){return this.fa(a)}wb(){return w&&
"cordova"===this.g}U(){const a=navigator.userAgent;return w&&ja.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ub(){return x}Ta(){return x&&ja.has(this.g)}Ua(){return"windows-webview2"===this.g||!!("preview"===this.g&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}u(){return this.Ua()||"xbox-uwp-webview2"===this.g}async $a(a){this.m&&!await ca()&&(this.m=!1);"macos-wkwebview"===this.g?this.F({type:"ready"}):this.u()&&(this.Xb(),this.pb=(await this.Kb()).registeredComponentIds);
if("playable-ad"===this.g){this.A=self.c3_base64files;this.la={};await this.Cb();for(let d=0,e=a.R.length;d<e;++d){var b=a.R[d];this.la.hasOwnProperty(b)?a.R[d]={ic:!0,mc:this.la[b]}:this.A.hasOwnProperty(b)&&(a.R[d]=URL.createObjectURL(this.A[b]))}a.pa=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Va(()=>{d++;document.documentElement.style.opacity=0===d%2?"1":"0.999"})}a.kc?this.l=a.kc:(b=location.origin,this.l=("null"===b?"file:///":b)+location.pathname,b=this.l.lastIndexOf("/"),
-1!==b&&(this.l=this.l.substr(0,b+1)));a.qc&&(this.ca=a.qc);b=new MessageChannel;this.$=b.port1;this.$.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Pb(d));this.Y=new self.xb(this);await la(this.Y);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.m?await this.Jb(a,b.port2):await this.Ib(a,b.port2)}va(a){a=this.ca.hasOwnProperty(a)?this.ca[a]:a.endsWith("/workermain.js")&&this.ca.hasOwnProperty("workermain.js")?this.ca["workermain.js"]:"playable-ad"===this.g&&this.A.hasOwnProperty(a)?this.A[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async sa(a,b,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.Fa)return a=await this.ra(d.hc?a:this.N+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,b);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}v(){return Math.max(window.innerWidth,1)}o(){return Math.max(window.innerHeight,1)}ta(){return this.u()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.g)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?
"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}Za(a){var b=this.l,d=location.href,e=this.v(),f=this.o(),h=this.ta(),g=window.devicePixelRatio,k=c.T(),l=a.wc,n=window.cr_previewImageBlobs||this.A,p=window.cr_previewProjectFileBlobs,q=window.cr_previewProjectFiles,xa=window.cr_swClientId||"";a=a.qb;var ya=(new URLSearchParams(self.location.search)).has("debug"),M=this.Y;return{runtimeBaseUrl:b,previewUrl:d,windowInnerWidth:e,
windowInnerHeight:f,cssDisplayMode:h,devicePixelRatio:g,isFullscreen:k,projectData:l,previewImageBlobs:n,previewProjectFileBlobs:p,previewProjectFileSWUrls:q,swClientId:xa,exportType:a,isDebug:ya,ife:!!self.vc,jobScheduler:{inputPort:M.Ea,outputPort:M.Ka,maxNumWorkers:M.ac},supportedAudioFormats:da,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.N+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.N+"opus.wasm.wasm",isFileProtocol:this.Fa,isiOSCordova:this.wb(),isiOSWebView:this.U(),
isWindowsWebView2:this.Ua(),isAnyWebView2Wrapper:this.u(),wrapperComponentIds:this.pb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Jb(a,b){const d=this.va(a.pc);"preview"===this.g?(this.P=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,n)=>{const p=q=>{this.P.removeEventListener("message",p);q.data&&"ok"===q.data.type?l():n()};this.P.addEventListener("message",p);this.P.postMessage({type:"construct-worker-init","import":(new URL(d,this.l)).toString()})})):
this.P=await this.sa(d,this.l,{type:"module",name:"Runtime",hc:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const h=document.createElement("div");h.className="c3htmlwrap";document.body.appendChild(h);this.j.push({canvas:e,da:h});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let g=a.pa||[],k=a.R;g=await Promise.all(g.map(l=>this.J(l)));k=await Promise.all(k.map(l=>this.J(l)));
if("cordova"===this.g)for(let l=0,n=a.oa.length;l<n;++l){const p=a.oa[l],q=p[0];if(q===a.Pa||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.J(q)}this.P.postMessage(Object.assign(this.Za(a),{type:"init-runtime",isInWorker:!0,messagePort:b,canvas:f,workerDependencyScripts:g,engineScripts:k,projectScripts:a.oa,mainProjectScript:a.Pa,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[b,f,...ma(this.Y)]);this.K=E.map(l=>new l(this));this.Ya();H(e);I(h);na(this.I);self.c3_callFunction=
(l,n)=>{var p=this.I;return p.h.yb(p.X,{name:l,params:n})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.ga("runtime","go-to-last-error-script"))}async Ib(a,b){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.j.push({canvas:d,da:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.K=E.map(g=>new g(this));this.Ya();
H(d);I(e);e=a.R.map(g=>"string"===typeof g?(new URL(g,this.l)).toString():g);if(Array.isArray(a.pa)){var f=[...a.pa].map(g=>g instanceof Blob?URL.createObjectURL(g):g);e.unshift(...f)}e=await Promise.all(e.map(g=>this.J(g)));await Promise.all(e.map(g=>z(g)));e=self.C3_ProjectScriptsStatus;f=a.Pa;const h=a.oa;for(let [g,k]of h)if(k||(k=g),g===f)try{k=await this.J(k),await z(k),"preview"!==this.g||e[g]||this.cb(g,"main script did not run to completion")}catch(l){this.cb(g,l)}else if("scriptsInEvents.js"===
g||g.endsWith("/scriptsInEvents.js"))k=await this.J(k),await z(k);"preview"===this.g&&"object"!==typeof self.rc.tc?(this.ia(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Za(a),{isInWorker:!1,messagePort:b,canvas:d,runOnStartupFunctions:ia}),na(this.I),this.ab(),this.Ha=self.C3_CreateRuntime(a),
await self.C3_InitRuntime(this.Ha,a))}cb(a,b){this.ia();console.error(`[Preview] Failed to load project main script (${a}): `,b);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}ab(){this.ia()}ia(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Nb(){const a=await oa(this.Y);return{outputPort:a,transferables:[a]}}Ub(a){if(!this.lb){var b=
a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:h,da:g}of this.j)h.style.width=b,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,g.style.width=b,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,this.mb&&(h.style.display="",g.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.mb=!1}}_OnSetHTMLLayerCount(a){var b=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const h=
a.marginLeft+"px",g=a.marginTop+"px";a=[];const k=[];if(b<this.j.length)for(;this.j.length>b;){const {canvas:l,da:n}=this.j.pop();n.remove();this.m&&!d?this.La.push(l):l.remove()}else if(b>this.j.length)for(let l=0,n=b-this.j.length;l<n;++l)b=document.createElement("canvas"),b.classList.add("c3overlay"),this.m?(d=b.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(b),document.body.appendChild(b),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),
b.style.width=e,b.style.height=f,b.style.marginLeft=h,b.style.marginTop=g,d.style.width=e,d.style.height=f,d.style.marginLeft=h,d.style.marginTop=g,H(b),I(d),this.j.push({canvas:b,da:d});for(const l of this.K)if(l instanceof window.Ra&&l.V)for(const n of l.L.values())e=l.h.Sa(n.dc),f=n.G,-1!==e&&-1!==f&&e!==f&&(f=n.ka,f.remove(),l.h.fa(e).appendChild(f),n.G=e);this.Aa();return{addedCanvases:a,transferables:k}}Lb(){for(const a of this.La)a.remove();this.La.length=0}Aa(){this.Ma||(this.Ma=!0,this.Va(this.ob))}Fb(){this.Wb(this.ob);
this.Ma=!1;let a=[];for(var b of this.K)if(b instanceof window.Ra){var d=b.V?[...b.L.values()]:null;d&&a.push(...d)}a.sort((h,g)=>{const k=h.G,l=g.G;return k!==l?k-l:h.Da-g.Da});let e=d=b=0,f=a.length;for(;e<f;++e){const h=a[e];h.G!==b&&(this.Xa(b,a.slice(d,e)),b=h.G,d=e)}d<e&&this.Xa(b,a.slice(d,e))}Xa(a,b){if(!(1>=b.length||a>=this.j.length)){b=b.map(k=>k.ka);var d=new Set(b);a=this.fa(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,h=Math.min(b.length,e.length);f<h&&b[f]===e[f];++f);
for(var g=f;g<h;++g)e[g].remove();for(g=f;g<h;++g)a.appendChild(b[g])}}Hb(){if(this.m)throw Error("not available in worker mode");return this.Ha}ga(a,b,d,e){this.$.postMessage({type:"event",component:a,handler:b,dispatchOpts:e||null,data:d,responseId:null},void 0)}yb(a,b){const d=ha++,e=new Promise((f,h)=>{G.set(d,{resolve:f,reject:h})});this.$.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:b,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const b=
a.type;if("event"===b)return this.Ob(a);if("result"===b)this.Rb(a);else if("runtime-ready"===b)this.Sb();else if("alert-error"===b)this.ia(),alert(a.message);else if("creating-runtime"===b)this.ab();else throw Error(`unknown message '${b}'`);}Ob(a){const b=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(b))if(a=a.get(d)){var h=null;try{h=a(e)}catch(g){console.error(`Exception in '${b}' handler '${d}':`,g);null!==f&&this.ha(f,!1,""+g);return}if(null===f)return h;h&&h.then?h.then(g=>this.ha(f,
!0,g)).catch(g=>{console.error(`Rejection from '${b}' handler '${d}':`,g);this.ha(f,!1,""+g)}):this.ha(f,!0,h)}else console.warn(`[DOM] No handler '${d}' for component '${b}'`);else console.warn(`[DOM] No event handlers for component '${b}'`)}ha(a,b,d){let e;d&&d.transferables&&(e=d.transferables);this.$.postMessage({type:"result",responseId:a,isOk:b,result:d},e)}Rb(a){const b=a.responseId,d=a.isOk;a=a.result;const e=G.get(b);d?e.resolve(a):e.reject(a);G.delete(b)}i(a,b,d){let e=F.get(a);e||(e=new Map,
F.set(a,e));if(e.has(b))throw Error(`[DOM] Component '${a}' already has handler '${b}'`);e.set(b,d)}static ea(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Ya(){for(const a of this.K)if("runtime"===a.X){this.I=a;return}throw Error("cannot find runtime DOM handler");}Pb(a){this.ga("debugger","message",a)}Sb(){for(const a of this.K)a.qa()}static T(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ka)}static ja(a){ka=!!a}Va(a){this.aa.add(a);
this.za()}Wb(a){this.aa.delete(a);0===this.aa.size&&this.Wa()}za(){-1===this.M&&0<this.aa.size&&(this.M=requestAnimationFrame(this.cc))}Wa(){-1!==this.M&&(cancelAnimationFrame(this.M),this.M=-1)}Qb(){this.M=-1;for(const a of this.aa)a();this.za()}ya(){this.I.ya()}zb(){this.lb=!0}tb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}vb(a){return!this.tb(a)}async J(a){return"cordova"===this.g&&(a.startsWith("file:")||this.Fa&&this.vb(a))?(a.startsWith(this.l)&&
(a=a.substr(this.l.length)),a=await this.ra(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Mb(a){const b=a.filename;switch(a.as){case "text":return await this.rb(b);case "buffer":return await this.ra(b);default:throw Error("unsupported type");}}Qa(a){const b=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(b,f=>{f.file(d,e)},e)})}async rb(a){a=await this.Qa(a);return await ea(a)}ua(){if(B.length&&!(8<=C)){C++;
var a=B.shift();this.Db(a.filename,a.nc,a.fc)}}ra(a){return new Promise((b,d)=>{B.push({filename:a,nc:e=>{C--;this.ua();b(e)},fc:e=>{C--;this.ua();d(e)}});this.ua()})}async Db(a,b,d){try{const e=await this.Qa(a),f=await fa(e);b(f)}catch(e){d(e)}}bb(a){if("entered-fullscreen"===a)c.ja(!0),J(this.I);else if("exited-fullscreen"===a)c.ja(!1),J(this.I);else if("object"===typeof a){const b=a.type;"directory-handles"!==b&&("wrapper-init-response"===b?(this.Oa(a),this.Oa=null):"extension-message"===b?this.ga("runtime",
"wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a))}else console.warn("Unknown wrapper message: ",a)}Tb(a){this.F({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}F(a){this.u()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Xb(){window.moveTo=(a,b)=>{this.F({type:"set-window-position",windowX:Math.ceil(a),
windowY:Math.ceil(b)})};window.resizeTo=(a,b)=>{this.F({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(b)})}}Kb(){return this.u()?new Promise(a=>{this.Oa=a;this.F({type:"wrapper-init"})}):Promise.resolve()}async Cb(){const a=[];for(const [b,d]of Object.entries(this.A))a.push(this.Bb(b,d));await Promise.all(a)}async Bb(a,b){if("object"===typeof b)this.A[a]=new Blob([b.str],{type:b.type}),this.la[a]=b.str;else{let d=await this.Gb(b);d||(d=this.Eb(b));this.A[a]=d}}async Gb(a){try{return await (await fetch(a)).blob()}catch(b){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
b),null}}Eb(a){a=this.Vb(a);return this.Ab(a.data,a.jc)}Vb(a){var b=a.indexOf(",");if(0>b)throw new URIError("expected comma in data: uri");var d=a.substring(b+1);b=a.substring(5,b).split(";");a=b[0]||"";const e=b[2];d="base64"===b[1]||"base64"===e?atob(d):decodeURIComponent(d);return{jc:a,data:d}}Ab(a,b){var d=a.length;let e=d>>2,f=new Uint8Array(d),h=new Uint32Array(f.buffer,0,e),g,k;for(k=g=0;g<e;++g)h[g]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:b})}};"use strict";const K=self.D,pa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),L={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},N={dispatchUserScriptEvent:!0},O={dispatchRuntimeEvent:!0};function qa(c){return new Promise((a,b)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>b(e);d.rel="stylesheet";d.href=c;document.head.appendChild(d)})}
function ra(c){return new Promise((a,b)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>b(e);d.src=c})}async function sa(c){c=URL.createObjectURL(c);try{return await ra(c)}finally{URL.revokeObjectURL(c)}}function ta(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const ua=new Set(["input","textarea","datalist","select"]),va=new Set(["canvas","body","html"]);
function P(c){c.target.tagName&&va.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function Q(c){c.target.tagName&&c.target.classList.contains("c3htmlwrap")&&c.preventDefault()}function wa(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}
self.C3_GetSvgImageSize=async function(c){c=await sa(c);if(0<c.width&&0<c.height)return[c.width,c.height];c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const a=c.getBoundingClientRect();document.body.removeChild(c);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(c,a,b,d,e){c=await sa(c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(c,0,0,a,b);return f};
let R=!1;document.addEventListener("pause",()=>R=!0);document.addEventListener("resume",()=>R=!1);function H(c){c.addEventListener("selectstart",P);c.addEventListener("gesturehold",P);c.addEventListener("pointerdown",P)}function I(c){c.addEventListener("selectstart",Q);c.addEventListener("gesturehold",Q);c.addEventListener("touchstart",Q)}function na(c){c.ib=!0;c.Ga=c.h.v();c.Z=c.h.o()}
function J(c){if(!c.s){var a=K.T();a&&"any"!==c.Na&&za(c);m(c,"fullscreenchange",{isFullscreen:a,innerWidth:c.v(),innerHeight:c.o()})}}async function Aa(c){await Promise.all(c.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ba(c){var a=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);a=a?await createImageBitmap(c,a):await createImageBitmap(c);return{imageBitmap:a,transferables:[a]}}async function Ca(c){return await self.C3_GetSvgImageSize(c.blob)}function Da(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}
function Ea(c){self.setTimeout(()=>{c.hb=!0},1E3);"cordova"===c.h.g?(document.addEventListener("pause",()=>T(c,!0)),document.addEventListener("resume",()=>T(c,!1))):document.addEventListener("visibilitychange",()=>T(c,"hidden"===document.visibilityState));c.ma=!("hidden"!==document.visibilityState&&!R);return{isSuspended:c.ma}}
function Fa(c){c.fb||(c.fb=!0,window.addEventListener("deviceorientation",a=>{c.s||m(c,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},L)}),window.addEventListener("deviceorientationabsolute",a=>{c.s||m(c,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},L)}))}
function Ga(c){c.eb||(c.eb=!0,window.addEventListener("devicemotion",a=>{if(!c.s){var b=null,d=a.acceleration;d&&(b={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(c,"devicemotion",{acceleration:b,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},L)}}))}async function Ha(c){await qa(c.url)}
function Ia(c,a){c.jb=a.message;-1===c.Ca&&(c.Ca=setTimeout(()=>{c.Ca=-1;const b=document.getElementById("exportToVideoMessage");b&&(b.textContent=c.jb)},250))}function U(c,a){console.warn("[Construct] Fullscreen request failed: ",a);m(c,"fullscreenerror",{isFullscreen:K.T(),innerWidth:c.v(),innerHeight:c.o()})}
function T(c,a){c.ma!==a&&((c.ma=a)?c.h.Wa():c.h.za(),m(c,"visibilitychange",{hidden:a}),!a&&c.h.U()&&(c=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(c,50),setTimeout(c,100),setTimeout(c,250),setTimeout(c,500)))}
function Ja(c,a,b){"Backspace"===b.key&&P(b);"nwjs"===c.h.g&&"u"===b.key&&(b.ctrlKey||b.metaKey)&&b.preventDefault();if(!c.s){var d=pa.get(b.code)||b.code;r(c,a,{code:d,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,metaKey:b.metaKey,shiftKey:b.shiftKey,timeStamp:b.timeStamp},L)}}
function V(c,a,b,d){c.s||b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents||r(c,a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY+c.C,pageX:b.pageX,pageY:b.pageY+c.C,movementX:b.movementX||0,movementY:b.movementY||0,timeStamp:b.timeStamp},d)}
function W(c,a,b){if(!c.s){var d=0;"mouse"===b.pointerType&&(d=c.Ja);r(c,a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,buttons:b.buttons,lastButtons:d,clientX:b.clientX,clientY:b.clientY+c.C,pageX:b.pageX,pageY:b.pageY+c.C,movementX:b.movementX||0,movementY:b.movementY||0,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},L);"mouse"===b.pointerType&&(c.Ja=
b.buttons)}}function X(c,a,b){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";c.C=0;if(0<b){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-b)/2,a>b&&(a=b),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,c.C=a))}}
function Ka(c,a,b,d){const e=c.v(),f=c.o();c.O=-1;e!=a||f!=b?m(c,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:K.T(),cssDisplayMode:c.h.ta()}):10>d&&La(c,e,f,d+1)}function La(c,a,b,d){-1!==c.O&&clearTimeout(c.O);c.O=setTimeout(()=>Ka(c,a,b,d),48)}
function za(c){c=c.Na;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ma(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}
K.ea(class extends self.S{constructor(c){super(c,"runtime");this.ib=!1;this.O=-1;this.Na="any";this.ma=this.eb=this.fb=!1;this.na=document.createElement("div");this.na.className="c3-screen-reader-text";this.na.setAttribute("aria-live","polite");document.body.appendChild(this.na);this.H=null;this.s=!1;this.jb="";this.Ca=-1;this.hb=!1;this.Ga=c.v();this.Z=c.o();this.C=this.ba=0;c.i("runtime","invoke-download",b=>{const d=b.url;b=b.filename;const e=document.createElement("a"),f=document.body;e.textContent=
b;e.href=d;e.download=b;f.appendChild(e);e.click();f.removeChild(e)});c.i("runtime","load-webfonts",b=>Aa(b));c.i("runtime","raster-svg-image",b=>Ba(b));c.i("runtime","get-svg-image-size",b=>Ca(b));c.i("runtime","set-target-orientation",b=>{this.Na=b.targetOrientation});c.i("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});c.i("runtime","post-to-debugger",b=>Da(b));c.i("runtime","go-to-script",b=>Da(b));c.i("runtime","before-start-ticking",()=>Ea(this));c.i("runtime","debug-highlight",
b=>{if(b.show){this.H||(this.H=document.createElement("div"),this.H.id="inspectOutline",document.body.appendChild(this.H));var d=this.H;d.style.display="";d.style.left=b.left-1+"px";d.style.top=b.top-1+"px";d.style.width=b.width+2+"px";d.style.height=b.height+2+"px";d.textContent=b.name}else this.H&&(this.H.style.display="none")});c.i("runtime","enable-device-orientation",()=>Fa(this));c.i("runtime","enable-device-motion",()=>Ga(this));c.i("runtime","add-stylesheet",b=>Ha(b));c.i("runtime","script-create-worker",
b=>{const d=b.port2;(new Worker(b.url,b.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});c.i("runtime","alert",b=>this.wa(b));c.i("runtime","screen-reader-text",b=>{var d=b.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+b.id,d.textContent=b.text,this.na.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+b.id))?d.textContent=b.text:console.warn(`[Construct] Missing screen reader text with id ${b.id}`):"release"===d?(d=document.getElementById("c3-sr-"+b.id))?
d.remove():console.warn(`[Construct] Missing screen reader text with id ${b.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});c.i("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});c.i("runtime","set-exporting-to-video",b=>{this.s=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=b.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");this.h.sb().style.display=
"";this.h.zb()});c.i("runtime","export-to-video-progress",b=>Ia(this,b));c.i("runtime","exported-to-video",b=>{window.ec({type:"exported-video",arrayBuffer:b.arrayBuffer,contentType:b.contentType,time:b.time})});c.i("runtime","exported-to-image-sequence",b=>{window.ec({type:"exported-image-sequence",blobArr:b.blobArr,time:b.time,gif:b.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",b=>{const d=b.target;a.has(d.tagName.toLowerCase())||ta(d)||b.preventDefault()});
window.addEventListener("selectstart",P);window.addEventListener("gesturehold",P);window.addEventListener("touchstart",P,{passive:!1});window.addEventListener("pointerdown",P,{passive:!1});this.Ja=0;window.addEventListener("mousedown",b=>{1===b.button&&b.preventDefault()});window.addEventListener("mousewheel",wa,{passive:!1});window.addEventListener("wheel",wa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.s&&this.ib){var b=this.v();var d=this.o();if(this.h.Ta()){if(this.hb){if(this.Ga===
b&&d<this.Z){this.ba=this.Z-d;X(this,this.Z,this.ba);b=void 0;break a}0<this.ba&&(this.ba=0,X(this,d,this.ba))}this.Ga=b;this.Z=d}m(this,"window-resize",{innerWidth:b,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:K.T(),cssDisplayMode:this.h.ta()});this.h.U()&&(-1!==this.O&&clearTimeout(this.O),Ka(this,b,d,0))}b=void 0}return b});window.addEventListener("fullscreenchange",()=>J(this));window.addEventListener("webkitfullscreenchange",()=>J(this));window.addEventListener("mozfullscreenchange",
()=>J(this));window.addEventListener("fullscreenerror",b=>U(this,b));window.addEventListener("webkitfullscreenerror",b=>U(this,b));window.addEventListener("mozfullscreenerror",b=>U(this,b));if(c.U()){let b=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>b&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);b=d});document.documentElement.setAttribute("ioswebview","")}this.Ia=new Set;this.bc=new WeakSet;this.Zb=!1}qa(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,O)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(b){a=!1}m(this,"window-blur",{parentHasFocus:a},O);this.Ja=0});window.addEventListener("focusin",a=>{a=a.target;(ua.has(a.tagName.toLowerCase())||ta(a))&&m(this,"keyboard-blur",null,O)});window.addEventListener("keydown",a=>Ja(this,"keydown",a));window.addEventListener("keyup",a=>Ja(this,"keyup",a));window.addEventListener("mousedown",a=>V(this,"mousedown",a,N));
window.addEventListener("mousemove",a=>V(this,"mousemove",a,N));window.addEventListener("mouseup",a=>V(this,"mouseup",a,N));window.addEventListener("dblclick",a=>V(this,"dblclick",a,L));window.addEventListener("wheel",a=>{this.s||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.C,pageX:a.pageX,pageY:a.pageY+this.C,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},L)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Ma(a.target)&&
document.activeElement&&!Ma(document.activeElement)&&document.activeElement.blur();W(this,"pointerdown",a)});this.h.m&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{W(this,"pointermove",a)}):window.addEventListener("pointermove",a=>W(this,"pointermove",a));window.addEventListener("pointerup",a=>W(this,"pointerup",a));window.addEventListener("pointercancel",a=>W(this,"pointercancel",a));const c=()=>this.ya();window.addEventListener("pointerup",
c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",c,!0);this.h.ub()&&!this.h.Ta()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{X(this,this.o(),navigator.virtualKeyboard.boundingRect.height)}));this.h.U()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}v(){return this.h.v()}o(){return this.h.o()}ya(){var c=
[...this.Ia];this.Ia.clear();if(!this.Zb)for(const a of c)(c=a.play())&&c.catch(()=>{this.bc.has(a)||this.Ia.add(a)})}wa(c){alert(c.message)}});"use strict";async function la(c){if(c.Yb)throw Error("already initialised");c.Yb=!0;var a=c.B.va(("playable-ad"===c.B.g?c.B.N:"")+"dispatchworker.js");c.Ba=await c.B.sa(a,c.W,{name:"DispatchWorker"});a=new MessageChannel;c.Ea=a.port1;c.Ba.postMessage({type:"_init","in-port":a.port2},[a.port2]);c.Ka=await oa(c)}function ma(c){return[c.Ea,c.Ka]}
async function oa(c){const a=c.nb.length;var b=c.B.va(("playable-ad"===c.B.g?c.B.N:"")+"jobworker.js");b=await c.B.sa(b,c.W,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;c.Ba.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);c.nb.push(b);return e.port1}
self.xb=class{constructor(c){this.B=c;this.W=c.l;this.W="preview"===c.g?this.W+"workers/":this.W+c.N;this.ac=Math.min(navigator.hardwareConcurrency||2,16);this.Ba=null;this.nb=[];this.Ka=this.Ea=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.D({oc:!0,pc:"workermain.js",R:["scripts/c3runtime.js"],oa:[],Pa:"",lc:"scripts/",pa:[],qb:"html5"}));"use strict";
async function Na(c,a){a=a.type;let b=!0;0===a?b=await Oa():1===a&&(b=await Pa());m(c,"permission-result",{type:a,result:b})}async function Oa(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request orientation permission: ",c),!1}}
async function Pa(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request motion permission: ",c),!1}}self.D.ea(class extends self.S{constructor(c){super(c,"touch");t(this,"request-permission",a=>Na(this,a))}});"use strict";let Y=null,Z=null;window.addEventListener("beforeinstallprompt",c=>{c.preventDefault();Y=c;Z&&m(Z,"install-available");return!1});
function Qa(){}function Sa(c){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(c,"sw-message",a.data))}
function Ta(c){c=c.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}async function Ua(){if(!Y)return{result:"unavailable"};try{return Y.prompt(),{result:(await Y.userChoice).outcome}}catch(c){return console.error("[Construct] Requesting install failed: ",c),{result:"failed"}}}
self.D.ea(class extends self.S{constructor(c){super(c,"browser");this.g="";u(this,[["get-initial-state",a=>{this.g=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Sa(this)],["alert",a=>this.wa(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.xa(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Ta(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,
"_system"):"preview"===a||this.h.u()?window.open(b,"_blank"):this.uc||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if(this.h.u()||"macos-wkwebview"===this.g)self.D.ja(!0),this.h.F({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&
(b.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(b):a.mozRequestFullScreen?d=a.mozRequestFullScreen(b):a.msRequestFullscreen?d=a.msRequestFullscreen(b):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Qa)}}],["exit-fullscreen",()=>{if(this.h.u()||"macos-wkwebview"===this.g)self.D.ja(!1),this.h.F({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Qa)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const b=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var h=
document.querySelector(e);f=h?[h]:[]}else f=[document.documentElement];e=f;for(const g of e)b.startsWith("--")?g.style.setProperty(b,d):g.style[b]=d}catch(g){console.warn("[Browser] Failed to set style: ",g)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var b=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),b={isOk:!1}}}return b}],["set-window-size",a=>{window.resizeTo(a.windowWidth,
a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}],["request-install",()=>Ua()],["set-warn-on-close",a=>{a.enabled?window.addEventListener("beforeunload",this.gb):window.removeEventListener("beforeunload",this.gb)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});this.gb=
a=>a.preventDefault();document.addEventListener("backbutton",()=>{m(this,"backbutton")})}qa(){Y?m(this,"install-available"):Z=this;window.addEventListener("appinstalled",()=>{m(this,"app-installed")})}wa(c){alert(c.message)}xa(c){c=c.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():null;c?a.focus():a.blur()}else c?window.focus():window.blur()}});"use strict";
function Va(c){return new Promise((a,b)=>{const d=new FileReader;d.onload=()=>a(d.result);d.onerror=()=>b(d.error);d.readAsArrayBuffer(c)})}async function Wa(c,a){a=a.text;let b=!1;try{await navigator.clipboard.writeText(a),b=!0}catch(d){console.error("Failed to copy to clipboard: ",d),b=!1}m(c,"copy-result",{isOk:b})}
async function Xa(c,a){const b=a.arrayBuffer;a=a.type;let d=!1;try{const e={};e[a]=new Blob([b],{type:a});await navigator.clipboard.write([new ClipboardItem(e)]);d=!0}catch(e){console.error("Failed to copy to clipboard: ",e),d=!1}m(c,"copy-result",{isOk:d})}async function Ya(c){let a=!1,b="";try{b=await navigator.clipboard.readText(),a=!0}catch(d){console.error("Failed to paste: ",d),b="",a=!1}m(c,"request-paste-text-result",{isOk:a,text:b})}
async function Za(c){let a=!1,b=[];try{var d=await navigator.clipboard.read();if(1<=d.length){const e=d[0];d=[];const f=e.types;for(const h of f)d.push((async()=>{const g=await e.getType(h);return await Va(g)})());b=(await Promise.all(d)).map((h,g)=>[f[g],h]);a=!0}else a=!1}catch(e){console.error("Failed to paste: ",e),a=!1}m(c,"request-paste-binary-result",{isOk:a,binary:b})}
async function $a(c,a){if((new Set(["canvas","body","html"])).has((a.target.tagName||"").toLowerCase())){a.preventDefault();var b=a.clipboardData.getData("text");b?m(c,"window-paste-text",{text:b}):1<=a.clipboardData.files.length&&(a=a.clipboardData.files[0],b=await Va(a),m(c,"window-paste-binary",{arrayBuffer:b,type:a.type}))}}
self.D.ea(class extends self.S{constructor(c){super(c,"clipboard");u(this,[["copy-text",a=>Wa(this,a)],["copy-binary",a=>Xa(this,a)],["request-paste-text",()=>Ya(this)],["request-paste-binary",()=>Za(this)]]);window.addEventListener("paste",a=>$a(this,a))}});
