function m(c,a,b,d){c.h.ja(c.$,a,b,d)}function r(c,a,b,d){c.h.m?m(c,a,b,d):c.h.Nb()._OnMessageFromDOM({type:"event",component:c.$,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function t(c,a,b){c.h.i(c.$,a,b)}function u(c,a){for(const [b,d]of a)t(c,b,d)}window.V=class{constructor(c,a){this.h=c;this.$=a}sa(){}};window.wc=class{constructor(){}};"use strict";class aa{constructor(c){this.aa=c;this.Ja=!1;this.Ma=!0;this.ba=this.A=this.Va=-1}}
function ba(c,a){const b=a.elementId,d=c.Za(b,a),e=new aa(d);c.I.set(b,e);d.style.boxSizing="border-box";d.style.display="none";e.Ma=!!a.isVisible;d.addEventListener("focus",()=>{v(c,"elem-focused",b)});d.addEventListener("blur",()=>{v(c,"elem-blurred",b)});const f=a.htmlIndex;e.Va=f;e.ba=a.htmlZIndex;c.M&&(a=c.h.wa(f),e.A=a,c.h.W(a).appendChild(d))}function ca(c,a,b){t(c,a,d=>{const e=w(c,d.elementId);return b(e,d)})}
function w(c,a){c=c.I.get(a);if(!c)throw Error(`no element with id ${a}`);return c.aa}function v(c,a,b,d){d||(d={});d.elementId=b;m(c,a,d)}function da(c,a,b){var d;d||(d={});d.elementId=b;r(c,a,d)}
window.va=class extends self.V{constructor(c){super(c,"text-input");this.I=new Map;this.M=!0;u(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const b=w(this,a);this.M&&b.parentElement.removeChild(b);this.I.delete(a)}],["set-visible",a=>{if(this.M){var b=this.I.get(a.elementId),d=b.aa;b.Ja?d.style.display=a.isVisible?"":"none":b.Ma=!!a.isVisible}}],["update-position",a=>{if(this.M){var b=this.I.get(a.elementId),d=b.aa,e=this.h;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";var f=a.fontSize;null!==f&&(d.style.fontSize=f+"em");f=a.htmlIndex;b.Va=f;f=e.wa(f);f!==b.A&&(d.remove(),e.W(f).appendChild(d),b.A=f,e.Ga());a=a.htmlZIndex;a!==b.ba&&(b.ba=a,e.Ga());b.Ja||(b.Ja=!0,b.Ma&&(d.style.display=""))}}],["update-state",a=>{const b=w(this,a.elementId);this.ya(b,a)}],["focus",a=>this.Da(a)],["set-css-style",a=>{const b=w(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?b.style.setProperty(d,a):b.style[d]=a}],["set-attribute",a=>
{w(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{w(this,a.elementId).removeAttribute(a.name)}]]);ca(this,"get-element",a=>a)}Za(){throw Error("required override");}ya(){throw Error("required override");}Da(c){var a=w(this,c.elementId);c.focus?a.focus():a.blur()}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent),fa=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);
let ha=0;function y(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.mc?new Promise(b=>{const d="c3_resolve_"+ha;++ha;self[d]=b;a.textContent=c.qc+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((b,d)=>{a.onload=b;a.onerror=d;a.src=c;document.head.appendChild(a)})}
async function ia(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let c=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){c=!0}}),b=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return c&&b}catch(c){return console.warn("Error feature detecting worker mode: ",c),!1}}let z=new Audio;
const ja={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function ka(c){c=await la(c);return(new TextDecoder("utf-8")).decode(c)}
function la(c){return new Promise((a,b)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsArrayBuffer(c)})}const A=[];let B=0;window.RealFile=window.File;const D=[],E=new Map,F=new Map;let ma=0;const na=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");na.push(c)};const oa=new Set(["cordova","playable-ad","instant-games"]);let pa=!1;
window.C=class c{constructor(a){this.m=a.sc;this.ea=null;this.l="";this.P=a.pc;this.ha={};this.Oa=this.S=null;this.N=[];this.J=null;this.sb=!0;this.j=[];this.Sa=[];this.Ta=!1;this.ub=()=>this.Lb();this.rb=!1;this.ca=null;this.O=-1;this.ic=()=>this.Wb();this.fa=new Set;this.Wa=null;this.vb=[];this.g=a.wb;this.La="file"===location.protocol.substr(0,4);if("playable-ad"===this.g||"instant-games"===this.g)this.m=!1;fa&&(this.m=!1);if("cordova"===this.g&&this.m&&x){const b=/Chrome\/(\d+)/i.exec(navigator.userAgent);
b&&90<=parseInt(b[1],10)||(this.m=!1)}this.u()?self.chrome.webview.addEventListener("message",b=>this.jb(b.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=b=>this.jb(b));this.na=this.B=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.i("canvas","update-size",b=>this.$b(b));this.i("canvas","set-html-layer-count",
b=>this._OnSetHTMLLayerCount(b));this.i("canvas","cleanup-html-layers",()=>this.Rb());this.i("runtime","cordova-fetch-local-file",b=>this.Sb(b));this.i("runtime","create-job-worker",()=>this.Tb());this.i("runtime","send-wrapper-extension-message",b=>this.Zb(b));"cordova"===this.g?document.addEventListener("deviceready",()=>this.hb(a)):this.hb(a)}yb(){return this.j[0].canvas}wa(a){return Math.min(a,this.j.length-1)}W(a){if(0>a||a>=this.j.length)throw new RangeError("invalid canvas layer");return this.j[a].ia}_GetHTMLWrapElement(a){return this.W(a)}Cb(){return ea&&
"cordova"===this.g}Y(){const a=navigator.userAgent;return ea&&oa.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Ab(){return x}$a(){return x&&oa.has(this.g)}ab(){return"windows-webview2"===this.g||!!("preview"===this.g&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}u(){return this.ab()||"xbox-uwp-webview2"===this.g}async hb(a){this.m&&!await ia()&&(this.m=!1);"macos-wkwebview"===this.g?this.G({type:"ready"}):this.u()&&(this.cc(),this.vb=(await this.Qb()).registeredComponentIds);
if("playable-ad"===this.g){this.B=self.c3_base64files;this.na={};await this.Ib();for(let d=0,e=a.T.length;d<e;++d){var b=a.T[d];this.na.hasOwnProperty(b)?a.T[d]={mc:!0,qc:this.na[b]}:this.B.hasOwnProperty(b)&&(a.T[d]=URL.createObjectURL(this.B[b]))}a.ra=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.bb(()=>{d++;document.documentElement.style.opacity=0===d%2?"1":"0.999"})}a.oc?this.l=a.oc:(b=location.origin,this.l=("null"===b?"file:///":b)+location.pathname,b=this.l.lastIndexOf("/"),
-1!==b&&(this.l=this.l.substr(0,b+1)));a.uc&&(this.ha=a.uc);b=new MessageChannel;this.ea=b.port1;this.ea.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Vb(d));this.ca=new self.Db(this);await qa(this.ca);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.m?await this.Pb(a,b.port2):await this.Ob(a,b.port2)}Aa(a){a=this.ha.hasOwnProperty(a)?this.ha[a]:a.endsWith("/workermain.js")&&this.ha.hasOwnProperty("workermain.js")?this.ha["workermain.js"]:"playable-ad"===this.g&&this.B.hasOwnProperty(a)?this.B[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ua(a,b,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.La)return a=await this.ta(d.lc?a:this.P+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,b);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}v(){return Math.max(window.innerWidth,1)}o(){return Math.max(window.innerHeight,1)}xa(){return this.u()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.g)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?
"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}gb(a){var b=this.l,d=location.href,e=this.v(),f=this.o(),h=this.xa(),g=window.devicePixelRatio,k=c.X(),l=a.Ac,n=window.cr_previewImageBlobs||this.B,p=window.cr_previewProjectFileBlobs,q=window.cr_previewProjectFiles,Ea=window.cr_swClientId||"";a=a.wb;var Fa=(new URLSearchParams(self.location.search)).has("debug"),O=this.ca;return{runtimeBaseUrl:b,previewUrl:d,windowInnerWidth:e,
windowInnerHeight:f,cssDisplayMode:h,devicePixelRatio:g,isFullscreen:k,projectData:l,previewImageBlobs:n,previewProjectFileBlobs:p,previewProjectFileSWUrls:q,swClientId:Ea,exportType:a,isDebug:Fa,ife:!!self.zc,jobScheduler:{inputPort:O.Ka,outputPort:O.Ra,maxNumWorkers:O.fc},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.P+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.P+"opus.wasm.wasm",isFileProtocol:this.La,isiOSCordova:this.Cb(),isiOSWebView:this.Y(),
isWindowsWebView2:this.ab(),isAnyWebView2Wrapper:this.u(),wrapperComponentIds:this.vb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Pb(a,b){const d=this.Aa(a.tc);"preview"===this.g?(this.S=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,n)=>{const p=q=>{this.S.removeEventListener("message",p);q.data&&"ok"===q.data.type?l():n()};this.S.addEventListener("message",p);this.S.postMessage({type:"construct-worker-init","import":(new URL(d,this.l)).toString()})})):
this.S=await this.ua(d,this.l,{type:"module",name:"Runtime",lc:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const h=document.createElement("div");h.className="c3htmlwrap";document.body.appendChild(h);this.j.push({canvas:e,ia:h});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let g=a.ra||[],k=a.T;g=await Promise.all(g.map(l=>this.L(l)));k=await Promise.all(k.map(l=>this.L(l)));
if("cordova"===this.g)for(let l=0,n=a.qa.length;l<n;++l){const p=a.qa[l],q=p[0];if(q===a.Xa||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.L(q)}this.S.postMessage(Object.assign(this.gb(a),{type:"init-runtime",isInWorker:!0,messagePort:b,canvas:f,workerDependencyScripts:g,engineScripts:k,projectScripts:a.qa,mainProjectScript:a.Xa,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[b,f,...ra(this.ca)]);this.N=D.map(l=>new l(this));this.fb();G(e);H(h);sa(this.J);self.c3_callFunction=
(l,n)=>{var p=this.J;return p.h.Eb(p.$,{name:l,params:n})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.ja("runtime","go-to-last-error-script"))}async Ob(a,b){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.j.push({canvas:d,ia:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.N=D.map(g=>new g(this));this.fb();
G(d);H(e);e=a.T.map(g=>"string"===typeof g?(new URL(g,this.l)).toString():g);if(Array.isArray(a.ra)){var f=[...a.ra].map(g=>g instanceof Blob?URL.createObjectURL(g):g);e.unshift(...f)}e=await Promise.all(e.map(g=>this.L(g)));await Promise.all(e.map(g=>y(g)));e=self.C3_ProjectScriptsStatus;f=a.Xa;const h=a.qa;for(let [g,k]of h)if(k||(k=g),g===f)try{k=await this.L(k),await y(k),"preview"!==this.g||e[g]||this.kb(g,"main script did not run to completion")}catch(l){this.kb(g,l)}else if("scriptsInEvents.js"===
g||g.endsWith("/scriptsInEvents.js"))k=await this.L(k),await y(k);"preview"===this.g&&"object"!==typeof self.vc.xc?(this.la(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.gb(a),{isInWorker:!1,messagePort:b,canvas:d,runOnStartupFunctions:na}),sa(this.J),this.ib(),this.Oa=self.C3_CreateRuntime(a),
await self.C3_InitRuntime(this.Oa,a))}kb(a,b){this.la();console.error(`[Preview] Failed to load project main script (${a}): `,b);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}ib(){this.la()}la(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Tb(){const a=await ta(this.ca);return{outputPort:a,transferables:[a]}}$b(a){if(!this.rb){var b=
a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:h,ia:g}of this.j)h.style.width=b,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,g.style.width=b,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,this.sb&&(h.style.display="",g.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.sb=!1}}_OnSetHTMLLayerCount(a){var b=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const h=
a.marginLeft+"px",g=a.marginTop+"px";a=[];const k=[];if(b<this.j.length)for(;this.j.length>b;){const {canvas:l,ia:n}=this.j.pop();n.remove();this.m&&!d?this.Sa.push(l):l.remove()}else if(b>this.j.length)for(let l=0,n=b-this.j.length;l<n;++l)b=document.createElement("canvas"),b.classList.add("c3overlay"),this.m?(d=b.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(b),document.body.appendChild(b),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),
b.style.width=e,b.style.height=f,b.style.marginLeft=h,b.style.marginTop=g,d.style.width=e,d.style.height=f,d.style.marginLeft=h,d.style.marginTop=g,G(b),H(d),this.j.push({canvas:b,ia:d});for(const l of this.N)if(l instanceof window.va&&l.M)for(const n of l.I.values())e=l.h.wa(n.Va),f=n.A,-1!==e&&-1!==f&&e!==f&&(f=n.aa,f.remove(),l.h.W(e).appendChild(f),n.A=e);this.Ga();return{addedCanvases:a,transferables:k}}Rb(){for(const a of this.Sa)a.remove();this.Sa.length=0}Ga(){this.Ta||(this.Ta=!0,this.bb(this.ub))}Lb(){this.bc(this.ub);
this.Ta=!1;let a=[];for(var b of this.N)if(b instanceof window.va){var d=b.M?[...b.I.values()]:null;d&&a.push(...d)}a.sort((h,g)=>{const k=h.A,l=g.A;return k!==l?k-l:h.ba-g.ba});let e=d=b=0,f=a.length;for(;e<f;++e){const h=a[e];h.A!==b&&(this.eb(b,a.slice(d,e)),b=h.A,d=e)}d<e&&this.eb(b,a.slice(d,e))}eb(a,b){if(!(1>=b.length||a>=this.j.length)){b=b.map(k=>k.aa);var d=new Set(b);a=this.W(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,h=Math.min(b.length,e.length);f<h&&b[f]===e[f];++f);
for(var g=f;g<h;++g)e[g].remove();for(g=f;g<h;++g)a.appendChild(b[g])}}Nb(){if(this.m)throw Error("not available in worker mode");return this.Oa}ja(a,b,d,e){this.ea.postMessage({type:"event",component:a,handler:b,dispatchOpts:e||null,data:d,responseId:null},void 0)}Eb(a,b){const d=ma++,e=new Promise((f,h)=>{F.set(d,{resolve:f,reject:h})});this.ea.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:b,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const b=
a.type;if("event"===b)return this.Ub(a);if("result"===b)this.Xb(a);else if("runtime-ready"===b)this.Yb();else if("alert-error"===b)this.la(),alert(a.message);else if("creating-runtime"===b)this.ib();else throw Error(`unknown message '${b}'`);}Ub(a){const b=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=E.get(b))if(a=a.get(d)){var h=null;try{h=a(e)}catch(g){console.error(`Exception in '${b}' handler '${d}':`,g);null!==f&&this.ka(f,!1,""+g);return}if(null===f)return h;h&&h.then?h.then(g=>this.ka(f,
!0,g)).catch(g=>{console.error(`Rejection from '${b}' handler '${d}':`,g);this.ka(f,!1,""+g)}):this.ka(f,!0,h)}else console.warn(`[DOM] No handler '${d}' for component '${b}'`);else console.warn(`[DOM] No event handlers for component '${b}'`)}ka(a,b,d){let e;d&&d.transferables&&(e=d.transferables);this.ea.postMessage({type:"result",responseId:a,isOk:b,result:d},e)}Xb(a){const b=a.responseId,d=a.isOk;a=a.result;const e=F.get(b);d?e.resolve(a):e.reject(a);F.delete(b)}i(a,b,d){let e=E.get(a);e||(e=new Map,
E.set(a,e));if(e.has(b))throw Error(`[DOM] Component '${a}' already has handler '${b}'`);e.set(b,d)}static U(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}fb(){for(const a of this.N)if("runtime"===a.$){this.J=a;return}throw Error("cannot find runtime DOM handler");}Vb(a){this.ja("debugger","message",a)}Yb(){for(const a of this.N)a.sa()}static X(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||pa)}static ma(a){pa=!!a}bb(a){this.fa.add(a);
this.Fa()}bc(a){this.fa.delete(a);0===this.fa.size&&this.cb()}Fa(){-1===this.O&&0<this.fa.size&&(this.O=requestAnimationFrame(this.ic))}cb(){-1!==this.O&&(cancelAnimationFrame(this.O),this.O=-1)}Wb(){this.O=-1;for(const a of this.fa)a();this.Fa()}Ea(){this.J.Ea()}Fb(){this.rb=!0}zb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Bb(a){return!this.zb(a)}async L(a){return"cordova"===this.g&&(a.startsWith("file:")||this.La&&this.Bb(a))?(a.startsWith(this.l)&&
(a=a.substr(this.l.length)),a=await this.ta(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Sb(a){const b=a.filename;switch(a.as){case "text":return await this.xb(b);case "buffer":return await this.ta(b);default:throw Error("unsupported type");}}Ya(a){const b=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(b,f=>{f.file(d,e)},e)})}async xb(a){a=await this.Ya(a);return await ka(a)}za(){if(A.length&&!(8<=B)){B++;
var a=A.shift();this.Jb(a.filename,a.rc,a.kc)}}ta(a){return new Promise((b,d)=>{A.push({filename:a,rc:e=>{B--;this.za();b(e)},kc:e=>{B--;this.za();d(e)}});this.za()})}async Jb(a,b,d){try{const e=await this.Ya(a),f=await la(e);b(f)}catch(e){d(e)}}jb(a){if("entered-fullscreen"===a)c.ma(!0),I(this.J);else if("exited-fullscreen"===a)c.ma(!1),I(this.J);else if("object"===typeof a){const b=a.type;"directory-handles"!==b&&("wrapper-init-response"===b?(this.Wa(a),this.Wa=null):"extension-message"===b?this.ja("runtime",
"wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a))}else console.warn("Unknown wrapper message: ",a)}Zb(a){this.G({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}G(a){this.u()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}cc(){window.moveTo=(a,b)=>{this.G({type:"set-window-position",windowX:Math.ceil(a),
windowY:Math.ceil(b)})};window.resizeTo=(a,b)=>{this.G({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(b)})}}Qb(){return this.u()?new Promise(a=>{this.Wa=a;this.G({type:"wrapper-init"})}):Promise.resolve()}async Ib(){const a=[];for(const [b,d]of Object.entries(this.B))a.push(this.Hb(b,d));await Promise.all(a)}async Hb(a,b){if("object"===typeof b)this.B[a]=new Blob([b.str],{type:b.type}),this.na[a]=b.str;else{let d=await this.Mb(b);d||(d=this.Kb(b));this.B[a]=d}}async Mb(a){try{return await (await fetch(a)).blob()}catch(b){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
b),null}}Kb(a){a=this.ac(a);return this.Gb(a.data,a.nc)}ac(a){var b=a.indexOf(",");if(0>b)throw new URIError("expected comma in data: uri");var d=a.substring(b+1);b=a.substring(5,b).split(";");a=b[0]||"";const e=b[2];d="base64"===b[1]||"base64"===e?atob(d):decodeURIComponent(d);return{nc:a,data:d}}Gb(a,b){var d=a.length;let e=d>>2,f=new Uint8Array(d),h=new Uint32Array(f.buffer,0,e),g,k;for(k=g=0;g<e;++g)h[g]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:b})}};"use strict";const J=self.C,ua=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},L={dispatchUserScriptEvent:!0},M={dispatchRuntimeEvent:!0};function wa(c){return new Promise((a,b)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>b(e);d.rel="stylesheet";d.href=c;document.head.appendChild(d)})}
function xa(c){return new Promise((a,b)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>b(e);d.src=c})}async function ya(c){c=URL.createObjectURL(c);try{return await xa(c)}finally{URL.revokeObjectURL(c)}}function za(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const Aa=new Set(["input","textarea","datalist","select"]),Ba=new Set(["canvas","body","html"]);
function N(c){c.target.tagName&&Ba.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function P(c){c.target.tagName&&c.target.classList.contains("c3htmlwrap")&&c.preventDefault()}function Ca(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}
self.C3_GetSvgImageSize=async function(c){c=await ya(c);if(0<c.width&&0<c.height)return[c.width,c.height];c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const a=c.getBoundingClientRect();document.body.removeChild(c);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(c,a,b,d,e){c=await ya(c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(c,0,0,a,b);return f};
let Q=!1;document.addEventListener("pause",()=>Q=!0);document.addEventListener("resume",()=>Q=!1);function G(c){c.addEventListener("selectstart",N);c.addEventListener("gesturehold",N);c.addEventListener("pointerdown",N)}function H(c){c.addEventListener("selectstart",P);c.addEventListener("gesturehold",P);c.addEventListener("touchstart",P)}function sa(c){c.pb=!0;c.Na=c.h.v();c.da=c.h.o()}
function I(c){if(!c.s){var a=J.X();a&&"any"!==c.Ua&&Da(c);m(c,"fullscreenchange",{isFullscreen:a,innerWidth:c.v(),innerHeight:c.o()})}}async function Ga(c){await Promise.all(c.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ha(c){var a=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);a=a?await createImageBitmap(c,a):await createImageBitmap(c);return{imageBitmap:a,transferables:[a]}}async function Ia(c){return await self.C3_GetSvgImageSize(c.blob)}function Ja(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}
function Ka(c){self.setTimeout(()=>{c.ob=!0},1E3);"cordova"===c.h.g?(document.addEventListener("pause",()=>R(c,!0)),document.addEventListener("resume",()=>R(c,!1))):document.addEventListener("visibilitychange",()=>R(c,"hidden"===document.visibilityState));c.oa=!("hidden"!==document.visibilityState&&!Q);return{isSuspended:c.oa}}
function La(c){c.mb||(c.mb=!0,window.addEventListener("deviceorientation",a=>{c.s||m(c,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{c.s||m(c,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Ma(c){c.lb||(c.lb=!0,window.addEventListener("devicemotion",a=>{if(!c.s){var b=null,d=a.acceleration;d&&(b={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(c,"devicemotion",{acceleration:b,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Na(c){await wa(c.url)}
function Oa(c,a){c.qb=a.message;-1===c.Ia&&(c.Ia=setTimeout(()=>{c.Ia=-1;const b=document.getElementById("exportToVideoMessage");b&&(b.textContent=c.qb)},250))}function S(c,a){console.warn("[Construct] Fullscreen request failed: ",a);m(c,"fullscreenerror",{isFullscreen:J.X(),innerWidth:c.v(),innerHeight:c.o()})}
function R(c,a){c.oa!==a&&((c.oa=a)?c.h.cb():c.h.Fa(),m(c,"visibilitychange",{hidden:a}),!a&&c.h.Y()&&(c=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(c,50),setTimeout(c,100),setTimeout(c,250),setTimeout(c,500)))}
function Pa(c,a,b){"Backspace"===b.key&&N(b);"nwjs"===c.h.g&&"u"===b.key&&(b.ctrlKey||b.metaKey)&&b.preventDefault();if(!c.s){var d=ua.get(b.code)||b.code;r(c,a,{code:d,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,metaKey:b.metaKey,shiftKey:b.shiftKey,timeStamp:b.timeStamp},K)}}
function T(c,a,b,d){c.s||b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents||r(c,a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY+c.F,pageX:b.pageX,pageY:b.pageY+c.F,movementX:b.movementX||0,movementY:b.movementY||0,timeStamp:b.timeStamp},d)}
function U(c,a,b){if(!c.s){var d=0;"mouse"===b.pointerType&&(d=c.Qa);r(c,a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,buttons:b.buttons,lastButtons:d,clientX:b.clientX,clientY:b.clientY+c.F,pageX:b.pageX,pageY:b.pageY+c.F,movementX:b.movementX||0,movementY:b.movementY||0,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},K);"mouse"===b.pointerType&&(c.Qa=
b.buttons)}}function W(c,a,b){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";c.F=0;if(0<b){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-b)/2,a>b&&(a=b),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,c.F=a))}}
function Qa(c,a,b,d){const e=c.v(),f=c.o();c.R=-1;e!=a||f!=b?m(c,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.X(),cssDisplayMode:c.h.xa()}):10>d&&Ra(c,e,f,d+1)}function Ra(c,a,b,d){-1!==c.R&&clearTimeout(c.R);c.R=setTimeout(()=>Qa(c,a,b,d),48)}
function Da(c){c=c.Ua;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Sa(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}
J.U(class extends self.V{constructor(c){super(c,"runtime");this.pb=!1;this.R=-1;this.Ua="any";this.oa=this.lb=this.mb=!1;this.pa=document.createElement("div");this.pa.className="c3-screen-reader-text";this.pa.setAttribute("aria-live","polite");document.body.appendChild(this.pa);this.H=null;this.s=!1;this.qb="";this.Ia=-1;this.ob=!1;this.Na=c.v();this.da=c.o();this.F=this.ga=0;c.i("runtime","invoke-download",b=>{const d=b.url;b=b.filename;const e=document.createElement("a"),f=document.body;e.textContent=
b;e.href=d;e.download=b;f.appendChild(e);e.click();f.removeChild(e)});c.i("runtime","load-webfonts",b=>Ga(b));c.i("runtime","raster-svg-image",b=>Ha(b));c.i("runtime","get-svg-image-size",b=>Ia(b));c.i("runtime","set-target-orientation",b=>{this.Ua=b.targetOrientation});c.i("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});c.i("runtime","post-to-debugger",b=>Ja(b));c.i("runtime","go-to-script",b=>Ja(b));c.i("runtime","before-start-ticking",()=>Ka(this));c.i("runtime","debug-highlight",
b=>{if(b.show){this.H||(this.H=document.createElement("div"),this.H.id="inspectOutline",document.body.appendChild(this.H));var d=this.H;d.style.display="";d.style.left=b.left-1+"px";d.style.top=b.top-1+"px";d.style.width=b.width+2+"px";d.style.height=b.height+2+"px";d.textContent=b.name}else this.H&&(this.H.style.display="none")});c.i("runtime","enable-device-orientation",()=>La(this));c.i("runtime","enable-device-motion",()=>Ma(this));c.i("runtime","add-stylesheet",b=>Na(b));c.i("runtime","script-create-worker",
b=>{const d=b.port2;(new Worker(b.url,b.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});c.i("runtime","alert",b=>this.Ba(b));c.i("runtime","screen-reader-text",b=>{var d=b.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+b.id,d.textContent=b.text,this.pa.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+b.id))?d.textContent=b.text:console.warn(`[Construct] Missing screen reader text with id ${b.id}`):"release"===d?(d=document.getElementById("c3-sr-"+b.id))?
d.remove():console.warn(`[Construct] Missing screen reader text with id ${b.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});c.i("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});c.i("runtime","set-exporting-to-video",b=>{this.s=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=b.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");this.h.yb().style.display=
"";this.h.Fb()});c.i("runtime","export-to-video-progress",b=>Oa(this,b));c.i("runtime","exported-to-video",b=>{window.jc({type:"exported-video",arrayBuffer:b.arrayBuffer,contentType:b.contentType,time:b.time})});c.i("runtime","exported-to-image-sequence",b=>{window.jc({type:"exported-image-sequence",blobArr:b.blobArr,time:b.time,gif:b.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",b=>{const d=b.target;a.has(d.tagName.toLowerCase())||za(d)||b.preventDefault()});
window.addEventListener("selectstart",N);window.addEventListener("gesturehold",N);window.addEventListener("touchstart",N,{passive:!1});window.addEventListener("pointerdown",N,{passive:!1});this.Qa=0;window.addEventListener("mousedown",b=>{1===b.button&&b.preventDefault()});window.addEventListener("mousewheel",Ca,{passive:!1});window.addEventListener("wheel",Ca,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.s&&this.pb){var b=this.v();var d=this.o();if(this.h.$a()){if(this.ob){if(this.Na===
b&&d<this.da){this.ga=this.da-d;W(this,this.da,this.ga);b=void 0;break a}0<this.ga&&(this.ga=0,W(this,d,this.ga))}this.Na=b;this.da=d}m(this,"window-resize",{innerWidth:b,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.X(),cssDisplayMode:this.h.xa()});this.h.Y()&&(-1!==this.R&&clearTimeout(this.R),Qa(this,b,d,0))}b=void 0}return b});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",
()=>I(this));window.addEventListener("fullscreenerror",b=>S(this,b));window.addEventListener("webkitfullscreenerror",b=>S(this,b));window.addEventListener("mozfullscreenerror",b=>S(this,b));if(c.Y()){let b=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>b&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);b=d});document.documentElement.setAttribute("ioswebview","")}this.Pa=new Set;this.hc=new WeakSet;this.ec=!1}sa(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,M)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(b){a=!1}m(this,"window-blur",{parentHasFocus:a},M);this.Qa=0});window.addEventListener("focusin",a=>{a=a.target;(Aa.has(a.tagName.toLowerCase())||za(a))&&m(this,"keyboard-blur",null,M)});window.addEventListener("keydown",a=>Pa(this,"keydown",a));window.addEventListener("keyup",a=>Pa(this,"keyup",a));window.addEventListener("mousedown",a=>T(this,"mousedown",a,L));
window.addEventListener("mousemove",a=>T(this,"mousemove",a,L));window.addEventListener("mouseup",a=>T(this,"mouseup",a,L));window.addEventListener("dblclick",a=>T(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.s||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.F,pageX:a.pageX,pageY:a.pageY+this.F,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Sa(a.target)&&
document.activeElement&&!Sa(document.activeElement)&&document.activeElement.blur();U(this,"pointerdown",a)});this.h.m&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{U(this,"pointermove",a)}):window.addEventListener("pointermove",a=>U(this,"pointermove",a));window.addEventListener("pointerup",a=>U(this,"pointerup",a));window.addEventListener("pointercancel",a=>U(this,"pointercancel",a));const c=()=>this.Ea();window.addEventListener("pointerup",
c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",c,!0);this.h.Ab()&&!this.h.$a()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{W(this,this.o(),navigator.virtualKeyboard.boundingRect.height)}));this.h.Y()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}v(){return this.h.v()}o(){return this.h.o()}Ea(){var c=
[...this.Pa];this.Pa.clear();if(!this.ec)for(const a of c)(c=a.play())&&c.catch(()=>{this.hc.has(a)||this.Pa.add(a)})}Ba(c){alert(c.message)}});"use strict";async function qa(c){if(c.dc)throw Error("already initialised");c.dc=!0;var a=c.D.Aa(("playable-ad"===c.D.g?c.D.P:"")+"dispatchworker.js");c.Ha=await c.D.ua(a,c.Z,{name:"DispatchWorker"});a=new MessageChannel;c.Ka=a.port1;c.Ha.postMessage({type:"_init","in-port":a.port2},[a.port2]);c.Ra=await ta(c)}function ra(c){return[c.Ka,c.Ra]}
async function ta(c){const a=c.tb.length;var b=c.D.Aa(("playable-ad"===c.D.g?c.D.P:"")+"jobworker.js");b=await c.D.ua(b,c.Z,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;c.Ha.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);c.tb.push(b);return e.port1}
self.Db=class{constructor(c){this.D=c;this.Z=c.l;this.Z="preview"===c.g?this.Z+"workers/":this.Z+c.P;this.fc=Math.min(navigator.hardwareConcurrency||2,16);this.Ha=null;this.tb=[];this.Ra=this.Ka=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.C({sc:!1,tc:"workermain.js",T:["scripts/c3runtime.js"],qa:[],Xa:"",pc:"scripts/",ra:[],wb:"html5"}));"use strict";
async function Ta(c,a){a=a.type;let b=!0;0===a?b=await Ua():1===a&&(b=await Va());m(c,"permission-result",{type:a,result:b})}async function Ua(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request orientation permission: ",c),!1}}
async function Va(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request motion permission: ",c),!1}}self.C.U(class extends self.V{constructor(c){super(c,"touch");t(this,"request-permission",a=>Ta(this,a))}});"use strict";let X=null,Y=null;window.addEventListener("beforeinstallprompt",c=>{c.preventDefault();X=c;Y&&m(Y,"install-available");return!1});
function Wa(){}function Xa(c){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(c,"sw-message",a.data))}
function Ya(c){c=c.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}async function Za(){if(!X)return{result:"unavailable"};try{return X.prompt(),{result:(await X.userChoice).outcome}}catch(c){return console.error("[Construct] Requesting install failed: ",c),{result:"failed"}}}
self.C.U(class extends self.V{constructor(c){super(c,"browser");this.g="";u(this,[["get-initial-state",a=>this.Ca(a)],["ready-for-sw-messages",()=>Xa(this)],["alert",a=>this.Ba(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Da(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Ya(a)],["unlock-orientation",()=>{try{screen.orientation&&
screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();
else if("url"===b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a||this.h.u()?window.open(b,"_blank"):this.yc||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if(this.h.u()||"macos-wkwebview"===this.g)self.C.ma(!0),
this.h.G({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(b):a.mozRequestFullScreen?d=a.mozRequestFullScreen(b):a.msRequestFullscreen?d=a.msRequestFullscreen(b):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof
Promise&&d.catch(Wa)}}],["exit-fullscreen",()=>{if(this.h.u()||"macos-wkwebview"===this.g)self.C.ma(!1),this.h.G({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Wa)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",
a=>{const b=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var h=document.querySelector(e);f=h?[h]:[]}else f=[document.documentElement];e=f;for(const g of e)b.startsWith("--")?g.style.setProperty(b,d):g.style[b]=d}catch(g){console.warn("[Browser] Failed to set style: ",g)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var b=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:
{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),b={isOk:!1}}}return b}],["set-window-size",a=>{window.resizeTo(a.windowWidth,a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}],["request-install",()=>Za()],["set-warn-on-close",a=>{a.enabled?window.addEventListener("beforeunload",this.nb):window.removeEventListener("beforeunload",this.nb)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",
()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});this.nb=a=>a.preventDefault();document.addEventListener("backbutton",()=>{m(this,"backbutton")})}sa(){X?m(this,"install-available"):Y=this;window.addEventListener("appinstalled",()=>{m(this,"app-installed")})}Ca(c){this.g=c.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,
screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}Ba(c){alert(c.message)}Da(c){c=c.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():null;c?a.focus():a.blur()}else c?window.focus():window.blur()}});"use strict";function $a(c){return new Promise((a,b)=>{c.getInsetTop(a,b)})}function ab(c){return new Promise((a,b)=>{c.getInsetRight(a,b)})}
function bb(c){return new Promise((a,b)=>{c.getInsetBottom(a,b)})}function cb(c){return new Promise((a,b)=>{c.getInsetLeft(a,b)})}
async function db(c){if(!c.K)try{c.K=await navigator.wakeLock.request("screen"),c.K.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");c.K=null;m(c,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),m(c,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),m(c,"wake-lock-error")}}
async function eb(c){const a=await fb();m(c,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function fb(){var c=self.AndroidNotch;if(c)try{return await Promise.all([$a(c),ab(c),bb(c),cb(c)])}catch(b){return console.error("[Construct] Failed to get Android safe area inset: ",b),[0,0,0,0]}else{var a=document.body;c=a.style;c.setProperty("--temp-sai-top","env(safe-area-inset-top)");c.setProperty("--temp-sai-right","env(safe-area-inset-right)");c.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");c.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(b=>{b=parseInt(b,10);return isFinite(b)?b:0});c.removeProperty("--temp-sai-top");c.removeProperty("--temp-sai-right");c.removeProperty("--temp-sai-bottom");c.removeProperty("--temp-sai-left");return a}}
self.C.U(class extends self.V{constructor(c){super(c,"platform-info");u(this,[["get-initial-state",()=>this.Ca()],["request-wake-lock",()=>db(this)],["release-wake-lock",()=>{this.K&&(this.K.release(),this.K=null)}]]);window.addEventListener("resize",()=>eb(this));this.K=null}async Ca(){const c=await fb();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:c,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==
typeof nw}}});"use strict";function Z(c){c.stopPropagation()}function gb(c){13!==c.which&&27!==c.which&&c.stopPropagation()}
self.C.U(class extends self.va{constructor(c){super(c);ca(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}Za(c,a){let b;const d=a.type;"textarea"===d?(b=document.createElement("textarea"),b.style.resize="none"):(b=document.createElement("input"),b.type=d);b.style.position="absolute";b.autocomplete="off";b.addEventListener("pointerdown",Z);b.addEventListener("pointermove",Z);b.addEventListener("pointerrawupdate",Z);b.addEventListener("pointerup",Z);b.addEventListener("mousedown",Z);b.addEventListener("mouseup",
Z);b.addEventListener("keydown",gb);b.addEventListener("keyup",gb);b.addEventListener("click",e=>{e.stopPropagation();da(this,"click",c)});b.addEventListener("dblclick",e=>{e.stopPropagation();da(this,"dblclick",c)});b.addEventListener("input",()=>v(this,"change",c,{text:b.value}));a.id&&(b.id=a.id);a.className&&(b.className=a.className);this.ya(b,a);return b}ya(c,a){c.value=a.text;c.placeholder=a.placeholder;c.title=a.title;c.disabled=!a.isEnabled;c.readOnly=a.isReadOnly;c.spellcheck=a.spellCheck;
a=a.maxLength;0>a?c.removeAttribute("maxlength"):c.setAttribute("maxlength",a)}});
