function l(b,a,c,d){b.i.ia(b.L,a,c,d,void 0)}function m(b,a,c,d){b.i.s?l(b,a,c,d):b.i.nb()._OnMessageFromDOM({type:"event",component:b.L,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.i.g(b.L,a,c)}function aa(b,a){for(const [c,d]of a)n(b,c,d)}window.ga=class{constructor(b,a){this.i=b;this.L=a}Aa(){}};window.eb=class{constructor(b){this.Ma=b;this.Ab=5;this.H=-1;this.X=-Infinity;this.Fb=()=>{this.H=-1;this.X=Date.now();this.M=!0;this.Ma();this.M=!1};this.Na=this.M=!1}};
"use strict";function ba(b,a){n(b,"get-element",c=>{const d=b.o.get(c.elementId);return a(d,c)})}
window.Ub=class extends self.ga{constructor(b,a){super(b,a);this.o=new Map;this.na=!0;aa(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=this.o.get(c);this.na&&d.parentElement.removeChild(d);this.o.delete(c)}],["set-visible",c=>{this.na&&(this.o.get(c.elementId).style.display=c.isVisible?"":"none")}],["update-position",c=>{if(this.na){var d=this.o.get(c.elementId);d.style.left=c.left+"px";d.style.top=c.top+"px";d.style.width=c.width+"px";d.style.height=
c.height+"px";c=c.fontSize;null!==c&&(d.style.fontSize=c+"em")}}],["update-state",c=>{this.o.get(c.elementId);throw Error("required override");}],["focus",c=>{const d=this.o.get(c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{this.o.get(c.elementId).style[c.prop]=c.val}],["set-attribute",c=>{this.o.get(c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{this.o.get(c.elementId).removeAttribute(c.name)}]]);ba(this,c=>c)}};"use strict";
const p=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),q=/android/i.test(navigator.userAgent);let t=0;function u(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Kb?new Promise(c=>{const d="c3_resolve_"+t;++t;self[d]=c;a.textContent=b.Ob+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let v=!1,w=!1;
function ca(){if(!v){try{new Worker("blob://",{get type(){w=!0}})}catch(b){}v=!0}return w}let x=new Audio;const da={"audio/webm; codecs=opus":!!x.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!x.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!x.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!x.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!x.canPlayType("audio/mp4"),"audio/mpeg":!!x.canPlayType("audio/mpeg")};x=null;
async function ea(b){b=await y(b);return(new TextDecoder("utf-8")).decode(b)}function y(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const z=[];let A=0;window.RealFile=window.File;const B=[],C=new Map,D=new Map;let fa=0;const E=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");E.push(b)};const F=new Set(["cordova","playable-ad","instant-games"]);let H=!1;
window.ja=class b{constructor(a){this.s=a.Qb;this.O=null;this.m="";this.ca=a.Nb;this.T={};this.sa=this.Va=null;this.W=[];this.j=this.va=null;this.Qa=!1;this.N=null;this.F=-1;this.Eb=()=>this.ub();this.Ua=[];this.h=a.Wa;this.ra="file"===location.protocol.substr(0,4);!this.s||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ca()||(this.s=!1);if("playable-ad"===this.h||"instant-games"===this.h)this.s=!1;if("cordova"===this.h&&this.s)if(q){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.s=!1)}else this.s=!1;this.Z=this.v=null;"html5"!==this.h||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.g("runtime","cordova-fetch-local-file",c=>this.qb(c));this.g("runtime","create-job-worker",()=>this.rb());"cordova"===this.h?document.addEventListener("deviceready",()=>this.Fa(a)):this.Fa(a)}ab(){return p&&
"cordova"===this.h}ha(){const a=navigator.userAgent;return p&&F.has(this.h)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Za(){return q}Ca(){return q&&F.has(this.h)}async Fa(a){"macos-wkwebview"===this.h&&this.yb();if("playable-ad"===this.h){this.v=self.c3_base64files;this.Z={};await this.jb();for(let d=0,e=a.I.length;d<e;++d){var c=a.I[d].toLowerCase();this.Z.hasOwnProperty(c)?a.I[d]={Kb:!0,Ob:this.Z[c]}:this.v.hasOwnProperty(c)&&(a.I[d]=URL.createObjectURL(this.v[c]))}}a.Mb?this.m=
a.Mb:(c=location.origin,this.m=("null"===c?"file:///":c)+location.pathname,c=this.m.lastIndexOf("/"),-1!==c&&(this.m=this.m.substr(0,c+1)));a.Sb&&(this.T=a.Sb);c=new MessageChannel;this.O=c.port1;this.O.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.tb(d));this.N=new self.bb(this);await ha(this.N);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,
e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.s?await this.pb(a,c.port2):await this.ob(a,c.port2)}la(a){a=this.T.hasOwnProperty(a)?this.T[a]:a.endsWith("/workermain.js")&&this.T.hasOwnProperty("workermain.js")?this.T["workermain.js"]:"playable-ad"===this.h&&this.v.hasOwnProperty(a.toLowerCase())?this.v[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async fa(a,c,d){if(a.startsWith("blob:"))return new Worker(a,
d);if("cordova"===this.h&&this.ra)return a=await this.ea(d.Jb?a:this.ca+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}A(){return Math.max(window.innerWidth,1)}u(){return Math.max(window.innerHeight,1)}Ea(a){var c=this.m,d=location.href,e=this.A(),f=this.u(),g=window.devicePixelRatio,
h=b.J(),k=a.Yb,r=window.cr_previewImageBlobs||this.v,pa=window.cr_previewProjectFileBlobs,qa=window.cr_previewProjectFiles,ra=window.Wb||"";a=a.Wa;var sa=(new URLSearchParams(self.location.search)).has("debug"),G=this.N;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:r,previewProjectFileBlobs:pa,previewProjectFileSWUrls:qa,swClientId:ra,exportType:a,isDebug:sa,ife:!!self.Xb,jobScheduler:{inputPort:G.qa,outputPort:G.ua,
maxNumWorkers:G.Cb},supportedAudioFormats:da,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ca+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ca+"opus.wasm.wasm",isFileProtocol:this.ra,isiOSCordova:this.ab(),isiOSWebView:this.ha(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async pb(a,c){var d=this.la(a.Rb);this.Va=await this.fa(d,this.m,{type:"module",name:"Runtime",Jb:!0});this.j=document.createElement("canvas");this.j.style.display="none";d=this.j.transferControlToOffscreen();
document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let e=a.ya||[],f=a.I;e=await Promise.all(e.map(g=>this.C(g)));f=await Promise.all(f.map(g=>this.C(g)));if("cordova"===this.h)for(let g=0,h=a.da.length;g<h;++g){const k=a.da[g],r=k[0];if(r===a.xa||"scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))k[1]=await this.C(r)}this.Va.postMessage(Object.assign(this.Ea(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:d,
workerDependencyScripts:e,engineScripts:f,projectScripts:a.da,mainProjectScript:a.xa,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,d,...ia(this.N)]);this.W=B.map(g=>new g(this));this.Da();self.c3_callFunction=(g,h)=>{var k=this.va;return k.i.cb(k.L,{name:g,params:h})};"preview"===this.h&&(self.goToLastErrorScript=()=>this.ia("runtime","go-to-last-error-script"))}async ob(a,c){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=
this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.W=B.map(g=>new g(this));this.Da();var d=a.I.map(g=>"string"===typeof g?(new URL(g,this.m)).toString():g);Array.isArray(a.ya)&&d.unshift(...a.ya);d=await Promise.all(d.map(g=>this.C(g)));await Promise.all(d.map(g=>u(g)));d=self.C3_ProjectScriptsStatus;const e=a.xa,f=a.da;for(let [g,h]of f)if(h||=g,g===e)try{h=await this.C(h),await u(h),"preview"!==this.h||d[g]||this.Ha(g,"main script did not run to completion")}catch(k){this.Ha(g,
k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.C(h),await u(h);"preview"===this.h&&"object"!==typeof self.Tb.Vb?(this.V(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ea(a),{isInWorker:!1,messagePort:c,canvas:this.j,runOnStartupFunctions:E}),this.Ga(),this.sa=
self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.sa,a))}Ha(a,c){this.V();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ga(){this.V()}V(){const a=window.Hb;a&&(a.parentElement.removeChild(a),window.Hb=null)}async rb(){const a=await I(this.N);return{outputPort:a,transferables:[a]}}nb(){if(this.s)throw Error("not available in worker mode");
return this.sa}ia(a,c,d,e,f){this.O.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}cb(a,c){const d=fa++,e=new Promise((f,g)=>{D.set(d,{resolve:f,reject:g})});this.O.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.sb(a);if("result"===c)this.vb(a);else if("runtime-ready"===c)this.wb();else if("alert-error"===c)this.V(),
alert(a.message);else if("creating-runtime"===c)this.Ga();else throw Error(`unknown message '${c}'`);}sb(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=C.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.U(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.U(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.U(f,!1,""+h)}):this.U(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);
else console.warn(`[DOM] No event handlers for component '${c}'`)}U(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.O.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}vb(a){const c=a.responseId,d=a.isOk;a=a.result;const e=D.get(c);d?e.resolve(a):e.reject(a);D.delete(c)}g(a,c,d){let e=C.get(a);e||(e=new Map,C.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static za(a){if(B.includes(a))throw Error("DOM handler already added");B.push(a)}Da(){for(const a of this.W)if("runtime"===
a.L){this.va=a;return}throw Error("cannot find runtime DOM handler");}tb(a){this.ia("debugger","message",a)}wb(){for(const a of this.W)a.Aa()}static J(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||H)}static Ja(a){H=!!a}Ia(){-1===this.F&&this.Ua.length&&(this.F=requestAnimationFrame(this.Eb))}hb(){-1!==this.F&&(cancelAnimationFrame(this.F),this.F=-1)}ub(){this.F=-1;for(const a of this.Ua)a();this.Ia()}ma(){this.va.ma()}fb(){this.Qa=!0}Ya(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||
"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}$a(a){return!this.Ya(a)}async C(a){return"cordova"===this.h&&(a.startsWith("file:")||this.ra&&this.$a(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.ea(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async qb(a){const c=a.filename;switch(a.as){case "text":return await this.Xa(c);case "buffer":return await this.ea(c);default:throw Error("unsupported type");}}Ba(a){const c=window.cordova.file.applicationDirectory+
"www/"+a.toLowerCase();return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Xa(a){a=await this.Ba(a);return await ea(a)}ka(){if(z.length&&!(8<=A)){A++;var a=z.shift();this.kb(a.filename,a.Pb,a.Ib)}}ea(a){return new Promise((c,d)=>{z.push({filename:a,Pb:e=>{A--;this.ka();c(e)},Ib:e=>{A--;this.ka();d(e)}});this.ka()})}async kb(a,c,d){try{const e=await this.Ba(a),f=await y(e);c(f)}catch(e){d(e)}}yb(){var a={type:"ready"};if("windows-webview2"===this.h)window.chrome.webview.postMessage(JSON.stringify(a));
else if("macos-wkwebview"===this.h)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async jb(){const a=[];for(const [c,d]of Object.entries(this.v))a.push(this.ib(c,d));await Promise.all(a)}async ib(a,c){if("object"===typeof c)this.v[a]=new Blob([c.str],{type:c.type}),this.Z[a]=c.str;else{let d=await this.mb(c);d||=this.lb(c);this.v[a]=d}}async mb(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}lb(a){a=this.xb(a);return this.gb(a.data,a.Lb)}xb(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Lb:a,data:d}}gb(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const J=self.ja;function K(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const ka=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),L={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},la={dispatchUserScriptEvent:!0},M={dispatchRuntimeEvent:!0};
function ma(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function na(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function N(b){b=URL.createObjectURL(b);try{return await na(b)}finally{URL.revokeObjectURL(b)}}
function oa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function ta(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await N(b);var d=await oa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await N(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await N(b)}
function O(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const ua=new Set(["input","textarea","datalist","select"]),va=new Set(["canvas","body","html"]);function P(b){va.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function wa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await N(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await ta(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Q=!1;document.addEventListener("pause",()=>Q=!0);document.addEventListener("resume",()=>Q=!1);async function xa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function ya(b){return await self.C3_GetSvgImageSize(b.blob)}
function za(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Aa(b){self.setTimeout(()=>{b.Oa=!0},1E3);"cordova"===b.i.h?(document.addEventListener("pause",()=>R(b,!0)),document.addEventListener("resume",()=>R(b,!1))):document.addEventListener("visibilitychange",()=>R(b,document.hidden));return{isSuspended:!(!document.hidden&&!Q)}}
function Ba(b){b.La||(b.La=!0,window.addEventListener("deviceorientation",a=>{b.l||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},L)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},L)}))}
function Ca(b){b.Ka||(b.Ka=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},L)}}))}async function Da(b){await ma(b.url)}
function Ea(b,a){b.Pa=a.message;-1===b.pa&&(b.pa=setTimeout(()=>{b.pa=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Pa)},250))}function S(b){if(!b.l){var a=J.J();a&&"any"!==b.wa&&Fa(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.A(),innerHeight:b.u()})}}function T(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:J.J(),innerWidth:b.A(),innerHeight:b.u()})}
function R(b,a){a?b.i.hb():b.i.Ia();l(b,"visibilitychange",{hidden:a})}function Ga(b,a,c){"Backspace"===c.key&&P(c);if(!b.l){var d=ka.get(c.code)||c.code;m(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},L)}}
function U(b,a,c,d){b.l||K(c)||m(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function V(b){window!==window.top&&window.focus();Ha(b.target)&&document.activeElement&&!Ha(document.activeElement)&&document.activeElement.blur()}
function W(b,a,c){if(!b.l){if(b.R&&"pointermove"!==a){var d=b.R;d.M||(-1!==d.H&&(self.clearTimeout(d.H),d.H=-1),d.X=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.P);m(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:(c.movementX||0)+b.$,movementY:(c.movementY||0)+b.aa,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||
0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},L);b.$=0;b.aa=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),U(b,d,c,la),b.P=c.buttons)}}
function X(b,a,c){if(!b.l&&!K(c)){var d=b.P;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");m(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},L);b.P=c.buttons;U(b,c.type,c,la)}}
function Y(b,a,c){if(!b.l)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];m(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},L)}}
function Z(b,a){document.body.style.transform="";if(0<a){var c=document.activeElement;c&&(c=c.getBoundingClientRect(),b=(c.top+c.bottom)/2-(b-a)/2,b>a&&(b=a),0>b&&(b=0),0<b&&(document.body.style.transform=`translateY(${-b}px)`))}}function Ia(b,a,c,d){const e=b.A(),f=b.u();b.G=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.J()}):10>d&&Ja(b,e,f,d+1)}
function Ja(b,a,c,d){-1!==b.G&&clearTimeout(b.G);b.G=setTimeout(()=>Ia(b,a,c,d),48)}
function Fa(b){b=b.wa;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Ha(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.za(class extends self.ga{constructor(b){super(b,"runtime");this.Ra=!0;this.G=-1;this.wa="any";this.Ka=this.La=!1;this.B=null;this.l=!1;this.Pa="";this.pa=-1;this.D=this.R=null;this.aa=this.$=0;this.Oa=!1;this.Ta=b.A();this.Y=b.u();this.S=0;b.g("canvas","update-size",d=>{var e=this.i;e.Qa||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",this.Ra&&(e.style.display="",this.Ra=!1))});b.g("runtime","invoke-download",
d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.g("runtime","raster-svg-image",d=>xa(d));b.g("runtime","get-svg-image-size",d=>ya(d));b.g("runtime","set-target-orientation",d=>{this.wa=d.targetOrientation});b.g("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.g("runtime","post-to-debugger",d=>za(d));b.g("runtime","go-to-script",d=>za(d));b.g("runtime",
"before-start-ticking",()=>Aa(this));b.g("runtime","debug-highlight",d=>{if(d.show){this.B||(this.B=document.createElement("div"),this.B.id="inspectOutline",document.body.appendChild(this.B));var e=this.B;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.B&&(this.B.style.display="none")});b.g("runtime","enable-device-orientation",()=>Ba(this));b.g("runtime","enable-device-motion",()=>Ca(this));
b.g("runtime","add-stylesheet",d=>Da(d));b.g("runtime","alert",d=>{alert(d.message)});b.g("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.g("runtime","set-exporting-to-video",d=>{this.l=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.fb()});b.g("runtime","export-to-video-progress",
d=>Ea(this,d));b.g("runtime","exported-to-video",d=>{window.Gb({type:"exported-video",blob:d.blob,time:d.time})});b.g("runtime","exported-to-image-sequence",d=>{window.Gb({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||O(e)||d.preventDefault()});const c=b.j;window.addEventListener("selectstart",P);window.addEventListener("gesturehold",P);c.addEventListener("selectstart",
P);c.addEventListener("gesturehold",P);window.addEventListener("touchstart",P,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",P,{passive:!1}),c.addEventListener("pointerdown",P)):c.addEventListener("touchstart",P);this.P=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",wa,{passive:!1});window.addEventListener("wheel",wa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l){var d=this.A();
var e=this.u();if(this.i.Ca()){if(this.Oa){if(this.Ta===d&&e<this.Y){this.S=this.Y-e;Z(this.Y,this.S);d=void 0;break a}0<this.S&&(this.S=0,Z(e,this.S))}this.Ta=d;this.Y=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.J()});this.i.ha()&&(-1!==this.G&&clearTimeout(this.G),Ia(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>S(this));window.addEventListener("webkitfullscreenchange",()=>S(this));window.addEventListener("mozfullscreenchange",
()=>S(this));window.addEventListener("fullscreenerror",d=>T(this,d));window.addEventListener("webkitfullscreenerror",d=>T(this,d));window.addEventListener("mozfullscreenerror",d=>T(this,d));if(b.ha())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=
new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):O(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(J.Ja(!0),S(this)):"exited-fullscreen"===d?(J.Ja(!1),S(this)):console.warn("Unknown wrapper message: ",d)};this.ta=new Set;this.Db=new WeakSet;this.Bb=!1}Aa(){window.addEventListener("focus",()=>{l(this,"window-focus",null,M)});window.addEventListener("blur",
()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}l(this,"window-blur",{parentHasFocus:a},M);this.P=0});window.addEventListener("focusin",a=>{a=a.target;(ua.has(a.tagName.toLowerCase())||O(a))&&l(this,"keyboard-blur",null,M)});window.addEventListener("keydown",a=>Ga(this,"keydown",a));window.addEventListener("keyup",a=>Ga(this,"keyup",a));window.addEventListener("dblclick",a=>U(this,"dblclick",a,L));window.addEventListener("wheel",a=>{this.l||l(this,"wheel",{clientX:a.clientX,
clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},L)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{V(a);W(this,"pointerdown",a)}),this.i.s&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.R=new self.eb(()=>{W(this,"pointermove",this.D);this.D=null}),this.R.Na=!0,window.addEventListener("pointerrawupdate",a=>{this.D&&(this.$+=this.D.movementX||0,this.aa+=this.D.movementY||
0);this.D=a;a=this.R;if(-1===a.H){var c=Date.now(),d=c-a.X,e=a.Ab;d>=e&&a.Na?(a.X=c,a.M=!0,a.Ma(),a.M=!1):a.H=self.setTimeout(a.Fb,Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>W(this,"pointermove",a)),window.addEventListener("pointerup",a=>W(this,"pointerup",a)),window.addEventListener("pointercancel",a=>W(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{V(a);X(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>X(this,"pointermove",a)),window.addEventListener("mouseup",
a=>X(this,"pointerup",a)),window.addEventListener("touchstart",a=>{V(a);Y(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>Y(this,"pointermove",a)),window.addEventListener("touchend",a=>Y(this,"pointerup",a)),window.addEventListener("touchcancel",a=>Y(this,"pointercancel",a)));const b=()=>this.ma();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.i.Za()&&!this.i.Ca()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Z(this.u(),navigator.virtualKeyboard.boundingRect.height)}))}A(){return this.i.A()}u(){return this.i.u()}ma(){var b=[...this.ta];this.ta.clear();if(!this.Bb)for(const a of b)(b=a.play())&&b.catch(()=>{this.Db.has(a)||this.ta.add(a)})}});"use strict";
async function ha(b){if(b.zb)throw Error("already initialised");b.zb=!0;var a=b.ba.la("dispatchworker.js");b.oa=await b.ba.fa(a,b.K,{name:"DispatchWorker"});a=new MessageChannel;b.qa=a.port1;b.oa.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.ua=await I(b)}function ia(b){return[b.qa,b.ua]}
async function I(b){const a=b.Sa.length;var c=b.ba.la("jobworker.js");c=await b.ba.fa(c,b.K,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.oa.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Sa.push(c);return e.port1}
self.bb=class{constructor(b){this.ba=b;this.K=b.m;this.K="preview"===b.h?this.K+"workers/":this.K+b.ca;this.Cb=Math.min(navigator.hardwareConcurrency||2,16);this.oa=null;this.Sa=[];this.ua=this.qa=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ja({Qb:!0,Rb:"workermain.js",I:["scripts/c3runtime.js"],da:[],xa:"",Nb:"scripts/",ya:[],Wa:"html5"}));"use strict";
async function Ka(b,a){a=a.type;let c=!0;0===a?c=await La():1===a&&(c=await Ma());l(b,"permission-result",{type:a,result:c})}async function La(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Ma(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.ja.za(class extends self.ga{constructor(b){super(b,"touch");n(this,"request-permission",a=>Ka(this,a))}});
