function k(b,a,d,c){b.i.la(b.R,a,d,c,void 0)}function p(b,a,d,c){b.i.o?k(b,a,d,c):b.i.sb()._OnMessageFromDOM({type:"event",component:b.R,handler:a,dispatchOpts:c||null,data:d,responseId:null})}function q(b,a,d){b.i.h(b.R,a,d)}function r(b,a){for(const [d,c]of a)q(b,d,c)}window.F=class{constructor(b,a){this.i=b;this.R=a}Ja(){}};window.Wb=class{constructor(){}};"use strict";class aa{constructor(b){this.wa=b;this.ya=!1;this.Ba=!0}}
function ba(b,a){const d=a.elementId,c=b.La(d,a),e=new aa(c);b.S.set(d,e);c.style.boxSizing="border-box";c.style.display="none";e.Ba=!!a.isVisible;c.addEventListener("focus",()=>{t(b,"elem-focused",d)});c.addEventListener("blur",()=>{t(b,"elem-blurred",d)});b.ca&&document.body.appendChild(c)}function v(b,a,d){q(b,a,c=>{const e=w(b,c.elementId);return d(e,c)})}function w(b,a){b=b.S.get(a);if(!b)throw Error(`no element with id ${a}`);return b.wa}
function t(b,a,d,c){c||(c={});c.elementId=d;k(b,a,c)}function x(b,a,d){var c;c||(c={});c.elementId=d;p(b,a,c)}
window.bb=class extends self.F{constructor(b){super(b,"text-input");this.S=new Map;this.ca=!0;r(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const d=w(this,a);this.ca&&d.parentElement.removeChild(d);this.S.delete(a)}],["set-visible",a=>{if(this.ca){var d=this.S.get(a.elementId),c=d.wa;d.ya?c.style.display=a.isVisible?"":"none":d.Ba=!!a.isVisible}}],["update-position",a=>{if(this.ca){var d=this.S.get(a.elementId),c=d.wa;c.style.left=a.left+"px";c.style.top=a.top+"px";c.style.width=a.width+
"px";c.style.height=a.height+"px";a=a.fontSize;null!==a&&(c.style.fontSize=a+"em");d.ya||(d.ya=!0,d.Ba&&(c.style.display=""))}}],["update-state",a=>{const d=w(this,a.elementId);this.ma(d,a)}],["focus",a=>this.ra(a)],["set-css-style",a=>{const d=w(this,a.elementId),c=a.prop;a=a.val;c.startsWith("--")?d.style.setProperty(c,a):d.style[c]=a}],["set-attribute",a=>{w(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{w(this,a.elementId).removeAttribute(a.name)}]]);v(this,"get-element",
a=>a)}La(){throw Error("required override");}ma(){throw Error("required override");}ra(b){var a=w(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const y=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),z=/android/i.test(navigator.userAgent),ca=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let da=0;
function A(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Mb?new Promise(d=>{const c="c3_resolve_"+da;++da;self[c]=d;a.textContent=b.Qb+`\n\nself["${c}"]();`;document.head.appendChild(a)}):new Promise((d,c)=>{a.onload=d;a.onerror=c;a.src=b;document.head.appendChild(a)})}let ea=!1,fa=!1;function ha(){if(!ea){try{new Worker("blob://",{get type(){fa=!0}})}catch(b){}ea=!0}return fa}let B=new Audio;
const ia={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function ja(b){b=await ka(b);return(new TextDecoder("utf-8")).decode(b)}
function ka(b){return new Promise((a,d)=>{const c=new FileReader;c.onload=e=>a(e.target.result);c.onerror=e=>d(e);c.readAsArrayBuffer(b)})}const C=[];let D=0;window.RealFile=window.File;const E=[],G=new Map,H=new Map;let la=0;const ma=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ma.push(b)};const na=new Set(["cordova","playable-ad","instant-games"]);let oa=!1;
window.u=class b{constructor(a){this.o=a.Sb;this.V=null;this.m="";this.K=a.Pb;this.Z={};this.Da=this.M=null;this.da=[];this.j=this.X=null;this.Xa=!1;this.T=null;this.J=-1;this.Hb=()=>this.zb();this.Ga=[];this.g=a.$a;this.Aa="file"===location.protocol.substr(0,4);!this.o||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ha()||(this.o=!1);this.o&&ca&&(this.o=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.o=!1;if("cordova"===this.g&&this.o)if(z){const d=/Chrome\/(\d+)/i.exec(navigator.userAgent);
d&&90<=parseInt(d[1],10)||(this.o=!1)}else this.o=!1;this.ea=this.B=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime","cordova-fetch-local-file",d=>this.vb(d));this.h("runtime","create-job-worker",()=>this.wb());"cordova"===this.g?document.addEventListener("deviceready",()=>this.Pa(a)):this.Pa(a)}gb(){return y&&
"cordova"===this.g}ka(){const a=navigator.userAgent;return y&&na.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}eb(){return z}Ma(){return z&&na.has(this.g)}async Pa(a){"macos-wkwebview"===this.g&&this.ua({type:"ready"});if("playable-ad"===this.g){this.B=self.c3_base64files;this.ea={};await this.ob();for(let c=0,e=a.N.length;c<e;++c){var d=a.N[c];this.ea.hasOwnProperty(d)?a.N[c]={Mb:!0,Qb:this.ea[d]}:this.B.hasOwnProperty(d)&&(a.N[c]=URL.createObjectURL(this.B[d]))}a.ha=[]}if("nwjs"===
this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let c=0;this.kb(()=>{c++;document.body.style.opacity=0===c%2?"1":"0.999"})}a.Ob?this.m=a.Ob:(d=location.origin,this.m=("null"===d?"file:///":d)+location.pathname,d=this.m.lastIndexOf("/"),-1!==d&&(this.m=this.m.substr(0,d+1)));a.Ub&&(this.Z=a.Ub);d=new MessageChannel;this.V=d.port1;this.V.onmessage=c=>this._OnMessageFromRuntime(c.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(c=>this.yb(c));this.T=new self.hb(this);await pa(this.T);
"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((c,e)=>{window.AndroidFullScreen.immersiveMode(c,e)})}catch(c){console.error("Failed to enter Android immersive mode: ",c)}this.o?await this.ub(a,d.port2):await this.tb(a,d.port2)}oa(a){a=this.Z.hasOwnProperty(a)?this.Z[a]:a.endsWith("/workermain.js")&&this.Z.hasOwnProperty("workermain.js")?this.Z["workermain.js"]:"playable-ad"===this.g&&this.B.hasOwnProperty(a)?this.B[a]:
a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ja(a,d,c){if(a.startsWith("blob:"))return new Worker(a,c);if("cordova"===this.g&&this.Aa)return a=await this.ia(c.Lb?a:this.K+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),c);a=new URL(a,d);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),c)}return new Worker(a,c)}A(){return Math.max(window.innerWidth,
1)}v(){return Math.max(window.innerHeight,1)}Oa(a){var d=this.m,c=location.href,e=this.A(),f=this.v(),g=window.devicePixelRatio,h=b.O(),l=a.ac,m=window.cr_previewImageBlobs||this.B,n=window.cr_previewProjectFileBlobs,Da=window.cr_previewProjectFiles,Ea=window.Zb||"";a=a.$a;var Fa=(new URLSearchParams(self.location.search)).has("debug"),N=this.T;return{runtimeBaseUrl:d,previewUrl:c,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:l,previewImageBlobs:m,previewProjectFileBlobs:n,
previewProjectFileSWUrls:Da,swClientId:Ea,exportType:a,isDebug:Fa,ife:!!self.$b,jobScheduler:{inputPort:N.za,outputPort:N.Fa,maxNumWorkers:N.Fb},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.K+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.K+"opus.wasm.wasm",isFileProtocol:this.Aa,isiOSCordova:this.gb(),isiOSWebView:this.ka(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async ub(a,d){const c=this.oa(a.Tb);"preview"===this.g?(this.M=new Worker("previewworker.js",
{type:"module",name:"Runtime"}),await new Promise((h,l)=>{const m=n=>{this.M.removeEventListener("message",m);n.data&&"ok"===n.data.type?h():l()};this.M.addEventListener("message",m);this.M.postMessage({type:"construct-worker-init","import":(new URL(c,this.m)).toString()})})):this.M=await this.ja(c,this.m,{type:"module",name:"Runtime",Lb:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);window.c3canvas=
this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.ha||[],g=a.N;f=await Promise.all(f.map(h=>this.I(h)));g=await Promise.all(g.map(h=>this.I(h)));if("cordova"===this.g)for(let h=0,l=a.ga.length;h<l;++h){const m=a.ga[h],n=m[0];if(n===a.Ia||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m[1]=await this.I(n)}this.M.postMessage(Object.assign(this.Oa(a),{type:"init-runtime",isInWorker:!0,messagePort:d,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ga,
mainProjectScript:a.Ia,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[d,e,...qa(this.T)]);this.da=E.map(h=>new h(this));this.Na();ra(this.X);self.c3_callFunction=(h,l)=>{var m=this.X;return m.i.ib(m.R,{name:h,params:l})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.la("runtime","go-to-last-error-script"))}async tb(a,d){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();
this.da=E.map(g=>new g(this));this.Na();var c=a.N.map(g=>"string"===typeof g?(new URL(g,this.m)).toString():g);Array.isArray(a.ha)&&c.unshift(...a.ha);c=await Promise.all(c.map(g=>this.I(g)));await Promise.all(c.map(g=>A(g)));c=self.C3_ProjectScriptsStatus;const e=a.Ia,f=a.ga;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.I(h),await A(h),"preview"!==this.g||c[g]||this.Ra(g,"main script did not run to completion")}catch(l){this.Ra(g,l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=
await this.I(h),await A(h);"preview"===this.g&&"object"!==typeof self.Vb.Xb?(this.aa(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Oa(a),{isInWorker:!1,messagePort:d,canvas:this.j,runOnStartupFunctions:ma}),ra(this.X),this.Qa(),this.Da=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Da,
a))}Ra(a,d){this.aa();console.error(`[Preview] Failed to load project main script (${a}): `,d);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Qa(){this.aa()}aa(){const a=window.Jb;a&&(a.parentElement.removeChild(a),window.Jb=null)}async wb(){const a=await sa(this.T);return{outputPort:a,transferables:[a]}}sb(){if(this.o)throw Error("not available in worker mode");return this.Da}la(a,d,c,e,f){this.V.postMessage({type:"event",
component:a,handler:d,dispatchOpts:e||null,data:c,responseId:null},f)}ib(a,d){const c=la++,e=new Promise((f,g)=>{H.set(c,{resolve:f,reject:g})});this.V.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:d,responseId:c},void 0);return e}_OnMessageFromRuntime(a){const d=a.type;if("event"===d)return this.xb(a);if("result"===d)this.Ab(a);else if("runtime-ready"===d)this.Bb();else if("alert-error"===d)this.aa(),alert(a.message);else if("creating-runtime"===d)this.Qa();
else throw Error(`unknown message '${d}'`);}xb(a){const d=a.component,c=a.handler,e=a.data,f=a.responseId;if(a=G.get(d))if(a=a.get(c)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${d}' handler '${c}':`,h);null!==f&&this.$(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.$(f,!0,h)).catch(h=>{console.error(`Rejection from '${d}' handler '${c}':`,h);this.$(f,!1,""+h)}):this.$(f,!0,g)}else console.warn(`[DOM] No handler '${c}' for component '${d}'`);else console.warn(`[DOM] No event handlers for component '${d}'`)}$(a,
d,c){let e;c&&c.transferables&&(e=c.transferables);this.V.postMessage({type:"result",responseId:a,isOk:d,result:c},e)}Ab(a){const d=a.responseId,c=a.isOk;a=a.result;const e=H.get(d);c?e.resolve(a):e.reject(a);H.delete(d)}h(a,d,c){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(d))throw Error(`[DOM] Component '${a}' already has handler '${d}'`);e.set(d,c)}static D(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Na(){for(const a of this.da)if("runtime"===a.R){this.X=a;return}throw Error("cannot find runtime DOM handler");
}yb(a){this.la("debugger","message",a)}Bb(){for(const a of this.da)a.Ja()}static O(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||oa)}static ba(a){oa=!!a}kb(a){this.Ga.push(a);this.ta()}ta(){-1===this.J&&this.Ga.length&&(this.J=requestAnimationFrame(this.Hb))}mb(){-1!==this.J&&(cancelAnimationFrame(this.J),this.J=-1)}zb(){this.J=-1;for(const a of this.Ga)a();this.ta()}sa(){this.X.sa()}jb(){this.Xa=!0}cb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||
"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}fb(a){return!this.cb(a)}async I(a){return"cordova"===this.g&&(a.startsWith("file:")||this.Aa&&this.fb(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.ia(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async vb(a){const d=a.filename;switch(a.as){case "text":return await this.ab(d);case "buffer":return await this.ia(d);default:throw Error("unsupported type");}}Ka(a){const d=window.cordova.file.applicationDirectory+
"www/"+a;return new Promise((c,e)=>{window.resolveLocalFileSystemURL(d,f=>{f.file(c,e)},e)})}async ab(a){a=await this.Ka(a);return await ja(a)}na(){if(C.length&&!(8<=D)){D++;var a=C.shift();this.pb(a.filename,a.Rb,a.Kb)}}ia(a){return new Promise((d,c)=>{C.push({filename:a,Rb:e=>{D--;this.na();d(e)},Kb:e=>{D--;this.na();c(e)}});this.na()})}async pb(a,d,c){try{const e=await this.Ka(a),f=await ka(e);d(f)}catch(e){c(e)}}ua(a){if("windows-webview2"===this.g)window.chrome.webview.postMessage(JSON.stringify(a));
else if("macos-wkwebview"===this.g)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async ob(){const a=[];for(const [d,c]of Object.entries(this.B))a.push(this.nb(d,c));await Promise.all(a)}async nb(a,d){if("object"===typeof d)this.B[a]=new Blob([d.str],{type:d.type}),this.ea[a]=d.str;else{let c=await this.rb(d);c||(c=this.qb(d));this.B[a]=c}}async rb(a){try{return await (await fetch(a)).blob()}catch(d){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
d),null}}qb(a){a=this.Cb(a);return this.lb(a.data,a.Nb)}Cb(a){var d=a.indexOf(",");if(0>d)throw new URIError("expected comma in data: uri");var c=a.substring(d+1);d=a.substring(5,d).split(";");a=d[0]||"";const e=d[2];c="base64"===d[1]||"base64"===e?atob(c):decodeURIComponent(c);return{Nb:a,data:c}}lb(a,d){var c=a.length;let e=c>>2,f=new Uint8Array(c),g=new Uint32Array(f.buffer,0,e),h,l;for(l=h=0;h<e;++h)g[h]=a.charCodeAt(l++)|a.charCodeAt(l++)<<8|a.charCodeAt(l++)<<16|a.charCodeAt(l++)<<24;for(c&=
3;c--;)f[l]=a.charCodeAt(l),++l;return new Blob([f],{type:d})}};"use strict";const I=self.u;function ta(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const ua=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},va={dispatchUserScriptEvent:!0},K={dispatchRuntimeEvent:!0};
function wa(b){return new Promise((a,d)=>{const c=document.createElement("link");c.onload=()=>a(c);c.onerror=e=>d(e);c.rel="stylesheet";c.href=b;document.head.appendChild(c)})}function xa(b){return new Promise((a,d)=>{const c=new Image;c.onload=()=>a(c);c.onerror=e=>d(e);c.src=b})}async function L(b){b=URL.createObjectURL(b);try{return await xa(b)}finally{URL.revokeObjectURL(b)}}
function ya(b){return new Promise((a,d)=>{let c=new FileReader;c.onload=e=>a(e.target.result);c.onerror=e=>d(e);c.readAsText(b)})}
async function za(b,a,d){if(!/firefox/i.test(navigator.userAgent))return await L(b);var c=await ya(b);c=(new DOMParser).parseFromString(c,"image/svg+xml");const e=c.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await L(b)}e.setAttribute("width",a+"px");e.setAttribute("height",d+"px");c=(new XMLSerializer).serializeToString(c);b=new Blob([c],{type:"image/svg+xml"});return await L(b)}
function M(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Aa=new Set(["input","textarea","datalist","select"]),Ba=new Set(["canvas","body","html"]);function O(b){b.target.tagName&&Ba.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ca(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await L(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,d,c,e){b=await za(b,a,d);const f=document.createElement("canvas");f.width=c;f.height=e;f.getContext("2d").drawImage(b,0,0,a,d);return f};
let P=!1;document.addEventListener("pause",()=>P=!0);document.addEventListener("resume",()=>P=!1);function ra(b){b.Va=!0;b.Ca=b.i.A();b.U=b.i.v()}async function Ga(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ha(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ia(b){return await self.C3_GetSvgImageSize(b.blob)}function Ja(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ka(b){self.setTimeout(()=>{b.Ua=!0},1E3);"cordova"===b.i.g?(document.addEventListener("pause",()=>Q(b,!0)),document.addEventListener("resume",()=>Q(b,!1))):document.addEventListener("visibilitychange",()=>Q(b,document.hidden));return{isSuspended:!(!document.hidden&&!P)}}
function La(b){b.Ta||(b.Ta=!0,window.addEventListener("deviceorientation",a=>{b.l||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Ma(b){b.Sa||(b.Sa=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var d=null,c=a.acceleration;c&&(d={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var e=a.accelerationIncludingGravity;e&&(c={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:d,accelerationIncludingGravity:c,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Na(b){await wa(b.url)}
function Oa(b,a){b.Wa=a.message;-1===b.xa&&(b.xa=setTimeout(()=>{b.xa=-1;const d=document.getElementById("exportToVideoMessage");d&&(d.textContent=b.Wa)},250))}function R(b){if(!b.l){var a=I.O();a&&"any"!==b.Ha&&Pa(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.A(),innerHeight:b.v()})}}function S(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:I.O(),innerWidth:b.A(),innerHeight:b.v()})}
function Q(b,a){a?b.i.mb():b.i.ta();k(b,"visibilitychange",{hidden:a})}function Qa(b,a,d){"Backspace"===d.key&&O(d);if(!b.l){var c=ua.get(d.code)||d.code;p(b,a,{code:c,key:d.key,which:d.which,repeat:d.repeat,altKey:d.altKey,ctrlKey:d.ctrlKey,metaKey:d.metaKey,shiftKey:d.shiftKey,timeStamp:d.timeStamp},J)}}
function T(b,a,d,c){b.l||ta(d)||p(b,a,{button:d.button,buttons:d.buttons,clientX:d.clientX,clientY:d.clientY+b.s,pageX:d.pageX,pageY:d.pageY+b.s,movementX:d.movementX||0,movementY:d.movementY||0,timeStamp:d.timeStamp},c)}function U(b){window!==window.top&&window.focus();Ra(b.target)&&document.activeElement&&!Ra(document.activeElement)&&document.activeElement.blur()}
function V(b,a,d){if(!b.l){var c=0;"mouse"===d.pointerType&&(c=b.W);p(b,a,{pointerId:d.pointerId,pointerType:d.pointerType,button:d.button,buttons:d.buttons,lastButtons:c,clientX:d.clientX,clientY:d.clientY+b.s,pageX:d.pageX,pageY:d.pageY+b.s,movementX:d.movementX||0,movementY:d.movementY||0,width:d.width||0,height:d.height||0,pressure:d.pressure||0,tangentialPressure:d.tangentialPressure||0,tiltX:d.tiltX||0,tiltY:d.tiltY||0,twist:d.twist||0,timeStamp:d.timeStamp},J);"mouse"===d.pointerType&&(c="mousemove",
"pointerdown"===a?c="mousedown":"pointerup"===a&&(c="mouseup"),T(b,c,d,va),b.W=d.buttons)}}
function W(b,a,d){if(!b.l&&!ta(d)){var c=b.W;"pointerdown"===a&&0!==c?a="pointermove":"pointerup"===a&&0!==d.buttons&&(a="pointermove");p(b,a,{pointerId:1,pointerType:"mouse",button:d.button,buttons:d.buttons,lastButtons:c,clientX:d.clientX,clientY:d.clientY+b.s,pageX:d.pageX,pageY:d.pageY+b.s,movementX:d.movementX||0,movementY:d.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:d.timeStamp},J);b.W=d.buttons;T(b,d.type,d,va)}}
function X(b,a,d){if(!b.l)for(let c=0,e=d.changedTouches.length;c<e;++c){const f=d.changedTouches[c];p(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.s,pageX:f.pageX,pageY:f.pageY+b.s,movementX:d.movementX||0,movementY:d.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:d.timeStamp},
J)}}function Y(b,a,d){document.body.style.transform="";b.s=0;if(0<d){var c=document.activeElement;c&&(c=c.getBoundingClientRect(),a=(c.top+c.bottom)/2-(a-d)/2,a>d&&(a=d),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.s=a))}}function Sa(b,a,d,c){const e=b.A(),f=b.v();b.L=-1;e!=a||f!=d?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.O()}):10>c&&Ta(b,e,f,c+1)}
function Ta(b,a,d,c){-1!==b.L&&clearTimeout(b.L);b.L=setTimeout(()=>Sa(b,a,d,c),48)}
function Pa(b){b=b.Ha;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Ra(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.D(class extends self.F{constructor(b){super(b,"runtime");this.Ya=!0;this.Va=!1;this.L=-1;this.Ha="any";this.Sa=this.Ta=!1;this.fa=document.createElement("div");this.fa.className="c3-screen-reader-text";this.fa.setAttribute("aria-live","polite");document.body.appendChild(this.fa);this.G=null;this.l=!1;this.Wa="";this.xa=-1;this.Ua=!1;this.Ca=b.A();this.U=b.v();this.s=this.Y=0;b.h("canvas","update-size",c=>{var e=this.i;e.Xa||(e=e.j,e.style.width=c.styleWidth+"px",e.style.height=c.styleHeight+"px",
e.style.marginLeft=c.marginLeft+"px",e.style.marginTop=c.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",c.displayScale),this.Ya&&(e.style.display="",this.Ya=!1))});b.h("runtime","invoke-download",c=>{const e=c.url;c=c.filename;const f=document.createElement("a"),g=document.body;f.textContent=c;f.href=e;f.download=c;g.appendChild(f);f.click();g.removeChild(f)});b.h("runtime","load-webfonts",c=>Ga(c));b.h("runtime","raster-svg-image",c=>Ha(c));b.h("runtime","get-svg-image-size",
c=>Ia(c));b.h("runtime","set-target-orientation",c=>{this.Ha=c.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime","post-to-debugger",c=>Ja(c));b.h("runtime","go-to-script",c=>Ja(c));b.h("runtime","before-start-ticking",()=>Ka(this));b.h("runtime","debug-highlight",c=>{if(c.show){this.G||(this.G=document.createElement("div"),this.G.id="inspectOutline",document.body.appendChild(this.G));var e=this.G;e.style.display="";e.style.left=c.left-
1+"px";e.style.top=c.top-1+"px";e.style.width=c.width+2+"px";e.style.height=c.height+2+"px";e.textContent=c.name}else this.G&&(this.G.style.display="none")});b.h("runtime","enable-device-orientation",()=>La(this));b.h("runtime","enable-device-motion",()=>Ma(this));b.h("runtime","add-stylesheet",c=>Na(c));b.h("runtime","script-create-worker",c=>{const e=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.h("runtime","alert",c=>this.pa(c));b.h("runtime","screen-reader-text",
c=>{var e=c.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+c.id,e.textContent=c.text,this.fa.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+c.id))?e.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===e?(e=document.getElementById("c3-sr-"+c.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});b.h("runtime","hide-cordova-splash",
()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",c=>{this.l=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=c.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.jb()});b.h("runtime","export-to-video-progress",c=>Oa(this,c));b.h("runtime","exported-to-video",c=>{window.Ib({type:"exported-video",blob:c.blob,time:c.time})});b.h("runtime",
"exported-to-image-sequence",c=>{window.Ib({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const e=c.target;a.has(e.tagName.toLowerCase())||M(e)||c.preventDefault()});const d=b.j;window.addEventListener("selectstart",O);window.addEventListener("gesturehold",O);d.addEventListener("selectstart",O);d.addEventListener("gesturehold",O);window.addEventListener("touchstart",O,{passive:!1});
"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",O,{passive:!1}),d.addEventListener("pointerdown",O)):d.addEventListener("touchstart",O);this.W=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ca,{passive:!1});window.addEventListener("wheel",Ca,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.Va){var c=this.A();var e=this.v();if(this.i.Ma()){if(this.Ua){if(this.Ca===c&&e<this.U){this.Y=
this.U-e;Y(this,this.U,this.Y);c=void 0;break a}0<this.Y&&(this.Y=0,Y(this,e,this.Y))}this.Ca=c;this.U=e}k(this,"window-resize",{innerWidth:c,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.O()});this.i.ka()&&(-1!==this.L&&clearTimeout(this.L),Sa(this,c,e,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>R(this));window.addEventListener("webkitfullscreenchange",()=>R(this));window.addEventListener("mozfullscreenchange",()=>R(this));window.addEventListener("fullscreenerror",
c=>S(this,c));window.addEventListener("webkitfullscreenerror",c=>S(this,c));window.addEventListener("mozfullscreenerror",c=>S(this,c));if(b.ka())if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>c&&(document.scrollingElement.scrollTop=0);c=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var c=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?e.has(f.type.toLowerCase()||"text"):M(f)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>{"entered-fullscreen"===c?(I.ba(!0),R(this)):"exited-fullscreen"===c?(I.ba(!1),R(this)):console.warn("Unknown wrapper message: ",c)};this.Ea=new Set;this.Gb=new WeakSet;this.Eb=!1}Ja(){window.addEventListener("focus",()=>{k(this,"window-focus",null,K)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(d){a=
!1}k(this,"window-blur",{parentHasFocus:a},K);this.W=0});window.addEventListener("focusin",a=>{a=a.target;(Aa.has(a.tagName.toLowerCase())||M(a))&&k(this,"keyboard-blur",null,K)});window.addEventListener("keydown",a=>Qa(this,"keydown",a));window.addEventListener("keyup",a=>Qa(this,"keyup",a));window.addEventListener("dblclick",a=>T(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.l||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.s,pageX:a.pageX,pageY:a.pageY+this.s,deltaX:a.deltaX,
deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{U(a);V(this,"pointerdown",a)}),this.i.o&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{V(this,"pointermove",a)}):window.addEventListener("pointermove",a=>V(this,"pointermove",a)),window.addEventListener("pointerup",a=>V(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>V(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{U(a);W(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>W(this,"pointermove",a)),window.addEventListener("mouseup",a=>W(this,"pointerup",a)),window.addEventListener("touchstart",a=>{U(a);X(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>X(this,"pointermove",a)),window.addEventListener("touchend",a=>X(this,"pointerup",a)),window.addEventListener("touchcancel",a=>X(this,"pointercancel",a)));const b=
()=>this.sa();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.eb()&&!this.i.Ma()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Y(this,this.v(),navigator.virtualKeyboard.boundingRect.height)}))}A(){return this.i.A()}v(){return this.i.v()}sa(){var b=
[...this.Ea];this.Ea.clear();if(!this.Eb)for(const a of b)(b=a.play())&&b.catch(()=>{this.Gb.has(a)||this.Ea.add(a)})}pa(b){alert(b.message)}});"use strict";async function pa(b){if(b.Db)throw Error("already initialised");b.Db=!0;var a=b.C.oa(("playable-ad"===b.C.g?b.C.K:"")+"dispatchworker.js");b.va=await b.C.ja(a,b.P,{name:"DispatchWorker"});a=new MessageChannel;b.za=a.port1;b.va.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Fa=await sa(b)}function qa(b){return[b.za,b.Fa]}
async function sa(b){const a=b.Za.length;var d=b.C.oa(("playable-ad"===b.C.g?b.C.K:"")+"jobworker.js");d=await b.C.ja(d,b.P,{name:"JobWorker"+a});const c=new MessageChannel,e=new MessageChannel;b.va.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);d.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":e.port2},[c.port2,e.port2]);b.Za.push(d);return e.port1}
self.hb=class{constructor(b){this.C=b;this.P=b.m;this.P="preview"===b.g?this.P+"workers/":this.P+b.K;this.Fb=Math.min(navigator.hardwareConcurrency||2,16);this.va=null;this.Za=[];this.Fa=this.za=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.u({Sb:!1,Tb:"workermain.js",N:["scripts/c3runtime.js"],ga:[],Ia:"",Pb:"scripts/",ha:[],$a:"html5"}));"use strict";
async function Ua(b,a){a=a.type;let d=!0;0===a?d=await Va():1===a&&(d=await Wa());k(b,"permission-result",{type:a,result:d})}async function Va(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Wa(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.u.D(class extends self.F{constructor(b){super(b,"touch");q(this,"request-permission",a=>Ua(this,a))}});"use strict";function Xa(){}
function Ya(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Za(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.u.D(class extends self.F{constructor(b){super(b,"browser");this.g="";r(this,[["get-initial-state",a=>this.qa(a)],["ready-for-sw-messages",()=>Ya(this)],["alert",a=>this.pa(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.ra(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Za(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var d=a.type;if("back"===d)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===d)window.history.forward();else if("reload"===d)location.reload();else if("url"===
d){d=a.url;const c=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(d,"_system"):"preview"===a||"windows-webview2"===a?window.open(d,"_blank"):this.Yb||(2===c?window.top.location=d:1===c?window.parent.location=d:window.location=d)}else"new-window"===d&&(d=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(d,"_system"):window.open(d,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.g||"macos-wkwebview"===this.g)self.u.ba(!0),
this.i.ua({type:"set-fullscreen",fullscreen:!0});else{const d={navigationUI:"auto"};a=a.navUI;1===a?d.navigationUI="hide":2===a&&(d.navigationUI="show");a=document.documentElement;let c;a.requestFullscreen?c=a.requestFullscreen(d):a.mozRequestFullScreen?c=a.mozRequestFullScreen(d):a.msRequestFullscreen?c=a.msRequestFullscreen(d):a.webkitRequestFullScreen&&(c="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());c instanceof
Promise&&c.catch(Xa)}}],["exit-fullscreen",()=>{if("windows-webview2"===this.g||"macos-wkwebview"===this.g)self.u.ba(!1),this.i.ua({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Xa)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",
a=>{const d=a.prop,c=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)d.startsWith("--")?h.style.setProperty(d,c):h.style[d]=c}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const c=a.prop;a=a.selector;try{const e=document.querySelector(a);var d=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(c)}:
{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),d={isOk:!1}}}return d}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}qa(b){this.g=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,
referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}pa(b){alert(b.message)}ra(b){b=b.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";
async function $a(b){if(!b.H)try{b.H=await navigator.wakeLock.request("screen"),b.H.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.H=null;k(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),k(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),k(b,"wake-lock-error")}}
function ab(){var b=document.body;const a=b.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");b=getComputedStyle(b);b=[b.getPropertyValue("--temp-sai-top"),b.getPropertyValue("--temp-sai-right"),b.getPropertyValue("--temp-sai-bottom"),b.getPropertyValue("--temp-sai-left")].map(d=>{d=parseInt(d,10);
return isFinite(d)?d:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return b}
self.u.D(class extends self.F{constructor(b){super(b,"platform-info");r(this,[["get-initial-state",()=>this.qa()],["request-wake-lock",()=>$a(this)],["release-wake-lock",()=>{this.H&&(this.H.release(),this.H=null)}]]);window.addEventListener("resize",()=>{k(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:ab()})});this.H=null}qa(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:ab(),supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==typeof nw}}});"use strict";
self.u.D(class extends self.F{constructor(b){super(b,"mouse");r(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.i.j.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{k(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{k(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";function Z(b){b.stopPropagation()}function cb(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.u.D(class extends self.bb{constructor(b){super(b);v(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}La(b,a){let d;const c=a.type;"textarea"===c?(d=document.createElement("textarea"),d.style.resize="none"):(d=document.createElement("input"),d.type=c);d.style.position="absolute";d.autocomplete="off";d.addEventListener("pointerdown",Z);d.addEventListener("pointermove",Z);d.addEventListener("pointerrawupdate",Z);d.addEventListener("pointerup",Z);d.addEventListener("mousedown",Z);d.addEventListener("mouseup",
Z);d.addEventListener("keydown",cb);d.addEventListener("keyup",cb);d.addEventListener("click",e=>{e.stopPropagation();x(this,"click",b)});d.addEventListener("dblclick",e=>{e.stopPropagation();x(this,"dblclick",b)});d.addEventListener("input",()=>t(this,"change",b,{text:d.value}));a.id&&(d.id=a.id);a.className&&(d.className=a.className);this.ma(d,a);return d}ma(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;b.spellcheck=a.spellCheck;
a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});"use strict";function db(b){return new Promise((a,d)=>{const c=new FileReader;c.onload=()=>a(c.result);c.onerror=()=>d(c.error);c.readAsArrayBuffer(b)})}async function eb(b,a){a=a.text;let d=!1;try{await navigator.clipboard.writeText(a),d=!0}catch(c){console.error("Failed to copy to clipboard: ",c),d=!1}k(b,"copy-result",{isOk:d})}
async function fb(b,a){const d=a.arrayBuffer;a=a.type;let c=!1;try{const e={};e[a]=new Blob([d],{type:a});await navigator.clipboard.write([new ClipboardItem(e)]);c=!0}catch(e){console.error("Failed to copy to clipboard: ",e),c=!1}k(b,"copy-result",{isOk:c})}async function gb(b){let a=!1,d="";try{d=await navigator.clipboard.readText(),a=!0}catch(c){console.error("Failed to paste: ",c),d="",a=!1}k(b,"request-paste-text-result",{isOk:a,text:d})}
async function ib(b){let a=!1,d=[];try{var c=await navigator.clipboard.read();if(1<=c.length){const e=c[0];c=[];const f=e.types;for(const g of f)c.push((async()=>{const h=await e.getType(g);return await db(h)})());d=(await Promise.all(c)).map((g,h)=>[f[h],g]);a=!0}else a=!1}catch(e){console.error("Failed to paste: ",e),a=!1}k(b,"request-paste-binary-result",{isOk:a,binary:d})}
async function jb(b,a){if((new Set(["canvas","body","html"])).has((a.target.tagName||"").toLowerCase())){a.preventDefault();var d=a.clipboardData.getData("text");d?k(b,"window-paste-text",{text:d}):1<=a.clipboardData.files.length&&(a=a.clipboardData.files[0],d=await db(a),k(b,"window-paste-binary",{arrayBuffer:d,type:a.type}))}}
self.u.D(class extends self.F{constructor(b){super(b,"clipboard");r(this,[["copy-text",a=>eb(this,a)],["copy-binary",a=>fb(this,a)],["request-paste-text",()=>gb(this)],["request-paste-binary",()=>ib(this)]]);window.addEventListener("paste",a=>jb(this,a))}});
