function k(b,a,c,d){b.i.na(b.S,a,c,d,void 0)}function p(b,a,c,d){b.i.o?k(b,a,c,d):b.i.sb()._OnMessageFromDOM({type:"event",component:b.S,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.i.h(b.S,a,c)}function r(b,a){for(const [c,d]of a)q(b,c,d)}window.N=class{constructor(b,a){this.i=b;this.S=a}Ka(){}};window.Wb=class{constructor(){}};"use strict";class aa{constructor(b){this.xa=b;this.za=!1;this.Ca=!0}}
function ba(b,a){const c=a.elementId,d=b.ka(c,a),e=new aa(d);b.T.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Ca=!!a.isVisible;d.addEventListener("focus",()=>{t(b,"elem-focused",c)});d.addEventListener("blur",()=>{t(b,"elem-blurred",c)});b.da&&document.body.appendChild(d)}function u(b,a,c){q(b,a,d=>{const e=w(b,d.elementId);return c(e,d)})}function w(b,a){b=b.T.get(a);if(!b)throw Error(`no element with id ${a}`);return b.xa}
function t(b,a,c,d){d||(d={});d.elementId=c;k(b,a,d)}function x(b,a,c){var d;d||(d={});d.elementId=c;p(b,a,d)}
window.Ma=class extends self.N{constructor(b,a){super(b,a);this.T=new Map;this.da=!0;r(this,[["create",c=>ba(this,c)],["destroy",c=>{c=c.elementId;const d=w(this,c);this.da&&d.parentElement.removeChild(d);this.T.delete(c)}],["set-visible",c=>{if(this.da){var d=this.T.get(c.elementId),e=d.xa;d.za?e.style.display=c.isVisible?"":"none":d.Ca=!!c.isVisible}}],["update-position",c=>{if(this.da){var d=this.T.get(c.elementId),e=d.xa;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=c.width+"px";
e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.za||(d.za=!0,d.Ca&&(e.style.display=""))}}],["update-state",c=>{const d=w(this,c.elementId);this.P(d,c)}],["focus",c=>this.sa(c)],["set-css-style",c=>{const d=w(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{w(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{w(this,c.elementId).removeAttribute(c.name)}]]);u(this,"get-element",c=>
c)}ka(){throw Error("required override");}P(){throw Error("required override");}sa(b){var a=w(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent),da=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ea=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Mb?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.Qb+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let fa=!1,ha=!1;function ia(){if(!fa){try{new Worker("blob://",{get type(){ha=!0}})}catch(b){}fa=!0}return ha}let A=new Audio;
const ja={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ka(b){b=await la(b);return(new TextDecoder("utf-8")).decode(b)}
function la(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const B=[];let C=0;window.RealFile=window.File;const D=[],E=new Map,F=new Map;let ma=0;const na=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");na.push(b)};const oa=new Set(["cordova","playable-ad","instant-games"]);let pa=!1;
window.v=class b{constructor(a){this.o=a.Sb;this.W=null;this.m="";this.J=a.Pb;this.$={};this.Ea=this.L=null;this.ea=[];this.j=this.Y=null;this.Ya=!1;this.U=null;this.I=-1;this.Hb=()=>this.zb();this.Ha=[];this.g=a.ab;this.Ba="file"===location.protocol.substr(0,4);!this.o||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ia()||(this.o=!1);this.o&&da&&(this.o=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.o=!1;if("cordova"===this.g&&this.o)if(y){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.o=!1)}else this.o=!1;this.fa=this.B=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime","cordova-fetch-local-file",c=>this.vb(c));this.h("runtime","create-job-worker",()=>this.wb());"cordova"===this.g?document.addEventListener("deviceready",()=>this.Qa(a)):this.Qa(a)}gb(){return ca&&
"cordova"===this.g}ma(){const a=navigator.userAgent;return ca&&oa.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}eb(){return y}Na(){return y&&oa.has(this.g)}async Qa(a){"macos-wkwebview"===this.g&&this.va({type:"ready"});if("playable-ad"===this.g){this.B=self.c3_base64files;this.fa={};await this.ob();for(let d=0,e=a.M.length;d<e;++d){var c=a.M[d];this.fa.hasOwnProperty(c)?a.M[d]={Mb:!0,Qb:this.fa[c]}:this.B.hasOwnProperty(c)&&(a.M[d]=URL.createObjectURL(this.B[c]))}a.ia=[]}if("nwjs"===
this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.kb(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Ob?this.m=a.Ob:(c=location.origin,this.m=("null"===c?"file:///":c)+location.pathname,c=this.m.lastIndexOf("/"),-1!==c&&(this.m=this.m.substr(0,c+1)));a.Ub&&(this.$=a.Ub);c=new MessageChannel;this.W=c.port1;this.W.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.yb(d));this.U=new self.hb(this);await qa(this.U);
"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.o?await this.ub(a,c.port2):await this.tb(a,c.port2)}pa(a){a=this.$.hasOwnProperty(a)?this.$[a]:a.endsWith("/workermain.js")&&this.$.hasOwnProperty("workermain.js")?this.$["workermain.js"]:"playable-ad"===this.g&&this.B.hasOwnProperty(a)?this.B[a]:
a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async la(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.Ba)return a=await this.ja(d.Lb?a:this.J+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}A(){return Math.max(window.innerWidth,
1)}u(){return Math.max(window.innerHeight,1)}Pa(a){var c=this.m,d=location.href,e=this.A(),f=this.u(),g=window.devicePixelRatio,h=b.O(),l=a.ac,m=window.cr_previewImageBlobs||this.B,n=window.cr_previewProjectFileBlobs,Da=window.cr_previewProjectFiles,Ea=window.Zb||"";a=a.ab;var Fa=(new URLSearchParams(self.location.search)).has("debug"),P=this.U;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:l,previewImageBlobs:m,previewProjectFileBlobs:n,
previewProjectFileSWUrls:Da,swClientId:Ea,exportType:a,isDebug:Fa,ife:!!self.$b,jobScheduler:{inputPort:P.Aa,outputPort:P.Ga,maxNumWorkers:P.Fb},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.J+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.J+"opus.wasm.wasm",isFileProtocol:this.Ba,isiOSCordova:this.gb(),isiOSWebView:this.ma(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async ub(a,c){const d=this.pa(a.Tb);"preview"===this.g?(this.L=new Worker("previewworker.js",
{type:"module",name:"Runtime"}),await new Promise((h,l)=>{const m=n=>{this.L.removeEventListener("message",m);n.data&&"ok"===n.data.type?h():l()};this.L.addEventListener("message",m);this.L.postMessage({type:"construct-worker-init","import":(new URL(d,this.m)).toString()})})):this.L=await this.la(d,this.m,{type:"module",name:"Runtime",Lb:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);window.c3canvas=
this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.ia||[],g=a.M;f=await Promise.all(f.map(h=>this.H(h)));g=await Promise.all(g.map(h=>this.H(h)));if("cordova"===this.g)for(let h=0,l=a.ha.length;h<l;++h){const m=a.ha[h],n=m[0];if(n===a.Ja||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m[1]=await this.H(n)}this.L.postMessage(Object.assign(this.Pa(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ha,
mainProjectScript:a.Ja,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ra(this.U)]);this.ea=D.map(h=>new h(this));this.Oa();sa(this.Y);self.c3_callFunction=(h,l)=>{var m=this.Y;return m.i.ib(m.S,{name:h,params:l})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.na("runtime","go-to-last-error-script"))}async tb(a,c){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();
this.ea=D.map(g=>new g(this));this.Oa();var d=a.M.map(g=>"string"===typeof g?(new URL(g,this.m)).toString():g);if(Array.isArray(a.ia)){var e=[...a.ia].map(g=>g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.H(g)));await Promise.all(d.map(g=>z(g)));d=self.C3_ProjectScriptsStatus;e=a.Ja;const f=a.ha;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.H(h),await z(h),"preview"!==this.g||d[g]||this.Sa(g,"main script did not run to completion")}catch(l){this.Sa(g,
l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.H(h),await z(h);"preview"===this.g&&"object"!==typeof self.Vb.Xb?(this.ba(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Pa(a),{isInWorker:!1,messagePort:c,canvas:this.j,runOnStartupFunctions:na}),sa(this.Y),
this.Ra(),this.Ea=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ea,a))}Sa(a,c){this.ba();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ra(){this.ba()}ba(){const a=window.Jb;a&&(a.parentElement.removeChild(a),window.Jb=null)}async wb(){const a=await ta(this.U);return{outputPort:a,transferables:[a]}}sb(){if(this.o)throw Error("not available in worker mode");
return this.Ea}na(a,c,d,e,f){this.W.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}ib(a,c){const d=ma++,e=new Promise((f,g)=>{F.set(d,{resolve:f,reject:g})});this.W.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.xb(a);if("result"===c)this.Ab(a);else if("runtime-ready"===c)this.Bb();else if("alert-error"===c)this.ba(),
alert(a.message);else if("creating-runtime"===c)this.Ra();else throw Error(`unknown message '${c}'`);}xb(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=E.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.aa(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.aa(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.aa(f,!1,""+h)}):this.aa(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);
else console.warn(`[DOM] No event handlers for component '${c}'`)}aa(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.W.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ab(a){const c=a.responseId,d=a.isOk;a=a.result;const e=F.get(c);d?e.resolve(a):e.reject(a);F.delete(c)}h(a,c,d){let e=E.get(a);e||(e=new Map,E.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static G(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}Oa(){for(const a of this.ea)if("runtime"===
a.S){this.Y=a;return}throw Error("cannot find runtime DOM handler");}yb(a){this.na("debugger","message",a)}Bb(){for(const a of this.ea)a.Ka()}static O(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||pa)}static ca(a){pa=!!a}kb(a){this.Ha.push(a);this.ua()}ua(){-1===this.I&&this.Ha.length&&(this.I=requestAnimationFrame(this.Hb))}mb(){-1!==this.I&&(cancelAnimationFrame(this.I),this.I=-1)}zb(){this.I=-1;for(const a of this.Ha)a();this.ua()}ta(){this.Y.ta()}jb(){this.Ya=
!0}cb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}fb(a){return!this.cb(a)}async H(a){return"cordova"===this.g&&(a.startsWith("file:")||this.Ba&&this.fb(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.ja(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async vb(a){const c=a.filename;switch(a.as){case "text":return await this.bb(c);case "buffer":return await this.ja(c);default:throw Error("unsupported type");}}La(a){const c=
window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async bb(a){a=await this.La(a);return await ka(a)}oa(){if(B.length&&!(8<=C)){C++;var a=B.shift();this.pb(a.filename,a.Rb,a.Kb)}}ja(a){return new Promise((c,d)=>{B.push({filename:a,Rb:e=>{C--;this.oa();c(e)},Kb:e=>{C--;this.oa();d(e)}});this.oa()})}async pb(a,c,d){try{const e=await this.La(a),f=await la(e);c(f)}catch(e){d(e)}}va(a){if("windows-webview2"===this.g)window.chrome.webview.postMessage(JSON.stringify(a));
else if("macos-wkwebview"===this.g)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async ob(){const a=[];for(const [c,d]of Object.entries(this.B))a.push(this.nb(c,d));await Promise.all(a)}async nb(a,c){if("object"===typeof c)this.B[a]=new Blob([c.str],{type:c.type}),this.fa[a]=c.str;else{let d=await this.rb(c);d||(d=this.qb(c));this.B[a]=d}}async rb(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}qb(a){a=this.Cb(a);return this.lb(a.data,a.Nb)}Cb(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Nb:a,data:d}}lb(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,l;for(l=h=0;h<e;++h)g[h]=a.charCodeAt(l++)|a.charCodeAt(l++)<<8|a.charCodeAt(l++)<<16|a.charCodeAt(l++)<<24;for(d&=
3;d--;)f[l]=a.charCodeAt(l),++l;return new Blob([f],{type:c})}};"use strict";const G=self.v;function ua(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const va=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),H={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},wa={dispatchUserScriptEvent:!0},I={dispatchRuntimeEvent:!0};
function xa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function ya(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await ya(b)}finally{URL.revokeObjectURL(b)}}
function za(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Aa(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await za(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function K(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ba=new Set(["input","textarea","datalist","select"]),Ca=new Set(["canvas","body","html"]);function L(b){b.target.tagName&&Ca.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ga(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Aa(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let M=!1;document.addEventListener("pause",()=>M=!0);document.addEventListener("resume",()=>M=!1);function sa(b){b.Wa=!0;b.Da=b.i.A();b.V=b.i.u()}async function Ha(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ia(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ja(b){return await self.C3_GetSvgImageSize(b.blob)}function Ka(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function La(b){self.setTimeout(()=>{b.Va=!0},1E3);"cordova"===b.i.g?(document.addEventListener("pause",()=>O(b,!0)),document.addEventListener("resume",()=>O(b,!1))):document.addEventListener("visibilitychange",()=>O(b,document.hidden));return{isSuspended:!(!document.hidden&&!M)}}
function Na(b){b.Ua||(b.Ua=!0,window.addEventListener("deviceorientation",a=>{b.l||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},H)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},H)}))}
function Oa(b){b.Ta||(b.Ta=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},H)}}))}async function Pa(b){await xa(b.url)}
function Qa(b,a){b.Xa=a.message;-1===b.ya&&(b.ya=setTimeout(()=>{b.ya=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Xa)},250))}function Q(b){if(!b.l){var a=G.O();a&&"any"!==b.Ia&&Ra(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.A(),innerHeight:b.u()})}}function R(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:G.O(),innerWidth:b.A(),innerHeight:b.u()})}
function O(b,a){a?b.i.mb():b.i.ua();k(b,"visibilitychange",{hidden:a})}function Sa(b,a,c){"Backspace"===c.key&&L(c);if(!b.l){var d=va.get(c.code)||c.code;p(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},H)}}
function S(b,a,c,d){b.l||ua(c)||p(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function T(b){window!==window.top&&window.focus();Ta(b.target)&&document.activeElement&&!Ta(document.activeElement)&&document.activeElement.blur()}
function U(b,a,c){if(!b.l){var d=0;"mouse"===c.pointerType&&(d=b.X);p(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},H);"mouse"===c.pointerType&&(d="mousemove",
"pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),S(b,d,c,wa),b.X=c.buttons)}}
function V(b,a,c){if(!b.l&&!ua(c)){var d=b.X;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");p(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},H);b.X=c.buttons;S(b,c.type,c,wa)}}
function W(b,a,c){if(!b.l)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];p(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.s,pageX:f.pageX,pageY:f.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
H)}}function X(b,a,c){document.body.style.transform="";b.s=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.s=a))}}function Ua(b,a,c,d){const e=b.A(),f=b.u();b.K=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.O()}):10>d&&Va(b,e,f,d+1)}
function Va(b,a,c,d){-1!==b.K&&clearTimeout(b.K);b.K=setTimeout(()=>Ua(b,a,c,d),48)}
function Ra(b){b=b.Ia;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Ta(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
G.G(class extends self.N{constructor(b){super(b,"runtime");this.Za=!0;this.Wa=!1;this.K=-1;this.Ia="any";this.Ta=this.Ua=!1;this.ga=document.createElement("div");this.ga.className="c3-screen-reader-text";this.ga.setAttribute("aria-live","polite");document.body.appendChild(this.ga);this.D=null;this.l=!1;this.Xa="";this.ya=-1;this.Va=!1;this.Da=b.A();this.V=b.u();this.s=this.Z=0;b.h("canvas","update-size",d=>{var e=this.i;e.Ya||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",
e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Za&&(e.style.display="",this.Za=!1))});b.h("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.h("runtime","load-webfonts",d=>Ha(d));b.h("runtime","raster-svg-image",d=>Ia(d));b.h("runtime","get-svg-image-size",
d=>Ja(d));b.h("runtime","set-target-orientation",d=>{this.Ia=d.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime","post-to-debugger",d=>Ka(d));b.h("runtime","go-to-script",d=>Ka(d));b.h("runtime","before-start-ticking",()=>La(this));b.h("runtime","debug-highlight",d=>{if(d.show){this.D||(this.D=document.createElement("div"),this.D.id="inspectOutline",document.body.appendChild(this.D));var e=this.D;e.style.display="";e.style.left=d.left-
1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.D&&(this.D.style.display="none")});b.h("runtime","enable-device-orientation",()=>Na(this));b.h("runtime","enable-device-motion",()=>Oa(this));b.h("runtime","add-stylesheet",d=>Pa(d));b.h("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.h("runtime","alert",d=>this.qa(d));b.h("runtime","screen-reader-text",
d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ga.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});b.h("runtime","hide-cordova-splash",
()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",d=>{this.l=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.jb()});b.h("runtime","export-to-video-progress",d=>Qa(this,d));b.h("runtime","exported-to-video",d=>{window.Ib({type:"exported-video",arrayBuffer:d.arrayBuffer,contentType:d.contentType,
time:d.time})});b.h("runtime","exported-to-image-sequence",d=>{window.Ib({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||K(e)||d.preventDefault()});const c=b.j;window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);c.addEventListener("selectstart",L);c.addEventListener("gesturehold",L);window.addEventListener("touchstart",
L,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",L,{passive:!1}),c.addEventListener("pointerdown",L)):c.addEventListener("touchstart",L);this.X=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ga,{passive:!1});window.addEventListener("wheel",Ga,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.Wa){var d=this.A();var e=this.u();if(this.i.Na()){if(this.Va){if(this.Da===d&&e<
this.V){this.Z=this.V-e;X(this,this.V,this.Z);d=void 0;break a}0<this.Z&&(this.Z=0,X(this,e,this.Z))}this.Da=d;this.V=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.O()});this.i.ma()&&(-1!==this.K&&clearTimeout(this.K),Ua(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>Q(this));window.addEventListener("webkitfullscreenchange",()=>Q(this));window.addEventListener("mozfullscreenchange",()=>Q(this));window.addEventListener("fullscreenerror",
d=>R(this,d));window.addEventListener("webkitfullscreenerror",d=>R(this,d));window.addEventListener("mozfullscreenerror",d=>R(this,d));if(b.ma())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):K(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(G.ca(!0),Q(this)):"exited-fullscreen"===d?(G.ca(!1),Q(this)):console.warn("Unknown wrapper message: ",d)};this.Fa=new Set;this.Gb=new WeakSet;this.Eb=!1}Ka(){window.addEventListener("focus",()=>{k(this,"window-focus",null,I)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}k(this,"window-blur",{parentHasFocus:a},I);this.X=0});window.addEventListener("focusin",a=>{a=a.target;(Ba.has(a.tagName.toLowerCase())||K(a))&&k(this,"keyboard-blur",null,I)});window.addEventListener("keydown",a=>Sa(this,"keydown",a));window.addEventListener("keyup",a=>Sa(this,"keyup",a));window.addEventListener("dblclick",a=>S(this,"dblclick",a,H));window.addEventListener("wheel",a=>{this.l||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.s,pageX:a.pageX,pageY:a.pageY+this.s,deltaX:a.deltaX,
deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},H)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{T(a);U(this,"pointerdown",a)}),this.i.o&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{U(this,"pointermove",a)}):window.addEventListener("pointermove",a=>U(this,"pointermove",a)),window.addEventListener("pointerup",a=>U(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>U(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{T(a);V(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>V(this,"pointermove",a)),window.addEventListener("mouseup",a=>V(this,"pointerup",a)),window.addEventListener("touchstart",a=>{T(a);W(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>W(this,"pointermove",a)),window.addEventListener("touchend",a=>W(this,"pointerup",a)),window.addEventListener("touchcancel",a=>W(this,"pointercancel",a)));const b=
()=>this.ta();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.eb()&&!this.i.Na()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{X(this,this.u(),navigator.virtualKeyboard.boundingRect.height)}))}A(){return this.i.A()}u(){return this.i.u()}ta(){var b=
[...this.Fa];this.Fa.clear();if(!this.Eb)for(const a of b)(b=a.play())&&b.catch(()=>{this.Gb.has(a)||this.Fa.add(a)})}qa(b){alert(b.message)}});"use strict";async function qa(b){if(b.Db)throw Error("already initialised");b.Db=!0;var a=b.C.pa(("playable-ad"===b.C.g?b.C.J:"")+"dispatchworker.js");b.wa=await b.C.la(a,b.R,{name:"DispatchWorker"});a=new MessageChannel;b.Aa=a.port1;b.wa.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Ga=await ta(b)}function ra(b){return[b.Aa,b.Ga]}
async function ta(b){const a=b.$a.length;var c=b.C.pa(("playable-ad"===b.C.g?b.C.J:"")+"jobworker.js");c=await b.C.la(c,b.R,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.wa.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.$a.push(c);return e.port1}
self.hb=class{constructor(b){this.C=b;this.R=b.m;this.R="preview"===b.g?this.R+"workers/":this.R+b.J;this.Fb=Math.min(navigator.hardwareConcurrency||2,16);this.wa=null;this.$a=[];this.Ga=this.Aa=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.v({Sb:!1,Tb:"workermain.js",M:["scripts/c3runtime.js"],ha:[],Ja:"",Pb:"scripts/",ia:[],ab:"html5"}));"use strict";function Y(b){b.stopPropagation()}function Wa(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.v.G(class extends self.Ma{constructor(b){super(b,"text-input");u(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}ka(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",Y);c.addEventListener("pointermove",Y);c.addEventListener("pointerrawupdate",Y);c.addEventListener("pointerup",Y);c.addEventListener("mousedown",
Y);c.addEventListener("mouseup",Y);c.addEventListener("keydown",Wa);c.addEventListener("keyup",Wa);c.addEventListener("click",e=>{e.stopPropagation();x(this,"click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();x(this,"dblclick",b)});c.addEventListener("input",()=>t(this,"change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.P(c,a);return c}P(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;
b.spellcheck=a.spellCheck;a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});"use strict";function Xa(){}function Ya(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Za(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.v.G(class extends self.N{constructor(b){super(b,"browser");this.g="";r(this,[["get-initial-state",a=>this.ra(a)],["ready-for-sw-messages",()=>Ya(this)],["alert",a=>this.qa(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.sa(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Za(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.Yb||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.g||"macos-wkwebview"===this.g)self.v.ca(!0),
this.i.va({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof
Promise&&d.catch(Xa)}}],["exit-fullscreen",()=>{if("windows-webview2"===this.g||"macos-wkwebview"===this.g)self.v.ca(!1),this.i.va({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Xa)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",
a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:
{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}ra(b){this.g=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,
referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}qa(b){alert(b.message)}sa(b){b=b.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";
async function $a(b,a){a=a.type;let c=!0;0===a?c=await ab():1===a&&(c=await bb());k(b,"permission-result",{type:a,result:c})}async function ab(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function bb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.v.G(class extends self.N{constructor(b){super(b,"touch");q(this,"request-permission",a=>$a(this,a))}});"use strict";function cb(b){return new Promise((a,c)=>{b.getInsetTop(a,c)})}
function db(b){return new Promise((a,c)=>{b.getInsetRight(a,c)})}function eb(b){return new Promise((a,c)=>{b.getInsetBottom(a,c)})}function fb(b){return new Promise((a,c)=>{b.getInsetLeft(a,c)})}
async function gb(b){if(!b.F)try{b.F=await navigator.wakeLock.request("screen"),b.F.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.F=null;k(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),k(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),k(b,"wake-lock-error")}}
async function ib(b){const a=await jb();k(b,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function jb(){var b=self.AndroidNotch;if(b)try{return await Promise.all([cb(b),db(b),eb(b),fb(b)])}catch(c){return console.error("[Construct] Failed to get Android safe area inset: ",c),[0,0,0,0]}else{var a=document.body;b=a.style;b.setProperty("--temp-sai-top","env(safe-area-inset-top)");b.setProperty("--temp-sai-right","env(safe-area-inset-right)");b.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");b.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);return isFinite(c)?c:0});b.removeProperty("--temp-sai-top");b.removeProperty("--temp-sai-right");b.removeProperty("--temp-sai-bottom");b.removeProperty("--temp-sai-left");return a}}
self.v.G(class extends self.N{constructor(b){super(b,"platform-info");r(this,[["get-initial-state",()=>this.ra()],["request-wake-lock",()=>gb(this)],["release-wake-lock",()=>{this.F&&(this.F.release(),this.F=null)}]]);window.addEventListener("resize",()=>ib(this));this.F=null}async ra(){const b=await jb();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:b,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==
typeof nw}}});"use strict";function Z(b){b.stopPropagation()}
self.v.G(class extends self.Ma{constructor(b){super(b,"file-chooser");u(this,"click",a=>{a.click()});u(this,"clear",a=>{a.value=""})}ka(b,a){const c=document.createElement("input");c.type="file";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",Z);c.addEventListener("change",
()=>t(this,"change",b,{files:Array.from(c.files)}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.P(c,a);return c}P(b,a){b.setAttribute("accept",a.accept);a.isMultiSelect?b.setAttribute("multiple",""):b.removeAttribute("multiple")}});
