function k(b,a,c,d){b.i.sa(b.V,a,c,d,void 0)}function p(b,a,c,d){b.i.v?k(b,a,c,d):b.i.xb()._OnMessageFromDOM({type:"event",component:b.V,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.i.h(b.V,a,c)}function r(b,a){for(const [c,d]of a)q(b,c,d)}window.R=class{constructor(b,a){this.i=b;this.V=a}La(){}};window.ob=class{constructor(b){this.Xa=b;this.Jb=5;this.N=-1;this.ja=-Infinity;this.Ob=()=>{this.N=-1;this.ja=Date.now();this.W=!0;this.Xa();this.W=!1};this.Ya=this.W=!1}};
"use strict";function aa(b,a){const c=a.elementId,d=b.pa(c,a);b.s.set(c,d);d.style.boxSizing="border-box";a.isVisible||(d.style.display="none");d.addEventListener("focus",()=>{t(b,"elem-focused",c)});d.addEventListener("blur",()=>{t(b,"elem-blurred",c)});b.ha&&document.body.appendChild(d)}function u(b,a,c){q(b,a,d=>{const e=b.s.get(d.elementId);return c(e,d)})}function t(b,a,c,d){d||(d={});d.elementId=c;k(b,a,d)}function v(b,a,c){var d;d||(d={});d.elementId=c;p(b,a,d)}
window.Na=class extends self.R{constructor(b,a){super(b,a);this.s=new Map;this.ha=!0;r(this,[["create",c=>aa(this,c)],["destroy",c=>{c=c.elementId;const d=this.s.get(c);this.ha&&d.parentElement.removeChild(d);this.s.delete(c)}],["set-visible",c=>{this.ha&&(this.s.get(c.elementId).style.display=c.isVisible?"":"none")}],["update-position",c=>{if(this.ha){var d=this.s.get(c.elementId);d.style.left=c.left+"px";d.style.top=c.top+"px";d.style.width=c.width+"px";d.style.height=c.height+"px";c=c.fontSize;
null!==c&&(d.style.fontSize=c+"em")}}],["update-state",c=>{const d=this.s.get(c.elementId);this.T(d,c)}],["focus",c=>this.xa(c)],["set-css-style",c=>{const d=this.s.get(c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{this.s.get(c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{this.s.get(c.elementId).removeAttribute(c.name)}]]);u(this,"get-element",c=>c)}pa(){throw Error("required override");}T(){throw Error("required override");
}xa(b){var a=this.s.get(b.elementId);b.focus?a.focus():a.blur()}};"use strict";const w=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent);let ba=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Tb?new Promise(c=>{const d="c3_resolve_"+ba;++ba;self[d]=c;a.textContent=b.Xb+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ca=!1,da=!1;function ea(){if(!ca){try{new Worker("blob://",{get type(){da=!0}})}catch(b){}ca=!0}return da}let z=new Audio;
const fa={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function ha(b){b=await ia(b);return(new TextDecoder("utf-8")).decode(b)}
function ia(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const B=[];let C=0;window.RealFile=window.File;const D=[],E=new Map,F=new Map;let ja=0;const ka=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ka.push(b)};const la=new Set(["cordova","playable-ad","instant-games"]);let ma=!1;
window.A=class b{constructor(a){this.v=a.Zb;this.Z=null;this.m="";this.L=a.Wb;this.da={};this.Fa=this.O=null;this.ia=[];this.j=this.ba=null;this.bb=!1;this.X=null;this.K=-1;this.Nb=()=>this.Eb();this.fb=[];this.g=a.gb;this.Da="file"===location.protocol.substr(0,4);!this.v||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ea()||(this.v=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.v=!1;if("cordova"===this.g&&this.v)if(x){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.v=!1)}else this.v=!1;this.ka=this.C=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime","cordova-fetch-local-file",c=>this.Ab(c));this.h("runtime","create-job-worker",()=>this.Bb());"cordova"===this.g?document.addEventListener("deviceready",()=>this.Ra(a)):this.Ra(a)}lb(){return w&&
"cordova"===this.g}ra(){const a=navigator.userAgent;return w&&la.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}jb(){return x}Oa(){return x&&la.has(this.g)}async Ra(a){"macos-wkwebview"===this.g&&this.za({type:"ready"});if("playable-ad"===this.g){this.C=self.c3_base64files;this.ka={};await this.tb();for(let d=0,e=a.P.length;d<e;++d){var c=a.P[d];this.ka.hasOwnProperty(c)?a.P[d]={Tb:!0,Xb:this.ka[c]}:this.C.hasOwnProperty(c)&&(a.P[d]=URL.createObjectURL(this.C[c]))}}a.Vb?this.m=
a.Vb:(c=location.origin,this.m=("null"===c?"file:///":c)+location.pathname,c=this.m.lastIndexOf("/"),-1!==c&&(this.m=this.m.substr(0,c+1)));a.ac&&(this.da=a.ac);c=new MessageChannel;this.Z=c.port1;this.Z.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Db(d));this.X=new self.mb(this);await na(this.X);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,
e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.v?await this.zb(a,c.port2):await this.yb(a,c.port2)}ua(a){a=this.da.hasOwnProperty(a)?this.da[a]:a.endsWith("/workermain.js")&&this.da.hasOwnProperty("workermain.js")?this.da["workermain.js"]:"playable-ad"===this.g&&this.C.hasOwnProperty(a)?this.C[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async qa(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===
this.g&&this.Da)return a=await this.oa(d.Sb?a:this.L+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}B(){return Math.max(window.innerWidth,1)}u(){return Math.max(window.innerHeight,1)}Qa(a){var c=this.m,d=location.href,e=this.B(),f=this.u(),g=window.devicePixelRatio,
h=b.S(),l=a.hc,m=window.cr_previewImageBlobs||this.C,n=window.cr_previewProjectFileBlobs,Aa=window.cr_previewProjectFiles,Ba=window.ec||"";a=a.gb;var Ca=(new URLSearchParams(self.location.search)).has("debug"),N=this.X;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:l,previewImageBlobs:m,previewProjectFileBlobs:n,previewProjectFileSWUrls:Aa,swClientId:Ba,exportType:a,isDebug:Ca,ife:!!self.fc,jobScheduler:{inputPort:N.Ca,outputPort:N.Ha,
maxNumWorkers:N.Lb},supportedAudioFormats:fa,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.L+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.L+"opus.wasm.wasm",isFileProtocol:this.Da,isiOSCordova:this.lb(),isiOSWebView:this.ra(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async zb(a,c){const d=this.ua(a.$b);"preview"===this.g?(this.O=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,l)=>{const m=n=>{this.O.removeEventListener("message",
m);n.data&&"ok"===n.data.type?h():l()};this.O.addEventListener("message",m);this.O.postMessage({type:"construct-worker-init","import":(new URL(d,this.m)).toString()})})):this.O=await this.qa(d,this.m,{type:"module",name:"Runtime",Sb:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.Ka||[],g=a.P;f=await Promise.all(f.map(h=>
this.I(h)));g=await Promise.all(g.map(h=>this.I(h)));if("cordova"===this.g)for(let h=0,l=a.na.length;h<l;++h){const m=a.na[h],n=m[0];if(n===a.Ja||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m[1]=await this.I(n)}this.O.postMessage(Object.assign(this.Qa(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.na,mainProjectScript:a.Ja,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...oa(this.X)]);this.ia=D.map(h=>
new h(this));this.Pa();pa(this.ba);self.c3_callFunction=(h,l)=>{var m=this.ba;return m.i.nb(m.V,{name:h,params:l})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.sa("runtime","go-to-last-error-script"))}async yb(a,c){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.ia=D.map(g=>new g(this));this.Pa();var d=a.P.map(g=>"string"===typeof g?(new URL(g,
this.m)).toString():g);Array.isArray(a.Ka)&&d.unshift(...a.Ka);d=await Promise.all(d.map(g=>this.I(g)));await Promise.all(d.map(g=>y(g)));d=self.C3_ProjectScriptsStatus;const e=a.Ja,f=a.na;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.I(h),await y(h),"preview"!==this.g||d[g]||this.Ta(g,"main script did not run to completion")}catch(l){this.Ta(g,l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.I(h),await y(h);"preview"===this.g&&"object"!==typeof self.bc.cc?
(this.fa(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Qa(a),{isInWorker:!1,messagePort:c,canvas:this.j,runOnStartupFunctions:ka}),pa(this.ba),this.Sa(),this.Fa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Fa,a))}Ta(a,c){this.fa();console.error(`[Preview] Failed to load project main script (${a}): `,
c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Sa(){this.fa()}fa(){const a=window.Qb;a&&(a.parentElement.removeChild(a),window.Qb=null)}async Bb(){const a=await qa(this.X);return{outputPort:a,transferables:[a]}}xb(){if(this.v)throw Error("not available in worker mode");return this.Fa}sa(a,c,d,e,f){this.Z.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}nb(a,c){const d=ja++,e=new Promise((f,g)=>{F.set(d,{resolve:f,reject:g})});this.Z.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Cb(a);if("result"===c)this.Fb(a);else if("runtime-ready"===c)this.Gb();else if("alert-error"===c)this.fa(),alert(a.message);else if("creating-runtime"===c)this.Sa();else throw Error(`unknown message '${c}'`);}Cb(a){const c=a.component,
d=a.handler,e=a.data,f=a.responseId;if(a=E.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.ea(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.ea(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.ea(f,!1,""+h)}):this.ea(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}ea(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.Z.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Fb(a){const c=a.responseId,d=a.isOk;a=a.result;const e=F.get(c);d?e.resolve(a):e.reject(a);F.delete(c)}h(a,c,d){let e=E.get(a);e||(e=new Map,E.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static H(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}Pa(){for(const a of this.ia)if("runtime"===a.V){this.ba=a;return}throw Error("cannot find runtime DOM handler");
}Db(a){this.sa("debugger","message",a)}Gb(){for(const a of this.ia)a.La()}static S(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ma)}static ga(a){ma=!!a}Ua(){-1===this.K&&this.fb.length&&(this.K=requestAnimationFrame(this.Nb))}rb(){-1!==this.K&&(cancelAnimationFrame(this.K),this.K=-1)}Eb(){this.K=-1;for(const a of this.fb)a();this.Ua()}ya(){this.ba.ya()}pb(){this.bb=!0}ib(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===
a.substr(0,5)}kb(a){return!this.ib(a)}async I(a){return"cordova"===this.g&&(a.startsWith("file:")||this.Da&&this.kb(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.oa(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ab(a){const c=a.filename;switch(a.as){case "text":return await this.hb(c);case "buffer":return await this.oa(c);default:throw Error("unsupported type");}}Ma(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,
e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async hb(a){a=await this.Ma(a);return await ha(a)}ta(){if(B.length&&!(8<=C)){C++;var a=B.shift();this.ub(a.filename,a.Yb,a.Rb)}}oa(a){return new Promise((c,d)=>{B.push({filename:a,Yb:e=>{C--;this.ta();c(e)},Rb:e=>{C--;this.ta();d(e)}});this.ta()})}async ub(a,c,d){try{const e=await this.Ma(a),f=await ia(e);c(f)}catch(e){d(e)}}za(a){if("windows-webview2"===this.g)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===
this.g)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async tb(){const a=[];for(const [c,d]of Object.entries(this.C))a.push(this.sb(c,d));await Promise.all(a)}async sb(a,c){if("object"===typeof c)this.C[a]=new Blob([c.str],{type:c.type}),this.ka[a]=c.str;else{let d=await this.wb(c);d||(d=this.vb(c));this.C[a]=d}}async wb(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}vb(a){a=this.Hb(a);return this.qb(a.data,a.Ub)}Hb(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Ub:a,data:d}}qb(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,l;for(l=h=0;h<e;++h)g[h]=a.charCodeAt(l++)|a.charCodeAt(l++)<<8|a.charCodeAt(l++)<<16|a.charCodeAt(l++)<<24;for(d&=
3;d--;)f[l]=a.charCodeAt(l),++l;return new Blob([f],{type:c})}};"use strict";const G=self.A;function ra(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const sa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),H={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},ta={dispatchUserScriptEvent:!0},I={dispatchRuntimeEvent:!0};
function ua(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function va(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await va(b)}finally{URL.revokeObjectURL(b)}}
function wa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function xa(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await wa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function K(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const ya=new Set(["input","textarea","datalist","select"]),za=new Set(["canvas","body","html"]);function L(b){za.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Da(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await xa(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let M=!1;document.addEventListener("pause",()=>M=!0);document.addEventListener("resume",()=>M=!1);function pa(b){b.$a=!0;b.Ea=b.i.B();b.Y=b.i.u()}async function Ea(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Fa(b){return await self.C3_GetSvgImageSize(b.blob)}
function Ga(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ha(b){self.setTimeout(()=>{b.Za=!0},1E3);"cordova"===b.i.g?(document.addEventListener("pause",()=>O(b,!0)),document.addEventListener("resume",()=>O(b,!1))):document.addEventListener("visibilitychange",()=>O(b,document.hidden));return{isSuspended:!(!document.hidden&&!M)}}
function Ia(b){b.Wa||(b.Wa=!0,window.addEventListener("deviceorientation",a=>{b.l||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},H)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},H)}))}
function Ja(b){b.Va||(b.Va=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},H)}}))}async function Ka(b){await ua(b.url)}
function La(b,a){b.ab=a.message;-1===b.Ba&&(b.Ba=setTimeout(()=>{b.Ba=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.ab)},250))}function P(b){if(!b.l){var a=G.S();a&&"any"!==b.Ia&&Ma(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.B(),innerHeight:b.u()})}}function Q(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:G.S(),innerWidth:b.B(),innerHeight:b.u()})}
function O(b,a){a?b.i.rb():b.i.Ua();k(b,"visibilitychange",{hidden:a})}function Oa(b,a,c){"Backspace"===c.key&&L(c);if(!b.l){var d=sa.get(c.code)||c.code;p(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},H)}}
function S(b,a,c,d){b.l||ra(c)||p(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.o,pageX:c.pageX,pageY:c.pageY+b.o,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function T(b){window!==window.top&&window.focus();Pa(b.target)&&document.activeElement&&!Pa(document.activeElement)&&document.activeElement.blur()}
function U(b,a,c){if(!b.l){if(b.aa&&"pointermove"!==a){var d=b.aa;d.W||(-1!==d.N&&(self.clearTimeout(d.N),d.N=-1),d.ja=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.$);p(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.o,pageX:c.pageX,pageY:c.pageY+b.o,movementX:(c.movementX||0)+b.la,movementY:(c.movementY||0)+b.ma,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||
0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},H);b.la=0;b.ma=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),S(b,d,c,ta),b.$=c.buttons)}}
function V(b,a,c){if(!b.l&&!ra(c)){var d=b.$;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");p(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.o,pageX:c.pageX,pageY:c.pageY+b.o,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},H);b.$=c.buttons;S(b,c.type,c,ta)}}
function W(b,a,c){if(!b.l)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];p(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.o,pageX:f.pageX,pageY:f.pageY+b.o,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
H)}}function X(b,a,c){document.body.style.transform="";b.o=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.o=a))}}function Qa(b,a,c,d){const e=b.B(),f=b.u();b.M=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.S()}):10>d&&Ra(b,e,f,d+1)}
function Ra(b,a,c,d){-1!==b.M&&clearTimeout(b.M);b.M=setTimeout(()=>Qa(b,a,c,d),48)}
function Ma(b){b=b.Ia;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Pa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
G.H(class extends self.R{constructor(b){super(b,"runtime");this.cb=!0;this.$a=!1;this.M=-1;this.Ia="any";this.Va=this.Wa=!1;this.F=null;this.l=!1;this.ab="";this.Ba=-1;this.J=this.aa=null;this.ma=this.la=0;this.Za=!1;this.Ea=b.B();this.Y=b.u();this.o=this.ca=0;b.h("canvas","update-size",d=>{var e=this.i;e.bb||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",
d.displayScale),this.cb&&(e.style.display="",this.cb=!1))});b.h("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.h("runtime","raster-svg-image",d=>Ea(d));b.h("runtime","get-svg-image-size",d=>Fa(d));b.h("runtime","set-target-orientation",d=>{this.Ia=d.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime",
"post-to-debugger",d=>Ga(d));b.h("runtime","go-to-script",d=>Ga(d));b.h("runtime","before-start-ticking",()=>Ha(this));b.h("runtime","debug-highlight",d=>{if(d.show){this.F||(this.F=document.createElement("div"),this.F.id="inspectOutline",document.body.appendChild(this.F));var e=this.F;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.F&&(this.F.style.display="none")});b.h("runtime","enable-device-orientation",
()=>Ia(this));b.h("runtime","enable-device-motion",()=>Ja(this));b.h("runtime","add-stylesheet",d=>Ka(d));b.h("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.h("runtime","alert",d=>this.va(d));b.h("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",d=>{this.l=!0;const e=document.createElement("h1");
e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.pb()});b.h("runtime","export-to-video-progress",d=>La(this,d));b.h("runtime","exported-to-video",d=>{window.Pb({type:"exported-video",blob:d.blob,time:d.time})});b.h("runtime","exported-to-image-sequence",d=>{window.Pb({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);
window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||K(e)||d.preventDefault()});const c=b.j;window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);c.addEventListener("selectstart",L);c.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",L,{passive:!1}),c.addEventListener("pointerdown",L)):c.addEventListener("touchstart",L);this.$=
0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Da,{passive:!1});window.addEventListener("wheel",Da,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.$a){var d=this.B();var e=this.u();if(this.i.Oa()){if(this.Za){if(this.Ea===d&&e<this.Y){this.ca=this.Y-e;X(this,this.Y,this.ca);d=void 0;break a}0<this.ca&&(this.ca=0,X(this,e,this.ca))}this.Ea=d;this.Y=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,
isFullscreen:G.S()});this.i.ra()&&(-1!==this.M&&clearTimeout(this.M),Qa(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>P(this));window.addEventListener("webkitfullscreenchange",()=>P(this));window.addEventListener("mozfullscreenchange",()=>P(this));window.addEventListener("fullscreenerror",d=>Q(this,d));window.addEventListener("webkitfullscreenerror",d=>Q(this,d));window.addEventListener("mozfullscreenerror",d=>Q(this,d));if(b.ra())if(window.visualViewport){let d=
Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):K(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===
d?(G.ga(!0),P(this)):"exited-fullscreen"===d?(G.ga(!1),P(this)):console.warn("Unknown wrapper message: ",d)};this.Ga=new Set;this.Mb=new WeakSet;this.Kb=!1}La(){window.addEventListener("focus",()=>{k(this,"window-focus",null,I)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},I);this.$=0});window.addEventListener("focusin",a=>{a=a.target;(ya.has(a.tagName.toLowerCase())||K(a))&&k(this,"keyboard-blur",
null,I)});window.addEventListener("keydown",a=>Oa(this,"keydown",a));window.addEventListener("keyup",a=>Oa(this,"keyup",a));window.addEventListener("dblclick",a=>S(this,"dblclick",a,H));window.addEventListener("wheel",a=>{this.l||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.o,pageX:a.pageX,pageY:a.pageY+this.o,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},H)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{T(a);
U(this,"pointerdown",a)}),this.i.v&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.aa=new self.ob(()=>{U(this,"pointermove",this.J);this.J=null}),this.aa.Ya=!0,window.addEventListener("pointerrawupdate",a=>{this.J&&(this.la+=this.J.movementX||0,this.ma+=this.J.movementY||0);this.J=a;a=this.aa;if(-1===a.N){var c=Date.now(),d=c-a.ja,e=a.Jb;d>=e&&a.Ya?(a.ja=c,a.W=!0,a.Xa(),a.W=!1):a.N=self.setTimeout(a.Ob,Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>U(this,"pointermove",
a)),window.addEventListener("pointerup",a=>U(this,"pointerup",a)),window.addEventListener("pointercancel",a=>U(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{T(a);V(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>V(this,"pointermove",a)),window.addEventListener("mouseup",a=>V(this,"pointerup",a)),window.addEventListener("touchstart",a=>{T(a);W(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>W(this,"pointermove",a)),window.addEventListener("touchend",
a=>W(this,"pointerup",a)),window.addEventListener("touchcancel",a=>W(this,"pointercancel",a)));const b=()=>this.ya();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.jb()&&!this.i.Oa()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{X(this,this.u(),
navigator.virtualKeyboard.boundingRect.height)}))}B(){return this.i.B()}u(){return this.i.u()}ya(){var b=[...this.Ga];this.Ga.clear();if(!this.Kb)for(const a of b)(b=a.play())&&b.catch(()=>{this.Mb.has(a)||this.Ga.add(a)})}va(b){alert(b.message)}});"use strict";
async function na(b){if(b.Ib)throw Error("already initialised");b.Ib=!0;var a=b.D.ua(("playable-ad"===b.D.g?b.D.L:"")+"dispatchworker.js");b.Aa=await b.D.qa(a,b.U,{name:"DispatchWorker"});a=new MessageChannel;b.Ca=a.port1;b.Aa.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Ha=await qa(b)}function oa(b){return[b.Ca,b.Ha]}
async function qa(b){const a=b.eb.length;var c=b.D.ua(("playable-ad"===b.D.g?b.D.L:"")+"jobworker.js");c=await b.D.qa(c,b.U,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Aa.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.eb.push(c);return e.port1}
self.mb=class{constructor(b){this.D=b;this.U=b.m;this.U="preview"===b.g?this.U+"workers/":this.U+b.L;this.Lb=Math.min(navigator.hardwareConcurrency||2,16);this.Aa=null;this.eb=[];this.Ha=this.Ca=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.A({Zb:!1,$b:"workermain.js",P:["scripts/c3runtime.js"],na:[],Ja:"",Wb:"scripts/",Ka:[],gb:"html5"}));"use strict";function Y(b){b.stopPropagation()}function Sa(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.A.H(class extends self.Na{constructor(b){super(b,"text-input");u(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}pa(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",Y);c.addEventListener("pointermove",Y);c.addEventListener("pointerrawupdate",Y);c.addEventListener("pointerup",Y);c.addEventListener("mousedown",
Y);c.addEventListener("mouseup",Y);c.addEventListener("keydown",Sa);c.addEventListener("keyup",Sa);c.addEventListener("click",e=>{e.stopPropagation();v(this,"click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();v(this,"dblclick",b)});c.addEventListener("input",()=>t(this,"change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.T(c,a);return c}T(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;
b.spellcheck=a.spellCheck;a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});"use strict";function Ta(){}function Ua(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Va(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.A.H(class extends self.R{constructor(b){super(b,"browser");this.g="";r(this,[["get-initial-state",a=>this.wa(a)],["ready-for-sw-messages",()=>Ua(this)],["alert",a=>this.va(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.xa(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Va(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.dc||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.g||"macos-wkwebview"===this.g)self.A.ga(!0),
this.i.za({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof
Promise&&d.catch(Ta)}}],["exit-fullscreen",()=>{if("windows-webview2"===this.g||"macos-wkwebview"===this.g)self.A.ga(!1),this.i.za({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Ta)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",
a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:
{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}wa(b){this.g=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,
referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}va(b){alert(b.message)}xa(b){b=b.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";
async function Wa(b,a){a=a.type;let c=!0;0===a?c=await Xa():1===a&&(c=await Ya());k(b,"permission-result",{type:a,result:c})}async function Xa(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Ya(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.A.H(class extends self.R{constructor(b){super(b,"touch");q(this,"request-permission",a=>Wa(this,a))}});"use strict";
async function Za(b){if(!b.G)try{b.G=await navigator.wakeLock.request("screen"),b.G.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.G=null;k(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),k(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),k(b,"wake-lock-error")}}
function $a(){var b=document.body;const a=b.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");b=getComputedStyle(b);b=[b.getPropertyValue("--temp-sai-top"),b.getPropertyValue("--temp-sai-right"),b.getPropertyValue("--temp-sai-bottom"),b.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);
return isFinite(c)?c:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return b}
self.A.H(class extends self.R{constructor(b){super(b,"platform-info");r(this,[["get-initial-state",()=>this.wa()],["request-wake-lock",()=>Za(this)],["release-wake-lock",()=>{this.G&&(this.G.release(),this.G=null)}]]);window.addEventListener("resize",()=>{k(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:$a()})});this.G=null}wa(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:$a(),supportsWakeLock:!!navigator.wakeLock}}});"use strict";function Z(b){b.stopPropagation()}
self.A.H(class extends self.Na{constructor(b){super(b,"file-chooser");u(this,"click",a=>{a.click()});u(this,"clear",a=>{a.value=""})}pa(b,a){const c=document.createElement("input");c.type="file";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",Z);c.addEventListener("change",
()=>t(this,"change",b,{files:Array.from(c.files)}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.T(c,a);return c}T(b,a){b.setAttribute("accept",a.accept);a.isMultiSelect?b.setAttribute("multiple",""):b.removeAttribute("multiple")}});
