function l(b,a,d,c){b.i.la(b.P,a,d,c,void 0)}function p(b,a,d,c){b.i.v?l(b,a,d,c):b.i.pb()._OnMessageFromDOM({type:"event",component:b.P,handler:a,dispatchOpts:c||null,data:d,responseId:null})}function q(b,a,d){b.i.h(b.P,a,d)}function aa(b,a){for(const [d,c]of a)q(b,d,c)}window.ja=class{constructor(b,a){this.i=b;this.P=a}Da(){}};window.gb=class{constructor(b){this.Pa=b;this.Cb=5;this.K=-1;this.ca=-Infinity;this.Hb=()=>{this.K=-1;this.ca=Date.now();this.R=!0;this.Pa();this.R=!1};this.Qa=this.R=!1}};
"use strict";function ba(b,a){q(b,"get-element",d=>{const c=b.u.get(d.elementId);return a(c,d)})}
window.Wb=class extends self.ja{constructor(b,a){super(b,a);this.u=new Map;this.qa=!0;aa(this,[["create",()=>{throw Error("required override");}],["destroy",d=>{d=d.elementId;const c=this.u.get(d);this.qa&&c.parentElement.removeChild(c);this.u.delete(d)}],["set-visible",d=>{this.qa&&(this.u.get(d.elementId).style.display=d.isVisible?"":"none")}],["update-position",d=>{if(this.qa){var c=this.u.get(d.elementId);c.style.left=d.left+"px";c.style.top=d.top+"px";c.style.width=d.width+"px";c.style.height=
d.height+"px";d=d.fontSize;null!==d&&(c.style.fontSize=d+"em")}}],["update-state",d=>{this.u.get(d.elementId);throw Error("required override");}],["focus",d=>{const c=this.u.get(d.elementId);d.focus?c.focus():c.blur()}],["set-css-style",d=>{const c=this.u.get(d.elementId),e=d.prop;d=d.val;e.startsWith("--")?c.style.setProperty(e,d):c.style[e]=d}],["set-attribute",d=>{this.u.get(d.elementId).setAttribute(d.name,d.val)}],["remove-attribute",d=>{this.u.get(d.elementId).removeAttribute(d.name)}]]);ba(this,
d=>d)}};"use strict";const r=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),t=/android/i.test(navigator.userAgent);let u=0;function v(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Mb?new Promise(d=>{const c="c3_resolve_"+u;++u;self[c]=d;a.textContent=b.Qb+`\n\nself["${c}"]();`;document.head.appendChild(a)}):new Promise((d,c)=>{a.onload=d;a.onerror=c;a.src=b;document.head.appendChild(a)})}let w=!1,x=!1;
function ca(){if(!w){try{new Worker("blob://",{get type(){x=!0}})}catch(b){}w=!0}return x}let y=new Audio;const da={"audio/webm; codecs=opus":!!y.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!y.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!y.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!y.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!y.canPlayType("audio/mp4"),"audio/mpeg":!!y.canPlayType("audio/mpeg")};y=null;
async function ea(b){b=await z(b);return(new TextDecoder("utf-8")).decode(b)}function z(b){return new Promise((a,d)=>{const c=new FileReader;c.onload=e=>a(e.target.result);c.onerror=e=>d(e);c.readAsArrayBuffer(b)})}const A=[];let B=0;window.RealFile=window.File;const C=[],D=new Map,E=new Map;let fa=0;const F=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");F.push(b)};const G=new Set(["cordova","playable-ad","instant-games"]);let I=!1;
window.ma=class b{constructor(a){this.v=a.Sb;this.U=null;this.m="";this.I=a.Pb;this.Z={};this.wa=this.L=null;this.ba=[];this.j=this.X=null;this.Ua=!1;this.S=null;this.H=-1;this.Gb=()=>this.wb();this.Xa=[];this.g=a.Ya;this.ua="file"===location.protocol.substr(0,4);!this.v||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ca()||(this.v=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.v=!1;if("cordova"===this.g&&this.v)if(t){const d=/Chrome\/(\d+)/i.exec(navigator.userAgent);
d&&90<=parseInt(d[1],10)||(this.v=!1)}else this.v=!1;this.da=this.B=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime","cordova-fetch-local-file",d=>this.sb(d));this.h("runtime","create-job-worker",()=>this.tb());"cordova"===this.g?document.addEventListener("deviceready",()=>this.Ia(a)):this.Ia(a)}cb(){return r&&
"cordova"===this.g}ka(){const a=navigator.userAgent;return r&&G.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ab(){return t}Fa(){return t&&G.has(this.g)}async Ia(a){"macos-wkwebview"===this.g&&this.Ab();if("playable-ad"===this.g){this.B=self.c3_base64files;this.da={};await this.lb();for(let c=0,e=a.M.length;c<e;++c){var d=a.M[c];this.da.hasOwnProperty(d)?a.M[c]={Mb:!0,Qb:this.da[d]}:this.B.hasOwnProperty(d)&&(a.M[c]=URL.createObjectURL(this.B[d]))}}a.Ob?this.m=a.Ob:(d=location.origin,
this.m=("null"===d?"file:///":d)+location.pathname,d=this.m.lastIndexOf("/"),-1!==d&&(this.m=this.m.substr(0,d+1)));a.Ub&&(this.Z=a.Ub);d=new MessageChannel;this.U=d.port1;this.U.onmessage=c=>this._OnMessageFromRuntime(c.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(c=>this.vb(c));this.S=new self.eb(this);await ha(this.S);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((c,e)=>{window.AndroidFullScreen.immersiveMode(c,
e)})}catch(c){console.error("Failed to enter Android immersive mode: ",c)}this.v?await this.rb(a,d.port2):await this.qb(a,d.port2)}oa(a){a=this.Z.hasOwnProperty(a)?this.Z[a]:a.endsWith("/workermain.js")&&this.Z.hasOwnProperty("workermain.js")?this.Z["workermain.js"]:"playable-ad"===this.g&&this.B.hasOwnProperty(a)?this.B[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ia(a,d,c){if(a.startsWith("blob:"))return new Worker(a,c);if("cordova"===this.g&&this.ua)return a=await this.ha(c.Lb?
a:this.I+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),c);a=new URL(a,d);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),c)}return new Worker(a,c)}A(){return Math.max(window.innerWidth,1)}s(){return Math.max(window.innerHeight,1)}Ha(a){var d=this.m,c=location.href,e=this.A(),f=this.s(),g=window.devicePixelRatio,h=b.N(),k=a.$b,m=window.cr_previewImageBlobs||
this.B,n=window.cr_previewProjectFileBlobs,sa=window.cr_previewProjectFiles,ta=window.Yb||"";a=a.Ya;var ua=(new URLSearchParams(self.location.search)).has("debug"),H=this.S;return{runtimeBaseUrl:d,previewUrl:c,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:m,previewProjectFileBlobs:n,previewProjectFileSWUrls:sa,swClientId:ta,exportType:a,isDebug:ua,ife:!!self.Zb,jobScheduler:{inputPort:H.ta,outputPort:H.ya,maxNumWorkers:H.Eb},supportedAudioFormats:da,
opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.I+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.I+"opus.wasm.wasm",isFileProtocol:this.ua,isiOSCordova:this.cb(),isiOSWebView:this.ka(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async rb(a,d){const c=this.oa(a.Tb);"preview"===this.g?(this.L=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const m=n=>{this.L.removeEventListener("message",m);n.data&&"ok"===n.data.type?h():
k()};this.L.addEventListener("message",m);this.L.postMessage({type:"construct-worker-init","import":(new URL(c,this.m)).toString()})})):this.L=await this.ia(c,this.m,{type:"module",name:"Runtime",Lb:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.Ba||[],g=a.M;f=await Promise.all(f.map(h=>this.F(h)));g=
await Promise.all(g.map(h=>this.F(h)));if("cordova"===this.g)for(let h=0,k=a.ga.length;h<k;++h){const m=a.ga[h],n=m[0];if(n===a.Aa||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m[1]=await this.F(n)}this.L.postMessage(Object.assign(this.Ha(a),{type:"init-runtime",isInWorker:!0,messagePort:d,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ga,mainProjectScript:a.Aa,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[d,e,...ia(this.S)]);this.ba=C.map(h=>new h(this));
this.Ga();J(this.X);self.c3_callFunction=(h,k)=>{var m=this.X;return m.i.fb(m.P,{name:h,params:k})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.la("runtime","go-to-last-error-script"))}async qb(a,d){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.ba=C.map(g=>new g(this));this.Ga();var c=a.M.map(g=>"string"===typeof g?(new URL(g,this.m)).toString():
g);Array.isArray(a.Ba)&&c.unshift(...a.Ba);c=await Promise.all(c.map(g=>this.F(g)));await Promise.all(c.map(g=>v(g)));c=self.C3_ProjectScriptsStatus;const e=a.Aa,f=a.ga;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.F(h),await v(h),"preview"!==this.g||c[g]||this.Ka(g,"main script did not run to completion")}catch(k){this.Ka(g,k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.F(h),await v(h);"preview"===this.g&&"object"!==typeof self.Vb.Xb?(this.aa(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ha(a),{isInWorker:!1,messagePort:d,canvas:this.j,runOnStartupFunctions:F}),J(this.X),this.Ja(),this.wa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.wa,a))}Ka(a,d){this.aa();console.error(`[Preview] Failed to load project main script (${a}): `,d);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ja(){this.aa()}aa(){const a=
window.Jb;a&&(a.parentElement.removeChild(a),window.Jb=null)}async tb(){const a=await ka(this.S);return{outputPort:a,transferables:[a]}}pb(){if(this.v)throw Error("not available in worker mode");return this.wa}la(a,d,c,e,f){this.U.postMessage({type:"event",component:a,handler:d,dispatchOpts:e||null,data:c,responseId:null},f)}fb(a,d){const c=fa++,e=new Promise((f,g)=>{E.set(c,{resolve:f,reject:g})});this.U.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:d,
responseId:c},void 0);return e}_OnMessageFromRuntime(a){const d=a.type;if("event"===d)return this.ub(a);if("result"===d)this.xb(a);else if("runtime-ready"===d)this.yb();else if("alert-error"===d)this.aa(),alert(a.message);else if("creating-runtime"===d)this.Ja();else throw Error(`unknown message '${d}'`);}ub(a){const d=a.component,c=a.handler,e=a.data,f=a.responseId;if(a=D.get(d))if(a=a.get(c)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${d}' handler '${c}':`,h);null!==f&&this.$(f,
!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.$(f,!0,h)).catch(h=>{console.error(`Rejection from '${d}' handler '${c}':`,h);this.$(f,!1,""+h)}):this.$(f,!0,g)}else console.warn(`[DOM] No handler '${c}' for component '${d}'`);else console.warn(`[DOM] No event handlers for component '${d}'`)}$(a,d,c){let e;c&&c.transferables&&(e=c.transferables);this.U.postMessage({type:"result",responseId:a,isOk:d,result:c},e)}xb(a){const d=a.responseId,c=a.isOk;a=a.result;const e=E.get(d);c?e.resolve(a):
e.reject(a);E.delete(d)}h(a,d,c){let e=D.get(a);e||(e=new Map,D.set(a,e));if(e.has(d))throw Error(`[DOM] Component '${a}' already has handler '${d}'`);e.set(d,c)}static Ca(a){if(C.includes(a))throw Error("DOM handler already added");C.push(a)}Ga(){for(const a of this.ba)if("runtime"===a.P){this.X=a;return}throw Error("cannot find runtime DOM handler");}vb(a){this.la("debugger","message",a)}yb(){for(const a of this.ba)a.Da()}static N(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement||I)}static Ma(a){I=!!a}La(){-1===this.H&&this.Xa.length&&(this.H=requestAnimationFrame(this.Gb))}jb(){-1!==this.H&&(cancelAnimationFrame(this.H),this.H=-1)}wb(){this.H=-1;for(const a of this.Xa)a();this.La()}pa(){this.X.pa()}hb(){this.Ua=!0}$a(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}bb(a){return!this.$a(a)}async F(a){return"cordova"===this.g&&(a.startsWith("file:")||this.ua&&this.bb(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),
a=await this.ha(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async sb(a){const d=a.filename;switch(a.as){case "text":return await this.Za(d);case "buffer":return await this.ha(d);default:throw Error("unsupported type");}}Ea(a){const d=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((c,e)=>{window.resolveLocalFileSystemURL(d,f=>{f.file(c,e)},e)})}async Za(a){a=await this.Ea(a);return await ea(a)}na(){if(A.length&&!(8<=B)){B++;var a=A.shift();this.mb(a.filename,
a.Rb,a.Kb)}}ha(a){return new Promise((d,c)=>{A.push({filename:a,Rb:e=>{B--;this.na();d(e)},Kb:e=>{B--;this.na();c(e)}});this.na()})}async mb(a,d,c){try{const e=await this.Ea(a),f=await z(e);d(f)}catch(e){c(e)}}Ab(){var a={type:"ready"};if("windows-webview2"===this.g)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.g)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async lb(){const a=[];for(const [d,
c]of Object.entries(this.B))a.push(this.kb(d,c));await Promise.all(a)}async kb(a,d){if("object"===typeof d)this.B[a]=new Blob([d.str],{type:d.type}),this.da[a]=d.str;else{let c=await this.ob(d);c||(c=this.nb(d));this.B[a]=c}}async ob(a){try{return await (await fetch(a)).blob()}catch(d){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",d),
null}}nb(a){a=this.zb(a);return this.ib(a.data,a.Nb)}zb(a){var d=a.indexOf(",");if(0>d)throw new URIError("expected comma in data: uri");var c=a.substring(d+1);d=a.substring(5,d).split(";");a=d[0]||"";const e=d[2];c="base64"===d[1]||"base64"===e?atob(c):decodeURIComponent(c);return{Nb:a,data:c}}ib(a,d){var c=a.length;let e=c>>2,f=new Uint8Array(c),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(c&=3;c--;)f[k]=
a.charCodeAt(k),++k;return new Blob([f],{type:d})}};"use strict";const K=self.ma;function la(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const na=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),L={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},oa={dispatchUserScriptEvent:!0},M={dispatchRuntimeEvent:!0};
function pa(b){return new Promise((a,d)=>{const c=document.createElement("link");c.onload=()=>a(c);c.onerror=e=>d(e);c.rel="stylesheet";c.href=b;document.head.appendChild(c)})}function qa(b){return new Promise((a,d)=>{const c=new Image;c.onload=()=>a(c);c.onerror=e=>d(e);c.src=b})}async function N(b){b=URL.createObjectURL(b);try{return await qa(b)}finally{URL.revokeObjectURL(b)}}
function ra(b){return new Promise((a,d)=>{let c=new FileReader;c.onload=e=>a(e.target.result);c.onerror=e=>d(e);c.readAsText(b)})}
async function va(b,a,d){if(!/firefox/i.test(navigator.userAgent))return await N(b);var c=await ra(b);c=(new DOMParser).parseFromString(c,"image/svg+xml");const e=c.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await N(b)}e.setAttribute("width",a+"px");e.setAttribute("height",d+"px");c=(new XMLSerializer).serializeToString(c);b=new Blob([c],{type:"image/svg+xml"});return await N(b)}
function O(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const wa=new Set(["input","textarea","datalist","select"]),xa=new Set(["canvas","body","html"]);function P(b){xa.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function ya(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await N(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,d,c,e){b=await va(b,a,d);const f=document.createElement("canvas");f.width=c;f.height=e;f.getContext("2d").drawImage(b,0,0,a,d);return f};
let Q=!1;document.addEventListener("pause",()=>Q=!0);document.addEventListener("resume",()=>Q=!1);function J(b){b.Sa=!0;b.va=b.i.A();b.T=b.i.s()}async function za(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Aa(b){return await self.C3_GetSvgImageSize(b.blob)}
function Ba(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ca(b){self.setTimeout(()=>{b.Ra=!0},1E3);"cordova"===b.i.g?(document.addEventListener("pause",()=>R(b,!0)),document.addEventListener("resume",()=>R(b,!1))):document.addEventListener("visibilitychange",()=>R(b,document.hidden));return{isSuspended:!(!document.hidden&&!Q)}}
function Da(b){b.Oa||(b.Oa=!0,window.addEventListener("deviceorientation",a=>{b.l||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},L)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},L)}))}
function Ea(b){b.Na||(b.Na=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var d=null,c=a.acceleration;c&&(d={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var e=a.accelerationIncludingGravity;e&&(c={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:d,accelerationIncludingGravity:c,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},L)}}))}async function Fa(b){await pa(b.url)}
function Ga(b,a){b.Ta=a.message;-1===b.sa&&(b.sa=setTimeout(()=>{b.sa=-1;const d=document.getElementById("exportToVideoMessage");d&&(d.textContent=b.Ta)},250))}function S(b){if(!b.l){var a=K.N();a&&"any"!==b.za&&Ha(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.A(),innerHeight:b.s()})}}function T(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:K.N(),innerWidth:b.A(),innerHeight:b.s()})}
function R(b,a){a?b.i.jb():b.i.La();l(b,"visibilitychange",{hidden:a})}function Ia(b,a,d){"Backspace"===d.key&&P(d);if(!b.l){var c=na.get(d.code)||d.code;p(b,a,{code:c,key:d.key,which:d.which,repeat:d.repeat,altKey:d.altKey,ctrlKey:d.ctrlKey,metaKey:d.metaKey,shiftKey:d.shiftKey,timeStamp:d.timeStamp},L)}}
function U(b,a,d,c){b.l||la(d)||p(b,a,{button:d.button,buttons:d.buttons,clientX:d.clientX,clientY:d.clientY+b.o,pageX:d.pageX,pageY:d.pageY+b.o,movementX:d.movementX||0,movementY:d.movementY||0,timeStamp:d.timeStamp},c)}function V(b){window!==window.top&&window.focus();Ja(b.target)&&document.activeElement&&!Ja(document.activeElement)&&document.activeElement.blur()}
function W(b,a,d){if(!b.l){if(b.W&&"pointermove"!==a){var c=b.W;c.R||(-1!==c.K&&(self.clearTimeout(c.K),c.K=-1),c.ca=Date.now())}c=0;"mouse"===d.pointerType&&(c=b.V);p(b,a,{pointerId:d.pointerId,pointerType:d.pointerType,button:d.button,buttons:d.buttons,lastButtons:c,clientX:d.clientX,clientY:d.clientY+b.o,pageX:d.pageX,pageY:d.pageY+b.o,movementX:(d.movementX||0)+b.ea,movementY:(d.movementY||0)+b.fa,width:d.width||0,height:d.height||0,pressure:d.pressure||0,tangentialPressure:d.tangentialPressure||
0,tiltX:d.tiltX||0,tiltY:d.tiltY||0,twist:d.twist||0,timeStamp:d.timeStamp},L);b.ea=0;b.fa=0;"mouse"===d.pointerType&&(c="mousemove","pointerdown"===a?c="mousedown":"pointerup"===a&&(c="mouseup"),U(b,c,d,oa),b.V=d.buttons)}}
function X(b,a,d){if(!b.l&&!la(d)){var c=b.V;"pointerdown"===a&&0!==c?a="pointermove":"pointerup"===a&&0!==d.buttons&&(a="pointermove");p(b,a,{pointerId:1,pointerType:"mouse",button:d.button,buttons:d.buttons,lastButtons:c,clientX:d.clientX,clientY:d.clientY+b.o,pageX:d.pageX,pageY:d.pageY+b.o,movementX:d.movementX||0,movementY:d.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:d.timeStamp},L);b.V=d.buttons;U(b,d.type,d,oa)}}
function Y(b,a,d){if(!b.l)for(let c=0,e=d.changedTouches.length;c<e;++c){const f=d.changedTouches[c];p(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.o,pageX:f.pageX,pageY:f.pageY+b.o,movementX:d.movementX||0,movementY:d.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:d.timeStamp},
L)}}function Z(b,a,d){document.body.style.transform="";b.o=0;if(0<d){var c=document.activeElement;c&&(c=c.getBoundingClientRect(),a=(c.top+c.bottom)/2-(a-d)/2,a>d&&(a=d),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.o=a))}}function Ka(b,a,d,c){const e=b.A(),f=b.s();b.J=-1;e!=a||f!=d?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:K.N()}):10>c&&La(b,e,f,c+1)}
function La(b,a,d,c){-1!==b.J&&clearTimeout(b.J);b.J=setTimeout(()=>Ka(b,a,d,c),48)}
function Ha(b){b=b.za;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Ja(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
K.Ca(class extends self.ja{constructor(b){super(b,"runtime");this.Va=!0;this.Sa=!1;this.J=-1;this.za="any";this.Na=this.Oa=!1;this.D=null;this.l=!1;this.Ta="";this.sa=-1;this.G=this.W=null;this.fa=this.ea=0;this.Ra=!1;this.va=b.A();this.T=b.s();this.o=this.Y=0;b.h("canvas","update-size",c=>{var e=this.i;e.Ua||(e=e.j,e.style.width=c.styleWidth+"px",e.style.height=c.styleHeight+"px",e.style.marginLeft=c.marginLeft+"px",e.style.marginTop=c.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",
c.displayScale),this.Va&&(e.style.display="",this.Va=!1))});b.h("runtime","invoke-download",c=>{const e=c.url;c=c.filename;const f=document.createElement("a"),g=document.body;f.textContent=c;f.href=e;f.download=c;g.appendChild(f);f.click();g.removeChild(f)});b.h("runtime","raster-svg-image",c=>za(c));b.h("runtime","get-svg-image-size",c=>Aa(c));b.h("runtime","set-target-orientation",c=>{this.za=c.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime",
"post-to-debugger",c=>Ba(c));b.h("runtime","go-to-script",c=>Ba(c));b.h("runtime","before-start-ticking",()=>Ca(this));b.h("runtime","debug-highlight",c=>{if(c.show){this.D||(this.D=document.createElement("div"),this.D.id="inspectOutline",document.body.appendChild(this.D));var e=this.D;e.style.display="";e.style.left=c.left-1+"px";e.style.top=c.top-1+"px";e.style.width=c.width+2+"px";e.style.height=c.height+2+"px";e.textContent=c.name}else this.D&&(this.D.style.display="none")});b.h("runtime","enable-device-orientation",
()=>Da(this));b.h("runtime","enable-device-motion",()=>Ea(this));b.h("runtime","add-stylesheet",c=>Fa(c));b.h("runtime","script-create-worker",c=>{const e=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.h("runtime","alert",c=>{alert(c.message)});b.h("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",c=>{this.l=!0;const e=document.createElement("h1");
e.id="exportToVideoMessage";e.textContent=c.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.hb()});b.h("runtime","export-to-video-progress",c=>Ga(this,c));b.h("runtime","exported-to-video",c=>{window.Ib({type:"exported-video",blob:c.blob,time:c.time})});b.h("runtime","exported-to-image-sequence",c=>{window.Ib({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);
window.addEventListener("contextmenu",c=>{const e=c.target;a.has(e.tagName.toLowerCase())||O(e)||c.preventDefault()});const d=b.j;window.addEventListener("selectstart",P);window.addEventListener("gesturehold",P);d.addEventListener("selectstart",P);d.addEventListener("gesturehold",P);window.addEventListener("touchstart",P,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",P,{passive:!1}),d.addEventListener("pointerdown",P)):d.addEventListener("touchstart",P);this.V=
0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",ya,{passive:!1});window.addEventListener("wheel",ya,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.Sa){var c=this.A();var e=this.s();if(this.i.Fa()){if(this.Ra){if(this.va===c&&e<this.T){this.Y=this.T-e;Z(this,this.T,this.Y);c=void 0;break a}0<this.Y&&(this.Y=0,Z(this,e,this.Y))}this.va=c;this.T=e}l(this,"window-resize",{innerWidth:c,innerHeight:e,devicePixelRatio:window.devicePixelRatio,
isFullscreen:K.N()});this.i.ka()&&(-1!==this.J&&clearTimeout(this.J),Ka(this,c,e,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>S(this));window.addEventListener("webkitfullscreenchange",()=>S(this));window.addEventListener("mozfullscreenchange",()=>S(this));window.addEventListener("fullscreenerror",c=>T(this,c));window.addEventListener("webkitfullscreenerror",c=>T(this,c));window.addEventListener("mozfullscreenerror",c=>T(this,c));if(b.ka())if(window.visualViewport){let c=
Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>c&&(document.scrollingElement.scrollTop=0);c=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var c=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?e.has(f.type.toLowerCase()||"text"):O(f)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>{"entered-fullscreen"===
c?(K.Ma(!0),S(this)):"exited-fullscreen"===c?(K.Ma(!1),S(this)):console.warn("Unknown wrapper message: ",c)};this.xa=new Set;this.Fb=new WeakSet;this.Db=!1}Da(){window.addEventListener("focus",()=>{l(this,"window-focus",null,M)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(d){a=!1}l(this,"window-blur",{parentHasFocus:a},M);this.V=0});window.addEventListener("focusin",a=>{a=a.target;(wa.has(a.tagName.toLowerCase())||O(a))&&l(this,"keyboard-blur",
null,M)});window.addEventListener("keydown",a=>Ia(this,"keydown",a));window.addEventListener("keyup",a=>Ia(this,"keyup",a));window.addEventListener("dblclick",a=>U(this,"dblclick",a,L));window.addEventListener("wheel",a=>{this.l||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.o,pageX:a.pageX,pageY:a.pageY+this.o,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},L)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{V(a);
W(this,"pointerdown",a)}),this.i.v&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.W=new self.gb(()=>{W(this,"pointermove",this.G);this.G=null}),this.W.Qa=!0,window.addEventListener("pointerrawupdate",a=>{this.G&&(this.ea+=this.G.movementX||0,this.fa+=this.G.movementY||0);this.G=a;a=this.W;if(-1===a.K){var d=Date.now(),c=d-a.ca,e=a.Cb;c>=e&&a.Qa?(a.ca=d,a.R=!0,a.Pa(),a.R=!1):a.K=self.setTimeout(a.Hb,Math.max(e-c,4))}})):window.addEventListener("pointermove",a=>W(this,"pointermove",
a)),window.addEventListener("pointerup",a=>W(this,"pointerup",a)),window.addEventListener("pointercancel",a=>W(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{V(a);X(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>X(this,"pointermove",a)),window.addEventListener("mouseup",a=>X(this,"pointerup",a)),window.addEventListener("touchstart",a=>{V(a);Y(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>Y(this,"pointermove",a)),window.addEventListener("touchend",
a=>Y(this,"pointerup",a)),window.addEventListener("touchcancel",a=>Y(this,"pointercancel",a)));const b=()=>this.pa();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.ab()&&!this.i.Fa()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Z(this,this.s(),
navigator.virtualKeyboard.boundingRect.height)}))}A(){return this.i.A()}s(){return this.i.s()}pa(){var b=[...this.xa];this.xa.clear();if(!this.Db)for(const a of b)(b=a.play())&&b.catch(()=>{this.Fb.has(a)||this.xa.add(a)})}});"use strict";
async function ha(b){if(b.Bb)throw Error("already initialised");b.Bb=!0;var a=b.C.oa(("playable-ad"===b.C.g?b.C.I:"")+"dispatchworker.js");b.ra=await b.C.ia(a,b.O,{name:"DispatchWorker"});a=new MessageChannel;b.ta=a.port1;b.ra.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.ya=await ka(b)}function ia(b){return[b.ta,b.ya]}
async function ka(b){const a=b.Wa.length;var d=b.C.oa(("playable-ad"===b.C.g?b.C.I:"")+"jobworker.js");d=await b.C.ia(d,b.O,{name:"JobWorker"+a});const c=new MessageChannel,e=new MessageChannel;b.ra.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);d.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":e.port2},[c.port2,e.port2]);b.Wa.push(d);return e.port1}
self.eb=class{constructor(b){this.C=b;this.O=b.m;this.O="preview"===b.g?this.O+"workers/":this.O+b.I;this.Eb=Math.min(navigator.hardwareConcurrency||2,16);this.ra=null;this.Wa=[];this.ya=this.ta=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ma({Sb:!0,Tb:"workermain.js",M:["scripts/c3runtime.js"],ga:[],Aa:"",Pb:"scripts/",Ba:[],Ya:"html5"}));"use strict";
async function Ma(b,a){a=a.type;let d=!0;0===a?d=await Na():1===a&&(d=await Oa());l(b,"permission-result",{type:a,result:d})}async function Na(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Oa(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.ma.Ca(class extends self.ja{constructor(b){super(b,"touch");q(this,"request-permission",a=>Ma(this,a))}});
