'use strict';function r(e,a,b,c){e.v.mc(e.$a,a,b,c,void 0)}function D(e,a,b,c){e.v.ra?r(e,a,b,c):e.v.kf()._OnMessageFromDOM({type:"event",component:e.$a,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function G(e,a,b){e.v.C(e.$a,a,b)}function H(e,a){for(const [b,c]of a)G(e,b,c)}function J(e){e.Qb||(e.v.Ve(e.de),e.Qb=!0)}window.Ea=class{constructor(e,a){this.v=e;this.$a=a;this.Qb=!1;this.de=()=>this.Ha()}fd(){}Ha(){}};function K(e){-1!==e.Sa&&(self.clearTimeout(e.Sa),e.Sa=-1)}
window.Me=class{constructor(e,a){this.Nc=e;this.xg=a;this.Sa=-1;this.Rb=-Infinity;this.ee=()=>{this.Sa=-1;this.Rb=Date.now();this.fb=!0;this.Nc();this.fb=!1};this.Nd=this.fb=!1}c(){K(this);this.ee=this.Nc=null}};"use strict";function L(e,a){const b=a.elementId,c=e.kd(b,a);e.Y.set(b,c);a.isVisible||(c.style.display="none");c.addEventListener("focus",()=>{M(e,"elem-focused",b)});c.addEventListener("blur",()=>{M(e,"elem-blurred",b)});e.Lb&&document.body.appendChild(c)}
function N(e,a,b){G(e,a,c=>{const g=e.Y.get(c.elementId);return b(g,c)})}function M(e,a,b,c){c||(c={});c.elementId=b;r(e,a,c)}function O(e,a,b){var c;c||(c={});c.elementId=b;D(e,a,c)}
window.ze=class extends self.Ea{constructor(e,a){super(e,a);this.Y=new Map;this.Lb=!0;H(this,[["create",b=>L(this,b)],["destroy",b=>{{b=b.elementId;const c=this.Y.get(b);this.Lb&&c.parentElement.removeChild(c);this.Y.delete(b)}}],["set-visible",b=>{this.Lb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Lb){var c=this.Y.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";b=b.fontSize;
null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{{const c=this.Y.get(b.elementId);this.sc(c,b)}}],["focus",b=>this.Ic(b)],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);N(this,"get-element",b=>b)}kd(){throw Error("required override");}sc(){throw Error("required override");}Ic(e){var a=this.Y.get(e.elementId);e.focus?a.focus():
a.blur()}};"use strict";
{const e=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(k,d){const h=document.createElement("script");h.async=!1;"module"===d&&(h.type="module");return k.Hg?new Promise(l=>{const n="c3_resolve_"+a;++a;self[n]=l;h.textContent=k.Kg+`\n\nself["${n}"]();`;document.head.appendChild(h)}):new Promise((l,n)=>{h.onload=l;h.onerror=n;h.src=k;document.head.appendChild(h)})}let c=!1,g=!1;function m(){if(!c){try{new Worker("blob://",{get type(){g=!0}})}catch(k){}c=
!0}return g}let p=new Audio;const w={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function A(k){k=await B(k);return(new TextDecoder("utf-8")).decode(k)}function B(k){return new Promise((d,
h)=>{const l=new FileReader;l.onload=n=>d(n.target.result);l.onerror=n=>h(n);l.readAsArrayBuffer(k)})}const v=[];let x=0;window.RealFile=window.File;const C=[],y=new Map,E=new Map;let F=0;const I=[];self.runOnStartup=function(k){if("function"!==typeof k)throw Error("runOnStartup called without a function");I.push(k)};const f=new Set(["cordova","playable-ad","instant-games"]);window.ua=class k{constructor(d){this.ra=d.Mg;this.pa=null;this.F="";this.Zb=d.Jg;this.da=d.he;this.tb={};this.La=this.sb=null;
this.Ob=[];this.hb=this.K=this.Qa=null;this.Pa=-1;this.Cg=()=>this.If();this.Oa=[];this.B=d.fe;!this.ra||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&("module"!==this.da||m())||(this.ra=!1);f.has(this.B)&&this.ra&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.ra=!1);this.Tb=this.ia=null;"html5"!==this.B&&"playable-ad"!==this.B||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
this.C("runtime","cordova-fetch-local-file",h=>this.sf(h));this.C("runtime","create-job-worker",()=>this.tf());"cordova"===this.B?document.addEventListener("deviceready",()=>this.zd(d)):this.zd(d)}c(){this.tc();this.pa&&(this.pa=this.pa.onmessage=null);this.sb&&(this.sb.terminate(),this.sb=null);this.La&&(this.La.c(),this.La=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}pd(){return e&&"cordova"===this.B}lc(){return e&&f.has(this.B)||navigator.standalone}async zd(d){if("playable-ad"===
this.B){this.ia=self.c3_base64files;this.Tb={};await this.$e();for(let l=0,n=d.Ta.length;l<n;++l){var h=d.Ta[l].toLowerCase();this.Tb.hasOwnProperty(h)?d.Ta[l]={Hg:!0,Kg:this.Tb[h]}:this.ia.hasOwnProperty(h)&&(d.Ta[l]=URL.createObjectURL(this.ia[h]))}}d.Dg?this.F=d.Dg:(h=location.origin,this.F=("null"===h?"file:///":h)+location.pathname,h=this.F.lastIndexOf("/"),-1!==h&&(this.F=this.F.substr(0,h+1)));d.Og&&(this.tb=d.Og);h=new MessageChannel;this.pa=h.port1;this.pa.onmessage=l=>this._OnMessageFromRuntime(l.data);
window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Ef(l));this.hb=new self.Ie(this);await P(this.hb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ra?await this.mf(d,h.port2):await this.lf(d,h.port2)}wc(d){d=this.tb.hasOwnProperty(d)?this.tb[d]:d.endsWith("/workermain.js")&&this.tb.hasOwnProperty("workermain.js")?this.tb["workermain.js"]:"playable-ad"===this.B&&this.ia.hasOwnProperty(d.toLowerCase())?
this.ia[d.toLowerCase()]:d;d instanceof Blob&&(d=URL.createObjectURL(d));return d}async dc(d,h,l){if(d.startsWith("blob:"))return new Worker(d,l);if(this.pd()&&"file:"===location.protocol)return d=await this.vb(this.Zb+d),new Worker(URL.createObjectURL(new Blob([d],{type:"application/javascript"})),l);d=new URL(d,h);if(location.origin!==d.origin){d=await fetch(d);if(!d.ok)throw Error("failed to fetch worker script");d=await d.blob();return new Worker(URL.createObjectURL(d),l)}return new Worker(d,
l)}xa(){return Math.max(window.innerWidth,1)}wa(){return Math.max(window.innerHeight,1)}yd(d){var h=this.hb;return{baseUrl:this.F,windowInnerWidth:this.xa(),windowInnerHeight:this.wa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:k.kc(),projectData:d.Ug,scriptsType:d.he,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Sg||"",exportType:d.fe,isDebug:-1<self.location.search.indexOf("debug"),
ife:!!self.Tg,jobScheduler:{inputPort:h.Tc,outputPort:h.$c,maxNumWorkers:h.zg},supportedAudioFormats:w,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Zb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Zb+"opus.wasm.wasm",isiOSCordova:this.pd(),isiOSWebView:this.lc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async mf(d,h){var l=this.wc(d.Ng);this.sb=await this.dc(l,this.F,{type:this.da,name:"Runtime"});this.K=document.createElement("canvas");this.K.style.display=
"none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;this.sb.postMessage(Object.assign(this.yd(d),{type:"init-runtime",isInWorker:!0,messagePort:h,canvas:l,workerDependencyScripts:d.ed||[],engineScripts:d.Ta,projectScripts:d.ub,mainProjectScript:d.ge,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[h,l,...Q(this.hb)]);this.Ob=C.map(n=>new n(this));this.xd();self.c3_callFunction=(n,q)=>this.Qa.nf(n,q);"preview"===this.B&&(self.goToLastErrorScript=
()=>this.mc("runtime","go-to-last-error-script"))}async lf(d,h){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Ob=C.map(q=>new q(this));this.xd();var l=d.Ta.map(q=>"string"===typeof q?(new URL(q,this.F)).toString():q);Array.isArray(d.ed)&&l.unshift(...d.ed);l=await Promise.all(l.map(q=>this.Ac(q,this.da)));await Promise.all(l.map(q=>b(q,this.da)));const n=self.C3_ProjectScriptsStatus;if("module"===this.da){l=d.ge;const q=
d.ub;for(let [u,t]of q)if(t||(t=u),u===l)try{t=await this.Ac(t,this.da),await b(t,this.da),"preview"!==this.B||n[u]||this.Hd(u,"main script did not run to completion")}catch(z){this.Hd(u,z)}else if("scriptsInEvents.js"===u||u.endsWith("/scriptsInEvents.js"))t=await this.Ac(t,this.da),await b(t,this.da)}else if(d.ub&&0<d.ub.length)try{if(await Promise.all(d.ub.map(q=>b(q[1],this.da))),Object.values(n).some(q=>!q)){self.setTimeout(()=>this.Id(n),100);return}}catch(q){console.error("[Preview] Error loading project scripts: ",
q);self.setTimeout(()=>this.Id(n),100);return}"preview"===this.B&&"object"!==typeof self.Pg.Qg?(this.Ya(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(d=Object.assign(this.yd(d),{isInWorker:!1,messagePort:h,canvas:this.K,runOnStartupFunctions:I}),this.Bd(),this.La=self.C3_CreateRuntime(d),await self.C3_InitRuntime(this.La,
d))}Id(d){this.Ya();d=`Failed to load project script '${Object.entries(d).filter(h=>!h[1]).map(h=>h[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+d);alert(d)}Hd(d,h){this.Ya();console.error(`[Preview] Failed to load project main script (${d}): `,h);alert(`Failed to load project main script (${d}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Bd(){this.Ya()}Ya(){const d=window.Eg;d&&(d.parentElement.removeChild(d),
window.Eg=null)}async tf(){const d=await R(this.hb);return{outputPort:d,transferables:[d]}}kf(){if(this.ra)throw Error("not available in worker mode");return this.La}mc(d,h,l,n,q){this.pa.postMessage({type:"event",component:d,handler:h,dispatchOpts:n||null,data:l,responseId:null},q)}qd(d,h,l,n,q){const u=F++,t=new Promise((z,V)=>{E.set(u,{resolve:z,reject:V})});this.pa.postMessage({type:"event",component:d,handler:h,dispatchOpts:n||null,data:l,responseId:u},q);return t}["_OnMessageFromRuntime"](d){const h=
d.type;if("event"===h)return this.yf(d);if("result"===h)this.Lf(d);else if("runtime-ready"===h)this.Mf();else if("alert-error"===h)this.Ya(),alert(d.message);else if("creating-runtime"===h)this.Bd();else throw Error(`unknown message '${h}'`);}yf(d){const h=d.component,l=d.handler,n=d.data,q=d.responseId;if(d=y.get(h))if(d=d.get(l)){var u=null;try{u=d(n)}catch(t){console.error(`Exception in '${h}' handler '${l}':`,t);null!==q&&this.Gb(q,!1,""+t);return}if(null===q)return u;u&&u.then?u.then(t=>this.Gb(q,
!0,t)).catch(t=>{console.error(`Rejection from '${h}' handler '${l}':`,t);this.Gb(q,!1,""+t)}):this.Gb(q,!0,u)}else console.warn(`[DOM] No handler '${l}' for component '${h}'`);else console.warn(`[DOM] No event handlers for component '${h}'`)}Gb(d,h,l){let n;l&&l.transferables&&(n=l.transferables);this.pa.postMessage({type:"result",responseId:d,isOk:h,result:l},n)}Lf(d){const h=d.responseId,l=d.isOk;d=d.result;const n=E.get(h);l?n.resolve(d):n.reject(d);E.delete(h)}C(d,h,l){let n=y.get(d);n||(n=new Map,
y.set(d,n));if(n.has(h))throw Error(`[DOM] Component '${d}' already has handler '${h}'`);n.set(h,l)}static Da(d){if(C.includes(d))throw Error("DOM handler already added");C.push(d)}xd(){for(const d of this.Ob)if("runtime"===d.$a){this.Qa=d;return}throw Error("cannot find runtime DOM handler");}Ef(d){this.mc("debugger","message",d)}Mf(){for(const d of this.Ob)d.fd()}static kc(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Ve(d){this.Oa.push(d);
this.Lc()}Yf(d){d=this.Oa.indexOf(d);if(-1===d)throw Error("invalid callback");this.Oa.splice(d,1);this.Oa.length||this.tc()}Lc(){-1===this.Pa&&this.Oa.length&&(this.Pa=requestAnimationFrame(this.Cg))}tc(){-1!==this.Pa&&(cancelAnimationFrame(this.Pa),this.Pa=-1)}If(){this.Pa=-1;for(const d of this.Oa)d();this.Lc()}va(d){this.Qa.va(d)}Ga(d){this.Qa.Ga(d)}Kc(){this.Qa.Kc()}Bb(d){this.Qa.Bb(d)}He(){return!!w["audio/webm; codecs=opus"]}async vg(d){d=await this.qd("runtime","opus-decode",{arrayBuffer:d},
null,[d]);return new Float32Array(d)}Ge(d){return/^(?:[a-z\-]+:)?\/\//.test(d)||"data:"===d.substr(0,5)||"blob:"===d.substr(0,5)}od(d){return!this.Ge(d)}async Ac(d,h){return"cordova"===this.B&&"module"===h&&(d.startsWith("file:")||"file:"===location.protocol&&this.od(d))?(d.startsWith(this.F)&&(d=d.substr(this.F.length)),d=await this.vb(d),URL.createObjectURL(new Blob([d],{type:"application/javascript"}))):d}async sf(d){const h=d.filename;switch(d.as){case "text":return await this.ye(h);case "buffer":return await this.vb(h);
default:throw Error("unsupported type");}}jd(d){const h=window.cordova.file.applicationDirectory+"www/"+d.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(h,q=>{q.file(l,n)},n)})}async ye(d){d=await this.jd(d);return await A(d)}uc(){if(v.length&&!(8<=x)){x++;var d=v.shift();this.af(d.filename,d.Lg,d.Gg)}}vb(d){return new Promise((h,l)=>{v.push({filename:d,Lg:n=>{x--;this.uc();h(n)},Gg:n=>{x--;this.uc();l(n)}});this.uc()})}async af(d,h,l){try{const n=await this.jd(d),q=await B(n);
h(q)}catch(n){l(n)}}async $e(){const d=[];for(const [h,l]of Object.entries(this.ia))d.push(this.Ze(h,l));await Promise.all(d)}async Ze(d,h){if("object"===typeof h)this.ia[d]=new Blob([h.str],{type:h.type}),this.Tb[d]=h.str;else{let l=await this.hf(h);l||(l=this.cf(h));this.ia[d]=l}}async hf(d){try{return await (await fetch(d)).blob()}catch(h){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
h),null}}cf(d){d=this.Sf(d);return this.Ye(d.data,d.Ig)}Sf(d){var h=d.indexOf(",");if(0>h)throw new URIError("expected comma in data: uri");var l=d.substring(h+1);h=d.substring(5,h).split(";");d=h[0]||"";const n=h[2];l="base64"===h[1]||"base64"===n?atob(l):decodeURIComponent(l);return{Ig:d,data:l}}Ye(d,h){var l=d.length;let n=l>>2,q=new Uint8Array(l),u=new Uint32Array(q.buffer,0,n),t,z;for(z=t=0;t<n;++t)u[t]=d.charCodeAt(z++)|d.charCodeAt(z++)<<8|d.charCodeAt(z++)<<16|d.charCodeAt(z++)<<24;for(l&=
3;l--;)q[z]=d.charCodeAt(z),++z;return new Blob([q],{type:h})}}}"use strict";
{const e=self.ua;function a(f){return f.sourceCapabilities&&f.sourceCapabilities.firesTouchEvents||f.originalEvent&&f.originalEvent.sourceCapabilities&&f.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(f){return new Promise((k,d)=>{const h=document.createElement("link");h.onload=()=>k(h);h.onerror=l=>d(l);h.rel=
"stylesheet";h.href=f;document.head.appendChild(h)})}function w(f){return new Promise((k,d)=>{const h=new Image;h.onload=()=>k(h);h.onerror=l=>d(l);h.src=f})}async function A(f){f=URL.createObjectURL(f);try{return await w(f)}finally{URL.revokeObjectURL(f)}}function B(f){return new Promise((k,d)=>{let h=new FileReader;h.onload=l=>k(l.target.result);h.onerror=l=>d(l);h.readAsText(f)})}async function v(f,k,d){if(!/firefox/i.test(navigator.userAgent))return await A(f);var h=await B(f);h=(new DOMParser).parseFromString(h,
"image/svg+xml");const l=h.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),q=l.getAttribute("height");if(!n.includes("%")&&!q.includes("%"))return await A(f)}l.setAttribute("width",k+"px");l.setAttribute("height",d+"px");h=(new XMLSerializer).serializeToString(h);f=new Blob([h],{type:"image/svg+xml"});return await A(f)}function x(f){do{if(f.parentNode&&f.hasAttribute("contenteditable"))return!0;f=f.parentNode}while(f);return!1}const C=new Set(["canvas",
"body","html"]);function y(f){C.has(f.target.tagName.toLowerCase())&&f.preventDefault()}function E(f){(f.metaKey||f.ctrlKey)&&f.preventDefault()}self.C3_GetSvgImageSize=async function(f){f=await A(f);if(0<f.width&&0<f.height)return[f.width,f.height];{f.style.position="absolute";f.style.left="0px";f.style.top="0px";f.style.visibility="hidden";document.body.appendChild(f);const k=f.getBoundingClientRect();document.body.removeChild(f);return[k.width,k.height]}};self.C3_RasterSvgImageBlob=async function(f,
k,d,h,l){f=await v(f,k,d);const n=document.createElement("canvas");n.width=h;n.height=l;n.getContext("2d").drawImage(f,0,0,k,d);return n};let F=!1;document.addEventListener("pause",()=>F=!0);document.addEventListener("resume",()=>F=!1);function I(){try{return window.parent&&window.parent.document.hasFocus()}catch(f){return!1}}e.Da(class extends self.Ea{constructor(f){super(f,"runtime");this.Sd=!0;this.Ra=-1;this.bd="any";this.Jd=this.Kd=!1;this.Wc=this.pb=this.za=null;f.C("canvas","update-size",h=>
this.Qf(h));f.C("runtime","invoke-download",h=>this.Cf(h));f.C("runtime","raster-svg-image",h=>this.Jf(h));f.C("runtime","get-svg-image-size",h=>this.Af(h));f.C("runtime","set-target-orientation",h=>this.Of(h));f.C("runtime","register-sw",()=>this.Kf());f.C("runtime","post-to-debugger",h=>this.Dd(h));f.C("runtime","go-to-script",h=>this.Dd(h));f.C("runtime","before-start-ticking",()=>this.rf());f.C("runtime","debug-highlight",h=>this.uf(h));f.C("runtime","enable-device-orientation",()=>this.Xe());
f.C("runtime","enable-device-motion",()=>this.We());f.C("runtime","add-stylesheet",h=>this.qf(h));f.C("runtime","alert",h=>this.Bc(h));f.C("runtime","hide-cordova-splash",()=>this.Bf());const k=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",h=>{const l=h.target;k.has(l.tagName.toLowerCase())||x(l)||h.preventDefault()});const d=f.K;window.addEventListener("selectstart",y);window.addEventListener("gesturehold",y);d.addEventListener("selectstart",y);d.addEventListener("gesturehold",
y);window.addEventListener("touchstart",y,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",y,{passive:!1}),d.addEventListener("pointerdown",y)):d.addEventListener("touchstart",y);this.mb=0;window.addEventListener("mousedown",h=>{1===h.button&&h.preventDefault()});window.addEventListener("mousewheel",E,{passive:!1});window.addEventListener("wheel",E,{passive:!1});window.addEventListener("resize",()=>this.Rf());window.addEventListener("fullscreenchange",()=>this.Dc());
window.addEventListener("webkitfullscreenchange",()=>this.Dc());window.addEventListener("mozfullscreenchange",()=>this.Dc());window.addEventListener("fullscreenerror",h=>this.Ec(h));window.addEventListener("webkitfullscreenerror",h=>this.Ec(h));window.addEventListener("mozfullscreenerror",h=>this.Ec(h));f.lc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var h=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));h="textarea"===
h?!0:"input"===h?l.has(n.type.toLowerCase()||"text"):x(n)}else h=!1}h||(document.scrollingElement.scrollTop=0)});this.Ma=new Set;this.Ub=new WeakSet;this.oa=!1}rf(){"cordova"===this.v.B?(document.addEventListener("pause",()=>this.Jc(!0)),document.addEventListener("resume",()=>this.Jc(!1))):document.addEventListener("visibilitychange",()=>this.Jc(document.hidden));return{isSuspended:!(!document.hidden&&!F)}}fd(){window.addEventListener("focus",()=>this.Hb("window-focus"));window.addEventListener("blur",
()=>{this.Hb("window-blur",{parentHasFocus:I()});this.mb=0});window.addEventListener("keydown",k=>this.Cd("keydown",k));window.addEventListener("keyup",k=>this.Cd("keyup",k));window.addEventListener("dblclick",k=>this.Gc("dblclick",k,c));window.addEventListener("wheel",k=>this.Gf(k));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",k=>{this.xc(k);this.Xa("pointerdown",k)}),this.v.ra&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.pb=new self.Me(()=>this.ff(),
5),this.pb.Nd=!0,window.addEventListener("pointerrawupdate",k=>this.Hf(k))):window.addEventListener("pointermove",k=>this.Xa("pointermove",k)),window.addEventListener("pointerup",k=>this.Xa("pointerup",k)),window.addEventListener("pointercancel",k=>this.Xa("pointercancel",k))):(window.addEventListener("mousedown",k=>{this.xc(k);this.Hc("pointerdown",k)}),window.addEventListener("mousemove",k=>this.Hc("pointermove",k)),window.addEventListener("mouseup",k=>this.Hc("pointerup",k)),window.addEventListener("touchstart",
k=>{this.xc(k);this.Fb("pointerdown",k)}),window.addEventListener("touchmove",k=>this.Fb("pointermove",k)),window.addEventListener("touchend",k=>this.Fb("pointerup",k)),window.addEventListener("touchcancel",k=>this.Fb("pointercancel",k)));const f=()=>this.Kc();window.addEventListener("pointerup",f,!0);window.addEventListener("touchend",f,!0);window.addEventListener("click",f,!0);window.addEventListener("keydown",f,!0);window.addEventListener("gamepadconnected",f,!0)}Hb(f,k){r(this,f,k||null,m)}xa(){return this.v.xa()}wa(){return this.v.wa()}Rf(){const f=
this.xa(),k=this.wa();this.Hb("window-resize",{innerWidth:f,innerHeight:k,devicePixelRatio:window.devicePixelRatio});this.v.lc()&&(-1!==this.Ra&&clearTimeout(this.Ra),this.Ed(f,k,0))}Zf(f,k,d){-1!==this.Ra&&clearTimeout(this.Ra);this.Ra=setTimeout(()=>this.Ed(f,k,d),48)}Ed(f,k,d){const h=this.xa(),l=this.wa();this.Ra=-1;h!=f||l!=k?this.Hb("window-resize",{innerWidth:h,innerHeight:l,devicePixelRatio:window.devicePixelRatio}):10>d&&this.Zf(h,l,d+1)}Of(f){this.bd=f.targetOrientation}rg(){const f=this.bd;
if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(k=>console.warn("[Construct 3] Failed to lock orientation: ",k));else try{let k=!1;screen.lockOrientation?k=screen.lockOrientation(f):screen.webkitLockOrientation?k=screen.webkitLockOrientation(f):screen.mozLockOrientation?k=screen.mozLockOrientation(f):screen.msLockOrientation&&(k=screen.msLockOrientation(f));k||console.warn("[Construct 3] Failed to lock orientation")}catch(k){console.warn("[Construct 3] Failed to lock orientation: ",
k)}}Dc(){const f=e.kc();f&&"any"!==this.bd&&this.rg();r(this,"fullscreenchange",{isFullscreen:f,innerWidth:this.xa(),innerHeight:this.wa()})}Ec(f){console.warn("[Construct 3] Fullscreen request failed: ",f);r(this,"fullscreenerror",{isFullscreen:e.kc(),innerWidth:this.xa(),innerHeight:this.wa()})}Jc(f){f?this.v.tc():this.v.Lc();r(this,"visibilitychange",{hidden:f})}Cd(f,k){"Backspace"===k.key&&y(k);const d=b.get(k.code)||k.code;D(this,f,{code:d,key:k.key,which:k.which,repeat:k.repeat,altKey:k.altKey,
ctrlKey:k.ctrlKey,metaKey:k.metaKey,shiftKey:k.shiftKey,timeStamp:k.timeStamp},c)}Gf(f){r(this,"wheel",{clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,deltaX:f.deltaX,deltaY:f.deltaY,deltaZ:f.deltaZ,deltaMode:f.deltaMode,timeStamp:f.timeStamp},c)}Gc(f,k,d){a(k)||D(this,f,{button:k.button,buttons:k.buttons,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,timeStamp:k.timeStamp},d)}Hc(f,k){if(!a(k)){var d=this.mb;"pointerdown"===f&&0!==d?f="pointermove":"pointerup"===
f&&0!==k.buttons&&(f="pointermove");D(this,f,{pointerId:1,pointerType:"mouse",button:k.button,buttons:k.buttons,lastButtons:d,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:k.timeStamp},c);this.mb=k.buttons;this.Gc(k.type,k,g)}}Xa(f,k){if(this.pb&&"pointermove"!==f){var d=this.pb;d.fb||(K(d),d.Rb=Date.now())}d=0;"mouse"===k.pointerType&&(d=this.mb);D(this,f,{pointerId:k.pointerId,pointerType:k.pointerType,
button:k.button,buttons:k.buttons,lastButtons:d,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:k.width||0,height:k.height||0,pressure:k.pressure||0,tangentialPressure:k.tangentialPressure||0,tiltX:k.tiltX||0,tiltY:k.tiltY||0,twist:k.twist||0,timeStamp:k.timeStamp},c);"mouse"===k.pointerType&&(d="mousemove","pointerdown"===f?d="mousedown":"pointerup"===f&&(d="mouseup"),this.Gc(d,k,g),this.mb=k.buttons)}Hf(f){this.Wc=f;f=this.pb;if(-1===f.Sa){var k=Date.now(),d=k-f.Rb,h=f.xg;
d>=h&&f.Nd?(f.Rb=k,f.fb=!0,f.Nc(),f.fb=!1):f.Sa=self.setTimeout(f.ee,Math.max(h-d,4))}}ff(){this.Xa("pointermove",this.Wc);this.Wc=null}Fb(f,k){for(let d=0,h=k.changedTouches.length;d<h;++d){const l=k.changedTouches[d];D(this,f,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:k.timeStamp},c)}}xc(f){window!==window.top&&window.focus();this.Ad(f.target)&&document.activeElement&&!this.Ad(document.activeElement)&&document.activeElement.blur()}Ad(f){return!f||f===document||f===window||f===document.body||"canvas"===f.tagName.toLowerCase()}Xe(){this.Kd||(this.Kd=!0,window.addEventListener("deviceorientation",f=>this.wf(f)),window.addEventListener("deviceorientationabsolute",f=>this.xf(f)))}We(){this.Jd||(this.Jd=!0,window.addEventListener("devicemotion",
f=>this.vf(f)))}wf(f){r(this,"deviceorientation",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp,webkitCompassHeading:f.webkitCompassHeading,webkitCompassAccuracy:f.webkitCompassAccuracy},c)}xf(f){r(this,"deviceorientationabsolute",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp},c)}vf(f){let k=null;var d=f.acceleration;d&&(k={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var h=f.accelerationIncludingGravity;h&&(d={x:h.x||
0,y:h.y||0,z:h.z||0});h=null;const l=f.rotationRate;l&&(h={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});r(this,"devicemotion",{acceleration:k,accelerationIncludingGravity:d,rotationRate:h,interval:f.interval,timeStamp:f.timeStamp},c)}Qf(f){const k=this.v.K;k.style.width=f.styleWidth+"px";k.style.height=f.styleHeight+"px";k.style.marginLeft=f.marginLeft+"px";k.style.marginTop=f.marginTop+"px";this.Sd&&(k.style.display="",this.Sd=!1)}Cf(f){const k=f.url;f=f.filename;const d=document.createElement("a"),
h=document.body;d.textContent=f;d.href=k;d.download=f;h.appendChild(d);d.click();h.removeChild(d)}async Jf(f){var k=f.imageBitmapOpts;f=await self.C3_RasterSvgImageBlob(f.blob,f.imageWidth,f.imageHeight,f.surfaceWidth,f.surfaceHeight);k=k?await createImageBitmap(f,k):await createImageBitmap(f);return{imageBitmap:k,transferables:[k]}}async Af(f){return await self.C3_GetSvgImageSize(f.blob)}async qf(f){await p(f.url)}Kc(){var f=[...this.Ma];this.Ma.clear();if(!this.oa)for(const k of f)(f=k.play())&&
f.catch(()=>{this.Ub.has(k)||this.Ma.add(k)})}va(f){if("function"!==typeof f.play)throw Error("missing play function");this.Ub.delete(f);let k;try{k=f.play()}catch(d){this.Ma.add(f);return}k&&k.catch(()=>{this.Ub.has(f)||this.Ma.add(f)})}Ga(f){this.Ma.delete(f);this.Ub.add(f)}Bb(f){this.oa=!!f}Bf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}uf(f){if(f.show){this.za||(this.za=document.createElement("div"),this.za.id="inspectOutline",document.body.appendChild(this.za));
var k=this.za;k.style.display="";k.style.left=f.left-1+"px";k.style.top=f.top-1+"px";k.style.width=f.width+2+"px";k.style.height=f.height+2+"px";k.textContent=f.name}else this.za&&(this.za.style.display="none")}Kf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Dd(f){window.c3_postToMessagePort&&(f.from="runtime",window.c3_postToMessagePort(f))}nf(f,k){return this.v.qd(this.$a,"js-invoke-function",{name:f,params:k},void 0,void 0)}Bc(f){alert(f.message)}})}"use strict";
async function P(e){if(e.wg)throw Error("already initialised");e.wg=!0;var a=e.Yb.wc("dispatchworker.js");e.Pc=await e.Yb.dc(a,e.F,{name:"DispatchWorker"});a=new MessageChannel;e.Tc=a.port1;e.Pc.postMessage({type:"_init","in-port":a.port2},[a.port2]);e.$c=await R(e)}function Q(e){return[e.Tc,e.$c]}
async function R(e){const a=e.Td.length;var b=e.Yb.wc("jobworker.js");b=await e.Yb.dc(b,e.F,{name:"JobWorker"+a});const c=new MessageChannel,g=new MessageChannel;e.Pc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":g.port2},[c.port2,g.port2]);e.Td.push(b);return g.port1}
self.Ie=class{constructor(e){this.Yb=e;this.F=e.F;this.F="preview"===e.B?this.F+"c3/workers/":this.F+e.Zb;this.zg=Math.min(navigator.hardwareConcurrency||2,16);this.Pc=null;this.Td=[];this.$c=this.Tc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ua({Mg:!1,Ng:"workermain.js",Ta:["scripts/c3runtime.js"],ub:[],ge:"",he:"module",Jg:"scripts/",ed:[],fe:"html5"}));"use strict";
async function S(e,a){a=a.type;let b=!0;0===a?b=await T():1===a&&(b=await U());r(e,"permission-result",{type:a,result:b})}async function T(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request orientation permission: ",e),!1}}
async function U(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request motion permission: ",e),!1}}self.ua.Da(class extends self.Ea{constructor(e){super(e,"touch");G(this,"request-permission",a=>S(this,a))}});"use strict";
function W(e){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>r(e,"sw-message",a.data))}
function aa(e){e=e.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(e):screen.webkitLockOrientation?a=screen.webkitLockOrientation(e):screen.mozLockOrientation?a=screen.mozLockOrientation(e):screen.msLockOrientation&&(a=screen.msLockOrientation(e));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.ua.Da(class extends self.Ea{constructor(e){super(e,"browser");this.B="";H(this,[["get-initial-state",a=>this.Fc(a)],["ready-for-sw-messages",()=>W(this)],["alert",a=>this.Bc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ic(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>aa(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===b)window.forward();else if("home"===b)window.home();else if("reload"===b)location.reload();
else if("url"===b){b=a.url;var c=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.Rg||(2===c?window.top.location=b:1===c?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,c=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?
Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,c))}],["request-fullscreen",a=>{{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==
typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{r(this,"online-state",{isOnline:!0})});window.addEventListener("offline",
()=>{r(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{r(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{r(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",a=>{a.handled=!0;r(this,"backbutton")})}Fc(e){this.B=e.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,
isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}Bc(e){alert(e.message)}Ic(e){e=e.isFocus;if("nwjs"===this.B){const a="nwjs"===this.B?nw.Window.get():null;e?a.focus():a.blur()}else e?window.focus():window.blur()}});"use strict";
{function e(b){b.stopPropagation()}function a(b){13!==b.which&&27!==b.which&&b.stopPropagation()}self.ua.Da(class extends self.ze{constructor(b){super(b,"text-input");N(this,"scroll-to-bottom",c=>this.Nf(c))}kd(b,c){let g;const m=c.type;"textarea"===m?(g=document.createElement("textarea"),g.style.resize="none"):(g=document.createElement("input"),g.type=m);g.style.position="absolute";g.autocomplete="off";g.addEventListener("touchstart",e);g.addEventListener("touchmove",e);g.addEventListener("touchend",
e);g.addEventListener("mousedown",e);g.addEventListener("mouseup",e);g.addEventListener("keydown",a);g.addEventListener("keyup",a);g.addEventListener("click",p=>{p.stopPropagation();O(this,"click",b)});g.addEventListener("dblclick",p=>{p.stopPropagation();O(this,"dblclick",b)});g.addEventListener("input",()=>M(this,"change",b,{text:g.value}));c.id&&(g.id=c.id);this.sc(g,c);return g}sc(b,c){b.value=c.text;b.placeholder=c.placeholder;b.title=c.title;b.disabled=!c.isEnabled;b.readOnly=c.isReadOnly;b.spellcheck=
c.spellCheck;c=c.maxLength;0>c?b.removeAttribute("maxlength"):b.setAttribute("maxlength",c)}Nf(b){b.scrollTop=b.scrollHeight}})}"use strict";
{const e=180/Math.PI;self.ea=class extends self.Ea{constructor(a){super(a,"audio");this.Nb=this.f=null;this.Pb=this.Sc=!1;this.qa=()=>this.sg();this.ba=[];this.D=[];this.ha=null;this.Ud="";this.Vd=-1;this.ob=new Map;this.Xc=1;this.oa=!1;this.cd=0;this.ac=1;this.Qc=0;this.Xd="HRTF";this.Od="inverse";this.Yd=600;this.Wd=1E4;this.$d=1;this.Qd=this.ad=!1;this.ce=this.v.He();this.ca=new Map;this.Ja=new Set;this.Uc=!1;this.Yc="";this.Aa=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.Ff(b,c);this.Mb=null;
self.C3Audio_GetOutputStream=()=>this.zf();self.C3Audio_DOMInterface=this;H(this,[["create-audio-context",b=>this.bf(b)],["play",b=>this.Tf(b)],["stop",b=>this.pg(b)],["stop-all",()=>this.qg()],["set-paused",b=>this.ig(b)],["set-volume",b=>this.ng(b)],["fade-volume",b=>this.gf(b)],["set-master-volume",b=>this.gg(b)],["set-muted",b=>this.hg(b)],["set-silent",b=>this.kg(b)],["set-looping",b=>this.fg(b)],["set-playback-rate",b=>this.jg(b)],["seek",b=>this.$f(b)],["preload",b=>this.Uf(b)],["unload",b=>
this.tg(b)],["unload-all",()=>this.ug()],["set-suspended",b=>this.lg(b)],["add-effect",b=>this.vd(b)],["set-effect-param",b=>this.cg(b)],["remove-effects",b=>this.Wf(b)],["tick",b=>this.Pf(b)],["load-state",b=>this.Df(b)]])}async bf(a){a.isiOSCordova&&(this.ad=!0);this.cd=a.timeScaleMode;this.Xd=["equalpower","HRTF","soundfield"][a.panningModel];this.Od=["linear","inverse","exponential"][a.distanceModel];this.Yd=a.refDistance;this.Wd=a.maxDistance;this.$d=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.ce||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.wd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.wd()};this.Nb=this.f.createGain();this.Nb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.ec();try{await Promise.all(a.preloadList.map(c=>this.Db(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}wd(){this.Pb||(this.Sc=!1,window.addEventListener("pointerup",this.qa,!0),window.addEventListener("touchend",this.qa,!0),window.addEventListener("click",this.qa,!0),window.addEventListener("keydown",this.qa,!0),this.Pb=!0)}df(){this.Pb&&(this.Sc=!0,window.removeEventListener("pointerup",this.qa,!0),window.removeEventListener("touchend",
this.qa,!0),window.removeEventListener("click",this.qa,!0),window.removeEventListener("keydown",this.qa,!0),this.Pb=!1)}sg(){if(!this.Sc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.df()}}W(){return this.f}ec(){return this.f.currentTime}sa(){return this.Nb}md(a){return(a=this.ca.get(a.toLowerCase()))?a[0].P():this.sa()}ie(a,b){a=a.toLowerCase();let c=this.ca.get(a);
c||(c=[],this.ca.set(a,c));b.eg(c.length);b.mg(a);c.push(b);this.Gd(a)}Gd(a){let b=this.sa();const c=this.ca.get(a);if(c&&c.length){b=c[0].P();for(let g=0,m=c.length;g<m;++g){const p=c[g];g+1===m?p.S(this.sa()):p.S(c[g+1].P())}}for(const g of this.ma(a))g.Ne(b);this.Aa&&this.Yc===a&&(this.Aa.disconnect(),this.Aa.connect(b))}xb(){return this.Xc}yb(){return this.oa}dg(){this.Qd=!0}Be(a,b){return b?this.v.vg(a).then(c=>{const g=this.f.createBuffer(1,c.length,48E3);g.getChannelData(0).set(c);return g}):
new Promise((c,g)=>{this.f.decodeAudioData(a,c,g)})}va(a){this.v.va(a)}Ga(a){this.v.Ga(a)}rd(a){let b=0;for(let c=0,g=this.D.length;c<g;++c){const m=this.D[c];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Oe(){let a=0;for(let b=0,c=this.ba.length;b<c;++b){const g=this.ba[b];this.ba[a]=g;g.ta()?g.c():++a}this.ba.length=a}*ma(a){if(a)for(const b of this.D)self.ea.Ce(b.$,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Db(a,b,c,g,m){for(const p of this.ba)if(p.Va()===b)return await X(p),
p;if(m)return null;g&&(this.ad||this.Qd)&&this.Oe();m="audio/webm; codecs=opus"===c&&!this.ce;g&&m&&this.dg();a=!g||this.ad||m?new self.we(this,a,b,c,g,m):new self.ue(this,a,b,c,g);this.ba.push(a);await X(a);return a}async vc(a,b,c,g,m){for(const p of this.D)if(p.Va()===b&&(p.cc()||m))return p.Qe(g),p;a=await this.Db(a,b,c,m);g="html5"===a.Mc?new self.ve(a.i,a,g):new self.xe(a.i,a,g);this.D.push(g);return g}Ue(a){let b=this.ob.get(a);if(!b){let c=null;b={dd:0,promise:new Promise(g=>c=g),resolve:c};
this.ob.set(a,b)}b.dd++}Xf(a){const b=this.ob.get(a);if(!b)throw Error("expected pending tag");b.dd--;0===b.dd&&(b.resolve(),this.ob.delete(a))}rc(a){a||(a=this.Ud);return(a=this.ob.get(a))?a.promise:Promise.resolve()}Eb(){if(0<this.Ja.size)J(this);else for(const a of this.D)if(a.nd()){J(this);break}}Ha(){for(var a of this.Ja)a.Ha();a=this.ec();for(var b of this.D)b.Ha(a);b=this.D.filter(c=>c.nd()).map(c=>c.Ua());r(this,"state",{tickCount:this.Vd,audioInstances:b,analysers:[...this.Ja].map(c=>c.Ee())});
0===b.length&&0===this.Ja.size&&this.Qb&&(this.v.Yf(this.de),this.Qb=!1)}nc(a,b,c){r(this,"trigger",{type:a,tag:b,aiid:c})}async Tf(a){const b=a.originalUrl,c=a.url,g=a.type,m=a.isMusic,p=a.tag,w=a.isLooping,A=a.vol,B=a.pos,v=a.panning;let x=a.off;0<x&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+this.f.currentTime);this.Ud=p;this.Ue(p);try{this.ha=await this.vc(b,c,g,p,m),v?(this.ha.Ab(!0),this.ha.Pe(v.x,
v.y,v.angle,v.innerAngle,v.outerAngle,v.outerGain),v.hasOwnProperty("uid")&&this.ha.Re(v.uid)):this.ha.Ab(!1),this.ha.Play(w,A,B,x)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Xf(p)}J(this)}pg(a){a=a.tag;for(const b of this.ma(a))b.na()}qg(){for(const a of this.D)a.na()}ig(a){const b=a.tag;a=a.paused;for(const c of this.ma(b))a?c.Wa():c.zb();this.Eb()}ng(a){const b=a.tag;a=a.vol;for(const c of this.ma(b))c.Cb(a)}async gf(a){const b=a.tag,c=a.vol,
g=a.duration;a=a.stopOnEnd;await this.rc(b);for(const m of this.ma(b))m.De(c,g,a);this.Eb()}gg(a){this.Xc=a.vol;for(const b of this.D)b.Jb()}hg(a){const b=a.tag;a=a.isMuted;for(const c of this.ma(b))c.sd(a)}kg(a){this.oa=a.isSilent;this.v.Bb(this.oa);for(const b of this.D)b.Ib()}fg(a){const b=a.tag;a=a.isLooping;for(const c of this.ma(b))c.pc(a)}async jg(a){const b=a.tag;a=a.rate;await this.rc(b);for(const c of this.ma(b))c.ud(a)}async $f(a){const b=a.tag;a=a.pos;await this.rc(b);for(const c of this.ma(b))c.oc(a)}async Uf(a){const b=
a.originalUrl,c=a.url,g=a.type;a=a.isMusic;try{await this.vc(b,c,g,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async tg(a){if(a=await this.Db("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ba.indexOf(a),-1!==a&&this.ba.splice(a,1)}ug(){for(const a of this.ba)a.c();this.ba.length=0}lg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.qc(a);a&&this.f.suspend&&this.f.suspend()}Pf(a){this.ac=a.timeScale;this.Qc=a.gameTime;this.Vd=a.tickCount;if(0!==
this.cd)for(var b of this.D)b.Ia();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const g of this.D)g.ga===a&&g.td(c.x,c.y,c.angle)}}async vd(a){var b=a.type;const c=a.tag;var g=a.params;if("filter"===b)g=new self.oe(this,...g);else if("delay"===b)g=new self.me(this,...g);else if("convolution"===b){b=null;try{b=await this.Db(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}g=new self.le(this,b.aa,...g);g.ag(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.pe(this,...g);else if("phaser"===b)g=new self.re(this,...g);else if("gain"===b)g=new self.qe(this,...g);else if("tremolo"===b)g=new self.te(this,...g);else if("ringmod"===b)g=new self.se(this,...g);else if("distortion"===b)g=new self.ne(this,...g);else if("compressor"===b)g=new self.ke(this,...g);else if("analyser"===b)g=new self.je(this,...g);else throw Error("invalid effect type");this.ie(c,
g);this.Fd()}cg(a){const b=a.index,c=a.param,g=a.value,m=a.ramp,p=a.time;a=this.ca.get(a.tag);!a||0>b||b>=a.length||(a[b].X(c,g,m,p),this.Fd())}Wf(a){a=a.tag.toLowerCase();const b=this.ca.get(a);if(b&&b.length){for(const c of b)c.c();this.ca.delete(a);this.Gd(a)}}Te(a){this.Ja.add(a);this.Eb()}Vf(a){this.Ja.delete(a)}Fd(){this.Uc||(this.Uc=!0,Promise.resolve().then(()=>this.ef()))}ef(){const a={};for(const [b,c]of this.ca)a[b]=c.map(g=>g.Ua());r(this,"fxstate",{fxstate:a});this.Uc=!1}async Df(a){const b=
a.saveLoadMode;if(3!==b)for(var c of this.D)c.ta()&&1===b||(c.ta()||2!==b)&&c.na();for(const g of this.ca.values())for(const m of g)m.c();this.ca.clear();this.ac=a.timeScale;this.Qc=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.oa=a.isSilent;this.v.Bb(this.oa);this.Xc=a.masterVolume;c=[];for(const g of Object.values(a.effects))c.push(Promise.all(g.map(m=>this.vd(m))));await Promise.all(c);await Promise.all(a.playing.map(g=>this.pf(g,b)));this.Eb()}async pf(a,b){if(3!==
b){var c=a.bufferOriginalUrl,g=a.bufferUrl,m=a.bufferType,p=a.isMusic,w=a.tag,A=a.isLooping,B=a.volume,v=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.vc(c,g,m,w,p)}catch(x){console.error("[Construct 3] Audio: error loading audio state: ",x);return}b.Le(a.pan);b.Play(A,B,v,0);a.isPlaying||b.Wa();b.zc(a)}}}Ff(a,b){this.Aa&&this.Aa.disconnect();this.Yc=b.toLowerCase();this.Aa=this.f.createMediaStreamSource(a);this.Aa.connect(this.md(this.Yc))}zf(){this.Mb||(this.Mb=this.f.createMediaStreamDestination(),
this.Nb.connect(this.Mb));return this.Mb.stream}static Ce(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Se(a){return a*e}static Ae(a){return Math.pow(10,a/20)}static ld(a){return Math.max(Math.min(self.ea.Ae(a),1),0)}static Ke(a){return Math.log(a)/Math.log(10)*20}static Je(a){return self.ea.Ke(Math.max(Math.min(a,1),0))}static Fg(a,b){return 1-Math.exp(-b*a)}};self.ua.Da(self.ea)}"use strict";function X(e){e.Sb||(e.Sb=e.yc());return e.Sb}
self.gd=class{constructor(e,a,b,c,g){this.i=e;this.Bg=a;this.Ca=b;this.R=c;this.yg=g;this.Mc="";this.Sb=null}c(){this.Sb=this.i=null}yc(){}W(){return this.i.W()}hc(){return this.Bg}Va(){return this.Ca}fc(){return this.R}ta(){return this.yg}fa(){}};"use strict";
self.ue=class extends self.gd{constructor(e,a,b,c,g){super(e,a,b,c,g);this.Mc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.ib=this.jb=null;this.J.addEventListener("canplaythrough",()=>!0);this.nb=this.W().createGain();this.lb=null;this.J.addEventListener("canplay",()=>{this.jb&&(this.jb(),this.ib=this.jb=null);!this.lb&&this.J&&(this.lb=this.W().createMediaElementSource(this.J),this.lb.connect(this.nb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Ca}' error: `,m);this.ib&&(this.ib(m),this.ib=this.jb=null)})}c(){this.i.rd(this);this.nb.disconnect();this.nb=null;this.lb.disconnect();this.lb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}yc(){return new Promise((e,a)=>{this.jb=e;this.ib=a;this.J.src=this.Ca})}O(){return this.J}fa(){return this.J.duration}};"use strict";
async function ba(e){if(e.ya)return e.ya;var a=e.i.v;if("cordova"===a.B&&a.od(e.Ca)&&"file:"===location.protocol)e.ya=await a.vb(e.Ca);else{a=await fetch(e.Ca);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);e.ya=await a.arrayBuffer()}}async function ca(e){if(e.aa)return e.aa;e.aa=await e.i.Be(e.ya,e.Ag);e.ya=null}
self.we=class extends self.gd{constructor(e,a,b,c,g,m){super(e,a,b,c,g);this.Mc="webaudio";this.aa=this.ya=null;this.Ag=!!m}c(){this.i.rd(this);this.aa=this.ya=null;super.c()}async yc(){try{await ba(this),await ca(this)}catch(e){console.error(`[Construct 3] Failed to load audio '${this.Ca}': `,e)}}fa(){return this.aa?this.aa.duration:0}};"use strict";
{let e=0;self.hd=class{constructor(a,b,c){this.i=a;this.L=b;this.$=c;this.Kb=e++;this.M=this.W().createGain();this.M.connect(this.sa());this.A=null;this.gb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.H=!0;this.V=this.la=this.G=!1;this.rb=1;this.Ka=!1;this.Z=1;a=this.i.cd;this.Vc=1===a&&!this.ta()||2===a;this.cb=this.ga=-1;this.be=!1}c(){this.L=this.i=null;this.A&&(this.A.disconnect(),this.A=null);this.M.disconnect();this.M=null}W(){return this.i.W()}sa(){return this.i.md(this.$)}xb(){return this.i.xb()}wb(){return this.Vc?
this.i.Qc:performance.now()/1E3}hc(){return this.L.hc()}Va(){return this.L.Va()}fc(){return this.L.fc()}ta(){return this.L.ta()}Qe(a){this.$=a}T(){}cc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}nd(){return!this.H&&!this.T()}Fa(){}fa(){return this.L.fa()}Play(){}na(){}Wa(){}zb(){}Cb(a){this.rb=a;this.M.gain.cancelScheduledValues(0);this.cb=-1;this.M.gain.value=this.ic()}De(a,b,c){if(!this.Ka){a*=this.xb();var g=this.M.gain;g.cancelScheduledValues(0);var m=this.i.ec();b=m+b;g.setValueAtTime(g.value,
m);g.linearRampToValueAtTime(a,b);this.rb=a;this.cb=b;this.be=c}}Jb(){this.Cb(this.rb)}Ha(a){-1!==this.cb&&a>=this.cb&&(this.cb=-1,this.be&&this.na(),this.i.nc("fade-ended",this.$,this.Kb))}ic(){const a=this.rb*this.xb();return isFinite(a)?a:0}sd(a){a=!!a;this.Ka!==a&&(this.Ka=a,this.Ib())}yb(){return this.i.yb()}Ib(){}pc(){}ud(a){this.Z!==a&&(this.Z=a,this.Ia())}Ia(){}oc(){}qc(){}Ab(a){a=!!a;this.gb!==a&&((this.gb=a)?(this.A||(this.A=this.W().createPanner(),this.A.panningModel=this.i.Xd,this.A.distanceModel=
this.i.Od,this.A.refDistance=this.i.Yd,this.A.maxDistance=this.i.Wd,this.A.rolloffFactor=this.i.$d),this.M.disconnect(),this.M.connect(this.A),this.A.connect(this.sa())):(this.A.disconnect(),this.M.disconnect(),this.M.connect(this.sa())))}Pe(a,b,c,g,m,p){this.gb&&(this.td(a,b,c),a=self.ea.Se,this.A.coneInnerAngle=a(g),this.A.coneOuterAngle=a(m),this.A.coneOuterGain=p)}td(a,b,c){this.gb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(c),this.ja[1]=Math.sin(c),this.ja[2]=0,this.A.setPosition(...this.ka),
this.A.setOrientation(...this.ja))}Re(a){this.ga=a}jc(){}Ne(a){const b=this.A||this.M;b.disconnect();b.connect(a)}Ua(){return{aiid:this.Kb,tag:this.$,duration:this.fa(),volume:this.rb,isPlaying:this.IsPlaying(),playbackTime:this.Fa(),playbackRate:this.Z,uid:this.ga,bufferOriginalUrl:this.hc(),bufferUrl:"",bufferType:this.fc(),isMusic:this.ta(),isLooping:this.V,isMuted:this.Ka,resumePosition:this.jc(),pan:this.Fe()}}zc(a){this.ud(a.playbackRate);this.sd(a.isMuted)}Fe(){if(!this.A)return null;const a=
this.A;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Le(a){if(a){this.Ab(!0);a=this.A;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.Ab(!1)}}}"use strict";
self.ve=class extends self.hd{constructor(e,a,b){super(e,a,b);this.L.nb.connect(this.M);this.L.onended=()=>this.Cc()}c(){this.na();this.L.nb.disconnect();super.c()}O(){return this.L.O()}Cc(){this.H=!0;this.ga=-1;this.i.nc("ended",this.$,this.Kb)}T(){return this.O().ended}cc(){return this.H?!0:this.T()}Fa(e){let a=this.O().currentTime;e&&(a*=this.Z);this.V||(a=Math.min(a,this.fa()));return a}Play(e,a,b){const c=this.O();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==e&&(c.loop=e);this.Cb(a);c.muted&&
(c.muted=!1);if(c.currentTime!==b)try{c.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Va()}' to position '${b}': `,g)}this.i.va(c);this.G=this.H=!1;this.V=e;this.Z=1}na(){const e=this.O();e.paused||e.pause();this.i.Ga(e);this.H=!0;this.G=!1;this.ga=-1}Wa(){if(!(this.G||this.H||this.T())){var e=this.O();e.paused||e.pause();this.i.Ga(e);this.G=!0}}zb(){!this.G||this.H||this.T()||(this.i.va(this.O()),this.G=!1)}Ib(){this.O().muted=this.Ka||this.yb()}pc(e){e=!!e;
this.V!==e&&(this.V=e,this.O().loop=e)}Ia(){let e=this.Z;this.Vc&&(e*=this.i.ac);try{this.O().playbackRate=e}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${e}':`,a)}}oc(e){if(!this.H&&!this.T())try{this.O().currentTime=e}catch(a){console.warn(`[Construct 3] Error seeking audio to '${e}': `,a)}}jc(){return this.Fa()}qc(e){e?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.va(this.O()),this.la=!1)}};"use strict";
function Y(e){e.j&&e.j.disconnect();e.j=null;e.Za=null}
self.xe=class extends self.hd{constructor(e,a,b){super(e,a,b);this.j=null;this.Vb=c=>this.Cc(c);this.Rc=!0;this.Za=null;this.N=this.$b=0;this.Zc=1}c(){this.na();Y(this);this.Vb=null;super.c()}Cc(e){this.G||this.la||e.target!==this.Za||(this.H=this.Rc=!0,this.ga=-1,Y(this),this.i.nc("ended",this.$,this.Kb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Rc}cc(){return!this.j||this.H?!0:this.T()}Fa(e){let a;a=this.G?this.N:this.wb()-this.$b;e&&(a*=this.Z);this.V||(a=Math.min(a,this.fa()));return a}Play(e,
a,b,c){this.Zc=1;this.Cb(a);Y(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.aa;this.j.connect(this.M);this.Za=this.j;this.j.onended=this.Vb;this.j.loop=e;this.j.start(c,b);this.G=this.H=this.Rc=!1;this.V=e;this.Z=1;this.$b=this.wb()-b}na(){if(this.j)try{this.j.stop(0)}catch(e){}this.H=!0;this.G=!1;this.ga=-1}Wa(){this.G||this.H||this.T()||(this.N=this.Fa(!0),this.V&&(this.N%=this.fa()),this.G=!0,this.j.stop(0))}zb(){!this.G||this.H||this.T()||(Y(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.L.aa,this.j.connect(this.M),this.Za=this.j,this.j.onended=this.Vb,this.j.loop=this.V,this.Jb(),this.Ia(),this.$b=this.wb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.G=!1)}ic(){return super.ic()*this.Zc}Ib(){this.Zc=this.Ka||this.yb()?0:1;this.Jb()}pc(e){e=!!e;this.V!==e&&(this.V=e,this.j&&(this.j.loop=e))}Ia(){let e=this.Z;this.Vc&&(e*=this.i.ac);this.j&&(this.j.playbackRate.value=e)}oc(e){this.H||this.T()||(this.G?this.N=e:(this.Wa(),this.N=e,this.zb()))}jc(){return this.N}qc(e){e?
this.IsPlaying()?(this.la=!0,this.N=this.Fa(!0),this.V&&(this.N%=this.fa()),this.j.stop(0)):this.la=!1:this.la&&(Y(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.aa,this.j.connect(this.M),this.Za=this.j,this.j.onended=this.Vb,this.j.loop=this.V,this.Jb(),this.Ia(),this.$b=this.wb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.la=!1)}zc(e){super.zc(e);this.N=e.resumePosition}};"use strict";
{class e{constructor(a){this.i=a;this.f=a.W();this.Rd=-1;this.R=this.$="";this.g=null}c(){this.f=null}eg(a){this.Rd=a}mg(a){this.$=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,c,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var m=this.f.currentTime;g+=m;switch(c){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,g)}}}Ua(){return{type:this.R,tag:this.$,params:this.g}}}
self.oe=class extends e{constructor(a,b,c,g,m,p,w){super(a);this.R="filter";this.g=[b,c,g,m,p,w];this.l=this.o();this.b=this.o();this.b.gain.value=w;this.a=this.o();this.a.gain.value=1-w;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=c;this.u.detune.value=g;this.u.Q.value=m;this.u.gain.vlaue=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,c,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,c,g)}}};self.me=class extends e{constructor(a,b,c,g){super(a);this.R="delay";this.g=[b,c,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.kb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.bb=this.o();this.bb.gain.value=c;this.l.connect(this.kb);this.l.connect(this.a);this.kb.connect(this.b);this.kb.connect(this.U);this.U.connect(this.bb);this.bb.connect(this.kb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.kb.disconnect();this.U.disconnect();this.bb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){const m=self.ea.ld;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 4:this.g[1]=m(b);this.m(this.bb.gain,m(b),c,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,c,g)}}};self.le=class extends e{constructor(a,b,c,g){super(a);this.R="convolution";this.g=[c,g];this.Md=this.Ld="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.ab=this.f.createConvolver();this.ab.normalize=c;this.ab.buffer=b;this.l.connect(this.ab);this.l.connect(this.a);this.ab.connect(this.b)}c(){this.l.disconnect();this.ab.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}ag(a,b){this.Ld=a;this.Md=b}Ua(){const a=
super.Ua();a.bufferOriginalUrl=this.Ld;a.bufferUrl="";a.bufferType=this.Md;return a}};self.pe=class extends e{constructor(a,b,c,g,m,p){super(a);this.R="flanger";this.g=[b,c,g,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.eb=this.o();this.eb.gain.value=m;this.U=this.f.createDelay(b+c);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.I=this.o();this.I.gain.value=c;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.eb);this.eb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.eb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,c,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,g);break;case 8:this.g[3]=b/100,this.m(this.eb.gain,b/100,c,g)}}};self.re=class extends e{constructor(a,b,c,g,m,p,w){super(a);this.R="phaser";this.g=[b,c,g,m,p,w];this.l=this.o();this.a=this.o();this.a.gain.value=1-w/2;this.b=this.o();this.b.gain.value=w/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
c;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=p;this.I=this.o();this.I.gain.value=m;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.I);this.I.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,c,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,c,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,g)}}};self.qe=class extends e{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,g){const m=self.ea.ld;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),c,g)}}};self.te=class extends e{constructor(a,b,c){super(a);this.R="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=c/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,c,g);this.m(this.I.gain,b/2,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.se=class extends e{constructor(a,b,c){super(a);this.R="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.qb=this.o();this.qb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.qb.gain);this.s.start(0);this.l.connect(this.qb);this.l.connect(this.a);this.qb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.qb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,c,g);
this.m(this.a.gain,1-b,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.ne=class extends e{constructor(a,b,c,g,m,p){super(a);this.R="distortion";this.g=[b,c,g,m,p];this.l=this.o();this.Xb=this.o();this.Wb=this.o();this.bg(g,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.bc=this.f.createWaveShaper();this.Oc=new Float32Array(65536);this.jf(b,c);this.bc.curve=this.Oc;this.l.connect(this.Xb);this.l.connect(this.a);this.Xb.connect(this.bc);this.bc.connect(this.Wb);
this.Wb.connect(this.b)}c(){this.l.disconnect();this.Xb.disconnect();this.bc.disconnect();this.Wb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}bg(a,b){.01>a&&(a=.01);this.Xb.gain.value=a;this.Wb.gain.value=Math.pow(1/a,.6)*b}jf(a,b){for(let c=0;32768>c;++c){let g=c/32768;g=this.og(g,a,b);this.Oc[32768+c]=g;this.Oc[32768-c-1]=-g}}og(a,b,c){c=1.05*c*b-b;const g=0>a?-a:a;return(g<b?g:b+c*self.ea.Fg(g-b,1/c))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}};self.ke=class extends e{constructor(a,b,c,g,m,p){super(a);this.R="compressor";this.g=[b,c,g,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=g;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.je=class extends e{constructor(a,b,c){super(a);this.R="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Pd=new Float32Array(this.h.frequencyBinCount);this.ae=new Uint8Array(b);this.Zd=this.Na=0;this.i.Te(this)}c(){this.i.Vf(this);this.h.disconnect();super.c()}Ha(){this.h.getFloatFrequencyData(this.Pd);this.h.getByteTimeDomainData(this.ae);const a=this.h.fftSize;let b=this.Na=0;for(var c=0;c<a;++c){let g=(this.ae[c]-128)/128;0>g&&(g=-g);
this.Na<g&&(this.Na=g);b+=g*g}c=self.ea.Je;this.Na=c(this.Na);this.Zd=c(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Ee(){return{tag:this.$,index:this.Rd,peak:this.Na,rms:this.Zd,binCount:this.h.frequencyBinCount,freqBins:this.Pd}}}}"use strict";
async function da(e){if(!e.Ba)try{e.Ba=await navigator.wakeLock.request("screen"),e.Ba.addEventListener("release",()=>{console.log("[Construct 3] Screen wake lock released");e.Ba=null;r(e,"wake-lock-released")}),console.log("[Construct 3] Screen wake lock acquired"),r(e,"wake-lock-acquired")}catch(a){console.warn("[Construct 3] Failed to acquire screen wake lock: ",a),r(e,"wake-lock-error")}}
function Z(){var e=document.body;const a=e.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");e=getComputedStyle(e);e=[e.getPropertyValue("--temp-sai-top"),e.getPropertyValue("--temp-sai-right"),e.getPropertyValue("--temp-sai-bottom"),e.getPropertyValue("--temp-sai-left")].map(b=>{b=parseInt(b,10);
return isFinite(b)?b:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return e}
self.ua.Da(class extends self.Ea{constructor(e){super(e,"platform-info");H(this,[["get-initial-state",()=>this.Fc()],["request-wake-lock",()=>da(this)],["release-wake-lock",()=>{this.Ba&&(this.Ba.release(),this.Ba=null)}]]);window.addEventListener("resize",()=>{r(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:Z()})});this.Ba=null}Fc(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:Z(),supportsWakeLock:!!navigator.wakeLock}}});
