const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.AJAX,
		C3.Plugins.BinaryData,
		C3.Plugins.Browser,
		C3.Plugins.Clipboard,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.DrawingCanvas.Acts.OutlineEllipse,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Plugins.Sprite.Exps.BBoxMidY,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Keyboard.Exps.TypedKey,
		C3.Plugins.Text.Cnds.PickTopBottom,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.AJAX.Acts.SetResponseBinary,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.Clipboard.Acts.CopyBinary,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.DrawingCanvas.Acts.FillEllipse,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.Browser.Cnds.OnUpdateFound,
		C3.Plugins.Browser.Cnds.OnUpdateReady,
		C3.Plugins.Browser.Acts.Reload
	];
};
self.C3_JsPropNameTable = [
	{DragDrop: 0},
	{Ruler: 0},
	{DrawingCanvas: 0},
	{Touch: 0},
	{Circle: 0},
	{Text: 0},
	{Keyboard: 0},
	{ButtonClear: 0},
	{ButtonCopy: 0},
	{AJAX: 0},
	{BinaryData: 0},
	{Browser: 0},
	{Clipboard: 0},
	{ButtonDownload: 0},
	{ProjectText: 0},
	{Logo: 0},
	{Button: 0}
];

self.InstanceType = {
	Ruler: class extends self.ISpriteInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	Touch: class extends self.IInstance {},
	Circle: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	ButtonClear: class extends self.ITextInstance {},
	ButtonCopy: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	Browser: class extends self.IInstance {},
	Clipboard: class extends self.IInstance {},
	ButtonDownload: class extends self.ITextInstance {},
	ProjectText: class extends self.ITextInstance {},
	Logo: class extends self.ISpriteInstance {},
	Button: class extends self.ITextInstance {}
}