const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Plugins.Keyboard,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.solid,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.trim,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.System.Exps.float,
		C3.Plugins.Browser.Cnds.OnUpdateFound,
		C3.Plugins.Browser.Cnds.OnUpdateReady,
		C3.Plugins.Browser.Acts.Reload,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.time,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.SetFontSize
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Browser: 0},
	{originalSize: 0},
	{ActiveButton: 0},
	{ButtonStart: 0},
	{Choices: 0},
	{ToggleButtonExample: 0},
	{ProjectText: 0},
	{Logo: 0},
	{Seen: 0},
	{"8Direction": 0},
	{Pointer: 0},
	{Keyboard: 0},
	{PlatformInfo: 0},
	{Label: 0},
	{Side: 0},
	{Solid: 0},
	{Border: 0},
	{BG: 0},
	{Start: 0},
	{End: 0},
	{Tween: 0},
	{Kayak: 0},
	{Dot: 0},
	{TimeOut: 0},
	{Label2: 0},
	{Label3: 0},
	{Button: 0},
	{ToggleButton: 0},
	{ppmi: 0},
	{tscale: 0},
	{StartTime: 0},
	{timeHrs: 0},
	{index: 0},
	{FindString: 0},
	{DataString: 0},
	{TokenString: 0},
	{NewElementString: 0},
	{NewDataString: 0},
	{N: 0},
	{outString: 0},
	{ReplaceString: 0},
	{listLen0: 0},
	{tempTotal: 0},
	{listLen: 0},
	{mean: 0},
	{tempIndex: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	ButtonStart: class extends self.ITextInstance {},
	ToggleButtonExample: class extends self.ITextInstance {},
	ProjectText: class extends self.ITextInstance {},
	Logo: class extends self.ISpriteInstance {},
	Pointer: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Label: class extends self.ITextInstance {},
	Border: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	Start: class extends self.ISpriteInstance {},
	End: class extends self.ISpriteInstance {},
	Kayak: class extends self.ISpriteInstance {},
	Dot: class extends self.ISpriteInstance {},
	TimeOut: class extends self.ITextInstance {},
	Label2: class extends self.ITextInstance {},
	Label3: class extends self.ITextInstance {},
	Button: class extends self.ITextInstance {},
	ToggleButton: class extends self.ITextInstance {}
}