function m(c,a,b,d){c.h.ea(c.W,a,b,d)}function r(c,a,b,d){c.h.m?m(c,a,b,d):c.h.Fb()._OnMessageFromDOM({type:"event",component:c.W,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function t(c,a,b){c.h.i(c.W,a,b)}function u(c,a){for(const [b,d]of a)t(c,b,d)}window.da=class{constructor(c,a){this.h=c;this.W=a}Oa(){}};window.qc=class{constructor(){}};"use strict";function aa(c,a){t(c,"get-element",b=>{const d=v(c,b.elementId);return a(d,b)})}
function v(c,a){c=c.L.get(a);if(!c)throw Error(`no element with id ${a}`);return c.ia}
window.Qa=class extends self.da{constructor(c,a){super(c,a);this.L=new Map;this.U=!0;u(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{b=b.elementId;const d=v(this,b);this.U&&d.parentElement.removeChild(d);this.L.delete(b)}],["set-visible",b=>{if(this.U){var d=this.L.get(b.elementId),e=d.ia;d.ib?e.style.display=b.isVisible?"":"none":d.Yb=!!b.isVisible}}],["update-position",b=>{if(this.U){var d=this.L.get(b.elementId),e=d.ia,f=this.h;e.style.left=b.left+"px";e.style.top=b.top+
"px";e.style.width=b.width+"px";e.style.height=b.height+"px";var h=b.fontSize;null!==h&&(e.style.fontSize=h+"em");h=b.htmlIndex;d.bc=h;h=f.Ra(h);h!==d.F&&(e.remove(),f.ra(h).appendChild(e),d.F=h,f.ya());b=b.htmlZIndex;b!==d.Ba&&(d.Ba=b,f.ya());d.ib||(d.ib=!0,d.Yb&&(e.style.display=""))}}],["update-state",b=>{v(this,b.elementId);throw Error("required override");}],["focus",b=>this.va(b)],["set-css-style",b=>{const d=v(this,b.elementId),e=b.prop;b=b.val;e.startsWith("--")?d.style.setProperty(e,b):d.style[e]=
b}],["set-attribute",b=>{v(this,b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{v(this,b.elementId).removeAttribute(b.name)}]]);aa(this,b=>b)}va(c){var a=v(this,c.elementId);c.focus?a.focus():a.blur()}};"use strict";const w=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent);let y=0;
function z(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.fc?new Promise(b=>{const d="c3_resolve_"+y;++y;self[d]=b;a.textContent=c.kc+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((b,d)=>{a.onload=b;a.onerror=d;a.src=c;document.head.appendChild(a)})}
async function ba(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let c=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){c=!0}}),b=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return c&&b}catch(c){return console.warn("Error feature detecting worker mode: ",c),!1}}let A=new Audio;
const ca={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ea(c){c=await B(c);return(new TextDecoder("utf-8")).decode(c)}
function B(c){return new Promise((a,b)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsArrayBuffer(c)})}const C=[];let D=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let fa=0;const ha=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");ha.push(c)};const ia=new Set(["cordova","playable-ad","instant-games"]);let ja=!1;
window.I=class c{constructor(a){this.m=a.mc;this.Z=null;this.l="";this.N=a.jc;this.ba={};this.Fa=this.P=null;this.K=[];this.H=null;this.kb=!0;this.j=[];this.Ja=[];this.Ka=!1;this.mb=()=>this.Db();this.jb=!1;this.X=null;this.M=-1;this.ac=()=>this.Ob();this.$=new Set;this.Ma=null;this.nb=[];this.g=a.ob;this.Da="file"===location.protocol.substr(0,4);if("playable-ad"===this.g||"instant-games"===this.g)this.m=!1;if("cordova"===this.g&&this.m&&x){const b=/Chrome\/(\d+)/i.exec(navigator.userAgent);b&&90<=
parseInt(b[1],10)||(this.m=!1)}this.u()?self.chrome.webview.addEventListener("message",b=>this.ab(b.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=b=>this.ab(b));this.ja=this.A=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.i("canvas","update-size",b=>this.Sb(b));this.i("canvas","set-html-layer-count",
b=>this._OnSetHTMLLayerCount(b));this.i("canvas","cleanup-html-layers",()=>this.Jb());this.i("runtime","cordova-fetch-local-file",b=>this.Kb(b));this.i("runtime","create-job-worker",()=>this.Lb());this.i("runtime","send-wrapper-extension-message",b=>this.Rb(b));"cordova"===this.g?document.addEventListener("deviceready",()=>this.Za(a)):this.Za(a)}qb(){return this.j[0].canvas}Ra(a){return Math.min(a,this.j.length-1)}ra(a){if(0>a||a>=this.j.length)throw new RangeError("invalid canvas layer");return this.j[a].ca}ub(){return w&&
"cordova"===this.g}T(){const a=navigator.userAgent;return w&&ia.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}sb(){return x}Sa(){return x&&ia.has(this.g)}Ta(){return"windows-webview2"===this.g||!!("preview"===this.g&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}u(){return this.Ta()||"xbox-uwp-webview2"===this.g}async Za(a){this.m&&!await ba()&&(this.m=!1);"macos-wkwebview"===this.g?this.D({type:"ready"}):this.u()&&(this.Vb(),this.nb=(await this.Ib()).registeredComponentIds);
if("playable-ad"===this.g){this.A=self.c3_base64files;this.ja={};await this.Ab();for(let d=0,e=a.R.length;d<e;++d){var b=a.R[d];this.ja.hasOwnProperty(b)?a.R[d]={fc:!0,kc:this.ja[b]}:this.A.hasOwnProperty(b)&&(a.R[d]=URL.createObjectURL(this.A[b]))}a.na=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Ua(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.ic?this.l=a.ic:(b=location.origin,this.l=("null"===b?"file:///":b)+location.pathname,b=this.l.lastIndexOf("/"),
-1!==b&&(this.l=this.l.substr(0,b+1)));a.oc&&(this.ba=a.oc);b=new MessageChannel;this.Z=b.port1;this.Z.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Nb(d));this.X=new self.vb(this);await ka(this.X);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.m?await this.Hb(a,b.port2):await this.Gb(a,b.port2)}ta(a){a=this.ba.hasOwnProperty(a)?this.ba[a]:a.endsWith("/workermain.js")&&this.ba.hasOwnProperty("workermain.js")?this.ba["workermain.js"]:"playable-ad"===this.g&&this.A.hasOwnProperty(a)?this.A[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async qa(a,b,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.Da)return a=await this.pa(d.ec?a:this.N+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,b);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}v(){return Math.max(window.innerWidth,1)}o(){return Math.max(window.innerHeight,1)}Ya(a){var b=this.l,d=location.href,e=this.v(),f=this.o(),h=window.devicePixelRatio,g=c.S(),k=a.uc,l=window.cr_previewImageBlobs||this.A,n=window.cr_previewProjectFileBlobs,p=window.cr_previewProjectFiles,q=window.cr_swClientId||
"";a=a.ob;var ta=(new URLSearchParams(self.location.search)).has("debug"),L=this.X;return{runtimeBaseUrl:b,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:h,isFullscreen:g,projectData:k,previewImageBlobs:l,previewProjectFileBlobs:n,previewProjectFileSWUrls:p,swClientId:q,exportType:a,isDebug:ta,ife:!!self.tc,jobScheduler:{inputPort:L.Ca,outputPort:L.Ia,maxNumWorkers:L.Zb},supportedAudioFormats:ca,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.N+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.N+"opus.wasm.wasm",isFileProtocol:this.Da,isiOSCordova:this.ub(),isiOSWebView:this.T(),isWindowsWebView2:this.Ta(),isAnyWebView2Wrapper:this.u(),wrapperComponentIds:this.nb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Hb(a,b){const d=this.ta(a.nc);"preview"===this.g?(this.P=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,n)=>{const p=q=>{this.P.removeEventListener("message",p);q.data&&"ok"===q.data.type?l():n()};this.P.addEventListener("message",
p);this.P.postMessage({type:"construct-worker-init","import":(new URL(d,this.l)).toString()})})):this.P=await this.qa(d,this.l,{type:"module",name:"Runtime",ec:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const h=document.createElement("div");h.className="c3htmlwrap";document.body.appendChild(h);this.j.push({canvas:e,ca:h});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();
let g=a.na||[],k=a.R;g=await Promise.all(g.map(l=>this.J(l)));k=await Promise.all(k.map(l=>this.J(l)));if("cordova"===this.g)for(let l=0,n=a.ma.length;l<n;++l){const p=a.ma[l],q=p[0];if(q===a.Na||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.J(q)}this.P.postMessage(Object.assign(this.Ya(a),{type:"init-runtime",isInWorker:!0,messagePort:b,canvas:f,workerDependencyScripts:g,engineScripts:k,projectScripts:a.ma,mainProjectScript:a.Na,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[b,f,...la(this.X)]);this.K=E.map(l=>new l(this));this.Xa();H(e);J(h);ma(this.H);self.c3_callFunction=(l,n)=>{var p=this.H;return p.h.wb(p.W,{name:l,params:n})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.ea("runtime","go-to-last-error-script"))}async Gb(a,b){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.j.push({canvas:d,ca:e});window.c3canvas=d;
self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.K=E.map(g=>new g(this));this.Xa();H(d);J(e);e=a.R.map(g=>"string"===typeof g?(new URL(g,this.l)).toString():g);if(Array.isArray(a.na)){var f=[...a.na].map(g=>g instanceof Blob?URL.createObjectURL(g):g);e.unshift(...f)}e=await Promise.all(e.map(g=>this.J(g)));await Promise.all(e.map(g=>z(g)));e=self.C3_ProjectScriptsStatus;f=a.Na;const h=a.ma;for(let [g,k]of h)if(k||(k=g),g===f)try{k=await this.J(k),await z(k),"preview"!==this.g||
e[g]||this.bb(g,"main script did not run to completion")}catch(l){this.bb(g,l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))k=await this.J(k),await z(k);"preview"===this.g&&"object"!==typeof self.pc.rc?(this.ga(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ya(a),{isInWorker:!1,
messagePort:b,canvas:d,runOnStartupFunctions:ha}),ma(this.H),this.$a(),this.Fa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Fa,a))}bb(a,b){this.ga();console.error(`[Preview] Failed to load project main script (${a}): `,b);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}$a(){this.ga()}ga(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=
null)}async Lb(){const a=await na(this.X);return{outputPort:a,transferables:[a]}}Sb(a){if(!this.jb){var b=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:h,ca:g}of this.j)h.style.width=b,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,g.style.width=b,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,this.kb&&(h.style.display="",g.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.kb=
!1}}_OnSetHTMLLayerCount(a){var b=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const h=a.marginLeft+"px",g=a.marginTop+"px";a=[];const k=[];if(b<this.j.length)for(;this.j.length>b;){const {canvas:l,ca:n}=this.j.pop();n.remove();this.m&&!d?this.Ja.push(l):l.remove()}else if(b>this.j.length)for(let l=0,n=b-this.j.length;l<n;++l)b=document.createElement("canvas"),b.classList.add("c3overlay"),this.m?(d=b.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(b),document.body.appendChild(b),
d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),b.style.width=e,b.style.height=f,b.style.marginLeft=h,b.style.marginTop=g,d.style.width=e,d.style.height=f,d.style.marginLeft=h,d.style.marginTop=g,H(b),J(d),this.j.push({canvas:b,ca:d});for(const l of this.K)if(l instanceof window.Qa&&l.U)for(const n of l.L.values())e=l.h.Ra(n.bc),f=n.F,-1!==e&&-1!==f&&e!==f&&(f=n.ia,f.remove(),l.h.ra(e).appendChild(f),n.F=e);this.ya();return{addedCanvases:a,transferables:k}}Jb(){for(const a of this.Ja)a.remove();
this.Ja.length=0}ya(){this.Ka||(this.Ka=!0,this.Ua(this.mb))}Db(){this.Ub(this.mb);this.Ka=!1;let a=[];for(var b of this.K)if(b instanceof window.Qa){var d=b.U?[...b.L.values()]:null;d&&a.push(...d)}a.sort((h,g)=>{const k=h.F,l=g.F;return k!==l?k-l:h.Ba-g.Ba});let e=d=b=0,f=a.length;for(;e<f;++e){const h=a[e];h.F!==b&&(this.Wa(b,a.slice(d,e)),b=h.F,d=e)}d<e&&this.Wa(b,a.slice(d,e))}Wa(a,b){if(!(1>=b.length||a>=this.j.length)){b=b.map(k=>k.ia);var d=new Set(b);a=this.ra(a);for(var e=Array.from(a.children).filter(k=>
d.has(k)),f=0,h=Math.min(b.length,e.length);f<h&&b[f]===e[f];++f);for(var g=f;g<h;++g)e[g].remove();for(g=f;g<h;++g)a.appendChild(b[g])}}Fb(){if(this.m)throw Error("not available in worker mode");return this.Fa}ea(a,b,d,e){this.Z.postMessage({type:"event",component:a,handler:b,dispatchOpts:e||null,data:d,responseId:null},void 0)}wb(a,b){const d=fa++,e=new Promise((f,h)=>{G.set(d,{resolve:f,reject:h})});this.Z.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:b,
responseId:d},void 0);return e}_OnMessageFromRuntime(a){const b=a.type;if("event"===b)return this.Mb(a);if("result"===b)this.Pb(a);else if("runtime-ready"===b)this.Qb();else if("alert-error"===b)this.ga(),alert(a.message);else if("creating-runtime"===b)this.$a();else throw Error(`unknown message '${b}'`);}Mb(a){const b=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(b))if(a=a.get(d)){var h=null;try{h=a(e)}catch(g){console.error(`Exception in '${b}' handler '${d}':`,g);null!==f&&this.fa(f,
!1,""+g);return}if(null===f)return h;h&&h.then?h.then(g=>this.fa(f,!0,g)).catch(g=>{console.error(`Rejection from '${b}' handler '${d}':`,g);this.fa(f,!1,""+g)}):this.fa(f,!0,h)}else console.warn(`[DOM] No handler '${d}' for component '${b}'`);else console.warn(`[DOM] No event handlers for component '${b}'`)}fa(a,b,d){let e;d&&d.transferables&&(e=d.transferables);this.Z.postMessage({type:"result",responseId:a,isOk:b,result:d},e)}Pb(a){const b=a.responseId,d=a.isOk;a=a.result;const e=G.get(b);d?e.resolve(a):
e.reject(a);G.delete(b)}i(a,b,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(b))throw Error(`[DOM] Component '${a}' already has handler '${b}'`);e.set(b,d)}static oa(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Xa(){for(const a of this.K)if("runtime"===a.W){this.H=a;return}throw Error("cannot find runtime DOM handler");}Nb(a){this.ea("debugger","message",a)}Qb(){for(const a of this.K)a.Oa()}static S(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement||ja)}static ha(a){ja=!!a}Ua(a){this.$.add(a);this.xa()}Ub(a){this.$.delete(a);0===this.$.size&&this.Va()}xa(){-1===this.M&&0<this.$.size&&(this.M=requestAnimationFrame(this.ac))}Va(){-1!==this.M&&(cancelAnimationFrame(this.M),this.M=-1)}Ob(){this.M=-1;for(const a of this.$)a();this.xa()}wa(){this.H.wa()}xb(){this.jb=!0}rb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}tb(a){return!this.rb(a)}async J(a){return"cordova"===this.g&&
(a.startsWith("file:")||this.Da&&this.tb(a))?(a.startsWith(this.l)&&(a=a.substr(this.l.length)),a=await this.pa(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Kb(a){const b=a.filename;switch(a.as){case "text":return await this.pb(b);case "buffer":return await this.pa(b);default:throw Error("unsupported type");}}Pa(a){const b=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(b,f=>{f.file(d,e)},e)})}async pb(a){a=
await this.Pa(a);return await ea(a)}sa(){if(C.length&&!(8<=D)){D++;var a=C.shift();this.Bb(a.filename,a.lc,a.dc)}}pa(a){return new Promise((b,d)=>{C.push({filename:a,lc:e=>{D--;this.sa();b(e)},dc:e=>{D--;this.sa();d(e)}});this.sa()})}async Bb(a,b,d){try{const e=await this.Pa(a),f=await B(e);b(f)}catch(e){d(e)}}ab(a){if("entered-fullscreen"===a)c.ha(!0),K(this.H);else if("exited-fullscreen"===a)c.ha(!1),K(this.H);else if("object"===typeof a){const b=a.type;"wrapper-init-response"===b?(this.Ma(a),this.Ma=
null):"extension-message"===b?this.ea("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Rb(a){this.D({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}D(a){this.u()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Vb(){window.moveTo=(a,b)=>{this.D({type:"set-window-position",
windowX:Math.ceil(a),windowY:Math.ceil(b)})};window.resizeTo=(a,b)=>{this.D({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(b)})}}Ib(){return this.u()?new Promise(a=>{this.Ma=a;this.D({type:"wrapper-init"})}):Promise.resolve()}async Ab(){const a=[];for(const [b,d]of Object.entries(this.A))a.push(this.zb(b,d));await Promise.all(a)}async zb(a,b){if("object"===typeof b)this.A[a]=new Blob([b.str],{type:b.type}),this.ja[a]=b.str;else{let d=await this.Eb(b);d||(d=this.Cb(b));this.A[a]=
d}}async Eb(a){try{return await (await fetch(a)).blob()}catch(b){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",b),null}}Cb(a){a=this.Tb(a);return this.yb(a.data,a.hc)}Tb(a){var b=a.indexOf(",");if(0>b)throw new URIError("expected comma in data: uri");var d=a.substring(b+1);b=a.substring(5,b).split(";");a=b[0]||"";const e=b[2];d="base64"===
b[1]||"base64"===e?atob(d):decodeURIComponent(d);return{hc:a,data:d}}yb(a,b){var d=a.length;let e=d>>2,f=new Uint8Array(d),h=new Uint32Array(f.buffer,0,e),g,k;for(k=g=0;g<e;++g)h[g]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:b})}};"use strict";
const M=self.I,oa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),N={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},O={dispatchUserScriptEvent:!0},P={dispatchRuntimeEvent:!0};function pa(c){return new Promise((a,b)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>b(e);d.rel="stylesheet";d.href=c;document.head.appendChild(d)})}function qa(c){return new Promise((a,b)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>b(e);d.src=c})}
async function Q(c){c=URL.createObjectURL(c);try{return await qa(c)}finally{URL.revokeObjectURL(c)}}function ra(c){return new Promise((a,b)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsText(c)})}
async function sa(c,a,b){if(!/firefox/i.test(navigator.userAgent))return await Q(c);var d=await ra(c);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),h=e.getAttribute("height");if(!f.includes("%")&&!h.includes("%"))return await Q(c)}e.setAttribute("width",a+"px");e.setAttribute("height",b+"px");d=(new XMLSerializer).serializeToString(d);c=new Blob([d],{type:"image/svg+xml"});return await Q(c)}
function R(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const ua=new Set(["input","textarea","datalist","select"]),va=new Set(["canvas","body","html"]);function S(c){c.target.tagName&&va.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function T(c){c.target.tagName&&c.target.classList.contains("c3htmlwrap")&&c.preventDefault()}function wa(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}
self.C3_GetSvgImageSize=async function(c){c=await Q(c);if(0<c.width&&0<c.height)return[c.width,c.height];c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const a=c.getBoundingClientRect();document.body.removeChild(c);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(c,a,b,d,e){c=await sa(c,a,b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(c,0,0,a,b);return f};
let U=!1;document.addEventListener("pause",()=>U=!0);document.addEventListener("resume",()=>U=!1);function H(c){c.addEventListener("selectstart",S);c.addEventListener("gesturehold",S);c.addEventListener("pointerdown",S)}function J(c){c.addEventListener("selectstart",T);c.addEventListener("gesturehold",T);c.addEventListener("touchstart",T)}function ma(c){c.gb=!0;c.Ea=c.h.v();c.Y=c.h.o()}
function K(c){if(!c.s){var a=M.S();a&&"any"!==c.La&&xa(c);m(c,"fullscreenchange",{isFullscreen:a,innerWidth:c.v(),innerHeight:c.o()})}}async function ya(c){await Promise.all(c.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function za(c){var a=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);a=a?await createImageBitmap(c,a):await createImageBitmap(c);return{imageBitmap:a,transferables:[a]}}async function Aa(c){return await self.C3_GetSvgImageSize(c.blob)}function Ba(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}
function Ca(c){self.setTimeout(()=>{c.fb=!0},1E3);"cordova"===c.h.g?(document.addEventListener("pause",()=>V(c,!0)),document.addEventListener("resume",()=>V(c,!1))):document.addEventListener("visibilitychange",()=>V(c,"hidden"===document.visibilityState));c.ka=!("hidden"!==document.visibilityState&&!U);return{isSuspended:c.ka}}
function Da(c){c.eb||(c.eb=!0,window.addEventListener("deviceorientation",a=>{c.s||m(c,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},N)}),window.addEventListener("deviceorientationabsolute",a=>{c.s||m(c,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},N)}))}
function Ea(c){c.cb||(c.cb=!0,window.addEventListener("devicemotion",a=>{if(!c.s){var b=null,d=a.acceleration;d&&(b={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(c,"devicemotion",{acceleration:b,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},N)}}))}async function Fa(c){await pa(c.url)}
function Ga(c,a){c.hb=a.message;-1===c.Aa&&(c.Aa=setTimeout(()=>{c.Aa=-1;const b=document.getElementById("exportToVideoMessage");b&&(b.textContent=c.hb)},250))}function W(c,a){console.warn("[Construct] Fullscreen request failed: ",a);m(c,"fullscreenerror",{isFullscreen:M.S(),innerWidth:c.v(),innerHeight:c.o()})}
function V(c,a){c.ka!==a&&((c.ka=a)?c.h.Va():c.h.xa(),m(c,"visibilitychange",{hidden:a}),!a&&c.h.T()&&(c=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(c,50),setTimeout(c,100),setTimeout(c,250),setTimeout(c,500)))}
function Ha(c,a,b){"Backspace"===b.key&&S(b);if(c.h.u()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(b.key)||b.ctrlKey&&d.includes(b.key))&&b.preventDefault()}c.s||(d=oa.get(b.code)||b.code,r(c,a,{code:d,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,metaKey:b.metaKey,shiftKey:b.shiftKey,timeStamp:b.timeStamp},N))}
function X(c,a,b,d){c.s||b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents||r(c,a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY+c.C,pageX:b.pageX,pageY:b.pageY+c.C,movementX:b.movementX||0,movementY:b.movementY||0,timeStamp:b.timeStamp},d)}
function Y(c,a,b){if(!c.s){var d=0;"mouse"===b.pointerType&&(d=c.Ha);r(c,a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,buttons:b.buttons,lastButtons:d,clientX:b.clientX,clientY:b.clientY+c.C,pageX:b.pageX,pageY:b.pageY+c.C,movementX:b.movementX||0,movementY:b.movementY||0,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},N);"mouse"===b.pointerType&&(c.Ha=
b.buttons)}}function Z(c,a,b){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";c.C=0;if(0<b){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-b)/2,a>b&&(a=b),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,c.C=a))}}
function Ia(c,a,b,d){const e=c.v(),f=c.o();c.O=-1;e!=a||f!=b?m(c,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:M.S()}):10>d&&Ja(c,e,f,d+1)}function Ja(c,a,b,d){-1!==c.O&&clearTimeout(c.O);c.O=setTimeout(()=>Ia(c,a,b,d),48)}
function xa(c){c=c.La;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ka(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}
M.oa(class extends self.da{constructor(c){super(c,"runtime");this.gb=!1;this.O=-1;this.La="any";this.ka=this.cb=this.eb=!1;this.la=document.createElement("div");this.la.className="c3-screen-reader-text";this.la.setAttribute("aria-live","polite");document.body.appendChild(this.la);this.G=null;this.s=!1;this.hb="";this.Aa=-1;this.fb=!1;this.Ea=c.v();this.Y=c.o();this.C=this.aa=0;c.i("runtime","invoke-download",b=>{const d=b.url;b=b.filename;const e=document.createElement("a"),f=document.body;e.textContent=
b;e.href=d;e.download=b;f.appendChild(e);e.click();f.removeChild(e)});c.i("runtime","load-webfonts",b=>ya(b));c.i("runtime","raster-svg-image",b=>za(b));c.i("runtime","get-svg-image-size",b=>Aa(b));c.i("runtime","set-target-orientation",b=>{this.La=b.targetOrientation});c.i("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});c.i("runtime","post-to-debugger",b=>Ba(b));c.i("runtime","go-to-script",b=>Ba(b));c.i("runtime","before-start-ticking",()=>Ca(this));c.i("runtime","debug-highlight",
b=>{if(b.show){this.G||(this.G=document.createElement("div"),this.G.id="inspectOutline",document.body.appendChild(this.G));var d=this.G;d.style.display="";d.style.left=b.left-1+"px";d.style.top=b.top-1+"px";d.style.width=b.width+2+"px";d.style.height=b.height+2+"px";d.textContent=b.name}else this.G&&(this.G.style.display="none")});c.i("runtime","enable-device-orientation",()=>Da(this));c.i("runtime","enable-device-motion",()=>Ea(this));c.i("runtime","add-stylesheet",b=>Fa(b));c.i("runtime","script-create-worker",
b=>{const d=b.port2;(new Worker(b.url,b.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});c.i("runtime","alert",b=>this.ua(b));c.i("runtime","screen-reader-text",b=>{var d=b.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+b.id,d.textContent=b.text,this.la.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+b.id))?d.textContent=b.text:console.warn(`[Construct] Missing screen reader text with id ${b.id}`):"release"===d?(d=document.getElementById("c3-sr-"+b.id))?
d.remove():console.warn(`[Construct] Missing screen reader text with id ${b.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});c.i("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});c.i("runtime","set-exporting-to-video",b=>{this.s=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=b.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");this.h.qb().style.display=
"";this.h.xb()});c.i("runtime","export-to-video-progress",b=>Ga(this,b));c.i("runtime","exported-to-video",b=>{window.cc({type:"exported-video",arrayBuffer:b.arrayBuffer,contentType:b.contentType,time:b.time})});c.i("runtime","exported-to-image-sequence",b=>{window.cc({type:"exported-image-sequence",blobArr:b.blobArr,time:b.time,gif:b.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",b=>{const d=b.target;a.has(d.tagName.toLowerCase())||R(d)||b.preventDefault()});
window.addEventListener("selectstart",S);window.addEventListener("gesturehold",S);window.addEventListener("touchstart",S,{passive:!1});window.addEventListener("pointerdown",S,{passive:!1});this.Ha=0;window.addEventListener("mousedown",b=>{1===b.button&&b.preventDefault()});window.addEventListener("mousewheel",wa,{passive:!1});window.addEventListener("wheel",wa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.s&&this.gb){var b=this.v();var d=this.o();if(this.h.Sa()){if(this.fb){if(this.Ea===
b&&d<this.Y){this.aa=this.Y-d;Z(this,this.Y,this.aa);b=void 0;break a}0<this.aa&&(this.aa=0,Z(this,d,this.aa))}this.Ea=b;this.Y=d}m(this,"window-resize",{innerWidth:b,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:M.S()});this.h.T()&&(-1!==this.O&&clearTimeout(this.O),Ia(this,b,d,0))}b=void 0}return b});window.addEventListener("fullscreenchange",()=>K(this));window.addEventListener("webkitfullscreenchange",()=>K(this));window.addEventListener("mozfullscreenchange",()=>K(this));
window.addEventListener("fullscreenerror",b=>W(this,b));window.addEventListener("webkitfullscreenerror",b=>W(this,b));window.addEventListener("mozfullscreenerror",b=>W(this,b));if(c.T()){if(window.visualViewport){let b=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>b&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);b=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var b=e.tagName.toLowerCase();
var d=new Set("email number password search tel text url".split(" "));b="textarea"===b?!0:"input"===b?d.has(e.type.toLowerCase()||"text"):R(e)}else b=!1}b||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.Ga=new Set;this.$b=new WeakSet;this.Xb=!1}Oa(){window.addEventListener("focus",()=>{m(this,"window-focus",null,P)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(b){a=!1}m(this,"window-blur",
{parentHasFocus:a},P);this.Ha=0});window.addEventListener("focusin",a=>{a=a.target;(ua.has(a.tagName.toLowerCase())||R(a))&&m(this,"keyboard-blur",null,P)});window.addEventListener("keydown",a=>Ha(this,"keydown",a));window.addEventListener("keyup",a=>Ha(this,"keyup",a));window.addEventListener("mousedown",a=>X(this,"mousedown",a,O));window.addEventListener("mousemove",a=>X(this,"mousemove",a,O));window.addEventListener("mouseup",a=>X(this,"mouseup",a,O));window.addEventListener("dblclick",a=>X(this,
"dblclick",a,N));window.addEventListener("wheel",a=>{this.s||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.C,pageX:a.pageX,pageY:a.pageY+this.C,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},N)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Ka(a.target)&&document.activeElement&&!Ka(document.activeElement)&&document.activeElement.blur();Y(this,"pointerdown",a)});this.h.m&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{Y(this,"pointermove",a)}):window.addEventListener("pointermove",a=>Y(this,"pointermove",a));window.addEventListener("pointerup",a=>Y(this,"pointerup",a));window.addEventListener("pointercancel",a=>Y(this,"pointercancel",a));const c=()=>this.wa();window.addEventListener("pointerup",c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",
c,!0);this.h.sb()&&!this.h.Sa()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Z(this,this.o(),navigator.virtualKeyboard.boundingRect.height)}));this.h.T()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}v(){return this.h.v()}o(){return this.h.o()}wa(){var c=[...this.Ga];this.Ga.clear();if(!this.Xb)for(const a of c)(c=a.play())&&c.catch(()=>{this.$b.has(a)||this.Ga.add(a)})}ua(c){alert(c.message)}});
"use strict";async function ka(c){if(c.Wb)throw Error("already initialised");c.Wb=!0;var a=c.B.ta(("playable-ad"===c.B.g?c.B.N:"")+"dispatchworker.js");c.za=await c.B.qa(a,c.V,{name:"DispatchWorker"});a=new MessageChannel;c.Ca=a.port1;c.za.postMessage({type:"_init","in-port":a.port2},[a.port2]);c.Ia=await na(c)}function la(c){return[c.Ca,c.Ia]}
async function na(c){const a=c.lb.length;var b=c.B.ta(("playable-ad"===c.B.g?c.B.N:"")+"jobworker.js");b=await c.B.qa(b,c.V,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;c.za.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);c.lb.push(b);return e.port1}
self.vb=class{constructor(c){this.B=c;this.V=c.l;this.V="preview"===c.g?this.V+"workers/":this.V+c.N;this.Zb=Math.min(navigator.hardwareConcurrency||2,16);this.za=null;this.lb=[];this.Ia=this.Ca=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.I({mc:!0,nc:"workermain.js",R:["scripts/c3runtime.js"],ma:[],Na:"",jc:"scripts/",na:[],ob:"html5"}));"use strict";
async function La(c,a){a=a.type;let b=!0;0===a?b=await Ma():1===a&&(b=await Na());m(c,"permission-result",{type:a,result:b})}async function Ma(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request orientation permission: ",c),!1}}
async function Na(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request motion permission: ",c),!1}}self.I.oa(class extends self.da{constructor(c){super(c,"touch");t(this,"request-permission",a=>La(this,a))}});"use strict";function Oa(){}
function Pa(c){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(c,"sw-message",a.data))}
function Ra(c){c=c.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.I.oa(class extends self.da{constructor(c){super(c,"browser");this.g="";u(this,[["get-initial-state",a=>{this.g=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Pa(this)],["alert",a=>this.ua(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.va(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Ra(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,
"_system"):"preview"===a||this.h.u()?window.open(b,"_blank"):this.sc||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if(this.h.u()||"macos-wkwebview"===this.g)self.I.ha(!0),this.h.D({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&
(b.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(b):a.mozRequestFullScreen?d=a.mozRequestFullScreen(b):a.msRequestFullscreen?d=a.msRequestFullscreen(b):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Oa)}}],["exit-fullscreen",()=>{if(this.h.u()||"macos-wkwebview"===this.g)self.I.ha(!1),this.h.D({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Oa)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const b=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var h=
document.querySelector(e);f=h?[h]:[]}else f=[document.documentElement];e=f;for(const g of e)b.startsWith("--")?g.style.setProperty(b,d):g.style[b]=d}catch(g){console.warn("[Browser] Failed to set style: ",g)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var b=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),b={isOk:!1}}}return b}],["set-window-size",a=>{window.resizeTo(a.windowWidth,
a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{m(this,"backbutton")})}ua(c){alert(c.message)}va(c){c=c.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():
null;c?a.focus():a.blur()}else c?window.focus():window.blur()}});
