'use strict';function r(f,g,h,m){f.f.da(f.J,g,h,m,void 0)}function B(f,g,h,m){f.f.j?r(f,g,h,m):f.f.pb()._OnMessageFromDOM({type:"event",component:f.J,handler:g,dispatchOpts:m||null,data:h,responseId:null})}function I(f,g,h){f.f.b(f.J,g,h)}function J(f,g){for(const [h,m]of g)I(f,h,m)}window.D=class{constructor(f,g){this.f=f;this.J=g}Ba(){}};
window.eb=class{constructor(f,g){this.Qa=f;this.Vb=g;this.B=-1;this.X=-Infinity;this.$b=()=>{this.B=-1;this.X=Date.now();this.K=!0;this.Qa();this.K=!1};this.Ra=this.K=!1}};"use strict";function M(f,g){I(f,"get-element",h=>{const m=f.h.get(h.elementId);return g(m,h)})}
window.nc=class extends self.D{constructor(f,g){super(f,g);this.h=new Map;this.ra=!0;J(this,[["create",()=>{throw Error("required override");}],["destroy",h=>{{h=h.elementId;const m=this.h.get(h);this.ra&&m.parentElement.removeChild(m);this.h.delete(h)}}],["set-visible",h=>{this.ra&&(this.h.get(h.elementId).style.display=h.isVisible?"":"none")}],["update-position",h=>{if(this.ra){var m=this.h.get(h.elementId);m.style.left=h.left+"px";m.style.top=h.top+"px";m.style.width=h.width+"px";m.style.height=
h.height+"px";h=h.fontSize;null!==h&&(m.style.fontSize=h+"em")}}],["update-state",h=>{this.h.get(h.elementId);throw Error("required override");}],["focus",h=>this.na(h)],["set-css-style",h=>{this.h.get(h.elementId).style[h.prop]=h.val}],["set-attribute",h=>{this.h.get(h.elementId).setAttribute(h.name,h.val)}],["remove-attribute",h=>{this.h.get(h.elementId).removeAttribute(h.name)}]]);M(this,h=>h)}na(f){var g=this.h.get(f.elementId);f.focus?g.focus():g.blur()}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let g=0;function h(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.dc?new Promise(d=>{const e="c3_resolve_"+g;++g;self[e]=d;a.textContent=c.hc+`\n\nself["${e}"]();`;document.head.appendChild(a)}):new Promise((d,e)=>{a.onload=d;a.onerror=e;a.src=c;document.head.appendChild(a)})}let m=!1,v=!1;function K(){if(!m){try{new Worker("blob://",{get type(){v=!0}})}catch(c){}m=!0}return v}let w=
new Audio;const L={"audio/webm; codecs=opus":!!w.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!w.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!w.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!w.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!w.canPlayType("audio/mp4"),"audio/mpeg":!!w.canPlayType("audio/mpeg")};w=null;async function y(c){c=await F(c);return(new TextDecoder("utf-8")).decode(c)}function F(c){return new Promise((a,
d)=>{const e=new FileReader;e.onload=k=>a(k.target.result);e.onerror=k=>d(k);e.readAsArrayBuffer(c)})}const C=[];let x=0;window.RealFile=window.File;const z=[],E=new Map,t=new Map;let G=0;const A=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");A.push(c)};const H=new Set(["cordova","playable-ad","instant-games"]);let b=!1;window.l=class c{constructor(a){this.j=a.jc;this.M=null;this.c="";this.$=a.fc;this.P={};this.va=this.Va=null;this.W=
[];this.L=this.g=this.ya=null;this.v=-1;this.Zb=()=>this.Ib();this.Ua=[];this.a=a.Wa;!this.j||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&K()||(this.j=!1);H.has(this.a)&&this.j&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is currently disabled in WebViews. Reverting to DOM mode."),this.j=!1);this.Y=this.i=null;"html5"!==this.a&&"playable-ad"!==this.a||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
this.b("runtime","cordova-fetch-local-file",d=>this.vb(d));this.b("runtime","create-job-worker",()=>this.wb());"cordova"===this.a?document.addEventListener("deviceready",()=>this.Ga(a)):this.Ga(a)}Da(){return f&&"cordova"===this.a}ca(){return f&&H.has(this.a)||navigator.standalone}async Ga(a){"macos-wkwebview"===this.a&&this.qa({type:"ready"});if("playable-ad"===this.a){this.i=self.c3_base64files;this.Y={};await this.kb();for(let e=0,k=a.C.length;e<k;++e){var d=a.C[e].toLowerCase();this.Y.hasOwnProperty(d)?
a.C[e]={dc:!0,hc:this.Y[d]}:this.i.hasOwnProperty(d)&&(a.C[e]=URL.createObjectURL(this.i[d]))}}a.ac?this.c=a.ac:(d=location.origin,this.c=("null"===d?"file:///":d)+location.pathname,d=this.c.lastIndexOf("/"),-1!==d&&(this.c=this.c.substr(0,d+1)));a.lc&&(this.P=a.lc);d=new MessageChannel;this.M=d.port1;this.M.onmessage=e=>this._OnMessageFromRuntime(e.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(e=>this.Fb(e));this.L=new self.bb(this);await N(this.L);"object"===typeof window.StatusBar&&
window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.j?await this.rb(a,d.port2):await this.qb(a,d.port2)}fa(a){a=this.P.hasOwnProperty(a)?this.P[a]:a.endsWith("/workermain.js")&&this.P.hasOwnProperty("workermain.js")?this.P["workermain.js"]:"playable-ad"===this.a&&this.i.hasOwnProperty(a.toLowerCase())?this.i[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ba(a,d,e){if(a.startsWith("blob:"))return new Worker(a,
e);if(this.Da()&&"file:"===location.protocol)return a=await this.aa(this.$+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),e);a=new URL(a,d);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),e)}return new Worker(a,e)}o(){return Math.max(window.innerWidth,1)}m(){return Math.max(window.innerHeight,1)}Fa(a){var d=this.L;return{baseUrl:this.c,windowInnerWidth:this.o(),
windowInnerHeight:this.m(),devicePixelRatio:window.devicePixelRatio,isFullscreen:c.F(),projectData:a.sc,previewImageBlobs:window.cr_previewImageBlobs||this.i,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.qc||"",exportType:a.Wa,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.rc,jobScheduler:{inputPort:d.ta,outputPort:d.xa,maxNumWorkers:d.Xb},supportedAudioFormats:L,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||
this.$+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.$+"opus.wasm.wasm",isiOSCordova:this.Da(),isiOSWebView:this.ca(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async rb(a,d){var e=this.fa(a.kc);this.Va=await this.ba(e,this.c,{type:"module",name:"Runtime"});this.g=document.createElement("canvas");this.g.style.display="none";e=this.g.transferControlToOffscreen();document.body.appendChild(this.g);window.c3canvas=this.g;this.Va.postMessage(Object.assign(this.Fa(a),
{type:"init-runtime",isInWorker:!0,messagePort:d,canvas:e,workerDependencyScripts:a.Aa||[],engineScripts:a.C,projectScripts:a.Ya,mainProjectScript:a.Xa,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[d,e,...O(this.L)]);this.W=z.map(k=>new k(this));this.Ea();self.c3_callFunction=(k,p)=>this.ya.sb(k,p);"preview"===this.a&&(self.goToLastErrorScript=()=>this.da("runtime","go-to-last-error-script"))}async qb(a,d){this.g=document.createElement("canvas");this.g.style.display="none";document.body.appendChild(this.g);
window.c3canvas=this.g;this.W=z.map(n=>new n(this));this.Ea();var e=a.C.map(n=>"string"===typeof n?(new URL(n,this.c)).toString():n);Array.isArray(a.Aa)&&e.unshift(...a.Aa);e=await Promise.all(e.map(n=>this.ha(n)));await Promise.all(e.map(n=>h(n)));e=self.C3_ProjectScriptsStatus;const k=a.Xa,p=a.Ya;for(let [n,q]of p)if(q||(q=n),n===k)try{q=await this.ha(q),await h(q),"preview"!==this.a||e[n]||this.Ma(n,"main script did not run to completion")}catch(u){this.Ma(n,u)}else if("scriptsInEvents.js"===n||
n.endsWith("/scriptsInEvents.js"))q=await this.ha(q),await h(q);"preview"===this.a&&"object"!==typeof self.mc.oc?(this.U(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Fa(a),{isInWorker:!1,messagePort:d,canvas:this.g,runOnStartupFunctions:A}),this.Ia(),this.va=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.va,
a))}Ma(a,d){this.U();console.error(`[Preview] Failed to load project main script (${a}): `,d);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ia(){this.U()}U(){const a=window.bc;a&&(a.parentElement.removeChild(a),window.bc=null)}async wb(){const a=await P(this.L);return{outputPort:a,transferables:[a]}}pb(){if(this.j)throw Error("not available in worker mode");return this.va}da(a,d,e,k,p){this.M.postMessage({type:"event",
component:a,handler:d,dispatchOpts:k||null,data:e,responseId:null},p)}cb(a,d){const e=G++,k=new Promise((p,n)=>{t.set(e,{resolve:p,reject:n})});this.M.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:d,responseId:e},void 0);return k}["_OnMessageFromRuntime"](a){const d=a.type;if("event"===d)return this.Bb(a);if("result"===d)this.Lb(a);else if("runtime-ready"===d)this.Mb();else if("alert-error"===d)this.U(),alert(a.message);else if("creating-runtime"===d)this.Ia();
else throw Error(`unknown message '${d}'`);}Bb(a){const d=a.component,e=a.handler,k=a.data,p=a.responseId;if(a=E.get(d))if(a=a.get(e)){var n=null;try{n=a(k)}catch(q){console.error(`Exception in '${d}' handler '${e}':`,q);null!==p&&this.T(p,!1,""+q);return}if(null===p)return n;n&&n.then?n.then(q=>this.T(p,!0,q)).catch(q=>{console.error(`Rejection from '${d}' handler '${e}':`,q);this.T(p,!1,""+q)}):this.T(p,!0,n)}else console.warn(`[DOM] No handler '${e}' for component '${d}'`);else console.warn(`[DOM] No event handlers for component '${d}'`)}T(a,
d,e){let k;e&&e.transferables&&(k=e.transferables);this.M.postMessage({type:"result",responseId:a,isOk:d,result:e},k)}Lb(a){const d=a.responseId,e=a.isOk;a=a.result;const k=t.get(d);e?k.resolve(a):k.reject(a);t.delete(d)}b(a,d,e){let k=E.get(a);k||(k=new Map,E.set(a,k));if(k.has(d))throw Error(`[DOM] Component '${a}' already has handler '${d}'`);k.set(d,e)}static R(a){if(z.includes(a))throw Error("DOM handler already added");z.push(a)}Ea(){for(const a of this.W)if("runtime"===a.J){this.ya=a;return}throw Error("cannot find runtime DOM handler");
}Fb(a){this.da("debugger","message",a)}Mb(){for(const a of this.W)a.Ba()}static F(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||b)}static V(a){b=!!a}Na(){-1===this.v&&this.Ua.length&&(this.v=requestAnimationFrame(this.Zb))}ib(){-1!==this.v&&(cancelAnimationFrame(this.v),this.v=-1)}Ib(){this.v=-1;for(const a of this.Ua)a();this.Na()}pa(){this.ya.pa()}$a(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}ab(a){return!this.$a(a)}async ha(a){return"cordova"===
this.a&&(a.startsWith("file:")||"file:"===location.protocol&&this.ab(a))?(a.startsWith(this.c)&&(a=a.substr(this.c.length)),a=await this.aa(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async vb(a){const d=a.filename;switch(a.as){case "text":return await this.Za(d);case "buffer":return await this.aa(d);default:throw Error("unsupported type");}}Ca(a){const d=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((e,k)=>{window.resolveLocalFileSystemURL(d,
p=>{p.file(e,k)},k)})}async Za(a){a=await this.Ca(a);return await y(a)}ea(){if(C.length&&!(8<=x)){x++;var a=C.shift();this.lb(a.filename,a.ic,a.cc)}}aa(a){return new Promise((d,e)=>{C.push({filename:a,ic:k=>{x--;this.ea();d(k)},cc:k=>{x--;this.ea();e(k)}});this.ea()})}async lb(a,d,e){try{const k=await this.Ca(a),p=await F(k);d(p)}catch(k){e(k)}}qa(a){if("windows-webview2"===this.a)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.a)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));
else throw Error("cannot send wrapper message");}async kb(){const a=[];for(const [d,e]of Object.entries(this.i))a.push(this.jb(d,e));await Promise.all(a)}async jb(a,d){if("object"===typeof d)this.i[a]=new Blob([d.str],{type:d.type}),this.Y[a]=d.str;else{let e=await this.ob(d);e||(e=this.mb(d));this.i[a]=e}}async ob(a){try{return await (await fetch(a)).blob()}catch(d){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
d),null}}mb(a){a=this.Rb(a);return this.hb(a.data,a.ec)}Rb(a){var d=a.indexOf(",");if(0>d)throw new URIError("expected comma in data: uri");var e=a.substring(d+1);d=a.substring(5,d).split(";");a=d[0]||"";const k=d[2];e="base64"===d[1]||"base64"===k?atob(e):decodeURIComponent(e);return{ec:a,data:e}}hb(a,d){var e=a.length;let k=e>>2,p=new Uint8Array(e),n=new Uint32Array(p.buffer,0,k),q,u;for(u=q=0;q<k;++q)n[q]=a.charCodeAt(u++)|a.charCodeAt(u++)<<8|a.charCodeAt(u++)<<16|a.charCodeAt(u++)<<24;for(e&=
3;e--;)p[u]=a.charCodeAt(u),++u;return new Blob([p],{type:d})}}}"use strict";
{const f=self.l;function g(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const h=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),m={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},v={dispatchUserScriptEvent:!0},K={dispatchRuntimeEvent:!0};function w(b){return new Promise((c,a)=>{const d=document.createElement("link");d.onload=()=>c(d);d.onerror=e=>a(e);d.rel=
"stylesheet";d.href=b;document.head.appendChild(d)})}function L(b){return new Promise((c,a)=>{const d=new Image;d.onload=()=>c(d);d.onerror=e=>a(e);d.src=b})}async function y(b){b=URL.createObjectURL(b);try{return await L(b)}finally{URL.revokeObjectURL(b)}}function F(b){return new Promise((c,a)=>{let d=new FileReader;d.onload=e=>c(e.target.result);d.onerror=e=>a(e);d.readAsText(b)})}async function C(b,c,a){if(!/firefox/i.test(navigator.userAgent))return await y(b);var d=await F(b);d=(new DOMParser).parseFromString(d,
"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const k=e.getAttribute("width"),p=e.getAttribute("height");if(!k.includes("%")&&!p.includes("%"))return await y(b)}e.setAttribute("width",c+"px");e.setAttribute("height",a+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await y(b)}function x(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const z=new Set(["input",
"textarea","datalist","select"]),E=new Set(["canvas","body","html"]);function t(b){E.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function G(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await y(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const c=b.getBoundingClientRect();document.body.removeChild(b);return[c.width,
c.height]}};self.C3_RasterSvgImageBlob=async function(b,c,a,d,e){b=await C(b,c,a);const k=document.createElement("canvas");k.width=d;k.height=e;k.getContext("2d").drawImage(b,0,0,c,a);return k};let A=!1;document.addEventListener("pause",()=>A=!0);document.addEventListener("resume",()=>A=!1);function H(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}f.R(class extends self.D{constructor(b){super(b,"runtime");this.Sa=!0;this.A=-1;this.za="any";this.Oa=this.Pa=!1;this.ua=
this.O=this.s=null;b.b("canvas","update-size",d=>this.Ob(d));b.b("runtime","invoke-download",d=>this.Eb(d));b.b("runtime","raster-svg-image",d=>this.Jb(d));b.b("runtime","get-svg-image-size",d=>this.Cb(d));b.b("runtime","set-target-orientation",d=>this.Nb(d));b.b("runtime","register-sw",()=>this.Kb());b.b("runtime","post-to-debugger",d=>this.Ka(d));b.b("runtime","go-to-script",d=>this.Ka(d));b.b("runtime","before-start-ticking",()=>this.ub());b.b("runtime","debug-highlight",d=>this.xb(d));b.b("runtime",
"enable-device-orientation",()=>this.gb());b.b("runtime","enable-device-motion",()=>this.fb());b.b("runtime","add-stylesheet",d=>this.tb(d));b.b("runtime","alert",d=>this.ia(d));b.b("runtime","hide-cordova-splash",()=>this.Db());const c=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;c.has(e.tagName.toLowerCase())||x(e)||d.preventDefault()});const a=b.g;window.addEventListener("selectstart",t);window.addEventListener("gesturehold",t);a.addEventListener("selectstart",
t);a.addEventListener("gesturehold",t);window.addEventListener("touchstart",t,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",t,{passive:!1}),a.addEventListener("pointerdown",t)):a.addEventListener("touchstart",t);this.N=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",G,{passive:!1});window.addEventListener("wheel",G,{passive:!1});window.addEventListener("resize",()=>this.Pb());window.addEventListener("fullscreenchange",
()=>this.G());window.addEventListener("webkitfullscreenchange",()=>this.G());window.addEventListener("mozfullscreenchange",()=>this.G());window.addEventListener("fullscreenerror",d=>this.ja(d));window.addEventListener("webkitfullscreenerror",d=>this.ja(d));window.addEventListener("mozfullscreenerror",d=>this.ja(d));b.ca()&&window.addEventListener("focusout",()=>{{const k=document.activeElement;if(k){var d=k.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(k.type.toLowerCase()||"text"):x(k)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>this.Qb(d);this.wa=new Set;this.Yb=new WeakSet;this.Wb=!1}ub(){"cordova"===this.f.a?(document.addEventListener("pause",()=>this.oa(!0)),document.addEventListener("resume",()=>this.oa(!1))):document.addEventListener("visibilitychange",()=>this.oa(document.hidden));return{isSuspended:!(!document.hidden&&!A)}}Ba(){window.addEventListener("focus",()=>
this.I("window-focus"));window.addEventListener("blur",()=>{this.I("window-blur",{parentHasFocus:H()});this.N=0});window.addEventListener("focusin",c=>{c=c.target;(z.has(c.tagName.toLowerCase())||x(c))&&this.I("keyboard-blur")});window.addEventListener("keydown",c=>this.Ja("keydown",c));window.addEventListener("keyup",c=>this.Ja("keyup",c));window.addEventListener("dblclick",c=>this.la("dblclick",c,m));window.addEventListener("wheel",c=>this.Gb(c));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
c=>{this.ga(c);this.H("pointerdown",c)}),this.f.j&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.O=new self.eb(()=>this.nb(),5),this.O.Ra=!0,window.addEventListener("pointerrawupdate",c=>this.Hb(c))):window.addEventListener("pointermove",c=>this.H("pointermove",c)),window.addEventListener("pointerup",c=>this.H("pointerup",c)),window.addEventListener("pointercancel",c=>this.H("pointercancel",c))):(window.addEventListener("mousedown",c=>{this.ga(c);this.ma("pointerdown",c)}),
window.addEventListener("mousemove",c=>this.ma("pointermove",c)),window.addEventListener("mouseup",c=>this.ma("pointerup",c)),window.addEventListener("touchstart",c=>{this.ga(c);this.S("pointerdown",c)}),window.addEventListener("touchmove",c=>this.S("pointermove",c)),window.addEventListener("touchend",c=>this.S("pointerup",c)),window.addEventListener("touchcancel",c=>this.S("pointercancel",c)));const b=()=>this.pa();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);
window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0)}I(b,c){r(this,b,c||null,K)}o(){return this.f.o()}m(){return this.f.m()}Pb(){const b=this.o(),c=this.m();this.I("window-resize",{innerWidth:b,innerHeight:c,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.F()});this.f.ca()&&(-1!==this.A&&clearTimeout(this.A),this.La(b,c,0))}Sb(b,c,a){-1!==this.A&&clearTimeout(this.A);this.A=setTimeout(()=>this.La(b,c,a),48)}La(b,c,a){const d=
this.o(),e=this.m();this.A=-1;d!=b||e!=c?this.I("window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.F()}):10>a&&this.Sb(d,e,a+1)}Nb(b){this.za=b.targetOrientation}Tb(){const b=this.za;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(c=>console.warn("[Construct 3] Failed to lock orientation: ",c));else try{let c=!1;screen.lockOrientation?c=screen.lockOrientation(b):screen.webkitLockOrientation?c=screen.webkitLockOrientation(b):
screen.mozLockOrientation?c=screen.mozLockOrientation(b):screen.msLockOrientation&&(c=screen.msLockOrientation(b));c||console.warn("[Construct 3] Failed to lock orientation")}catch(c){console.warn("[Construct 3] Failed to lock orientation: ",c)}}G(){const b=f.F();b&&"any"!==this.za&&this.Tb();r(this,"fullscreenchange",{isFullscreen:b,innerWidth:this.o(),innerHeight:this.m()})}ja(b){console.warn("[Construct 3] Fullscreen request failed: ",b);r(this,"fullscreenerror",{isFullscreen:f.F(),innerWidth:this.o(),
innerHeight:this.m()})}oa(b){b?this.f.ib():this.f.Na();r(this,"visibilitychange",{hidden:b})}Ja(b,c){"Backspace"===c.key&&t(c);const a=h.get(c.code)||c.code;B(this,b,{code:a,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},m)}Gb(b){r(this,"wheel",{clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,deltaX:b.deltaX,deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,timeStamp:b.timeStamp},m)}la(b,c,
a){g(c)||B(this,b,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,timeStamp:c.timeStamp},a)}ma(b,c){if(!g(c)){var a=this.N;"pointerdown"===b&&0!==a?b="pointermove":"pointerup"===b&&0!==c.buttons&&(b="pointermove");B(this,b,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:a,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},
m);this.N=c.buttons;this.la(c.type,c,v)}}H(b,c){if(this.O&&"pointermove"!==b){var a=this.O;a.K||(-1!==a.B&&(self.clearTimeout(a.B),a.B=-1),a.X=Date.now())}a=0;"mouse"===c.pointerType&&(a=this.N);B(this,b,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:a,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,
twist:c.twist||0,timeStamp:c.timeStamp},m);"mouse"===c.pointerType&&(a="mousemove","pointerdown"===b?a="mousedown":"pointerup"===b&&(a="mouseup"),this.la(a,c,v),this.N=c.buttons)}Hb(b){this.ua=b;b=this.O;if(-1===b.B){var c=Date.now(),a=c-b.X,d=b.Vb;a>=d&&b.Ra?(b.X=c,b.K=!0,b.Qa(),b.K=!1):b.B=self.setTimeout(b.$b,Math.max(d-a,4))}}nb(){this.H("pointermove",this.ua);this.ua=null}S(b,c){for(let a=0,d=c.changedTouches.length;a<d;++a){const e=c.changedTouches[a];B(this,b,{pointerId:e.identifier,pointerType:"touch",
button:0,buttons:0,lastButtons:0,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,width:2*(e.radiusX||e.webkitRadiusX||0),height:2*(e.radiusY||e.webkitRadiusY||0),pressure:e.force||e.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:e.rotationAngle||0,timeStamp:c.timeStamp},m)}}ga(b){window!==window.top&&window.focus();this.Ha(b.target)&&document.activeElement&&!this.Ha(document.activeElement)&&document.activeElement.blur()}Ha(b){return!b||b===document||b===window||b===document.body||
"canvas"===b.tagName.toLowerCase()}gb(){this.Pa||(this.Pa=!0,window.addEventListener("deviceorientation",b=>this.zb(b)),window.addEventListener("deviceorientationabsolute",b=>this.Ab(b)))}fb(){this.Oa||(this.Oa=!0,window.addEventListener("devicemotion",b=>this.yb(b)))}zb(b){r(this,"deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},m)}Ab(b){r(this,
"deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},m)}yb(b){let c=null;var a=b.acceleration;a&&(c={x:a.x||0,y:a.y||0,z:a.z||0});a=null;var d=b.accelerationIncludingGravity;d&&(a={x:d.x||0,y:d.y||0,z:d.z||0});d=null;const e=b.rotationRate;e&&(d={alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0});r(this,"devicemotion",{acceleration:c,accelerationIncludingGravity:a,rotationRate:d,interval:b.interval,timeStamp:b.timeStamp},m)}Ob(b){const c=
this.f.g;c.style.width=b.styleWidth+"px";c.style.height=b.styleHeight+"px";c.style.marginLeft=b.marginLeft+"px";c.style.marginTop=b.marginTop+"px";this.Sa&&(c.style.display="",this.Sa=!1)}Eb(b){const c=b.url;b=b.filename;const a=document.createElement("a"),d=document.body;a.textContent=b;a.href=c;a.download=b;d.appendChild(a);a.click();d.removeChild(a)}async Jb(b){var c=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);c=c?await createImageBitmap(b,
c):await createImageBitmap(b);return{imageBitmap:c,transferables:[c]}}async Cb(b){return await self.C3_GetSvgImageSize(b.blob)}async tb(b){await w(b.url)}pa(){var b=[...this.wa];this.wa.clear();if(!this.Wb)for(const c of b)(b=c.play())&&b.catch(()=>{this.Yb.has(c)||this.wa.add(c)})}Db(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}xb(b){if(b.show){this.s||(this.s=document.createElement("div"),this.s.id="inspectOutline",document.body.appendChild(this.s));var c=
this.s;c.style.display="";c.style.left=b.left-1+"px";c.style.top=b.top-1+"px";c.style.width=b.width+2+"px";c.style.height=b.height+2+"px";c.textContent=b.name}else this.s&&(this.s.style.display="none")}Kb(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ka(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}sb(b,c){return this.f.cb(this.J,{name:b,params:c})}ia(b){alert(b.message)}Qb(b){"entered-fullscreen"===b?(f.V(!0),this.G()):"exited-fullscreen"===b?(f.V(!1),this.G()):
console.warn("Unknown wrapper message: ",b)}})}"use strict";async function N(f){if(f.Ub)throw Error("already initialised");f.Ub=!0;var g=f.Z.fa("dispatchworker.js");f.sa=await f.Z.ba(g,f.c,{name:"DispatchWorker"});g=new MessageChannel;f.ta=g.port1;f.sa.postMessage({type:"_init","in-port":g.port2},[g.port2]);f.xa=await P(f)}function O(f){return[f.ta,f.xa]}
async function P(f){const g=f.Ta.length;var h=f.Z.fa("jobworker.js");h=await f.Z.ba(h,f.c,{name:"JobWorker"+g});const m=new MessageChannel,v=new MessageChannel;f.sa.postMessage({type:"_addJobWorker",port:m.port1},[m.port1]);h.postMessage({type:"init",number:g,"dispatch-port":m.port2,"output-port":v.port2},[m.port2,v.port2]);f.Ta.push(h);return v.port1}
self.bb=class{constructor(f){this.Z=f;this.c=f.c;this.c="preview"===f.a?this.c+"c3/workers/":this.c+f.$;this.Xb=Math.min(navigator.hardwareConcurrency||2,16);this.sa=null;this.Ta=[];this.xa=this.ta=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.l({jc:!1,kc:"workermain.js",C:["scripts/c3runtime.js"],Ya:[],Xa:"",fc:"scripts/",Aa:[],Wa:"html5"}));"use strict";
async function Q(f,g){g=g.type;let h=!0;0===g?h=await R():1===g&&(h=await S());r(f,"permission-result",{type:g,result:h})}async function R(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}
async function S(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}self.l.R(class extends self.D{constructor(f){super(f,"touch");I(this,"request-permission",g=>Q(this,g))}});"use strict";
function T(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(g=>r(f,"sw-message",g.data))}
function U(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(g=>console.warn("[Construct 3] Failed to lock orientation: ",g));else try{let g=!1;screen.lockOrientation?g=screen.lockOrientation(f):screen.webkitLockOrientation?g=screen.webkitLockOrientation(f):screen.mozLockOrientation?g=screen.mozLockOrientation(f):screen.msLockOrientation&&(g=screen.msLockOrientation(f));g||console.warn("[Construct 3] Failed to lock orientation")}catch(g){console.warn("[Construct 3] Failed to lock orientation: ",
g)}}
self.l.R(class extends self.D{constructor(f){super(f,"browser");this.a="";J(this,[["get-initial-state",g=>this.ka(g)],["ready-for-sw-messages",()=>T(this)],["alert",g=>this.ia(g)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",g=>this.na(g)],["vibrate",g=>{navigator.vibrate&&navigator.vibrate(g.pattern)}],["lock-orientation",g=>U(g)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(g){}}],["navigate",g=>{var h=g.type;if("back"===h)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===h)window.history.forward();else if("reload"===h)location.reload();else if("url"===
h){h=g.url;var m=g.target;g=g.exportType;"windows-uwp"===g&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(h)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(h,"_system"):"preview"===g||"windows-webview2"===g?window.open(h,"_blank"):this.pc||(2===m?window.top.location=h:1===m?window.parent.location=h:window.location=h)}else"new-window"===h&&(h=g.url,m=g.tag,"windows-uwp"===g.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(h)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(h,"_system"):window.open(h,m))}],["request-fullscreen",g=>{if("windows-webview2"===this.a||"macos-wkwebview"===this.a)self.l.V(!0),this.f.qa({type:"set-fullscreen",fullscreen:!0});else{const h={navigationUI:"auto"};g=g.navUI;1===g?h.navigationUI="hide":2===g&&(h.navigationUI="show");g=document.documentElement;g.requestFullscreen?g.requestFullscreen(h):g.mozRequestFullScreen?g.mozRequestFullScreen(h):g.msRequestFullscreen?g.msRequestFullscreen(h):
g.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):g.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.a||"macos-wkwebview"===this.a?(self.l.V(!1),this.f.qa({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&
document.webkitCancelFullScreen()}],["set-hash",g=>{location.hash=g.hash}]]);window.addEventListener("online",()=>{r(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{r(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{r(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{r(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",
g=>{g.handled=!0;r(this,"backbutton")})}ka(f){this.a=f.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}ia(f){alert(f.message)}na(f){f=f.isFocus;if("nwjs"===this.a){const g="nwjs"===this.a?nw.Window.get():
null;f?g.focus():g.blur()}else f?window.focus():window.blur()}});"use strict";async function V(f){if(!f.u)try{f.u=await navigator.wakeLock.request("screen"),f.u.addEventListener("release",()=>{console.log("[Construct 3] Screen wake lock released");f.u=null;r(f,"wake-lock-released")}),console.log("[Construct 3] Screen wake lock acquired"),r(f,"wake-lock-acquired")}catch(g){console.warn("[Construct 3] Failed to acquire screen wake lock: ",g),r(f,"wake-lock-error")}}
function W(){var f=document.body;const g=f.style;g.setProperty("--temp-sai-top","env(safe-area-inset-top)");g.setProperty("--temp-sai-right","env(safe-area-inset-right)");g.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");g.setProperty("--temp-sai-left","env(safe-area-inset-left)");f=getComputedStyle(f);f=[f.getPropertyValue("--temp-sai-top"),f.getPropertyValue("--temp-sai-right"),f.getPropertyValue("--temp-sai-bottom"),f.getPropertyValue("--temp-sai-left")].map(h=>{h=parseInt(h,10);
return isFinite(h)?h:0});g.removeProperty("--temp-sai-top");g.removeProperty("--temp-sai-right");g.removeProperty("--temp-sai-bottom");g.removeProperty("--temp-sai-left");return f}
self.l.R(class extends self.D{constructor(f){super(f,"platform-info");J(this,[["get-initial-state",()=>this.ka()],["request-wake-lock",()=>V(this)],["release-wake-lock",()=>{this.u&&(this.u.release(),this.u=null)}]]);window.addEventListener("resize",()=>{r(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:W()})});this.u=null}ka(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:W(),supportsWakeLock:!!navigator.wakeLock}}});
