'use strict';function t(n,m,h,p){n.g.Y(n.A,m,h,p,void 0)}function w(n,m,h,p){n.g.s?t(n,m,h,p):n.g.jb()._OnMessageFromDOM({type:"event",component:n.A,handler:m,dispatchOpts:p||null,data:h,responseId:null})}function A(n,m,h){n.g.a(n.A,m,h)}function B(n,m){for(const [h,p]of m)A(n,h,p)}window.I=class{constructor(n,m){this.g=n;this.A=m}sa(){}};
window.Ya=class{constructor(n,m){this.Ja=n;this.Pb=m;this.o=-1;this.S=-Infinity;this.Ub=()=>{this.o=-1;this.S=Date.now();this.B=!0;this.Ja();this.B=!1};this.Ka=this.B=!1}};"use strict";function C(n,m){A(n,"get-element",h=>{const p=n.h.get(h.elementId);return m(p,h)})}
window.fc=class extends self.I{constructor(n,m){super(n,m);this.h=new Map;this.ha=!0;B(this,[["create",()=>{throw Error("required override");}],["destroy",h=>{{h=h.elementId;const p=this.h.get(h);this.ha&&p.parentElement.removeChild(p);this.h.delete(h)}}],["set-visible",h=>{this.ha&&(this.h.get(h.elementId).style.display=h.isVisible?"":"none")}],["update-position",h=>{if(this.ha){var p=this.h.get(h.elementId);p.style.left=h.left+"px";p.style.top=h.top+"px";p.style.width=h.width+"px";p.style.height=
h.height+"px";h=h.fontSize;null!==h&&(p.style.fontSize=h+"em")}}],["update-state",h=>{this.h.get(h.elementId);throw Error("required override");}],["focus",h=>{{const p=this.h.get(h.elementId);h.focus?p.focus():p.blur()}}],["set-css-style",h=>{this.h.get(h.elementId).style[h.prop]=h.val}],["set-attribute",h=>{this.h.get(h.elementId).setAttribute(h.name,h.val)}],["remove-attribute",h=>{this.h.get(h.elementId).removeAttribute(h.name)}]]);C(this,h=>h)}};"use strict";
{var D=function(l){return g.has(l)},E=function(l){return new Promise((b,d)=>{const e=new FileReader;e.onload=k=>b(k.target.result);e.onerror=k=>d(k);e.readAsArrayBuffer(l)})},F=async function(l){l=await E(l);return(new TextDecoder("utf-8")).decode(l)},G=function(l){if(l.Xb){const b=document.createElement("script");b.async=!1;b.textContent=l.$b;document.head.appendChild(b)}else return new Promise((b,d)=>{const e=document.createElement("script");e.onload=b;e.onerror=d;e.async=!1;e.src=l;document.head.appendChild(e)})};
const n=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let m=new Audio;const h={"audio/webm; codecs=opus":!!m.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!m.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!m.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!m.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!m.canPlayType("audio/mp4"),"audio/mpeg":!!m.canPlayType("audio/mpeg")};m=null;const p=[];let u=0;window.RealFile=
window.File;const z=[],y=new Map,a=new Map;let c=0;const f=[];self.lc=function(l){if("function"!==typeof l)throw Error("runOnStartup called without a function");f.push(l)};const g=new Set(["cordova","playable-ad","instant-games"]);window.K=class l{constructor(b){this.s=b.bc;this.D=null;this.b="";this.pa=b.Zb;this.H={};this.la=this.Pa=null;this.R=[];this.C=this.c=this.oa=null;this.l=-1;this.Tb=()=>this.Cb();this.Na=[];this.f=b.Qa;D(this.f)&&this.s&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this.s=!1);this.Oa=!1;this.T=this.i=null;"html5"!==this.f&&"playable-ad"!==this.f||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.a("runtime","cordova-fetch-local-file",d=>this.qb(d));this.a("runtime","create-job-worker",()=>this.rb());"cordova"===this.f?document.addEventListener("deviceready",()=>this.Aa(b)):this.Aa(b)}va(){return n&&"cordova"===
this.f}J(){return n&&D(this.f)||navigator.standalone}async Aa(b){if("playable-ad"===this.f){this.i=self.c3_base64files;this.T={};await this.eb();for(let e=0,k=b.u.length;e<k;++e){var d=b.u[e].toLowerCase();this.T.hasOwnProperty(d)?b.u[e]={Xb:!0,$b:this.T[d]}:this.i.hasOwnProperty(d)&&(b.u[e]=URL.createObjectURL(this.i[d]))}}b.Vb?this.b=b.Vb:(d=location.origin,this.b=("null"===d?"file:///":d)+location.pathname,d=this.b.lastIndexOf("/"),-1!==d&&(this.b=this.b.substr(0,d+1)));if(b.dc)for(const [e,k]of Object.entries(b.dc))this.H[e]=
URL.createObjectURL(k);d=new MessageChannel;this.D=d.port1;this.D.onmessage=e=>this._OnMessageFromRuntime(e.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(e=>this.zb(e));this.C=new self.Wa(this);await this.C.Va();this.wa();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();await this.Mb();this.s?await this.lb(b,d.port2):await this.kb(b,d.port2)}$(b){return this.H.hasOwnProperty(b)?
this.H[b]:b.endsWith("/workermain.js")&&this.H.hasOwnProperty("workermain.js")?this.H["workermain.js"]:"playable-ad"===this.f&&this.i.hasOwnProperty(b.toLowerCase())?URL.createObjectURL(this.i[b.toLowerCase()]):b}async W(b,d,e){if(b.startsWith("blob:"))return new Worker(b,e);if(this.va()&&"file:"===location.protocol)return b=await this.ua(this.pa+b),new Worker(URL.createObjectURL(new Blob([b],{type:"application/javascript"})),e);b=new URL(b,d);if(location.origin!==b.origin){b=await fetch(b);if(!b.ok)throw Error("failed to fetch worker script");
b=await b.blob();return new Worker(URL.createObjectURL(b),e)}return new Worker(b,e)}wa(){if(this.J()){const b=document.documentElement.style,d=document.body.style,e=window.innerWidth<window.innerHeight,k=e?window.screen.width:window.screen.height;d.height=b.height=(e?window.screen.height:window.screen.width)+"px";d.width=b.width=k+"px"}}za(b){return{baseUrl:this.b,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:l.X(),projectData:b.kc,
previewImageBlobs:window.cr_previewImageBlobs||this.i,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:b.Qa,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.jc,jobScheduler:this.C.Ta(),supportedAudioFormats:h,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.pa+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.pa+"opus.wasm.wasm",isiOSCordova:this.va(),isiOSWebView:this.J(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async lb(b,d){var e=
this.$(b.cc);this.Pa=await this.W(e,this.b,{name:"Runtime"});this.c=document.createElement("canvas");this.c.style.display="none";e=this.c.transferControlToOffscreen();document.body.appendChild(this.c);window.c3canvas=this.c;this.Pa.postMessage(Object.assign(this.za(b),{type:"init-runtime",isInWorker:!0,messagePort:d,canvas:e,workerDependencyScripts:b.ra||[],engineScripts:b.u,projectScripts:window.ic,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[d,e,...this.C.Ua()]);this.R=z.map(k=>new k(this));
this.ya();self.c3_callFunction=(k,q)=>this.oa.mb(k,q);"preview"===this.f&&(self.goToLastErrorScript=()=>this.Y("runtime","go-to-last-error-script"))}async kb(b,d){this.c=document.createElement("canvas");this.c.style.display="none";document.body.appendChild(this.c);window.c3canvas=this.c;this.R=z.map(k=>new k(this));this.ya();const e=b.u.map(k=>"string"===typeof k?(new URL(k,this.b)).toString():k);Array.isArray(b.ra)&&e.unshift(...b.ra);await Promise.all(e.map(k=>G(k)));if(b.Ra&&0<b.Ra.length){const k=
self.C3_ProjectScriptsStatus;try{if(await Promise.all(b.Ra.map(q=>G(q[1]))),Object.values(k).some(q=>!q)){self.setTimeout(()=>this.Fa(k),100);return}}catch(q){console.error("[Preview] Error loading project scripts: ",q);self.setTimeout(()=>this.Fa(k),100);return}}"preview"===this.f&&"object"!==typeof self.ec.hc?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):
(b=Object.assign(this.za(b),{isInWorker:!1,messagePort:d,canvas:this.c,runOnStartupFunctions:f}),this.la=self.C3_CreateRuntime(b),await self.C3_InitRuntime(this.la,b))}Fa(b){b=`Failed to load project script '${Object.entries(b).filter(d=>!d[1]).map(d=>d[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+b);alert(b)}async rb(){const b=await this.C.xa();return{outputPort:b,transferables:[b]}}jb(){if(this.s)throw Error("not available in worker mode");return this.la}Y(b,
d,e,k,q){this.D.postMessage({type:"event",component:b,handler:d,dispatchOpts:k||null,data:e,responseId:null},this.Oa?void 0:q)}Xa(b,d){const e=c++,k=new Promise((q,v)=>{a.set(e,{resolve:q,reject:v})});this.D.postMessage({type:"event",component:b,handler:"js-invoke-function",dispatchOpts:null,data:d,responseId:e},void 0);return k}["_OnMessageFromRuntime"](b){const d=b.type;if("event"===d)return this.wb(b);if("result"===d)this.Fb(b);else if("runtime-ready"===d)this.Gb();else if("alert"===d)alert(b.message);
else throw Error(`unknown message '${d}'`);}wb(b){const d=b.component,e=b.handler,k=b.data,q=b.responseId;if(b=y.get(d))if(b=b.get(e)){var v=null;try{v=b(k)}catch(r){console.error(`Exception in '${d}' handler '${e}':`,r);null!==q&&this.O(q,!1,""+r);return}if(null===q)return v;v&&v.then?v.then(r=>this.O(q,!0,r)).catch(r=>{console.error(`Rejection from '${d}' handler '${e}':`,r);this.O(q,!1,""+r)}):this.O(q,!0,v)}else console.warn(`[DOM] No handler '${e}' for component '${d}'`);else console.warn(`[DOM] No event handlers for component '${d}'`)}O(b,
d,e){let k;e&&e.transferables&&(k=e.transferables);this.D.postMessage({type:"result",responseId:b,isOk:d,result:e},k)}Fb(b){const d=b.responseId,e=b.isOk;b=b.result;const k=a.get(d);e?k.resolve(b):k.reject(b);a.delete(d)}a(b,d,e){let k=y.get(b);k||(k=new Map,y.set(b,k));if(k.has(d))throw Error(`[DOM] Component '${b}' already has handler '${d}'`);k.set(d,e)}static V(b){if(z.includes(b))throw Error("DOM handler already added");z.push(b)}ya(){for(const b of this.R)if("runtime"===b.A){this.oa=b;return}throw Error("cannot find runtime DOM handler");
}zb(b){this.Y("debugger","message",b)}Gb(){for(const b of this.R)b.sa()}static X(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Ga(){-1===this.l&&this.Na.length&&(this.l=requestAnimationFrame(this.Tb))}bb(){-1!==this.l&&(cancelAnimationFrame(this.l),this.l=-1)}Cb(){this.l=-1;for(const b of this.Na)b();this.Ga()}ga(){this.oa.ga()}async qb(b){const d=b.filename;switch(b.as){case "text":return await this.Sa(d);case "buffer":return await this.ua(d);
default:throw Error("unsupported type");}}ta(b){const d=window.cordova.file.applicationDirectory+"www/"+b.toLowerCase();return new Promise((e,k)=>{window.resolveLocalFileSystemURL(d,q=>{q.file(e,k)},k)})}async Sa(b){b=await this.ta(b);return await F(b)}Z(){if(p.length&&!(8<=u)){u++;var b=p.shift();this.fb(b.filename,b.ac,b.Wb)}}ua(b){return new Promise((d,e)=>{p.push({filename:b,ac:k=>{u--;this.Z();d(k)},Wb:k=>{u--;this.Z();e(k)}});this.Z()})}async fb(b,d,e){try{const k=await this.ta(b),q=await E(k);
d(q)}catch(k){e(k)}}async eb(){const b=[];for(const [d,e]of Object.entries(this.i))b.push(this.cb(d,e));await Promise.all(b)}async cb(b,d){if("object"===typeof d)this.i[b]=new Blob([d.str],{type:d.type}),this.T[b]=d.str;else{let e=await this.ib(d);e||(e=this.gb(d));this.i[b]=e}}async ib(b){try{return await (await fetch(b)).blob()}catch(d){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
d),null}}gb(b){b=this.Kb(b);return this.ab(b.data,b.Yb)}Kb(b){var d=b.indexOf(",");if(0>d)throw new URIError("expected comma in data: uri");var e=b.substring(d+1);d=b.substring(5,d).split(";");b=d[0]||"";const k=d[2];e="base64"===d[1]||"base64"===k?atob(e):decodeURIComponent(e);return{Yb:b,data:e}}ab(b,d){var e=b.length;let k=e>>2,q=new Uint8Array(e),v=new Uint32Array(q.buffer,0,k),r,x;for(x=r=0;r<k;++r)v[r]=b.charCodeAt(x++)|b.charCodeAt(x++)<<8|b.charCodeAt(x++)<<16|b.charCodeAt(x++)<<24;for(e&=
3;e--;)q[x]=b.charCodeAt(x),++x;return new Blob([q],{type:d})}Mb(){let b=null;const d=new Promise(q=>b=q),e=new ArrayBuffer(1),k=new MessageChannel;k.port2.onmessage=q=>{q.data&&q.data.arrayBuffer||(this.Oa=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));b()};k.port1.postMessage({arrayBuffer:e},[e]);return d}}}"use strict";
{var J=function(){const a=document.activeElement;if(!a)return!1;const c=a.tagName.toLowerCase(),f=new Set("email number password search tel text url".split(" "));return"textarea"===c?!0:"input"===c?f.has(a.type.toLowerCase()||"text"):H(a)},L=function(){try{return window.parent&&window.parent.document.hasFocus()}catch(a){return!1}},M=function(a){(a.metaKey||a.ctrlKey)&&a.preventDefault()},N=function(a){z.has(a.target.tagName.toLowerCase())&&a.preventDefault()},H=function(a){do{if(a.parentNode&&a.hasAttribute("contenteditable"))return!0;
a=a.parentNode}while(a);return!1},Q=async function(a,c,f){if(!/firefox/i.test(navigator.userAgent))return await O(a);var g=await P(a);g=(new DOMParser).parseFromString(g,"image/svg+xml");const l=g.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const b=l.getAttribute("width"),d=l.getAttribute("height");if(!b.includes("%")&&!d.includes("%"))return await O(a)}l.setAttribute("width",c+"px");l.setAttribute("height",f+"px");g=(new XMLSerializer).serializeToString(g);a=new Blob([g],
{type:"image/svg+xml"});return await O(a)},P=function(a){return new Promise((c,f)=>{let g=new FileReader;g.onload=l=>c(l.target.result);g.onerror=l=>f(l);g.readAsText(a)})},O=async function(a){a=URL.createObjectURL(a);try{return await R(a)}finally{URL.revokeObjectURL(a)}},R=function(a){return new Promise((c,f)=>{const g=new Image;g.onload=()=>c(g);g.onerror=l=>f(l);g.src=a})},S=function(a){return new Promise((c,f)=>{const g=document.createElement("link");g.onload=()=>c(g);g.onerror=l=>f(l);g.rel=
"stylesheet";g.href=a;document.head.appendChild(g)})},T=function(a){return a.sourceCapabilities&&a.sourceCapabilities.firesTouchEvents||a.originalEvent&&a.originalEvent.sourceCapabilities&&a.originalEvent.sourceCapabilities.firesTouchEvents};const n=self.K,m=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),h={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},p={dispatchUserScriptEvent:!0},u={dispatchRuntimeEvent:!0},z=new Set(["canvas","body","html"]);self.C3_GetSvgImageSize=async function(a){a=
await O(a);if(0<a.width&&0<a.height)return[a.width,a.height];{a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.visibility="hidden";document.body.appendChild(a);const c=a.getBoundingClientRect();document.body.removeChild(a);return[c.width,c.height]}};self.C3_RasterSvgImageBlob=async function(a,c,f,g,l){a=await Q(a,c,f);const b=document.createElement("canvas");b.width=g;b.height=l;b.getContext("2d").drawImage(a,0,0,c,f);return b};let y=!1;document.addEventListener("pause",()=>
y=!0);document.addEventListener("resume",()=>y=!1);n.V(class extends self.I{constructor(a){super(a,"runtime");this.La=!0;this.m=-1;this.qa="any";this.Ha=this.Ia=!1;this.ka=this.G=this.j=null;a.a("canvas","update-size",g=>this.Ib(g));a.a("runtime","invoke-download",g=>this.yb(g));a.a("runtime","raster-svg-image",g=>this.Db(g));a.a("runtime","get-svg-image-size",g=>this.xb(g));a.a("runtime","set-target-orientation",g=>this.Hb(g));a.a("runtime","register-sw",()=>this.Eb());a.a("runtime","post-to-debugger",
g=>this.Da(g));a.a("runtime","go-to-script",g=>this.Da(g));a.a("runtime","before-start-ticking",()=>this.pb());a.a("runtime","debug-highlight",g=>this.sb(g));a.a("runtime","enable-device-orientation",()=>this.$a());a.a("runtime","enable-device-motion",()=>this.Za());a.a("runtime","add-stylesheet",g=>this.nb(g));a.a("runtime","alert",g=>this.ob(g));const c=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",g=>{const l=g.target;c.has(l.tagName.toLowerCase())||H(l)||g.preventDefault()});
const f=a.c;window.addEventListener("selectstart",N);window.addEventListener("gesturehold",N);f.addEventListener("selectstart",N);f.addEventListener("gesturehold",N);window.addEventListener("touchstart",N,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",N,{passive:!1}),f.addEventListener("pointerdown",N)):f.addEventListener("touchstart",N);this.F=0;window.addEventListener("mousedown",g=>{1===g.button&&g.preventDefault()});window.addEventListener("mousewheel",
M,{passive:!1});window.addEventListener("wheel",M,{passive:!1});window.addEventListener("resize",()=>this.Jb());a.J()&&window.addEventListener("focusout",()=>{J()||(document.scrollingElement.scrollTop=0)});this.ma=new Set;this.Sb=new WeakSet;this.Qb=!1}pb(){"cordova"===this.g.f?(document.addEventListener("pause",()=>this.fa(!0)),document.addEventListener("resume",()=>this.fa(!1))):document.addEventListener("visibilitychange",()=>this.fa(document.hidden));return{isSuspended:!(!document.hidden&&!y)}}sa(){window.addEventListener("focus",
()=>this.P("window-focus"));window.addEventListener("blur",()=>{this.P("window-blur",{parentHasFocus:L()});this.F=0});window.addEventListener("fullscreenchange",()=>this.ba());window.addEventListener("webkitfullscreenchange",()=>this.ba());window.addEventListener("mozfullscreenchange",()=>this.ba());window.addEventListener("fullscreenerror",c=>this.ca(c));window.addEventListener("webkitfullscreenerror",c=>this.ca(c));window.addEventListener("mozfullscreenerror",c=>this.ca(c));window.addEventListener("keydown",
c=>this.Ca("keydown",c));window.addEventListener("keyup",c=>this.Ca("keyup",c));window.addEventListener("dblclick",c=>this.da("dblclick",c,h));window.addEventListener("wheel",c=>this.Ab(c));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",c=>{this.aa(c);this.v("pointerdown",c)}),this.g.s&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.G=new self.Ya(()=>this.hb(),5),this.G.Ka=!0,window.addEventListener("pointerrawupdate",c=>this.Bb(c))):window.addEventListener("pointermove",
c=>this.v("pointermove",c)),window.addEventListener("pointerup",c=>this.v("pointerup",c)),window.addEventListener("pointercancel",c=>this.v("pointercancel",c))):(window.addEventListener("mousedown",c=>{this.aa(c);this.ea("pointerdown",c)}),window.addEventListener("mousemove",c=>this.ea("pointermove",c)),window.addEventListener("mouseup",c=>this.ea("pointerup",c)),window.addEventListener("touchstart",c=>{this.aa(c);this.N("pointerdown",c)}),window.addEventListener("touchmove",c=>this.N("pointermove",
c)),window.addEventListener("touchend",c=>this.N("pointerup",c)),window.addEventListener("touchcancel",c=>this.N("pointercancel",c)));const a=()=>this.ga();window.addEventListener("pointerup",a,!0);window.addEventListener("touchend",a,!0);window.addEventListener("click",a,!0);window.addEventListener("keydown",a,!0);window.addEventListener("gamepadconnected",a,!0)}P(a,c){t(this,a,c||null,u)}M(){return Math.max(window.innerWidth,1)}L(){return Math.max(window.innerHeight,1)}Jb(){const a=this.M(),c=this.L();
this.P("window-resize",{innerWidth:a,innerHeight:c,devicePixelRatio:window.devicePixelRatio});this.g.J()&&(-1!==this.m&&clearTimeout(this.m),this.Ea(a,c,0))}Lb(a,c,f){-1!==this.m&&clearTimeout(this.m);this.m=setTimeout(()=>this.Ea(a,c,f),48)}Ea(a,c,f){const g=this.M(),l=this.L();this.m=-1;g!=a||l!=c?this.P("window-resize",{innerWidth:g,innerHeight:l,devicePixelRatio:window.devicePixelRatio}):10>f&&this.Lb(g,l,f+1)}Hb(a){this.qa=a.targetOrientation}Nb(){const a=this.qa;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(a).catch(c=>
console.warn("[Construct 3] Failed to lock orientation: ",c));else try{let c=!1;screen.lockOrientation?c=screen.lockOrientation(a):screen.webkitLockOrientation?c=screen.webkitLockOrientation(a):screen.mozLockOrientation?c=screen.mozLockOrientation(a):screen.msLockOrientation&&(c=screen.msLockOrientation(a));c||console.warn("[Construct 3] Failed to lock orientation")}catch(c){console.warn("[Construct 3] Failed to lock orientation: ",c)}}ba(){const a=n.X();a&&"any"!==this.qa&&this.Nb();t(this,"fullscreenchange",
{isFullscreen:a,innerWidth:this.M(),innerHeight:this.L()})}ca(a){console.warn("[Construct 3] Fullscreen request failed: ",a);t(this,"fullscreenerror",{isFullscreen:n.X(),innerWidth:this.M(),innerHeight:this.L()})}fa(a){a?this.g.bb():this.g.Ga();t(this,"visibilitychange",{hidden:a})}Ca(a,c){"Backspace"===c.key&&N(c);const f=m.get(c.code)||c.code;w(this,a,{code:f,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},h)}Ab(a){t(this,
"wheel",{clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},h)}da(a,c,f){T(c)||w(this,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,timeStamp:c.timeStamp},f)}ea(a,c){if(!T(c)){var f=this.F;"pointerdown"===a&&0!==f?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");w(this,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,
lastButtons:f,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},h);this.F=c.buttons;this.da(c.type,c,p)}}v(a,c){if(this.G&&"pointermove"!==a){var f=this.G;f.B||(-1!==f.o&&(self.clearTimeout(f.o),f.o=-1),f.S=Date.now())}f=0;"mouse"===c.pointerType&&(f=this.F);w(this,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:f,clientX:c.clientX,clientY:c.clientY,
pageX:c.pageX,pageY:c.pageY,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},h);"mouse"===c.pointerType&&(f="mousemove","pointerdown"===a?f="mousedown":"pointerup"===a&&(f="pointerup"),this.da(f,c,p),this.F=c.buttons)}Bb(a){this.ka=a;a=this.G;if(-1===a.o){var c=Date.now(),f=c-a.S,g=a.Pb;f>=g&&a.Ka?(a.S=c,a.B=!0,a.Ja(),a.B=!1):a.o=self.setTimeout(a.Ub,Math.max(g-f,4))}}hb(){this.v("pointermove",
this.ka);this.ka=null}N(a,c){for(let f=0,g=c.changedTouches.length;f<g;++f){const l=c.changedTouches[f];w(this,a,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:c.timeStamp},h)}}aa(a){window!==window.top&&window.focus();
this.Ba(a.target)&&document.activeElement&&!this.Ba(document.activeElement)&&document.activeElement.blur()}Ba(a){return!a||a===document||a===window||a===document.body||"canvas"===a.tagName.toLowerCase()}$a(){this.Ia||(this.Ia=!0,window.addEventListener("deviceorientation",a=>this.ub(a)),window.addEventListener("deviceorientationabsolute",a=>this.vb(a)))}Za(){this.Ha||(this.Ha=!0,window.addEventListener("devicemotion",a=>this.tb(a)))}ub(a){t(this,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||
0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},h)}vb(a){t(this,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},h)}tb(a){let c=null;var f=a.acceleration;f&&(c={x:f.x||0,y:f.y||0,z:f.z||0});f=null;var g=a.accelerationIncludingGravity;g&&(f={x:g.x||0,y:g.y||0,z:g.z||0});g=null;const l=a.rotationRate;l&&(g={alpha:l.alpha||0,beta:l.beta||
0,gamma:l.gamma||0});t(this,"devicemotion",{acceleration:c,accelerationIncludingGravity:f,rotationRate:g,interval:a.interval,timeStamp:a.timeStamp},h)}Ib(a){const c=this.g,f=c.c;f.style.width=a.styleWidth+"px";f.style.height=a.styleHeight+"px";f.style.marginLeft=a.marginLeft+"px";f.style.marginTop=a.marginTop+"px";c.wa();this.La&&(f.style.display="",this.La=!1)}yb(a){const c=a.url;a=a.filename;const f=document.createElement("a"),g=document.body;f.textContent=a;f.href=c;f.download=a;g.appendChild(f);
f.click();g.removeChild(f)}async Db(a){var c=a.imageBitmapOpts;a=await self.C3_RasterSvgImageBlob(a.blob,a.imageWidth,a.imageHeight,a.surfaceWidth,a.surfaceHeight);c=c?await createImageBitmap(a,c):await createImageBitmap(a);return{imageBitmap:c,transferables:[c]}}async xb(a){return await self.C3_GetSvgImageSize(a.blob)}async nb(a){await S(a.url)}ga(){var a=[...this.ma];this.ma.clear();if(!this.Qb)for(const c of a)(a=c.play())&&a.catch(()=>{this.Sb.has(c)||this.ma.add(c)})}sb(a){if(a.show){this.j||
(this.j=document.createElement("div"),this.j.id="inspectOutline",document.body.appendChild(this.j));var c=this.j;c.style.display="";c.style.left=a.left-1+"px";c.style.top=a.top-1+"px";c.style.width=a.width+2+"px";c.style.height=a.height+2+"px";c.textContent=a.name}else this.j&&(this.j.style.display="none")}Eb(){window.C3_RegisterSW&&window.C3_RegisterSW()}Da(a){window.c3_postToMessagePort&&(a.from="runtime",window.c3_postToMessagePort(a))}mb(a,c){return this.g.Xa(this.A,{name:a,params:c})}ob(a){alert(a.message)}})}"use strict";
{const n=document.currentScript.src;self.Wa=class{constructor(m){this.U=m;this.b=n?n.substr(0,n.lastIndexOf("/")+1):m.b;this.Rb=Math.min(navigator.hardwareConcurrency||2,16);this.ia=null;this.Ma=[];this.na=this.ja=null}async Va(){if(this.Ob)throw Error("already initialised");this.Ob=!0;var m=this.U.$("dispatchworker.js");this.ia=await this.U.W(m,this.b,{name:"DispatchWorker"});m=new MessageChannel;this.ja=m.port1;this.ia.postMessage({type:"_init","in-port":m.port2},[m.port2]);this.na=await this.xa()}async xa(){const m=
this.Ma.length;var h=this.U.$("jobworker.js");h=await this.U.W(h,this.b,{name:"JobWorker"+m});const p=new MessageChannel,u=new MessageChannel;this.ia.postMessage({type:"_addJobWorker",port:p.port1},[p.port1]);h.postMessage({type:"init",number:m,"dispatch-port":p.port2,"output-port":u.port2},[p.port2,u.port2]);this.Ma.push(h);return u.port1}Ta(){return{inputPort:this.ja,outputPort:this.na,maxNumWorkers:this.Rb}}Ua(){return[this.ja,this.na]}}}"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.K({bc:"undefined"!==typeof OffscreenCanvas,cc:"workermain.js",u:["scripts/c3runtime.js"],Zb:"scripts/",ra:[],Qa:"html5"}));"use strict";async function U(n,m){m=m.type;let h=!0;0===m?h=await V():1===m&&(h=await W());t(n,"permission-result",{type:m,result:h})}
async function V(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(n){return console.warn("[Touch] Failed to request orientation permission: ",n),!1}}
async function W(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(n){return console.warn("[Touch] Failed to request motion permission: ",n),!1}}self.K.V(class extends self.I{constructor(n){super(n,"touch");A(this,"request-permission",m=>U(this,m))}});"use strict";self.K.V(class extends self.I{constructor(n){super(n,"mouse");A(this,"cursor",m=>{document.documentElement.style.cursor=m})}});