function k(b,a,c,d){b.i.$(b.S,a,c,d)}function p(b,a,c,d){b.i.o?k(b,a,c,d):b.i.vb()._OnMessageFromDOM({type:"event",component:b.S,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.i.h(b.S,a,c)}function r(b,a){for(const [c,d]of a)q(b,c,d)}window.O=class{constructor(b,a){this.i=b;this.S=a;this.Za=!1;this.Pb=()=>this.Ka()}Ha(){}Ka(){}};window.dc=class{constructor(){}};"use strict";function aa(b,a){q(b,"get-element",c=>{const d=t(b,c.elementId);return a(d,c)})}
function t(b,a){b=b.ea.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Ua}
window.cc=class extends self.O{constructor(b,a){super(b,a);this.ea=new Map;this.ta=!0;r(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=t(this,c);this.ta&&d.parentElement.removeChild(d);this.ea.delete(c)}],["set-visible",c=>{if(this.ta){var d=this.ea.get(c.elementId),e=d.Ua;d.Ya?e.style.display=c.isVisible?"":"none":d.Lb=!!c.isVisible}}],["update-position",c=>{if(this.ta){var d=this.ea.get(c.elementId),e=d.Ua;e.style.left=c.left+"px";e.style.top=c.top+
"px";e.style.width=c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.Ya||(d.Ya=!0,d.Lb&&(e.style.display=""))}}],["update-state",c=>{t(this,c.elementId);throw Error("required override");}],["focus",c=>this.qa(c)],["set-css-style",c=>{const d=t(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{t(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{t(this,c.elementId).removeAttribute(c.name)}]]);
aa(this,c=>c)}qa(b){var a=t(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const u=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),v=/android/i.test(navigator.userAgent),ba=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let w=0;
function x(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Tb?new Promise(c=>{const d="c3_resolve_"+w;++w;self[d]=c;a.textContent=b.Xb+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let y=!1,z=!1;function ca(){if(!y){try{new Worker("blob://",{get type(){z=!0}})}catch(b){}y=!0}return z}let A=new Audio;
const da={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ea(b){b=await fa(b);return(new TextDecoder("utf-8")).decode(b)}
function fa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const B=[];let C=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let ha=0;const ia=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ia.push(b)};const ja=new Set(["cordova","playable-ad","instant-games"]);let ka=!1;
window.D=class b{constructor(a){this.o=a.Zb;this.V=null;this.m="";this.K=a.Wb;this.Y={};this.Aa=this.M=null;this.da=[];this.j=this.H=null;this.$a=!1;this.T=null;this.J=-1;this.Ob=()=>this.Db();this.Da=[];this.Fa=null;this.eb=[];this.g=a.fb;this.xa="file"===location.protocol.substr(0,4);!this.o||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ca()||(this.o=!1);this.o&&ba&&(this.o=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.o=!1;if("cordova"===this.g&&this.o)if(v){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.o=!1)}else this.o=!1;this.B()?self.chrome.webview.addEventListener("message",c=>this.Qa(c.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=c=>this.Qa(c));this.fa=this.A=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime",
"cordova-fetch-local-file",c=>this.zb(c));this.h("runtime","create-job-worker",()=>this.Ab());this.h("runtime","send-wrapper-extension-message",c=>this.Gb(c));"cordova"===this.g?document.addEventListener("deviceready",()=>this.Oa(a)):this.Oa(a)}kb(){return u&&"cordova"===this.g}ma(){const a=navigator.userAgent;return u&&ja.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ib(){return v}Ja(){return v&&ja.has(this.g)}B(){return"windows-webview2"===this.g||!!("preview"===this.g&&
window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async Oa(a){"macos-wkwebview"===this.g?this.F({type:"ready"}):this.B()&&(this.Ib(),this.eb=(await this.yb()).registeredComponentIds);if("playable-ad"===this.g){this.A=self.c3_base64files;this.fa={};await this.rb();for(let d=0,e=a.N.length;d<e;++d){var c=a.N[d];this.fa.hasOwnProperty(c)?a.N[d]={Tb:!0,Xb:this.fa[c]}:this.A.hasOwnProperty(c)&&(a.N[d]=URL.createObjectURL(this.A[c]))}a.ja=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=
0;this.La(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Vb?this.m=a.Vb:(c=location.origin,this.m=("null"===c?"file:///":c)+location.pathname,c=this.m.lastIndexOf("/"),-1!==c&&(this.m=this.m.substr(0,c+1)));a.ac&&(this.Y=a.ac);c=new MessageChannel;this.V=c.port1;this.V.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Cb(d));this.T=new self.lb(this);await la(this.T);"object"===typeof window.StatusBar&&window.StatusBar.hide();
if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.o?await this.xb(a,c.port2):await this.wb(a,c.port2)}oa(a){a=this.Y.hasOwnProperty(a)?this.Y[a]:a.endsWith("/workermain.js")&&this.Y.hasOwnProperty("workermain.js")?this.Y["workermain.js"]:"playable-ad"===this.g&&this.A.hasOwnProperty(a)?this.A[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async la(a,
c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.xa)return a=await this.ka(d.Sb?a:this.K+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}v(){return Math.max(window.innerWidth,1)}u(){return Math.max(window.innerHeight,1)}Na(a){var c=
this.m,d=location.href,e=this.v(),f=this.u(),g=window.devicePixelRatio,h=b.P(),l=a.ic,m=window.cr_previewImageBlobs||this.A,n=window.cr_previewProjectFileBlobs,ya=window.cr_previewProjectFiles,za=window.cr_swClientId||"";a=a.fb;var Aa=(new URLSearchParams(self.location.search)).has("debug"),K=this.T;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:l,previewImageBlobs:m,previewProjectFileBlobs:n,previewProjectFileSWUrls:ya,swClientId:za,
exportType:a,isDebug:Aa,ife:!!self.hc,jobScheduler:{inputPort:K.wa,outputPort:K.Ca,maxNumWorkers:K.Mb},supportedAudioFormats:da,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.K+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.K+"opus.wasm.wasm",isFileProtocol:this.xa,isiOSCordova:this.kb(),isiOSWebView:this.ma(),isWebView2Wrapper:this.B(),wrapperComponentIds:this.eb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async xb(a,c){const d=this.oa(a.$b);"preview"===this.g?
(this.M=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,l)=>{const m=n=>{this.M.removeEventListener("message",m);n.data&&"ok"===n.data.type?h():l()};this.M.addEventListener("message",m);this.M.postMessage({type:"construct-worker-init","import":(new URL(d,this.m)).toString()})})):this.M=await this.la(d,this.m,{type:"module",name:"Runtime",Sb:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);
window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.ja||[],g=a.N;f=await Promise.all(f.map(h=>this.I(h)));g=await Promise.all(g.map(h=>this.I(h)));if("cordova"===this.g)for(let h=0,l=a.ia.length;h<l;++h){const m=a.ia[h],n=m[0];if(n===a.Ga||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m[1]=await this.I(n)}this.M.postMessage(Object.assign(this.Na(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,
projectScripts:a.ia,mainProjectScript:a.Ga,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ma(this.T)]);this.da=E.map(h=>new h(this));this.Ma();na(this.H);self.c3_callFunction=(h,l)=>{var m=this.H;return m.i.mb(m.S,{name:h,params:l})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.$("runtime","go-to-last-error-script"))}async wb(a,c){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&
self.C3_InsertHTMLPlaceholders();this.da=E.map(g=>new g(this));this.Ma();var d=a.N.map(g=>"string"===typeof g?(new URL(g,this.m)).toString():g);if(Array.isArray(a.ja)){var e=[...a.ja].map(g=>g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.I(g)));await Promise.all(d.map(g=>x(g)));d=self.C3_ProjectScriptsStatus;e=a.Ga;const f=a.ia;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.I(h),await x(h),"preview"!==this.g||d[g]||this.Ra(g,"main script did not run to completion")}catch(l){this.Ra(g,
l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.I(h),await x(h);"preview"===this.g&&"object"!==typeof self.bc.ec?(this.ba(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Na(a),{isInWorker:!1,messagePort:c,canvas:this.j,runOnStartupFunctions:ia}),na(this.H),
this.Pa(),this.Aa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Aa,a))}Ra(a,c){this.ba();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Pa(){this.ba()}ba(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ab(){const a=await oa(this.T);return{outputPort:a,
transferables:[a]}}vb(){if(this.o)throw Error("not available in worker mode");return this.Aa}$(a,c,d,e){this.V.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},void 0)}mb(a,c){const d=ha++,e=new Promise((f,g)=>{G.set(d,{resolve:f,reject:g})});this.V.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Bb(a);if("result"===
c)this.Eb(a);else if("runtime-ready"===c)this.Fb();else if("alert-error"===c)this.ba(),alert(a.message);else if("creating-runtime"===c)this.Pa();else throw Error(`unknown message '${c}'`);}Bb(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.aa(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.aa(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,
h);this.aa(f,!1,""+h)}):this.aa(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}aa(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.V.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Eb(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}h(a,c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);
e.set(c,d)}static Z(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Ma(){for(const a of this.da)if("runtime"===a.S){this.H=a;return}throw Error("cannot find runtime DOM handler");}Cb(a){this.$("debugger","message",a)}Fb(){for(const a of this.da)a.Ha()}static P(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ka)}static ca(a){ka=!!a}La(a){this.Da.push(a);this.sa()}sa(){-1===this.J&&this.Da.length&&(this.J=requestAnimationFrame(this.Ob))}pb(){-1!==
this.J&&(cancelAnimationFrame(this.J),this.J=-1)}Db(){this.J=-1;for(const a of this.Da)a();this.sa()}ra(){this.H.ra()}nb(){this.$a=!0}hb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}jb(a){return!this.hb(a)}async I(a){return"cordova"===this.g&&(a.startsWith("file:")||this.xa&&this.jb(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.ka(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async zb(a){const c=a.filename;
switch(a.as){case "text":return await this.gb(c);case "buffer":return await this.ka(c);default:throw Error("unsupported type");}}Ia(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async gb(a){a=await this.Ia(a);return await ea(a)}na(){if(B.length&&!(8<=C)){C++;var a=B.shift();this.sb(a.filename,a.Yb,a.Rb)}}ka(a){return new Promise((c,d)=>{B.push({filename:a,Yb:e=>{C--;this.na();c(e)},Rb:e=>{C--;this.na();
d(e)}});this.na()})}async sb(a,c,d){try{const e=await this.Ia(a),f=await fa(e);c(f)}catch(e){d(e)}}Qa(a){if("entered-fullscreen"===a)b.ca(!0),H(this.H);else if("exited-fullscreen"===a)b.ca(!1),H(this.H);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.Fa(a),this.Fa=null):"extension-message"===c?this.$("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Gb(a){this.F({type:"extension-message",
componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}F(a){this.B()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Ib(){window.moveTo=(a,c)=>{this.F({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.F({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}yb(){return this.B()?new Promise(a=>
{this.Fa=a;this.F({type:"wrapper-init"})}):Promise.resolve()}async rb(){const a=[];for(const [c,d]of Object.entries(this.A))a.push(this.qb(c,d));await Promise.all(a)}async qb(a,c){if("object"===typeof c)this.A[a]=new Blob([c.str],{type:c.type}),this.fa[a]=c.str;else{let d=await this.ub(c);d||(d=this.tb(c));this.A[a]=d}}async ub(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}tb(a){a=this.Hb(a);return this.ob(a.data,a.Ub)}Hb(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Ub:a,data:d}}ob(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,l;for(l=h=0;h<e;++h)g[h]=a.charCodeAt(l++)|a.charCodeAt(l++)<<8|a.charCodeAt(l++)<<16|a.charCodeAt(l++)<<24;for(d&=
3;d--;)f[l]=a.charCodeAt(l),++l;return new Blob([f],{type:c})}};"use strict";const I=self.D;function pa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const qa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},ra={dispatchUserScriptEvent:!0},L={dispatchRuntimeEvent:!0};
function sa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function ta(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function M(b){b=URL.createObjectURL(b);try{return await ta(b)}finally{URL.revokeObjectURL(b)}}
function ua(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function va(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await M(b);var d=await ua(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await M(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await M(b)}
function N(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const wa=new Set(["input","textarea","datalist","select"]),xa=new Set(["canvas","body","html"]);function P(b){b.target.tagName&&xa.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ba(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await M(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await va(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Q=!1;document.addEventListener("pause",()=>Q=!0);document.addEventListener("resume",()=>Q=!1);function na(b){b.Wa=!0;b.za=b.i.v();b.U=b.i.u()}function H(b){if(!b.l){var a=I.P();a&&"any"!==b.Ea&&Ca(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.v(),innerHeight:b.u()})}}async function Da(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ea(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Fa(b){return await self.C3_GetSvgImageSize(b.blob)}function Ga(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ha(b){self.setTimeout(()=>{b.Va=!0},1E3);"cordova"===b.i.g?(document.addEventListener("pause",()=>R(b,!0)),document.addEventListener("resume",()=>R(b,!1))):document.addEventListener("visibilitychange",()=>R(b,"hidden"===document.visibilityState));b.ga=!("hidden"!==document.visibilityState&&!Q);return{isSuspended:b.ga}}
function Ia(b){b.Ta||(b.Ta=!0,window.addEventListener("deviceorientation",a=>{b.l||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Ja(b){b.Sa||(b.Sa=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Ka(b){await sa(b.url)}
function La(b,a){b.Xa=a.message;-1===b.va&&(b.va=setTimeout(()=>{b.va=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Xa)},250))}function S(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:I.P(),innerWidth:b.v(),innerHeight:b.u()})}function R(b,a){b.ga!==a&&((b.ga=a)?b.i.pb():b.i.sa(),k(b,"visibilitychange",{hidden:a}))}
function Ma(b,a,c){"Backspace"===c.key&&P(c);if(!b.l){var d=qa.get(c.code)||c.code;p(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J)}}function T(b,a,c,d){b.l||pa(c)||p(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function U(b){window!==window.top&&window.focus();Na(b.target)&&document.activeElement&&!Na(document.activeElement)&&document.activeElement.blur()}
function V(b,a,c){if(!b.l){var d=0;"mouse"===c.pointerType&&(d=b.W);p(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&(d="mousemove",
"pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),T(b,d,c,ra),b.W=c.buttons)}}
function W(b,a,c){if(!b.l&&!pa(c)){var d=b.W;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");p(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},J);b.W=c.buttons;T(b,c.type,c,ra)}}
function X(b,a,c){if(!b.l)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];p(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.s,pageX:f.pageX,pageY:f.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
J)}}function Y(b,a,c){document.body.style.transform="";b.s=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.s=a))}}function Oa(b,a,c,d){const e=b.v(),f=b.u();b.L=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.P()}):10>d&&Pa(b,e,f,d+1)}
function Pa(b,a,c,d){-1!==b.L&&clearTimeout(b.L);b.L=setTimeout(()=>Oa(b,a,c,d),48)}
function Ca(b){b=b.Ea;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Na(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.Z(class extends self.O{constructor(b){super(b,"runtime");this.ab=!0;this.Wa=!1;this.L=-1;this.Ea="any";this.ga=this.Sa=this.Ta=!1;this.ha=document.createElement("div");this.ha.className="c3-screen-reader-text";this.ha.setAttribute("aria-live","polite");document.body.appendChild(this.ha);this.G=null;this.l=!1;this.Xa="";this.va=-1;this.Va=!1;this.za=b.v();this.U=b.u();this.s=this.X=0;b.h("canvas","update-size",d=>{var e=this.i;e.$a||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.ab&&(e.style.display="",this.ab=!1))});b.h("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.h("runtime","load-webfonts",d=>Da(d));b.h("runtime","raster-svg-image",d=>Ea(d));b.h("runtime","get-svg-image-size",
d=>Fa(d));b.h("runtime","set-target-orientation",d=>{this.Ea=d.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime","post-to-debugger",d=>Ga(d));b.h("runtime","go-to-script",d=>Ga(d));b.h("runtime","before-start-ticking",()=>Ha(this));b.h("runtime","debug-highlight",d=>{if(d.show){this.G||(this.G=document.createElement("div"),this.G.id="inspectOutline",document.body.appendChild(this.G));var e=this.G;e.style.display="";e.style.left=d.left-
1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.G&&(this.G.style.display="none")});b.h("runtime","enable-device-orientation",()=>Ia(this));b.h("runtime","enable-device-motion",()=>Ja(this));b.h("runtime","add-stylesheet",d=>Ka(d));b.h("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.h("runtime","alert",d=>this.pa(d));b.h("runtime","screen-reader-text",
d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ha.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});b.h("runtime","hide-cordova-splash",
()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",d=>{this.l=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.nb()});b.h("runtime","export-to-video-progress",d=>La(this,d));b.h("runtime","exported-to-video",d=>{window.Qb({type:"exported-video",arrayBuffer:d.arrayBuffer,contentType:d.contentType,
time:d.time})});b.h("runtime","exported-to-image-sequence",d=>{window.Qb({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||N(e)||d.preventDefault()});const c=b.j;window.addEventListener("selectstart",P);window.addEventListener("gesturehold",P);c.addEventListener("selectstart",P);c.addEventListener("gesturehold",P);window.addEventListener("touchstart",
P,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",P,{passive:!1}),c.addEventListener("pointerdown",P)):c.addEventListener("touchstart",P);this.W=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ba,{passive:!1});window.addEventListener("wheel",Ba,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.Wa){var d=this.v();var e=this.u();if(this.i.Ja()){if(this.Va){if(this.za===d&&e<
this.U){this.X=this.U-e;Y(this,this.U,this.X);d=void 0;break a}0<this.X&&(this.X=0,Y(this,e,this.X))}this.za=d;this.U=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.P()});this.i.ma()&&(-1!==this.L&&clearTimeout(this.L),Oa(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",()=>H(this));window.addEventListener("fullscreenerror",
d=>S(this,d));window.addEventListener("webkitfullscreenerror",d=>S(this,d));window.addEventListener("mozfullscreenerror",d=>S(this,d));if(b.ma())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):N(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Ba=new Set;this.Nb=new WeakSet;this.Kb=!1}Ha(){window.addEventListener("focus",()=>{k(this,"window-focus",null,L)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},L);this.W=0});window.addEventListener("focusin",a=>{a=a.target;(wa.has(a.tagName.toLowerCase())||N(a))&&
k(this,"keyboard-blur",null,L)});window.addEventListener("keydown",a=>Ma(this,"keydown",a));window.addEventListener("keyup",a=>Ma(this,"keyup",a));window.addEventListener("dblclick",a=>T(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.l||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.s,pageX:a.pageX,pageY:a.pageY+this.s,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{U(a);V(this,"pointerdown",a)}),this.i.o&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{V(this,"pointermove",a)}):window.addEventListener("pointermove",a=>V(this,"pointermove",a)),window.addEventListener("pointerup",a=>V(this,"pointerup",a)),window.addEventListener("pointercancel",a=>V(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{U(a);W(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>W(this,"pointermove",
a)),window.addEventListener("mouseup",a=>W(this,"pointerup",a)),window.addEventListener("touchstart",a=>{U(a);X(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>X(this,"pointermove",a)),window.addEventListener("touchend",a=>X(this,"pointerup",a)),window.addEventListener("touchcancel",a=>X(this,"pointercancel",a)));const b=()=>this.ra();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.ib()&&!this.i.Ja()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Y(this,this.u(),navigator.virtualKeyboard.boundingRect.height)}))}v(){return this.i.v()}u(){return this.i.u()}ra(){var b=[...this.Ba];this.Ba.clear();if(!this.Kb)for(const a of b)(b=a.play())&&b.catch(()=>{this.Nb.has(a)||this.Ba.add(a)})}pa(b){alert(b.message)}});"use strict";
async function la(b){if(b.Jb)throw Error("already initialised");b.Jb=!0;var a=b.C.oa(("playable-ad"===b.C.g?b.C.K:"")+"dispatchworker.js");b.ua=await b.C.la(a,b.R,{name:"DispatchWorker"});a=new MessageChannel;b.wa=a.port1;b.ua.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Ca=await oa(b)}function ma(b){return[b.wa,b.Ca]}
async function oa(b){const a=b.cb.length;var c=b.C.oa(("playable-ad"===b.C.g?b.C.K:"")+"jobworker.js");c=await b.C.la(c,b.R,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.ua.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.cb.push(c);return e.port1}
self.lb=class{constructor(b){this.C=b;this.R=b.m;this.R="preview"===b.g?this.R+"workers/":this.R+b.K;this.Mb=Math.min(navigator.hardwareConcurrency||2,16);this.ua=null;this.cb=[];this.Ca=this.wa=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.D({Zb:!0,$b:"workermain.js",N:["scripts/c3runtime.js"],ia:[],Ga:"",Wb:"scripts/",ja:[],fb:"html5"}));"use strict";
async function Qa(b,a){a=a.type;let c=!0;0===a?c=await Ra():1===a&&(c=await Sa());k(b,"permission-result",{type:a,result:c})}async function Ra(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Sa(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.D.Z(class extends self.O{constructor(b){super(b,"touch");q(this,"request-permission",a=>Qa(this,a))}});"use strict";function Ta(){}
function Ua(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Va(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.D.Z(class extends self.O{constructor(b){super(b,"browser");this.g="";r(this,[["get-initial-state",a=>{this.g=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>Ua(this)],
["alert",a=>this.pa(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.qa(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Va(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===
a||this.i.B()?window.open(c,"_blank"):this.fc||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.i.B()||"macos-wkwebview"===this.g)self.D.ca(!0),this.i.F({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");
a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Ta)}}],["exit-fullscreen",()=>{if(this.i.B()||"macos-wkwebview"===this.g)self.D.ca(!1),this.i.F({type:"set-fullscreen",fullscreen:!1});
else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Ta)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);
f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{k(this,"online-state",
{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}pa(b){alert(b.message)}qa(b){b=b.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";let Wa=!1;
async function Xa(b){var a=Ya(b.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:b.duration,startDelay:0,weakMagnitude:b.weakMag,strongMagnitude:b.strongMag})}catch(c){console.warn("[Gamepad] Failed to vibrate gamepad: ",c)}}function Z(){try{return Array.from(navigator.getGamepads()).filter(b=>b&&b.connected)}catch(b){return Wa||(console.warn("[Construct] Failed to access gamepads: ",b),Wa=!0),[]}}
function Ya(b){for(const a of Z())if(a.index===b)return a;return null}
self.D.Z(class extends self.O{constructor(b){super(b,"gamepad");this.bb=!!navigator.getGamepads;this.ya=!1;q(this,"is-supported",()=>this.bb);q(this,"ready",()=>{this.ya=!0;for(const a of Z())k(this,"gamepad-connected",{index:a.index,id:a.id});this.bb&&!this.Za&&(this.i.La(this.Pb),this.Za=!0)});q(this,"vibrate",a=>Xa(a));q(this,"reset-vibrate",a=>{(a=Ya(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});window.addEventListener("gamepadconnected",a=>{this.ya&&(a=a.gamepad,k(this,"gamepad-connected",
{index:a.index,id:a.id}))});window.addEventListener("gamepaddisconnected",a=>{this.ya&&k(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of Z()){const c=a.vibrationActuator;c&&c.reset&&c.reset()}})}Ka(){var b=Z();b.length&&(b=b.map(a=>({index:a.index,id:a.id,buttons:a.buttons.map(c=>({pressed:c.pressed,value:c.value})),axes:a.axes})),k(this,"input-update",b))}});
