function k(b,a,c,d){b.i.aa(b.T,a,c,d)}function p(b,a,c,d){b.i.o?k(b,a,c,d):b.i.tb()._OnMessageFromDOM({type:"event",component:b.T,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.i.h(b.T,a,c)}function r(b,a){for(const [c,d]of a)q(b,c,d)}window.P=class{constructor(b,a){this.i=b;this.T=a}Ia(){}};window.ac=class{constructor(){}};"use strict";function aa(b,a){q(b,"get-element",c=>{const d=t(b,c.elementId);return a(d,c)})}
function t(b,a){b=b.fa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Ta}
window.$b=class extends self.P{constructor(b,a){super(b,a);this.fa=new Map;this.va=!0;r(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=t(this,c);this.va&&d.parentElement.removeChild(d);this.fa.delete(c)}],["set-visible",c=>{if(this.va){var d=this.fa.get(c.elementId),e=d.Ta;d.Xa?e.style.display=c.isVisible?"":"none":d.Jb=!!c.isVisible}}],["update-position",c=>{if(this.va){var d=this.fa.get(c.elementId),e=d.Ta;e.style.left=c.left+"px";e.style.top=c.top+
"px";e.style.width=c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.Xa||(d.Xa=!0,d.Jb&&(e.style.display=""))}}],["update-state",c=>{t(this,c.elementId);throw Error("required override");}],["focus",c=>this.sa(c)],["set-css-style",c=>{const d=t(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{t(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{t(this,c.elementId).removeAttribute(c.name)}]]);
aa(this,c=>c)}sa(b){var a=t(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const u=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),v=/android/i.test(navigator.userAgent),ba=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let w=0;
function x(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Qb?new Promise(c=>{const d="c3_resolve_"+w;++w;self[d]=c;a.textContent=b.Ub+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let y=!1,z=!1;function ca(){if(!y){try{new Worker("blob://",{get type(){z=!0}})}catch(b){}y=!0}return z}let A=new Audio;
const da={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ea(b){b=await B(b);return(new TextDecoder("utf-8")).decode(b)}
function B(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const C=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,H=new Map;let fa=0;const ha=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ha.push(b)};const ia=new Set(["cordova","playable-ad","instant-games"]);let ja=!1;
window.D=class b{constructor(a){this.o=a.Wb;this.W=null;this.m="";this.L=a.Tb;this.Z={};this.Ba=this.N=null;this.ea=[];this.j=this.H=null;this.Ya=!1;this.U=null;this.K=-1;this.Mb=()=>this.Bb();this.Ea=[];this.Ga=null;this.ab=[];this.g=a.bb;this.za="file"===location.protocol.substr(0,4);!this.o||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ca()||(this.o=!1);this.o&&ba&&(this.o=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.o=!1;if("cordova"===this.g&&this.o)if(v){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.o=!1)}else this.o=!1;this.B()?self.chrome.webview.addEventListener("message",c=>this.Pa(c.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=c=>this.Pa(c));this.ga=this.A=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime",
"cordova-fetch-local-file",c=>this.xb(c));this.h("runtime","create-job-worker",()=>this.yb());this.h("runtime","send-wrapper-extension-message",c=>this.Eb(c));"cordova"===this.g?document.addEventListener("deviceready",()=>this.Na(a)):this.Na(a)}hb(){return u&&"cordova"===this.g}na(){const a=navigator.userAgent;return u&&ia.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}fb(){return v}Ka(){return v&&ia.has(this.g)}B(){return"windows-webview2"===this.g||!!("preview"===this.g&&
window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async Na(a){"macos-wkwebview"===this.g?this.F({type:"ready"}):this.B()&&(this.Gb(),this.ab=(await this.wb()).registeredComponentIds);if("playable-ad"===this.g){this.A=self.c3_base64files;this.ga={};await this.pb();for(let d=0,e=a.O.length;d<e;++d){var c=a.O[d];this.ga.hasOwnProperty(c)?a.O[d]={Qb:!0,Ub:this.ga[c]}:this.A.hasOwnProperty(c)&&(a.O[d]=URL.createObjectURL(this.A[c]))}a.ka=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=
0;this.lb(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Sb?this.m=a.Sb:(c=location.origin,this.m=("null"===c?"file:///":c)+location.pathname,c=this.m.lastIndexOf("/"),-1!==c&&(this.m=this.m.substr(0,c+1)));a.Yb&&(this.Z=a.Yb);c=new MessageChannel;this.W=c.port1;this.W.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ab(d));this.U=new self.ib(this);await ka(this.U);"object"===typeof window.StatusBar&&window.StatusBar.hide();
if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.o?await this.vb(a,c.port2):await this.ub(a,c.port2)}pa(a){a=this.Z.hasOwnProperty(a)?this.Z[a]:a.endsWith("/workermain.js")&&this.Z.hasOwnProperty("workermain.js")?this.Z["workermain.js"]:"playable-ad"===this.g&&this.A.hasOwnProperty(a)?this.A[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ma(a,
c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.za)return a=await this.la(d.Pb?a:this.L+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}v(){return Math.max(window.innerWidth,1)}u(){return Math.max(window.innerHeight,1)}Ma(a){var c=
this.m,d=location.href,e=this.v(),f=this.u(),g=window.devicePixelRatio,h=b.R(),l=a.ec,m=window.cr_previewImageBlobs||this.A,n=window.cr_previewProjectFileBlobs,wa=window.cr_previewProjectFiles,xa=window.cr_swClientId||"";a=a.bb;var ya=(new URLSearchParams(self.location.search)).has("debug"),K=this.U;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:l,previewImageBlobs:m,previewProjectFileBlobs:n,previewProjectFileSWUrls:wa,swClientId:xa,
exportType:a,isDebug:ya,ife:!!self.dc,jobScheduler:{inputPort:K.ya,outputPort:K.Da,maxNumWorkers:K.Kb},supportedAudioFormats:da,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.L+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.L+"opus.wasm.wasm",isFileProtocol:this.za,isiOSCordova:this.hb(),isiOSWebView:this.na(),isWebView2Wrapper:this.B(),wrapperComponentIds:this.ab,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async vb(a,c){const d=this.pa(a.Xb);"preview"===this.g?
(this.N=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,l)=>{const m=n=>{this.N.removeEventListener("message",m);n.data&&"ok"===n.data.type?h():l()};this.N.addEventListener("message",m);this.N.postMessage({type:"construct-worker-init","import":(new URL(d,this.m)).toString()})})):this.N=await this.ma(d,this.m,{type:"module",name:"Runtime",Pb:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);
window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.ka||[],g=a.O;f=await Promise.all(f.map(h=>this.J(h)));g=await Promise.all(g.map(h=>this.J(h)));if("cordova"===this.g)for(let h=0,l=a.ja.length;h<l;++h){const m=a.ja[h],n=m[0];if(n===a.Ha||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m[1]=await this.J(n)}this.N.postMessage(Object.assign(this.Ma(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,
projectScripts:a.ja,mainProjectScript:a.Ha,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...la(this.U)]);this.ea=F.map(h=>new h(this));this.La();ma(this.H);self.c3_callFunction=(h,l)=>{var m=this.H;return m.i.jb(m.T,{name:h,params:l})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.aa("runtime","go-to-last-error-script"))}async ub(a,c){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&
self.C3_InsertHTMLPlaceholders();this.ea=F.map(g=>new g(this));this.La();var d=a.O.map(g=>"string"===typeof g?(new URL(g,this.m)).toString():g);if(Array.isArray(a.ka)){var e=[...a.ka].map(g=>g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.J(g)));await Promise.all(d.map(g=>x(g)));d=self.C3_ProjectScriptsStatus;e=a.Ha;const f=a.ja;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.J(h),await x(h),"preview"!==this.g||d[g]||this.Qa(g,"main script did not run to completion")}catch(l){this.Qa(g,
l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.J(h),await x(h);"preview"===this.g&&"object"!==typeof self.Zb.bc?(this.ca(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ma(a),{isInWorker:!1,messagePort:c,canvas:this.j,runOnStartupFunctions:ha}),ma(this.H),
this.Oa(),this.Ba=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ba,a))}Qa(a,c){this.ca();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Oa(){this.ca()}ca(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async yb(){const a=await na(this.U);return{outputPort:a,
transferables:[a]}}tb(){if(this.o)throw Error("not available in worker mode");return this.Ba}aa(a,c,d,e){this.W.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},void 0)}jb(a,c){const d=fa++,e=new Promise((f,g)=>{H.set(d,{resolve:f,reject:g})});this.W.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.zb(a);if("result"===
c)this.Cb(a);else if("runtime-ready"===c)this.Db();else if("alert-error"===c)this.ca(),alert(a.message);else if("creating-runtime"===c)this.Oa();else throw Error(`unknown message '${c}'`);}zb(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.ba(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.ba(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,
h);this.ba(f,!1,""+h)}):this.ba(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}ba(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.W.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Cb(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}h(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);
e.set(c,d)}static $(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}La(){for(const a of this.ea)if("runtime"===a.T){this.H=a;return}throw Error("cannot find runtime DOM handler");}Ab(a){this.aa("debugger","message",a)}Db(){for(const a of this.ea)a.Ia()}static R(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ja)}static da(a){ja=!!a}lb(a){this.Ea.push(a);this.ua()}ua(){-1===this.K&&this.Ea.length&&(this.K=requestAnimationFrame(this.Mb))}nb(){-1!==
this.K&&(cancelAnimationFrame(this.K),this.K=-1)}Bb(){this.K=-1;for(const a of this.Ea)a();this.ua()}ta(){this.H.ta()}kb(){this.Ya=!0}eb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}gb(a){return!this.eb(a)}async J(a){return"cordova"===this.g&&(a.startsWith("file:")||this.za&&this.gb(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.la(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async xb(a){const c=a.filename;
switch(a.as){case "text":return await this.cb(c);case "buffer":return await this.la(c);default:throw Error("unsupported type");}}Ja(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async cb(a){a=await this.Ja(a);return await ea(a)}oa(){if(C.length&&!(8<=E)){E++;var a=C.shift();this.qb(a.filename,a.Vb,a.Ob)}}la(a){return new Promise((c,d)=>{C.push({filename:a,Vb:e=>{E--;this.oa();c(e)},Ob:e=>{E--;this.oa();
d(e)}});this.oa()})}async qb(a,c,d){try{const e=await this.Ja(a),f=await B(e);c(f)}catch(e){d(e)}}Pa(a){if("entered-fullscreen"===a)b.da(!0),I(this.H);else if("exited-fullscreen"===a)b.da(!1),I(this.H);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.Ga(a),this.Ga=null):"extension-message"===c?this.aa("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Eb(a){this.F({type:"extension-message",
componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}F(a){this.B()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Gb(){window.moveTo=(a,c)=>{this.F({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.F({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}wb(){return this.B()?new Promise(a=>
{this.Ga=a;this.F({type:"wrapper-init"})}):Promise.resolve()}async pb(){const a=[];for(const [c,d]of Object.entries(this.A))a.push(this.ob(c,d));await Promise.all(a)}async ob(a,c){if("object"===typeof c)this.A[a]=new Blob([c.str],{type:c.type}),this.ga[a]=c.str;else{let d=await this.sb(c);d||(d=this.rb(c));this.A[a]=d}}async sb(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}rb(a){a=this.Fb(a);return this.mb(a.data,a.Rb)}Fb(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Rb:a,data:d}}mb(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,l;for(l=h=0;h<e;++h)g[h]=a.charCodeAt(l++)|a.charCodeAt(l++)<<8|a.charCodeAt(l++)<<16|a.charCodeAt(l++)<<24;for(d&=
3;d--;)f[l]=a.charCodeAt(l),++l;return new Blob([f],{type:c})}};"use strict";const J=self.D;function oa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const pa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),L={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},qa={dispatchUserScriptEvent:!0},M={dispatchRuntimeEvent:!0};
function ra(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function sa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function N(b){b=URL.createObjectURL(b);try{return await sa(b)}finally{URL.revokeObjectURL(b)}}
function ta(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function ua(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await N(b);var d=await ta(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await N(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await N(b)}
function O(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const va=new Set(["input","textarea","datalist","select"]),za=new Set(["canvas","body","html"]);function Q(b){b.target.tagName&&za.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Aa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await N(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await ua(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let R=!1;document.addEventListener("pause",()=>R=!0);document.addEventListener("resume",()=>R=!1);function ma(b){b.Va=!0;b.Aa=b.i.v();b.V=b.i.u()}function I(b){if(!b.l){var a=J.R();a&&"any"!==b.Fa&&Ba(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.v(),innerHeight:b.u()})}}async function Ca(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Da(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ea(b){return await self.C3_GetSvgImageSize(b.blob)}function Fa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ga(b){self.setTimeout(()=>{b.Ua=!0},1E3);"cordova"===b.i.g?(document.addEventListener("pause",()=>S(b,!0)),document.addEventListener("resume",()=>S(b,!1))):document.addEventListener("visibilitychange",()=>S(b,"hidden"===document.visibilityState));b.ha=!("hidden"!==document.visibilityState&&!R);return{isSuspended:b.ha}}
function Ha(b){b.Sa||(b.Sa=!0,window.addEventListener("deviceorientation",a=>{b.l||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},L)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},L)}))}
function Ia(b){b.Ra||(b.Ra=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},L)}}))}async function Ja(b){await ra(b.url)}
function Ka(b,a){b.Wa=a.message;-1===b.xa&&(b.xa=setTimeout(()=>{b.xa=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Wa)},250))}function T(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:J.R(),innerWidth:b.v(),innerHeight:b.u()})}function S(b,a){b.ha!==a&&((b.ha=a)?b.i.nb():b.i.ua(),k(b,"visibilitychange",{hidden:a}))}
function La(b,a,c){"Backspace"===c.key&&Q(c);if(!b.l){var d=pa.get(c.code)||c.code;p(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},L)}}function U(b,a,c,d){b.l||oa(c)||p(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function V(b){window!==window.top&&window.focus();Ma(b.target)&&document.activeElement&&!Ma(document.activeElement)&&document.activeElement.blur()}
function W(b,a,c){if(!b.l){var d=0;"mouse"===c.pointerType&&(d=b.X);p(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},L);"mouse"===c.pointerType&&(d="mousemove",
"pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),U(b,d,c,qa),b.X=c.buttons)}}
function X(b,a,c){if(!b.l&&!oa(c)){var d=b.X;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");p(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},L);b.X=c.buttons;U(b,c.type,c,qa)}}
function Y(b,a,c){if(!b.l)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];p(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.s,pageX:f.pageX,pageY:f.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
L)}}function Z(b,a,c){document.body.style.transform="";b.s=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.s=a))}}function Na(b,a,c,d){const e=b.v(),f=b.u();b.M=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.R()}):10>d&&Oa(b,e,f,d+1)}
function Oa(b,a,c,d){-1!==b.M&&clearTimeout(b.M);b.M=setTimeout(()=>Na(b,a,c,d),48)}
function Ba(b){b=b.Fa;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Ma(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.$(class extends self.P{constructor(b){super(b,"runtime");this.Za=!0;this.Va=!1;this.M=-1;this.Fa="any";this.ha=this.Ra=this.Sa=!1;this.ia=document.createElement("div");this.ia.className="c3-screen-reader-text";this.ia.setAttribute("aria-live","polite");document.body.appendChild(this.ia);this.G=null;this.l=!1;this.Wa="";this.xa=-1;this.Ua=!1;this.Aa=b.v();this.V=b.u();this.s=this.Y=0;b.h("canvas","update-size",d=>{var e=this.i;e.Ya||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Za&&(e.style.display="",this.Za=!1))});b.h("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.h("runtime","load-webfonts",d=>Ca(d));b.h("runtime","raster-svg-image",d=>Da(d));b.h("runtime","get-svg-image-size",
d=>Ea(d));b.h("runtime","set-target-orientation",d=>{this.Fa=d.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime","post-to-debugger",d=>Fa(d));b.h("runtime","go-to-script",d=>Fa(d));b.h("runtime","before-start-ticking",()=>Ga(this));b.h("runtime","debug-highlight",d=>{if(d.show){this.G||(this.G=document.createElement("div"),this.G.id="inspectOutline",document.body.appendChild(this.G));var e=this.G;e.style.display="";e.style.left=d.left-
1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.G&&(this.G.style.display="none")});b.h("runtime","enable-device-orientation",()=>Ha(this));b.h("runtime","enable-device-motion",()=>Ia(this));b.h("runtime","add-stylesheet",d=>Ja(d));b.h("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.h("runtime","alert",d=>this.qa(d));b.h("runtime","screen-reader-text",
d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ia.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});b.h("runtime","hide-cordova-splash",
()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",d=>{this.l=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.kb()});b.h("runtime","export-to-video-progress",d=>Ka(this,d));b.h("runtime","exported-to-video",d=>{window.Nb({type:"exported-video",arrayBuffer:d.arrayBuffer,contentType:d.contentType,
time:d.time})});b.h("runtime","exported-to-image-sequence",d=>{window.Nb({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||O(e)||d.preventDefault()});const c=b.j;window.addEventListener("selectstart",Q);window.addEventListener("gesturehold",Q);c.addEventListener("selectstart",Q);c.addEventListener("gesturehold",Q);window.addEventListener("touchstart",
Q,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",Q,{passive:!1}),c.addEventListener("pointerdown",Q)):c.addEventListener("touchstart",Q);this.X=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Aa,{passive:!1});window.addEventListener("wheel",Aa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.Va){var d=this.v();var e=this.u();if(this.i.Ka()){if(this.Ua){if(this.Aa===d&&e<
this.V){this.Y=this.V-e;Z(this,this.V,this.Y);d=void 0;break a}0<this.Y&&(this.Y=0,Z(this,e,this.Y))}this.Aa=d;this.V=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.R()});this.i.na()&&(-1!==this.M&&clearTimeout(this.M),Na(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",()=>I(this));window.addEventListener("fullscreenerror",
d=>T(this,d));window.addEventListener("webkitfullscreenerror",d=>T(this,d));window.addEventListener("mozfullscreenerror",d=>T(this,d));if(b.na())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):O(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Ca=new Set;this.Lb=new WeakSet;this.Ib=!1}Ia(){window.addEventListener("focus",()=>{k(this,"window-focus",null,M)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},M);this.X=0});window.addEventListener("focusin",a=>{a=a.target;(va.has(a.tagName.toLowerCase())||O(a))&&
k(this,"keyboard-blur",null,M)});window.addEventListener("keydown",a=>La(this,"keydown",a));window.addEventListener("keyup",a=>La(this,"keyup",a));window.addEventListener("dblclick",a=>U(this,"dblclick",a,L));window.addEventListener("wheel",a=>{this.l||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.s,pageX:a.pageX,pageY:a.pageY+this.s,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},L)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{V(a);W(this,"pointerdown",a)}),this.i.o&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{W(this,"pointermove",a)}):window.addEventListener("pointermove",a=>W(this,"pointermove",a)),window.addEventListener("pointerup",a=>W(this,"pointerup",a)),window.addEventListener("pointercancel",a=>W(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{V(a);X(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>X(this,"pointermove",
a)),window.addEventListener("mouseup",a=>X(this,"pointerup",a)),window.addEventListener("touchstart",a=>{V(a);Y(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>Y(this,"pointermove",a)),window.addEventListener("touchend",a=>Y(this,"pointerup",a)),window.addEventListener("touchcancel",a=>Y(this,"pointercancel",a)));const b=()=>this.ta();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.fb()&&!this.i.Ka()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Z(this,this.u(),navigator.virtualKeyboard.boundingRect.height)}))}v(){return this.i.v()}u(){return this.i.u()}ta(){var b=[...this.Ca];this.Ca.clear();if(!this.Ib)for(const a of b)(b=a.play())&&b.catch(()=>{this.Lb.has(a)||this.Ca.add(a)})}qa(b){alert(b.message)}});"use strict";
async function ka(b){if(b.Hb)throw Error("already initialised");b.Hb=!0;var a=b.C.pa(("playable-ad"===b.C.g?b.C.L:"")+"dispatchworker.js");b.wa=await b.C.ma(a,b.S,{name:"DispatchWorker"});a=new MessageChannel;b.ya=a.port1;b.wa.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Da=await na(b)}function la(b){return[b.ya,b.Da]}
async function na(b){const a=b.$a.length;var c=b.C.pa(("playable-ad"===b.C.g?b.C.L:"")+"jobworker.js");c=await b.C.ma(c,b.S,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.wa.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.$a.push(c);return e.port1}
self.ib=class{constructor(b){this.C=b;this.S=b.m;this.S="preview"===b.g?this.S+"workers/":this.S+b.L;this.Kb=Math.min(navigator.hardwareConcurrency||2,16);this.wa=null;this.$a=[];this.Da=this.ya=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.D({Wb:!1,Xb:"workermain.js",O:["scripts/c3runtime.js"],ja:[],Ha:"",Tb:"scripts/",ka:[],bb:"html5"}));"use strict";
async function Pa(b,a){a=a.type;let c=!0;0===a?c=await Qa():1===a&&(c=await Ra());k(b,"permission-result",{type:a,result:c})}async function Qa(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Ra(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.D.$(class extends self.P{constructor(b){super(b,"touch");q(this,"request-permission",a=>Pa(this,a))}});"use strict";function Sa(){}
function Ta(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Ua(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.D.$(class extends self.P{constructor(b){super(b,"browser");this.g="";r(this,[["get-initial-state",a=>this.ra(a)],["ready-for-sw-messages",()=>Ta(this)],["alert",a=>this.qa(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.sa(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Ua(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||this.i.B()?window.open(c,"_blank"):this.cc||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.i.B()||"macos-wkwebview"===this.g)self.D.da(!0),this.i.F({type:"set-fullscreen",
fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Sa)}}],["exit-fullscreen",
()=>{if(this.i.B()||"macos-wkwebview"===this.g)self.D.da(!1),this.i.F({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Sa)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;
a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",
e),c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}ra(b){this.g=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,
screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}qa(b){alert(b.message)}sa(b){b=b.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";function Va(b){return new Promise((a,c)=>{b.getInsetTop(a,c)})}function Wa(b){return new Promise((a,c)=>{b.getInsetRight(a,c)})}
function Xa(b){return new Promise((a,c)=>{b.getInsetBottom(a,c)})}function Ya(b){return new Promise((a,c)=>{b.getInsetLeft(a,c)})}
async function Za(b){if(!b.I)try{b.I=await navigator.wakeLock.request("screen"),b.I.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.I=null;k(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),k(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),k(b,"wake-lock-error")}}
async function $a(b){const a=await ab();k(b,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function ab(){var b=self.AndroidNotch;if(b)try{return await Promise.all([Va(b),Wa(b),Xa(b),Ya(b)])}catch(c){return console.error("[Construct] Failed to get Android safe area inset: ",c),[0,0,0,0]}else{var a=document.body;b=a.style;b.setProperty("--temp-sai-top","env(safe-area-inset-top)");b.setProperty("--temp-sai-right","env(safe-area-inset-right)");b.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");b.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);return isFinite(c)?c:0});b.removeProperty("--temp-sai-top");b.removeProperty("--temp-sai-right");b.removeProperty("--temp-sai-bottom");b.removeProperty("--temp-sai-left");return a}}
self.D.$(class extends self.P{constructor(b){super(b,"platform-info");r(this,[["get-initial-state",()=>this.ra()],["request-wake-lock",()=>Za(this)],["release-wake-lock",()=>{this.I&&(this.I.release(),this.I=null)}]]);window.addEventListener("resize",()=>$a(this));this.I=null}async ra(){const b=await ab();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:b,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==
typeof nw}}});
