'use strict';function q(k,d,g,m){k.f.aa(k.G,d,g,m,void 0)}function w(k,d,g,m){k.f.l?q(k,d,g,m):k.f.jb()._OnMessageFromDOM({type:"event",component:k.G,handler:d,dispatchOpts:m||null,data:g,responseId:null})}function A(k,d,g){k.f.a(k.G,d,g)}function G(k,d){for(const [g,m]of d)A(k,g,m)}window.C=class{constructor(k,d){this.f=k;this.G=d}wa(){}};
window.Ya=class{constructor(k,d){this.Na=k;this.Ob=d;this.A=-1;this.V=-Infinity;this.Tb=()=>{this.A=-1;this.V=Date.now();this.H=!0;this.Na();this.H=!1};this.Oa=this.H=!1}};"use strict";function H(k,d){A(k,"get-element",g=>{const m=k.h.get(g.elementId);return d(m,g)})}
window.ec=class extends self.C{constructor(k,d){super(k,d);this.h=new Map;this.ma=!0;G(this,[["create",()=>{throw Error("required override");}],["destroy",g=>{{g=g.elementId;const m=this.h.get(g);this.ma&&m.parentElement.removeChild(m);this.h.delete(g)}}],["set-visible",g=>{this.ma&&(this.h.get(g.elementId).style.display=g.isVisible?"":"none")}],["update-position",g=>{if(this.ma){var m=this.h.get(g.elementId);m.style.left=g.left+"px";m.style.top=g.top+"px";m.style.width=g.width+"px";m.style.height=
g.height+"px";g=g.fontSize;null!==g&&(m.style.fontSize=g+"em")}}],["update-state",g=>{this.h.get(g.elementId);throw Error("required override");}],["focus",g=>this.ja(g)],["set-css-style",g=>{this.h.get(g.elementId).style[g.prop]=g.val}],["set-attribute",g=>{this.h.get(g.elementId).setAttribute(g.name,g.val)}],["remove-attribute",g=>{this.h.get(g.elementId).removeAttribute(g.name)}]]);H(this,g=>g)}ja(k){var d=this.h.get(k.elementId);k.focus?d.focus():d.blur()}};"use strict";
{const k=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function d(p){if(p.Wb){const c=document.createElement("script");c.async=!1;c.textContent=p.Zb;document.head.appendChild(c)}else return new Promise((c,e)=>{const a=document.createElement("script");a.onload=c;a.onerror=e;a.async=!1;a.src=p;document.head.appendChild(a)})}let g=new Audio;const m={"audio/webm; codecs=opus":!!g.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!g.canPlayType("audio/ogg; codecs=opus"),
"audio/webm; codecs=vorbis":!!g.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!g.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!g.canPlayType("audio/mp4"),"audio/mpeg":!!g.canPlayType("audio/mpeg")};g=null;async function u(p){p=await B(p);return(new TextDecoder("utf-8")).decode(p)}function B(p){return new Promise((c,e)=>{const a=new FileReader;a.onload=b=>c(b.target.result);a.onerror=b=>e(b);a.readAsArrayBuffer(p)})}const x=[];let v=0;window.RealFile=window.File;const t=
[],y=new Map,z=new Map;let E=0;const F=[];self.mc=function(p){if("function"!==typeof p)throw Error("runOnStartup called without a function");F.push(p)};const r=new Set(["cordova","playable-ad","instant-games"]);window.D=class p{constructor(c){this.l=c.ac;this.J=null;this.c="";this.Y=c.Yb;this.M={};this.j=this.qa=this.Sa=null;this.U=[];this.I=this.g=this.ta=null;this.u=-1;this.Sb=()=>this.Cb();this.Ra=[];this.b=c.Ta;!this.l||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation||(this.l=!1);
r.has(this.b)&&this.l&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.l=!1);this.W=this.i=null;"html5"!==this.b&&"playable-ad"!==this.b||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.a("runtime","cordova-fetch-local-file",e=>this.pb(e));this.a("runtime",
"create-job-worker",()=>this.qb());"cordova"===this.b?document.addEventListener("deviceready",()=>this.Da(c)):this.Da(c)}za(){return k&&"cordova"===this.b}O(){return k&&r.has(this.b)||navigator.standalone}async Da(c){"preview"===this.b&&(this.j=document.createElement("div"),this.j.className="previewLoadingMessage",this.j.textContent=c.kc,document.body.appendChild(this.j));if("playable-ad"===this.b){this.i=self.c3_base64files;this.W={};await this.eb();for(let a=0,b=c.B.length;a<b;++a){var e=c.B[a].toLowerCase();
this.W.hasOwnProperty(e)?c.B[a]={Wb:!0,Zb:this.W[e]}:this.i.hasOwnProperty(e)&&(c.B[a]=URL.createObjectURL(this.i[e]))}}c.Ub?this.c=c.Ub:(e=location.origin,this.c=("null"===e?"file:///":e)+location.pathname,e=this.c.lastIndexOf("/"),-1!==e&&(this.c=this.c.substr(0,e+1)));if(c.cc)for(const [a,b]of Object.entries(c.cc))this.M[a]=URL.createObjectURL(b);e=new MessageChannel;this.J=e.port1;this.J.onmessage=a=>this._OnMessageFromRuntime(a.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(a=>
this.zb(a));this.I=new self.Wa(this);await I(this.I);this.Aa();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.l?await this.lb(c,e.port2):await this.kb(c,e.port2)}ca(c){return this.M.hasOwnProperty(c)?this.M[c]:c.endsWith("/workermain.js")&&this.M.hasOwnProperty("workermain.js")?this.M["workermain.js"]:"playable-ad"===this.b&&this.i.hasOwnProperty(c.toLowerCase())?URL.createObjectURL(this.i[c.toLowerCase()]):
c}async Z(c,e,a){if(c.startsWith("blob:"))return new Worker(c,a);if(this.za()&&"file:"===location.protocol)return c=await this.ya(this.Y+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),a);c=new URL(c,e);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),a)}return new Worker(c,a)}o(){return Math.max(window.innerWidth,1)}m(){return Math.max(window.innerHeight,
1)}Aa(){if(this.O()){const c=document.documentElement.style,e=document.body.style,a=window.innerWidth<window.innerHeight,b=a?window.screen.width:window.screen.height;e.height=c.height=(a?window.screen.height:window.screen.width)+"px";e.width=c.width=b+"px"}}Ca(c){var e=this.I;return{baseUrl:this.c,windowInnerWidth:this.o(),windowInnerHeight:this.m(),devicePixelRatio:window.devicePixelRatio,isFullscreen:p.$(),projectData:c.lc,previewImageBlobs:window.cr_previewImageBlobs||this.i,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,
exportType:c.Ta,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.jc,jobScheduler:{inputPort:e.oa,outputPort:e.sa,maxNumWorkers:e.Qb},supportedAudioFormats:m,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Y+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Y+"opus.wasm.wasm",isiOSCordova:this.za(),isiOSWebView:this.O(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async lb(c,e){var a=this.ca(c.bc);this.Sa=await this.Z(a,this.c,{name:"Runtime"});this.g=document.createElement("canvas");
this.g.style.display="none";a=this.g.transferControlToOffscreen();document.body.appendChild(this.g);window.c3canvas=this.g;this.Sa.postMessage(Object.assign(this.Ca(c),{type:"init-runtime",isInWorker:!0,messagePort:e,canvas:a,workerDependencyScripts:c.va||[],engineScripts:c.B,projectScripts:window.ic,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[e,a,...J(this.I)]);this.U=t.map(b=>new b(this));this.Ba();self.c3_callFunction=(b,f)=>this.ta.mb(b,f);"preview"===this.b&&(self.goToLastErrorScript=
()=>this.aa("runtime","go-to-last-error-script"))}async kb(c,e){this.g=document.createElement("canvas");this.g.style.display="none";document.body.appendChild(this.g);window.c3canvas=this.g;this.U=t.map(b=>new b(this));this.Ba();const a=c.B.map(b=>"string"===typeof b?(new URL(b,this.c)).toString():b);Array.isArray(c.va)&&a.unshift(...c.va);await Promise.all(a.map(b=>d(b)));if(c.Ua&&0<c.Ua.length){const b=self.C3_ProjectScriptsStatus;try{if(await Promise.all(c.Ua.map(f=>d(f[1]))),Object.values(b).some(f=>
!f)){self.setTimeout(()=>this.Ja(b),100);return}}catch(f){console.error("[Preview] Error loading project scripts: ",f);self.setTimeout(()=>this.Ja(b),100);return}}"preview"===this.b&&"object"!==typeof self.dc.fc?(this.T(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Ca(c),{isInWorker:!1,messagePort:e,
canvas:this.g,runOnStartupFunctions:F}),this.Fa(),this.qa=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.qa,c))}Ja(c){this.T();c=`Failed to load project script '${Object.entries(c).filter(e=>!e[1]).map(e=>e[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+c);alert(c)}Fa(){this.T()}T(){this.j&&(this.j.parentElement.removeChild(this.j),this.j=null)}async qb(){const c=await K(this.I);return{outputPort:c,transferables:[c]}}jb(){if(this.l)throw Error("not available in worker mode");
return this.qa}aa(c,e,a,b,f){this.J.postMessage({type:"event",component:c,handler:e,dispatchOpts:b||null,data:a,responseId:null},f)}Xa(c,e){const a=E++,b=new Promise((f,h)=>{z.set(a,{resolve:f,reject:h})});this.J.postMessage({type:"event",component:c,handler:"js-invoke-function",dispatchOpts:null,data:e,responseId:a},void 0);return b}["_OnMessageFromRuntime"](c){const e=c.type;if("event"===e)return this.vb(c);if("result"===e)this.Fb(c);else if("runtime-ready"===e)this.Gb();else if("alert-error"===
e)this.T(),alert(c.message);else if("creating-runtime"===e)this.Fa();else throw Error(`unknown message '${e}'`);}vb(c){const e=c.component,a=c.handler,b=c.data,f=c.responseId;if(c=y.get(e))if(c=c.get(a)){var h=null;try{h=c(b)}catch(l){console.error(`Exception in '${e}' handler '${a}':`,l);null!==f&&this.R(f,!1,""+l);return}if(null===f)return h;h&&h.then?h.then(l=>this.R(f,!0,l)).catch(l=>{console.error(`Rejection from '${e}' handler '${a}':`,l);this.R(f,!1,""+l)}):this.R(f,!0,h)}else console.warn(`[DOM] No handler '${a}' for component '${e}'`);
else console.warn(`[DOM] No event handlers for component '${e}'`)}R(c,e,a){let b;a&&a.transferables&&(b=a.transferables);this.J.postMessage({type:"result",responseId:c,isOk:e,result:a},b)}Fb(c){const e=c.responseId,a=c.isOk;c=c.result;const b=z.get(e);a?b.resolve(c):b.reject(c);z.delete(e)}a(c,e,a){let b=y.get(c);b||(b=new Map,y.set(c,b));if(b.has(e))throw Error(`[DOM] Component '${c}' already has handler '${e}'`);b.set(e,a)}static N(c){if(t.includes(c))throw Error("DOM handler already added");t.push(c)}Ba(){for(const c of this.U)if("runtime"===
c.G){this.ta=c;return}throw Error("cannot find runtime DOM handler");}zb(c){this.aa("debugger","message",c)}Gb(){for(const c of this.U)c.wa()}static $(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Ka(){-1===this.u&&this.Ra.length&&(this.u=requestAnimationFrame(this.Sb))}bb(){-1!==this.u&&(cancelAnimationFrame(this.u),this.u=-1)}Cb(){this.u=-1;for(const c of this.Ra)c();this.Ka()}la(){this.ta.la()}async pb(c){const e=c.filename;switch(c.as){case "text":return await this.Va(e);
case "buffer":return await this.ya(e);default:throw Error("unsupported type");}}xa(c){const e=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((a,b)=>{window.resolveLocalFileSystemURL(e,f=>{f.file(a,b)},b)})}async Va(c){c=await this.xa(c);return await u(c)}ba(){if(x.length&&!(8<=v)){v++;var c=x.shift();this.fb(c.filename,c.$b,c.Vb)}}ya(c){return new Promise((e,a)=>{x.push({filename:c,$b:b=>{v--;this.ba();e(b)},Vb:b=>{v--;this.ba();a(b)}});this.ba()})}async fb(c,e,
a){try{const b=await this.xa(c),f=await B(b);e(f)}catch(b){a(b)}}async eb(){const c=[];for(const [e,a]of Object.entries(this.i))c.push(this.cb(e,a));await Promise.all(c)}async cb(c,e){if("object"===typeof e)this.i[c]=new Blob([e.str],{type:e.type}),this.W[c]=e.str;else{let a=await this.ib(e);a||(a=this.gb(e));this.i[c]=a}}async ib(c){try{return await (await fetch(c)).blob()}catch(e){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
e),null}}gb(c){c=this.Kb(c);return this.ab(c.data,c.Xb)}Kb(c){var e=c.indexOf(",");if(0>e)throw new URIError("expected comma in data: uri");var a=c.substring(e+1);e=c.substring(5,e).split(";");c=e[0]||"";const b=e[2];a="base64"===e[1]||"base64"===b?atob(a):decodeURIComponent(a);return{Xb:c,data:a}}ab(c,e){var a=c.length;let b=a>>2,f=new Uint8Array(a),h=new Uint32Array(f.buffer,0,b),l,n;for(n=l=0;l<b;++l)h[l]=c.charCodeAt(n++)|c.charCodeAt(n++)<<8|c.charCodeAt(n++)<<16|c.charCodeAt(n++)<<24;for(a&=
3;a--;)f[n]=c.charCodeAt(n),++n;return new Blob([f],{type:e})}}}"use strict";
{const k=self.D;function d(a){return a.sourceCapabilities&&a.sourceCapabilities.firesTouchEvents||a.originalEvent&&a.originalEvent.sourceCapabilities&&a.originalEvent.sourceCapabilities.firesTouchEvents}const g=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),m={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},u={dispatchUserScriptEvent:!0},B={dispatchRuntimeEvent:!0};function x(a){return new Promise((b,f)=>{const h=document.createElement("link");h.onload=()=>b(h);h.onerror=l=>f(l);h.rel=
"stylesheet";h.href=a;document.head.appendChild(h)})}function v(a){return new Promise((b,f)=>{const h=new Image;h.onload=()=>b(h);h.onerror=l=>f(l);h.src=a})}async function t(a){a=URL.createObjectURL(a);try{return await v(a)}finally{URL.revokeObjectURL(a)}}function y(a){return new Promise((b,f)=>{let h=new FileReader;h.onload=l=>b(l.target.result);h.onerror=l=>f(l);h.readAsText(a)})}async function z(a,b,f){if(!/firefox/i.test(navigator.userAgent))return await t(a);var h=await y(a);h=(new DOMParser).parseFromString(h,
"image/svg+xml");const l=h.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),L=l.getAttribute("height");if(!n.includes("%")&&!L.includes("%"))return await t(a)}l.setAttribute("width",b+"px");l.setAttribute("height",f+"px");h=(new XMLSerializer).serializeToString(h);a=new Blob([h],{type:"image/svg+xml"});return await t(a)}function E(a){do{if(a.parentNode&&a.hasAttribute("contenteditable"))return!0;a=a.parentNode}while(a);return!1}const F=new Set(["canvas",
"body","html"]);function r(a){F.has(a.target.tagName.toLowerCase())&&a.preventDefault()}function p(a){(a.metaKey||a.ctrlKey)&&a.preventDefault()}self.C3_GetSvgImageSize=async function(a){a=await t(a);if(0<a.width&&0<a.height)return[a.width,a.height];{a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.visibility="hidden";document.body.appendChild(a);const b=a.getBoundingClientRect();document.body.removeChild(a);return[b.width,b.height]}};self.C3_RasterSvgImageBlob=async function(a,
b,f,h,l){a=await z(a,b,f);const n=document.createElement("canvas");n.width=h;n.height=l;n.getContext("2d").drawImage(a,0,0,b,f);return n};let c=!1;document.addEventListener("pause",()=>c=!0);document.addEventListener("resume",()=>c=!1);function e(){try{return window.parent&&window.parent.document.hasFocus()}catch(a){return!1}}k.N(class extends self.C{constructor(a){super(a,"runtime");this.Pa=!0;this.v=-1;this.ua="any";this.La=this.Ma=!1;this.pa=this.L=this.s=null;a.a("canvas","update-size",h=>this.Ib(h));
a.a("runtime","invoke-download",h=>this.yb(h));a.a("runtime","raster-svg-image",h=>this.Db(h));a.a("runtime","get-svg-image-size",h=>this.wb(h));a.a("runtime","set-target-orientation",h=>this.Hb(h));a.a("runtime","register-sw",()=>this.Eb());a.a("runtime","post-to-debugger",h=>this.Ha(h));a.a("runtime","go-to-script",h=>this.Ha(h));a.a("runtime","before-start-ticking",()=>this.ob());a.a("runtime","debug-highlight",h=>this.rb(h));a.a("runtime","enable-device-orientation",()=>this.$a());a.a("runtime",
"enable-device-motion",()=>this.Za());a.a("runtime","add-stylesheet",h=>this.nb(h));a.a("runtime","alert",h=>this.ea(h));a.a("runtime","hide-cordova-splash",()=>this.xb());const b=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",h=>{const l=h.target;b.has(l.tagName.toLowerCase())||E(l)||h.preventDefault()});const f=a.g;window.addEventListener("selectstart",r);window.addEventListener("gesturehold",r);f.addEventListener("selectstart",r);f.addEventListener("gesturehold",
r);window.addEventListener("touchstart",r,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",r,{passive:!1}),f.addEventListener("pointerdown",r)):f.addEventListener("touchstart",r);this.K=0;window.addEventListener("mousedown",h=>{1===h.button&&h.preventDefault()});window.addEventListener("mousewheel",p,{passive:!1});window.addEventListener("wheel",p,{passive:!1});window.addEventListener("resize",()=>this.Jb());a.O()&&window.addEventListener("focusout",()=>{{const n=
document.activeElement;if(n){var h=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));h="textarea"===h?!0:"input"===h?l.has(n.type.toLowerCase()||"text"):E(n)}else h=!1}h||(document.scrollingElement.scrollTop=0)});this.ra=new Set;this.Rb=new WeakSet;this.Pb=!1}ob(){"cordova"===this.f.b?(document.addEventListener("pause",()=>this.ka(!0)),document.addEventListener("resume",()=>this.ka(!1))):document.addEventListener("visibilitychange",()=>this.ka(document.hidden));
return{isSuspended:!(!document.hidden&&!c)}}wa(){window.addEventListener("focus",()=>this.S("window-focus"));window.addEventListener("blur",()=>{this.S("window-blur",{parentHasFocus:e()});this.K=0});window.addEventListener("fullscreenchange",()=>this.fa());window.addEventListener("webkitfullscreenchange",()=>this.fa());window.addEventListener("mozfullscreenchange",()=>this.fa());window.addEventListener("fullscreenerror",b=>this.ga(b));window.addEventListener("webkitfullscreenerror",b=>this.ga(b));
window.addEventListener("mozfullscreenerror",b=>this.ga(b));window.addEventListener("keydown",b=>this.Ga("keydown",b));window.addEventListener("keyup",b=>this.Ga("keyup",b));window.addEventListener("dblclick",b=>this.ha("dblclick",b,m));window.addEventListener("wheel",b=>this.Ab(b));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",b=>{this.da(b);this.F("pointerdown",b)}),this.f.l&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.L=new self.Ya(()=>this.hb(),
5),this.L.Oa=!0,window.addEventListener("pointerrawupdate",b=>this.Bb(b))):window.addEventListener("pointermove",b=>this.F("pointermove",b)),window.addEventListener("pointerup",b=>this.F("pointerup",b)),window.addEventListener("pointercancel",b=>this.F("pointercancel",b))):(window.addEventListener("mousedown",b=>{this.da(b);this.ia("pointerdown",b)}),window.addEventListener("mousemove",b=>this.ia("pointermove",b)),window.addEventListener("mouseup",b=>this.ia("pointerup",b)),window.addEventListener("touchstart",
b=>{this.da(b);this.P("pointerdown",b)}),window.addEventListener("touchmove",b=>this.P("pointermove",b)),window.addEventListener("touchend",b=>this.P("pointerup",b)),window.addEventListener("touchcancel",b=>this.P("pointercancel",b)));const a=()=>this.la();window.addEventListener("pointerup",a,!0);window.addEventListener("touchend",a,!0);window.addEventListener("click",a,!0);window.addEventListener("keydown",a,!0);window.addEventListener("gamepadconnected",a,!0)}S(a,b){q(this,a,b||null,B)}o(){return this.f.o()}m(){return this.f.m()}Jb(){const a=
this.o(),b=this.m();this.S("window-resize",{innerWidth:a,innerHeight:b,devicePixelRatio:window.devicePixelRatio});this.f.O()&&(-1!==this.v&&clearTimeout(this.v),this.Ia(a,b,0))}Lb(a,b,f){-1!==this.v&&clearTimeout(this.v);this.v=setTimeout(()=>this.Ia(a,b,f),48)}Ia(a,b,f){const h=this.o(),l=this.m();this.v=-1;h!=a||l!=b?this.S("window-resize",{innerWidth:h,innerHeight:l,devicePixelRatio:window.devicePixelRatio}):10>f&&this.Lb(h,l,f+1)}Hb(a){this.ua=a.targetOrientation}Mb(){const a=this.ua;if(screen.orientation&&
screen.orientation.lock)screen.orientation.lock(a).catch(b=>console.warn("[Construct 3] Failed to lock orientation: ",b));else try{let b=!1;screen.lockOrientation?b=screen.lockOrientation(a):screen.webkitLockOrientation?b=screen.webkitLockOrientation(a):screen.mozLockOrientation?b=screen.mozLockOrientation(a):screen.msLockOrientation&&(b=screen.msLockOrientation(a));b||console.warn("[Construct 3] Failed to lock orientation")}catch(b){console.warn("[Construct 3] Failed to lock orientation: ",b)}}fa(){const a=
k.$();a&&"any"!==this.ua&&this.Mb();q(this,"fullscreenchange",{isFullscreen:a,innerWidth:this.o(),innerHeight:this.m()})}ga(a){console.warn("[Construct 3] Fullscreen request failed: ",a);q(this,"fullscreenerror",{isFullscreen:k.$(),innerWidth:this.o(),innerHeight:this.m()})}ka(a){a?this.f.bb():this.f.Ka();q(this,"visibilitychange",{hidden:a})}Ga(a,b){"Backspace"===b.key&&r(b);const f=g.get(b.code)||b.code;w(this,a,{code:f,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,metaKey:b.metaKey,
shiftKey:b.shiftKey,timeStamp:b.timeStamp},m)}Ab(a){q(this,"wheel",{clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},m)}ha(a,b,f){d(b)||w(this,a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,timeStamp:b.timeStamp},f)}ia(a,b){if(!d(b)){var f=this.K;"pointerdown"===a&&0!==f?a="pointermove":"pointerup"===a&&0!==b.buttons&&(a="pointermove");w(this,
a,{pointerId:1,pointerType:"mouse",button:b.button,buttons:b.buttons,lastButtons:f,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:b.timeStamp},m);this.K=b.buttons;this.ha(b.type,b,u)}}F(a,b){if(this.L&&"pointermove"!==a){var f=this.L;f.H||(-1!==f.A&&(self.clearTimeout(f.A),f.A=-1),f.V=Date.now())}f=0;"mouse"===b.pointerType&&(f=this.K);w(this,a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,
buttons:b.buttons,lastButtons:f,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},m);"mouse"===b.pointerType&&(f="mousemove","pointerdown"===a?f="mousedown":"pointerup"===a&&(f="pointerup"),this.ha(f,b,u),this.K=b.buttons)}Bb(a){this.pa=a;a=this.L;if(-1===a.A){var b=Date.now(),f=b-a.V,h=a.Ob;f>=h&&a.Oa?(a.V=b,
a.H=!0,a.Na(),a.H=!1):a.A=self.setTimeout(a.Tb,Math.max(h-f,4))}}hb(){this.F("pointermove",this.pa);this.pa=null}P(a,b){for(let f=0,h=b.changedTouches.length;f<h;++f){const l=b.changedTouches[f];w(this,a,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:l.rotationAngle||
0,timeStamp:b.timeStamp},m)}}da(a){window!==window.top&&window.focus();this.Ea(a.target)&&document.activeElement&&!this.Ea(document.activeElement)&&document.activeElement.blur()}Ea(a){return!a||a===document||a===window||a===document.body||"canvas"===a.tagName.toLowerCase()}$a(){this.Ma||(this.Ma=!0,window.addEventListener("deviceorientation",a=>this.tb(a)),window.addEventListener("deviceorientationabsolute",a=>this.ub(a)))}Za(){this.La||(this.La=!0,window.addEventListener("devicemotion",a=>this.sb(a)))}tb(a){q(this,
"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},m)}ub(a){q(this,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},m)}sb(a){let b=null;var f=a.acceleration;f&&(b={x:f.x||0,y:f.y||0,z:f.z||0});f=null;var h=a.accelerationIncludingGravity;h&&(f={x:h.x||0,y:h.y||0,z:h.z||0});
h=null;const l=a.rotationRate;l&&(h={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});q(this,"devicemotion",{acceleration:b,accelerationIncludingGravity:f,rotationRate:h,interval:a.interval,timeStamp:a.timeStamp},m)}Ib(a){const b=this.f,f=b.g;f.style.width=a.styleWidth+"px";f.style.height=a.styleHeight+"px";f.style.marginLeft=a.marginLeft+"px";f.style.marginTop=a.marginTop+"px";b.Aa();this.Pa&&(f.style.display="",this.Pa=!1)}yb(a){const b=a.url;a=a.filename;const f=document.createElement("a"),h=
document.body;f.textContent=a;f.href=b;f.download=a;h.appendChild(f);f.click();h.removeChild(f)}async Db(a){var b=a.imageBitmapOpts;a=await self.C3_RasterSvgImageBlob(a.blob,a.imageWidth,a.imageHeight,a.surfaceWidth,a.surfaceHeight);b=b?await createImageBitmap(a,b):await createImageBitmap(a);return{imageBitmap:b,transferables:[b]}}async wb(a){return await self.C3_GetSvgImageSize(a.blob)}async nb(a){await x(a.url)}la(){var a=[...this.ra];this.ra.clear();if(!this.Pb)for(const b of a)(a=b.play())&&a.catch(()=>
{this.Rb.has(b)||this.ra.add(b)})}xb(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}rb(a){if(a.show){this.s||(this.s=document.createElement("div"),this.s.id="inspectOutline",document.body.appendChild(this.s));var b=this.s;b.style.display="";b.style.left=a.left-1+"px";b.style.top=a.top-1+"px";b.style.width=a.width+2+"px";b.style.height=a.height+2+"px";b.textContent=a.name}else this.s&&(this.s.style.display="none")}Eb(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ha(a){window.c3_postToMessagePort&&
(a.from="runtime",window.c3_postToMessagePort(a))}mb(a,b){return this.f.Xa(this.G,{name:a,params:b})}ea(a){alert(a.message)}})}"use strict";async function I(k){if(k.Nb)throw Error("already initialised");k.Nb=!0;var d=k.X.ca("dispatchworker.js");k.na=await k.X.Z(d,k.c,{name:"DispatchWorker"});d=new MessageChannel;k.oa=d.port1;k.na.postMessage({type:"_init","in-port":d.port2},[d.port2]);k.sa=await K(k)}function J(k){return[k.oa,k.sa]}
async function K(k){const d=k.Qa.length;var g=k.X.ca("jobworker.js");g=await k.X.Z(g,k.c,{name:"JobWorker"+d});const m=new MessageChannel,u=new MessageChannel;k.na.postMessage({type:"_addJobWorker",port:m.port1},[m.port1]);g.postMessage({type:"init",number:d,"dispatch-port":m.port2,"output-port":u.port2},[m.port2,u.port2]);k.Qa.push(g);return u.port1}
self.Wa=class{constructor(k){this.X=k;this.c=k.c;this.c="preview"===k.b?this.c+"c3/workers/":this.c+k.Y;this.Qb=Math.min(navigator.hardwareConcurrency||2,16);this.na=null;this.Qa=[];this.sa=this.oa=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.D({ac:!0,bc:"workermain.js",B:["scripts/c3runtime.js"],Yb:"scripts/",va:[],Ta:"html5"}));"use strict";
async function M(k,d){d=d.type;let g=!0;0===d?g=await N():1===d&&(g=await O());q(k,"permission-result",{type:d,result:g})}async function N(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(k){return console.warn("[Touch] Failed to request orientation permission: ",k),!1}}
async function O(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(k){return console.warn("[Touch] Failed to request motion permission: ",k),!1}}self.D.N(class extends self.C{constructor(k){super(k,"touch");A(this,"request-permission",d=>M(this,d))}});"use strict";
function P(k){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(d=>q(k,"sw-message",d.data))}
function Q(k){k=k.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(k).catch(d=>console.warn("[Construct 3] Failed to lock orientation: ",d));else try{let d=!1;screen.lockOrientation?d=screen.lockOrientation(k):screen.webkitLockOrientation?d=screen.webkitLockOrientation(k):screen.mozLockOrientation?d=screen.mozLockOrientation(k):screen.msLockOrientation&&(d=screen.msLockOrientation(k));d||console.warn("[Construct 3] Failed to lock orientation")}catch(d){console.warn("[Construct 3] Failed to lock orientation: ",
d)}}
self.D.N(class extends self.C{constructor(k){super(k,"browser");this.b="";G(this,[["get-initial-state",d=>{this.b=d.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>P(this)],
["alert",d=>this.ea(d)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",d=>this.ja(d)],["vibrate",d=>{navigator.vibrate&&navigator.vibrate(d.pattern)}],["lock-orientation",d=>Q(d)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(d){}}],["navigate",d=>{var g=d.type;if("back"===g)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===g)window.forward();else if("home"===g)window.home();else if("reload"===g)location.reload();else if("url"===g){g=d.url;var m=d.target;d=d.exportType;"windows-uwp"===d&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(g)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(g,"_system"):"preview"===d?window.open(g,"_blank"):this.hc||(2===m?window.top.location=g:1===m?window.parent.location=g:window.location=g)}else"new-window"===g&&(g=d.url,m=d.tag,"windows-uwp"===d.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(g)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(g,"_system"):window.open(g,m))}],["request-fullscreen",
d=>{{const g={navigationUI:"auto"};d=d.navUI;1===d?g.navigationUI="hide":2===d&&(g.navigationUI="show");d=document.documentElement;d.requestFullscreen?d.requestFullscreen(g):d.mozRequestFullScreen?d.mozRequestFullScreen(g):d.msRequestFullscreen?d.msRequestFullscreen(g):d.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?d.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):d.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?document.exitFullscreen():
document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",d=>{location.hash=d.hash}]]);window.addEventListener("online",()=>{q(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{q(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{q(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",
()=>{q(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",d=>{d.handled=!0;q(this,"backbutton")})}ea(k){alert(k.message)}ja(k){k=k.isFocus;if("nwjs"===this.b){const d="nwjs"===this.b?nw.Window.get():null;k?d.focus():d.blur()}else k?window.focus():window.blur()}});"use strict";self.D.N(class extends self.C{constructor(k){super(k,"mouse");A(this,"cursor",d=>{document.documentElement.style.cursor=d})}});