function k(b,a,c,d){b.i.aa(b.R,a,c,d)}function p(b,a,c,d){b.i.o?k(b,a,c,d):b.i.vb()._OnMessageFromDOM({type:"event",component:b.R,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.i.h(b.R,a,c)}function r(b,a){for(const [c,d]of a)q(b,c,d)}window.$=class{constructor(b,a){this.i=b;this.R=a}Ka(){}};window.ac=class{constructor(){}};"use strict";class aa{constructor(b){this.wa=b;this.ya=!1;this.Ba=!0}}
function ba(b,a){const c=a.elementId,d=b.Ma(c,a),e=new aa(d);b.S.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Ba=!!a.isVisible;d.addEventListener("focus",()=>{t(b,"elem-focused",c)});d.addEventListener("blur",()=>{t(b,"elem-blurred",c)});b.ea&&document.body.appendChild(d)}function u(b,a,c){q(b,a,d=>{const e=v(b,d.elementId);return c(e,d)})}function v(b,a){b=b.S.get(a);if(!b)throw Error(`no element with id ${a}`);return b.wa}
function t(b,a,c,d){d||(d={});d.elementId=c;k(b,a,d)}function w(b,a,c){var d;d||(d={});d.elementId=c;p(b,a,d)}
window.fb=class extends self.${constructor(b){super(b,"text-input");this.S=new Map;this.ea=!0;r(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const c=v(this,a);this.ea&&c.parentElement.removeChild(c);this.S.delete(a)}],["set-visible",a=>{if(this.ea){var c=this.S.get(a.elementId),d=c.wa;c.ya?d.style.display=a.isVisible?"":"none":c.Ba=!!a.isVisible}}],["update-position",a=>{if(this.ea){var c=this.S.get(a.elementId),d=c.wa;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=a.width+
"px";d.style.height=a.height+"px";a=a.fontSize;null!==a&&(d.style.fontSize=a+"em");c.ya||(c.ya=!0,c.Ba&&(d.style.display=""))}}],["update-state",a=>{const c=v(this,a.elementId);this.oa(c,a)}],["focus",a=>this.sa(a)],["set-css-style",a=>{const c=v(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{v(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{v(this,a.elementId).removeAttribute(a.name)}]]);u(this,"get-element",
a=>a)}Ma(){throw Error("required override");}oa(){throw Error("required override");}sa(b){var a=v(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const x=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent),ca=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let z=0;
function A(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Rb?new Promise(c=>{const d="c3_resolve_"+z;++z;self[d]=c;a.textContent=b.Vb+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let da=!1,ea=!1;function fa(){if(!da){try{new Worker("blob://",{get type(){ea=!0}})}catch(b){}da=!0}return ea}let B=new Audio;
const ha={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function ia(b){b=await ja(b);return(new TextDecoder("utf-8")).decode(b)}
function ja(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const C=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,H=new Map;let ka=0;const la=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");la.push(b)};const ma=new Set(["cordova","playable-ad","instant-games"]);let na=!1;
window.D=class b{constructor(a){this.o=a.Xb;this.V=null;this.m="";this.K=a.Ub;this.Y={};this.Da=this.M=null;this.fa=[];this.j=this.H=null;this.Za=!1;this.T=null;this.J=-1;this.Nb=()=>this.Db();this.Ga=[];this.Ia=null;this.bb=[];this.g=a.cb;this.Aa="file"===location.protocol.substr(0,4);!this.o||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&fa()||(this.o=!1);this.o&&ca&&(this.o=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.o=!1;if("cordova"===this.g&&this.o)if(y){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.o=!1)}else this.o=!1;this.B()?self.chrome.webview.addEventListener("message",c=>this.Sa(c.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=c=>this.Sa(c));this.ga=this.A=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime",
"cordova-fetch-local-file",c=>this.zb(c));this.h("runtime","create-job-worker",()=>this.Ab());this.h("runtime","send-wrapper-extension-message",c=>this.Gb(c));"cordova"===this.g?document.addEventListener("deviceready",()=>this.Qa(a)):this.Qa(a)}jb(){return x&&"cordova"===this.g}na(){const a=navigator.userAgent;return x&&ma.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}hb(){return y}Na(){return y&&ma.has(this.g)}B(){return"windows-webview2"===this.g||!!("preview"===this.g&&
window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async Qa(a){"macos-wkwebview"===this.g?this.F({type:"ready"}):this.B()&&(this.Ib(),this.bb=(await this.yb()).registeredComponentIds);if("playable-ad"===this.g){this.A=self.c3_base64files;this.ga={};await this.rb();for(let d=0,e=a.N.length;d<e;++d){var c=a.N[d];this.ga.hasOwnProperty(c)?a.N[d]={Rb:!0,Vb:this.ga[c]}:this.A.hasOwnProperty(c)&&(a.N[d]=URL.createObjectURL(this.A[c]))}a.ka=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=
0;this.nb(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Tb?this.m=a.Tb:(c=location.origin,this.m=("null"===c?"file:///":c)+location.pathname,c=this.m.lastIndexOf("/"),-1!==c&&(this.m=this.m.substr(0,c+1)));a.Zb&&(this.Y=a.Zb);c=new MessageChannel;this.V=c.port1;this.V.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Cb(d));this.T=new self.kb(this);await oa(this.T);"object"===typeof window.StatusBar&&window.StatusBar.hide();
if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.o?await this.xb(a,c.port2):await this.wb(a,c.port2)}qa(a){a=this.Y.hasOwnProperty(a)?this.Y[a]:a.endsWith("/workermain.js")&&this.Y.hasOwnProperty("workermain.js")?this.Y["workermain.js"]:"playable-ad"===this.g&&this.A.hasOwnProperty(a)?this.A[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ma(a,
c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.Aa)return a=await this.la(d.Qb?a:this.K+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}v(){return Math.max(window.innerWidth,1)}u(){return Math.max(window.innerHeight,1)}Pa(a){var c=
this.m,d=location.href,e=this.v(),f=this.u(),g=window.devicePixelRatio,h=b.O(),l=a.ec,m=window.cr_previewImageBlobs||this.A,n=window.cr_previewProjectFileBlobs,Aa=window.cr_previewProjectFiles,Ba=window.cr_swClientId||"";a=a.cb;var Ca=(new URLSearchParams(self.location.search)).has("debug"),L=this.T;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:l,previewImageBlobs:m,previewProjectFileBlobs:n,previewProjectFileSWUrls:Aa,swClientId:Ba,
exportType:a,isDebug:Ca,ife:!!self.dc,jobScheduler:{inputPort:L.za,outputPort:L.Fa,maxNumWorkers:L.Lb},supportedAudioFormats:ha,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.K+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.K+"opus.wasm.wasm",isFileProtocol:this.Aa,isiOSCordova:this.jb(),isiOSWebView:this.na(),isWebView2Wrapper:this.B(),wrapperComponentIds:this.bb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async xb(a,c){const d=this.qa(a.Yb);"preview"===this.g?
(this.M=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,l)=>{const m=n=>{this.M.removeEventListener("message",m);n.data&&"ok"===n.data.type?h():l()};this.M.addEventListener("message",m);this.M.postMessage({type:"construct-worker-init","import":(new URL(d,this.m)).toString()})})):this.M=await this.ma(d,this.m,{type:"module",name:"Runtime",Qb:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);
window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.ka||[],g=a.N;f=await Promise.all(f.map(h=>this.I(h)));g=await Promise.all(g.map(h=>this.I(h)));if("cordova"===this.g)for(let h=0,l=a.ja.length;h<l;++h){const m=a.ja[h],n=m[0];if(n===a.Ja||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m[1]=await this.I(n)}this.M.postMessage(Object.assign(this.Pa(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,
projectScripts:a.ja,mainProjectScript:a.Ja,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...pa(this.T)]);this.fa=F.map(h=>new h(this));this.Oa();qa(this.H);self.c3_callFunction=(h,l)=>{var m=this.H;return m.i.lb(m.R,{name:h,params:l})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.aa("runtime","go-to-last-error-script"))}async wb(a,c){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&
self.C3_InsertHTMLPlaceholders();this.fa=F.map(g=>new g(this));this.Oa();var d=a.N.map(g=>"string"===typeof g?(new URL(g,this.m)).toString():g);if(Array.isArray(a.ka)){var e=[...a.ka].map(g=>g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.I(g)));await Promise.all(d.map(g=>A(g)));d=self.C3_ProjectScriptsStatus;e=a.Ja;const f=a.ja;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.I(h),await A(h),"preview"!==this.g||d[g]||this.Ta(g,"main script did not run to completion")}catch(l){this.Ta(g,
l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.I(h),await A(h);"preview"===this.g&&"object"!==typeof self.$b.bc?(this.ca(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Pa(a),{isInWorker:!1,messagePort:c,canvas:this.j,runOnStartupFunctions:la}),qa(this.H),
this.Ra(),this.Da=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Da,a))}Ta(a,c){this.ca();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ra(){this.ca()}ca(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ab(){const a=await ra(this.T);return{outputPort:a,
transferables:[a]}}vb(){if(this.o)throw Error("not available in worker mode");return this.Da}aa(a,c,d,e){this.V.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},void 0)}lb(a,c){const d=ka++,e=new Promise((f,g)=>{H.set(d,{resolve:f,reject:g})});this.V.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Bb(a);if("result"===
c)this.Eb(a);else if("runtime-ready"===c)this.Fb();else if("alert-error"===c)this.ca(),alert(a.message);else if("creating-runtime"===c)this.Ra();else throw Error(`unknown message '${c}'`);}Bb(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.ba(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.ba(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,
h);this.ba(f,!1,""+h)}):this.ba(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}ba(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.V.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Eb(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}h(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);
e.set(c,d)}static Z(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}Oa(){for(const a of this.fa)if("runtime"===a.R){this.H=a;return}throw Error("cannot find runtime DOM handler");}Cb(a){this.aa("debugger","message",a)}Fb(){for(const a of this.fa)a.Ka()}static O(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||na)}static da(a){na=!!a}nb(a){this.Ga.push(a);this.ua()}ua(){-1===this.J&&this.Ga.length&&(this.J=requestAnimationFrame(this.Nb))}pb(){-1!==
this.J&&(cancelAnimationFrame(this.J),this.J=-1)}Db(){this.J=-1;for(const a of this.Ga)a();this.ua()}ta(){this.H.ta()}mb(){this.Za=!0}gb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}ib(a){return!this.gb(a)}async I(a){return"cordova"===this.g&&(a.startsWith("file:")||this.Aa&&this.ib(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.la(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async zb(a){const c=a.filename;
switch(a.as){case "text":return await this.eb(c);case "buffer":return await this.la(c);default:throw Error("unsupported type");}}La(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async eb(a){a=await this.La(a);return await ia(a)}pa(){if(C.length&&!(8<=E)){E++;var a=C.shift();this.sb(a.filename,a.Wb,a.Pb)}}la(a){return new Promise((c,d)=>{C.push({filename:a,Wb:e=>{E--;this.pa();c(e)},Pb:e=>{E--;this.pa();
d(e)}});this.pa()})}async sb(a,c,d){try{const e=await this.La(a),f=await ja(e);c(f)}catch(e){d(e)}}Sa(a){if("entered-fullscreen"===a)b.da(!0),I(this.H);else if("exited-fullscreen"===a)b.da(!1),I(this.H);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.Ia(a),this.Ia=null):"extension-message"===c?this.aa("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Gb(a){this.F({type:"extension-message",
componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}F(a){this.B()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Ib(){window.moveTo=(a,c)=>{this.F({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.F({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}yb(){return this.B()?new Promise(a=>
{this.Ia=a;this.F({type:"wrapper-init"})}):Promise.resolve()}async rb(){const a=[];for(const [c,d]of Object.entries(this.A))a.push(this.qb(c,d));await Promise.all(a)}async qb(a,c){if("object"===typeof c)this.A[a]=new Blob([c.str],{type:c.type}),this.ga[a]=c.str;else{let d=await this.ub(c);d||(d=this.tb(c));this.A[a]=d}}async ub(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}tb(a){a=this.Hb(a);return this.ob(a.data,a.Sb)}Hb(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Sb:a,data:d}}ob(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,l;for(l=h=0;h<e;++h)g[h]=a.charCodeAt(l++)|a.charCodeAt(l++)<<8|a.charCodeAt(l++)<<16|a.charCodeAt(l++)<<24;for(d&=
3;d--;)f[l]=a.charCodeAt(l),++l;return new Blob([f],{type:c})}};"use strict";const J=self.D;function sa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const ta=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},ua={dispatchUserScriptEvent:!0},M={dispatchRuntimeEvent:!0};
function va(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function wa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function N(b){b=URL.createObjectURL(b);try{return await wa(b)}finally{URL.revokeObjectURL(b)}}
function xa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function ya(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await N(b);var d=await xa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await N(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await N(b)}
function O(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const za=new Set(["input","textarea","datalist","select"]),Da=new Set(["canvas","body","html"]);function P(b){b.target.tagName&&Da.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ea(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await N(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await ya(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Q=!1;document.addEventListener("pause",()=>Q=!0);document.addEventListener("resume",()=>Q=!1);function qa(b){b.Xa=!0;b.Ca=b.i.v();b.U=b.i.u()}function I(b){if(!b.l){var a=J.O();a&&"any"!==b.Ha&&Fa(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.v(),innerHeight:b.u()})}}async function Ga(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ha(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ia(b){return await self.C3_GetSvgImageSize(b.blob)}function Ja(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ka(b){self.setTimeout(()=>{b.Wa=!0},1E3);"cordova"===b.i.g?(document.addEventListener("pause",()=>R(b,!0)),document.addEventListener("resume",()=>R(b,!1))):document.addEventListener("visibilitychange",()=>R(b,"hidden"===document.visibilityState));b.ha=!("hidden"!==document.visibilityState&&!Q);return{isSuspended:b.ha}}
function La(b){b.Va||(b.Va=!0,window.addEventListener("deviceorientation",a=>{b.l||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Ma(b){b.Ua||(b.Ua=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Na(b){await va(b.url)}
function Oa(b,a){b.Ya=a.message;-1===b.xa&&(b.xa=setTimeout(()=>{b.xa=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Ya)},250))}function S(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:J.O(),innerWidth:b.v(),innerHeight:b.u()})}function R(b,a){b.ha!==a&&((b.ha=a)?b.i.pb():b.i.ua(),k(b,"visibilitychange",{hidden:a}))}
function Pa(b,a,c){"Backspace"===c.key&&P(c);if(!b.l){var d=ta.get(c.code)||c.code;p(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K)}}function T(b,a,c,d){b.l||sa(c)||p(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function U(b){window!==window.top&&window.focus();Qa(b.target)&&document.activeElement&&!Qa(document.activeElement)&&document.activeElement.blur()}
function V(b,a,c){if(!b.l){var d=0;"mouse"===c.pointerType&&(d=b.W);p(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&(d="mousemove",
"pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),T(b,d,c,ua),b.W=c.buttons)}}
function W(b,a,c){if(!b.l&&!sa(c)){var d=b.W;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");p(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},K);b.W=c.buttons;T(b,c.type,c,ua)}}
function X(b,a,c){if(!b.l)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];p(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.s,pageX:f.pageX,pageY:f.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
K)}}function Y(b,a,c){document.body.style.transform="";b.s=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.s=a))}}function Ra(b,a,c,d){const e=b.v(),f=b.u();b.L=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.O()}):10>d&&Sa(b,e,f,d+1)}
function Sa(b,a,c,d){-1!==b.L&&clearTimeout(b.L);b.L=setTimeout(()=>Ra(b,a,c,d),48)}
function Fa(b){b=b.Ha;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Qa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.Z(class extends self.${constructor(b){super(b,"runtime");this.$a=!0;this.Xa=!1;this.L=-1;this.Ha="any";this.ha=this.Ua=this.Va=!1;this.ia=document.createElement("div");this.ia.className="c3-screen-reader-text";this.ia.setAttribute("aria-live","polite");document.body.appendChild(this.ia);this.G=null;this.l=!1;this.Ya="";this.xa=-1;this.Wa=!1;this.Ca=b.v();this.U=b.u();this.s=this.X=0;b.h("canvas","update-size",d=>{var e=this.i;e.Za||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.$a&&(e.style.display="",this.$a=!1))});b.h("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.h("runtime","load-webfonts",d=>Ga(d));b.h("runtime","raster-svg-image",d=>Ha(d));b.h("runtime","get-svg-image-size",
d=>Ia(d));b.h("runtime","set-target-orientation",d=>{this.Ha=d.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime","post-to-debugger",d=>Ja(d));b.h("runtime","go-to-script",d=>Ja(d));b.h("runtime","before-start-ticking",()=>Ka(this));b.h("runtime","debug-highlight",d=>{if(d.show){this.G||(this.G=document.createElement("div"),this.G.id="inspectOutline",document.body.appendChild(this.G));var e=this.G;e.style.display="";e.style.left=d.left-
1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.G&&(this.G.style.display="none")});b.h("runtime","enable-device-orientation",()=>La(this));b.h("runtime","enable-device-motion",()=>Ma(this));b.h("runtime","add-stylesheet",d=>Na(d));b.h("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.h("runtime","alert",d=>this.ra(d));b.h("runtime","screen-reader-text",
d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ia.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});b.h("runtime","hide-cordova-splash",
()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",d=>{this.l=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.mb()});b.h("runtime","export-to-video-progress",d=>Oa(this,d));b.h("runtime","exported-to-video",d=>{window.Ob({type:"exported-video",arrayBuffer:d.arrayBuffer,contentType:d.contentType,
time:d.time})});b.h("runtime","exported-to-image-sequence",d=>{window.Ob({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||O(e)||d.preventDefault()});const c=b.j;window.addEventListener("selectstart",P);window.addEventListener("gesturehold",P);c.addEventListener("selectstart",P);c.addEventListener("gesturehold",P);window.addEventListener("touchstart",
P,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",P,{passive:!1}),c.addEventListener("pointerdown",P)):c.addEventListener("touchstart",P);this.W=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ea,{passive:!1});window.addEventListener("wheel",Ea,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.Xa){var d=this.v();var e=this.u();if(this.i.Na()){if(this.Wa){if(this.Ca===d&&e<
this.U){this.X=this.U-e;Y(this,this.U,this.X);d=void 0;break a}0<this.X&&(this.X=0,Y(this,e,this.X))}this.Ca=d;this.U=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.O()});this.i.na()&&(-1!==this.L&&clearTimeout(this.L),Ra(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",()=>I(this));window.addEventListener("fullscreenerror",
d=>S(this,d));window.addEventListener("webkitfullscreenerror",d=>S(this,d));window.addEventListener("mozfullscreenerror",d=>S(this,d));if(b.na())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):O(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Ea=new Set;this.Mb=new WeakSet;this.Kb=!1}Ka(){window.addEventListener("focus",()=>{k(this,"window-focus",null,M)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},M);this.W=0});window.addEventListener("focusin",a=>{a=a.target;(za.has(a.tagName.toLowerCase())||O(a))&&
k(this,"keyboard-blur",null,M)});window.addEventListener("keydown",a=>Pa(this,"keydown",a));window.addEventListener("keyup",a=>Pa(this,"keyup",a));window.addEventListener("dblclick",a=>T(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.l||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.s,pageX:a.pageX,pageY:a.pageY+this.s,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{U(a);V(this,"pointerdown",a)}),this.i.o&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{V(this,"pointermove",a)}):window.addEventListener("pointermove",a=>V(this,"pointermove",a)),window.addEventListener("pointerup",a=>V(this,"pointerup",a)),window.addEventListener("pointercancel",a=>V(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{U(a);W(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>W(this,"pointermove",
a)),window.addEventListener("mouseup",a=>W(this,"pointerup",a)),window.addEventListener("touchstart",a=>{U(a);X(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>X(this,"pointermove",a)),window.addEventListener("touchend",a=>X(this,"pointerup",a)),window.addEventListener("touchcancel",a=>X(this,"pointercancel",a)));const b=()=>this.ta();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.hb()&&!this.i.Na()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Y(this,this.u(),navigator.virtualKeyboard.boundingRect.height)}))}v(){return this.i.v()}u(){return this.i.u()}ta(){var b=[...this.Ea];this.Ea.clear();if(!this.Kb)for(const a of b)(b=a.play())&&b.catch(()=>{this.Mb.has(a)||this.Ea.add(a)})}ra(b){alert(b.message)}});"use strict";
async function oa(b){if(b.Jb)throw Error("already initialised");b.Jb=!0;var a=b.C.qa(("playable-ad"===b.C.g?b.C.K:"")+"dispatchworker.js");b.va=await b.C.ma(a,b.P,{name:"DispatchWorker"});a=new MessageChannel;b.za=a.port1;b.va.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Fa=await ra(b)}function pa(b){return[b.za,b.Fa]}
async function ra(b){const a=b.ab.length;var c=b.C.qa(("playable-ad"===b.C.g?b.C.K:"")+"jobworker.js");c=await b.C.ma(c,b.P,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.va.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.ab.push(c);return e.port1}
self.kb=class{constructor(b){this.C=b;this.P=b.m;this.P="preview"===b.g?this.P+"workers/":this.P+b.K;this.Lb=Math.min(navigator.hardwareConcurrency||2,16);this.va=null;this.ab=[];this.Fa=this.za=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.D({Xb:!0,Yb:"workermain.js",N:["scripts/c3runtime.js"],ja:[],Ja:"",Ub:"scripts/",ka:[],cb:"html5"}));"use strict";
async function Ta(b,a){a=a.type;let c=!0;0===a?c=await Ua():1===a&&(c=await Va());k(b,"permission-result",{type:a,result:c})}async function Ua(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Va(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.D.Z(class extends self.${constructor(b){super(b,"touch");q(this,"request-permission",a=>Ta(this,a))}});"use strict";function Wa(){}
function Xa(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Ya(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.D.Z(class extends self.${constructor(b){super(b,"browser");this.g="";r(this,[["get-initial-state",a=>{this.g=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>Xa(this)],
["alert",a=>this.ra(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.sa(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Ya(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===
a||this.i.B()?window.open(c,"_blank"):this.cc||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.i.B()||"macos-wkwebview"===this.g)self.D.da(!0),this.i.F({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");
a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Wa)}}],["exit-fullscreen",()=>{if(this.i.B()||"macos-wkwebview"===this.g)self.D.da(!1),this.i.F({type:"set-fullscreen",fullscreen:!1});
else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Wa)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);
f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{k(this,"online-state",
{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}ra(b){alert(b.message)}sa(b){b=b.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";function Z(b){b.stopPropagation()}
function Za(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.D.Z(class extends self.fb{constructor(b){super(b);u(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}Ma(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",
Z);c.addEventListener("keydown",Za);c.addEventListener("keyup",Za);c.addEventListener("click",e=>{e.stopPropagation();w(this,"click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();w(this,"dblclick",b)});c.addEventListener("input",()=>t(this,"change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.oa(c,a);return c}oa(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;b.spellcheck=a.spellCheck;
a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});
