function k(a,b,c,d){a.D.Tb(a.Qa,b,c,d,void 0)}function aa(a,b,c){return a.D.Qd(a.Qa,b,c)}function m(a,b,c,d){a.D.ga?k(a,b,c,d):a.D.$d()._OnMessageFromDOM({type:"event",component:a.Qa,handler:b,dispatchOpts:d||null,data:c,responseId:null})}function u(a,b,c){a.D.s(a.Qa,b,c)}function fa(a,b){for(const [c,d]of b)u(a,c,d)}window.nb=class{constructor(a,b){this.D=a;this.Qa=b}Nc(){}ma(){}};window.Ke=class{constructor(){}};"use strict";class ha{constructor(a){this.hc=a;this.lc=!1;this.sc=!0}}
function ia(a,b){const c=b.elementId,d=a.Pb(c,b),e=new ha(d);a.Sa.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.sc=!!b.isVisible;b=a.Yb(d);b.addEventListener("focus",()=>{ja(a,"elem-focused",c)});b.addEventListener("blur",()=>{ja(a,"elem-blurred",c)});a.qb&&document.body.appendChild(d)}function ka(a,b,c){u(a,b,d=>{const e=w(a,d.elementId);return c(e,d)})}function w(a,b){a=a.Sa.get(b);if(!a)throw Error(`no element with id ${b}`);return a.hc}
function ja(a,b,c,d){d||(d={});d.elementId=c;k(a,b,d)}function ma(a,b,c,d){d||(d={});d.elementId=c;m(a,b,d)}
window.Pc=class extends self.nb{constructor(a,b){super(a,b);this.Sa=new Map;this.qb=!0;fa(this,[["create",c=>ia(this,c)],["destroy",c=>{c=c.elementId;const d=w(this,c);this.qb&&d.parentElement.removeChild(d);this.Sa.delete(c)}],["set-visible",c=>{if(this.qb){var d=this.Sa.get(c.elementId),e=d.hc;d.lc?e.style.display=c.isVisible?"":"none":d.sc=!!c.isVisible}}],["update-position",c=>{if(this.qb){var d=this.Sa.get(c.elementId),e=d.hc;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=c.width+
"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.lc||(d.lc=!0,d.sc&&(e.style.display=""))}}],["update-state",c=>{const d=w(this,c.elementId);this.Oa(d,c)}],["focus",c=>{const d=this.Yb(w(this,c.elementId));c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=w(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{w(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{w(this,c.elementId).removeAttribute(c.name)}]]);
ka(this,"get-element",c=>c)}Pb(){throw Error("required override");}Oa(){throw Error("required override");}Yb(a){return a}};"use strict";const na=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),oa=/android/i.test(navigator.userAgent);let pa=0;
function qa(a){const b=document.createElement("script");b.async=!1;b.type="module";return a.Ae?new Promise(c=>{const d="c3_resolve_"+pa;++pa;self[d]=c;b.textContent=a.Ee+`\n\nself["${d}"]();`;document.head.appendChild(b)}):new Promise((c,d)=>{b.onload=c;b.onerror=d;b.src=a;document.head.appendChild(b)})}let ra=!1,sa=!1;function ta(){if(!ra){try{new Worker("blob://",{get type(){sa=!0}})}catch(a){}ra=!0}return sa}let B=new Audio;
const ua={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function va(a){a=await wa(a);return(new TextDecoder("utf-8")).decode(a)}
function wa(a){return new Promise((b,c)=>{const d=new FileReader;d.onload=e=>b(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(a)})}const xa=[];let Aa=0;window.RealFile=window.File;const Ba=[],Ca=new Map,Da=new Map;let Ea=0;const Fa=[];self.runOnStartup=function(a){if("function"!==typeof a)throw Error("runOnStartup called without a function");Fa.push(a)};const Ga=new Set(["cordova","playable-ad","instant-games"]);let Ha=!1;
window.za=class a{constructor(b){this.ga=b.Ge;this.Za=null;this.W="";this.Fa=b.De;this.lb={};this.xc=this.Ja=null;this.ub=[];this.N=this.hb=null;this.jd=!1;this.Xa=null;this.Da=-1;this.re=()=>this.ge();this.Dc=[];this.v=b.sd;this.rc="file"===location.protocol.substr(0,4);!this.ga||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ta()||(this.ga=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ga=!1;if("cordova"===this.v&&this.ga)if(oa){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ga=!1)}else this.ga=!1;this.Ab=this.ja=null;"html5"!==this.v||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.s("runtime","cordova-fetch-local-file",c=>this.ce(c));this.s("runtime","create-job-worker",()=>this.de());"cordova"===this.v?document.addEventListener("deviceready",()=>this.Wc(b)):this.Wc(b)}Od(){return na&&
"cordova"===this.v}Sb(){const b=navigator.userAgent;return na&&Ga.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(b)}Md(){return oa}Sc(){return oa&&Ga.has(this.v)}async Wc(b){"macos-wkwebview"===this.v&&this.ke();if("playable-ad"===this.v){this.ja=self.c3_base64files;this.Ab={};await this.Wd();for(let d=0,e=b.Ka.length;d<e;++d){var c=b.Ka[d];this.Ab.hasOwnProperty(c)?b.Ka[d]={Ae:!0,Ee:this.Ab[c]}:this.ja.hasOwnProperty(c)&&(b.Ka[d]=URL.createObjectURL(this.ja[c]))}b.Lb=[]}if("nwjs"===
this.v&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Sd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}b.Ce?this.W=b.Ce:(c=location.origin,this.W=("null"===c?"file:///":c)+location.pathname,c=this.W.lastIndexOf("/"),-1!==c&&(this.W=this.W.substr(0,c+1)));b.Ie&&(this.lb=b.Ie);c=new MessageChannel;this.Za=c.port1;this.Za.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.fe(d));this.Xa=new self.Pd(this);
await Ia(this.Xa);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ga?await this.be(b,c.port2):await this.ae(b,c.port2)}Zb(b){b=this.lb.hasOwnProperty(b)?this.lb[b]:b.endsWith("/workermain.js")&&this.lb.hasOwnProperty("workermain.js")?this.lb["workermain.js"]:"playable-ad"===this.v&&this.ja.hasOwnProperty(b)?
this.ja[b]:b;b instanceof Blob&&(b=URL.createObjectURL(b));return b}async Qb(b,c,d){if(b.startsWith("blob:"))return new Worker(b,d);if("cordova"===this.v&&this.rc)return b=await this.Ob(d.ze?b:this.Fa+b),new Worker(URL.createObjectURL(new Blob([b],{type:"application/javascript"})),d);b=new URL(b,c);if(location.origin!==b.origin){b=await fetch(b);if(!b.ok)throw Error("failed to fetch worker script");b=await b.blob();return new Worker(URL.createObjectURL(b),d)}return new Worker(b,d)}ha(){return Math.max(window.innerWidth,
1)}ca(){return Math.max(window.innerHeight,1)}Vc(b){var c=this.W,d=location.href,e=this.ha(),f=this.ca(),g=window.devicePixelRatio,h=a.Na(),l=b.Oe,z=window.cr_previewImageBlobs||this.ja,t=window.cr_previewProjectFileBlobs,S=window.cr_previewProjectFiles,F=window.Me||"";b=b.sd;var A=(new URLSearchParams(self.location.search)).has("debug"),q=this.Xa;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:l,previewImageBlobs:z,previewProjectFileBlobs:t,
previewProjectFileSWUrls:S,swClientId:F,exportType:b,isDebug:A,ife:!!self.Ne,jobScheduler:{inputPort:q.pc,outputPort:q.Bc,maxNumWorkers:q.ne},supportedAudioFormats:ua,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Fa+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Fa+"opus.wasm.wasm",isFileProtocol:this.rc,isiOSCordova:this.Od(),isiOSWebView:this.Sb(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async be(b,c){const d=this.Zb(b.He);"preview"===this.v?(this.Ja=new Worker("previewworker.js",
{type:"module",name:"Runtime"}),await new Promise((h,l)=>{const z=t=>{this.Ja.removeEventListener("message",z);t.data&&"ok"===t.data.type?h():l()};this.Ja.addEventListener("message",z);this.Ja.postMessage({type:"construct-worker-init","import":(new URL(d,this.W)).toString()})})):this.Ja=await this.Qb(d,this.W,{type:"module",name:"Runtime",ze:!0});this.N=document.createElement("canvas");this.N.style.display="none";const e=this.N.transferControlToOffscreen();document.body.appendChild(this.N);window.c3canvas=
this.N;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=b.Lb||[],g=b.Ka;f=await Promise.all(f.map(h=>this.Aa(h)));g=await Promise.all(g.map(h=>this.Aa(h)));if("cordova"===this.v)for(let h=0,l=b.Kb.length;h<l;++h){const z=b.Kb[h],t=z[0];if(t===b.Lc||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))z[1]=await this.Aa(t)}this.Ja.postMessage(Object.assign(this.Vc(b),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:b.Kb,
mainProjectScript:b.Lc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...Ja(this.Xa)]);this.ub=Ba.map(h=>new h(this));this.Uc();Ka(this.hb);self.c3_callFunction=(h,l)=>aa(this.hb,"js-invoke-function",{name:h,params:l});"preview"===this.v&&(self.goToLastErrorScript=()=>this.Tb("runtime","go-to-last-error-script"))}async ae(b,c){this.N=document.createElement("canvas");this.N.style.display="none";document.body.appendChild(this.N);window.c3canvas=this.N;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();
this.ub=Ba.map(g=>new g(this));this.Uc();var d=b.Ka.map(g=>"string"===typeof g?(new URL(g,this.W)).toString():g);Array.isArray(b.Lb)&&d.unshift(...b.Lb);d=await Promise.all(d.map(g=>this.Aa(g)));await Promise.all(d.map(g=>qa(g)));d=self.C3_ProjectScriptsStatus;const e=b.Lc,f=b.Kb;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Aa(h),await qa(h),"preview"!==this.v||d[g]||this.Yc(g,"main script did not run to completion")}catch(l){this.Yc(g,l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=
await this.Aa(h),await qa(h);"preview"===this.v&&"object"!==typeof self.Je.Le?(this.pb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(b=Object.assign(this.Vc(b),{isInWorker:!1,messagePort:c,canvas:this.N,runOnStartupFunctions:Fa}),Ka(this.hb),this.Xc(),this.xc=self.C3_CreateRuntime(b),await self.C3_InitRuntime(this.xc,
b))}Yc(b,c){this.pb();console.error(`[Preview] Failed to load project main script (${b}): `,c);alert(`Failed to load project main script (${b}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Xc(){this.pb()}pb(){const b=window.we;b&&(b.parentElement.removeChild(b),window.we=null)}async de(){const b=await La(this.Xa);return{outputPort:b,transferables:[b]}}$d(){if(this.ga)throw Error("not available in worker mode");return this.xc}Tb(b,c,d,e,f){this.Za.postMessage({type:"event",
component:b,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}Qd(b,c,d){const e=Ea++,f=new Promise((g,h)=>{Da.set(e,{resolve:g,reject:h})});this.Za.postMessage({type:"event",component:b,handler:c,dispatchOpts:null,data:d,responseId:e},void 0);return f}_OnMessageFromRuntime(b){const c=b.type;if("event"===c)return this.ee(b);if("result"===c)this.he(b);else if("runtime-ready"===c)this.ie();else if("alert-error"===c)this.pb(),alert(b.message);else if("creating-runtime"===c)this.Xc();else throw Error(`unknown message '${c}'`);
}ee(b){const c=b.component,d=b.handler,e=b.data,f=b.responseId;if(b=Ca.get(c))if(b=b.get(d)){var g=null;try{g=b(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.ob(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.ob(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.ob(f,!1,""+h)}):this.ob(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}ob(b,
c,d){let e;d&&d.transferables&&(e=d.transferables);this.Za.postMessage({type:"result",responseId:b,isOk:c,result:d},e)}he(b){const c=b.responseId,d=b.isOk;b=b.result;const e=Da.get(c);d?e.resolve(b):e.reject(b);Da.delete(c)}s(b,c,d){let e=Ca.get(b);e||(e=new Map,Ca.set(b,e));if(e.has(c))throw Error(`[DOM] Component '${b}' already has handler '${c}'`);e.set(c,d)}static Ma(b){if(Ba.includes(b))throw Error("DOM handler already added");Ba.push(b)}Uc(){for(const b of this.ub)if("runtime"===b.Qa){this.hb=
b;return}throw Error("cannot find runtime DOM handler");}fe(b){this.Tb("debugger","message",b)}ie(){for(const b of this.ub)b.Nc()}static Na(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||Ha)}static Zc(b){Ha=!!b}Sd(b){this.Dc.push(b);this.ac()}ac(){-1===this.Da&&this.Dc.length&&(this.Da=requestAnimationFrame(this.re))}Ud(){-1!==this.Da&&(cancelAnimationFrame(this.Da),this.Da=-1)}ge(){this.Da=-1;for(const b of this.Dc)b();this.ac()}$b(){this.hb.$b()}Rd(){this.jd=
!0}Ld(b){return/^(?:[a-z\-]+:)?\/\//.test(b)||"data:"===b.substr(0,5)||"blob:"===b.substr(0,5)}Nd(b){return!this.Ld(b)}async Aa(b){return"cordova"===this.v&&(b.startsWith("file:")||this.rc&&this.Nd(b))?(b.startsWith(this.W)&&(b=b.substr(this.W.length)),b=await this.Ob(b),URL.createObjectURL(new Blob([b],{type:"application/javascript"}))):b}async ce(b){const c=b.filename;switch(b.as){case "text":return await this.Jd(c);case "buffer":return await this.Ob(c);default:throw Error("unsupported type");}}Oc(b){const c=
window.cordova.file.applicationDirectory+"www/"+b;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Jd(b){b=await this.Oc(b);return await va(b)}Xb(){if(xa.length&&!(8<=Aa)){Aa++;var b=xa.shift();this.Xd(b.filename,b.Fe,b.xe)}}Ob(b){return new Promise((c,d)=>{xa.push({filename:b,Fe:e=>{Aa--;this.Xb();c(e)},xe:e=>{Aa--;this.Xb();d(e)}});this.Xb()})}async Xd(b,c,d){try{const e=await this.Oc(b),f=await wa(e);c(f)}catch(e){d(e)}}ke(){var b={type:"ready"};if("windows-webview2"===
this.v)window.chrome.webview.postMessage(JSON.stringify(b));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(b));else throw Error("cannot send wrapper message");}async Wd(){const b=[];for(const [c,d]of Object.entries(this.ja))b.push(this.Vd(c,d));await Promise.all(b)}async Vd(b,c){if("object"===typeof c)this.ja[b]=new Blob([c.str],{type:c.type}),this.Ab[b]=c.str;else{let d=await this.Zd(c);d||(d=this.Yd(c));this.ja[b]=d}}async Zd(b){try{return await (await fetch(b)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Yd(b){b=this.je(b);return this.Td(b.data,b.Be)}je(b){var c=b.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=b.substring(c+1);c=b.substring(5,c).split(";");b=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Be:b,data:d}}Td(b,c){var d=b.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,l;for(l=h=0;h<e;++h)g[h]=b.charCodeAt(l++)|b.charCodeAt(l++)<<8|b.charCodeAt(l++)<<16|b.charCodeAt(l++)<<24;for(d&=
3;d--;)f[l]=b.charCodeAt(l),++l;return new Blob([f],{type:c})}};"use strict";const D=self.za;function Ma(a){return a.sourceCapabilities&&a.sourceCapabilities.firesTouchEvents||a.originalEvent&&a.originalEvent.sourceCapabilities&&a.originalEvent.sourceCapabilities.firesTouchEvents}const Na=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),G={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Oa={dispatchUserScriptEvent:!0},Pa={dispatchRuntimeEvent:!0};
function Qa(a){return new Promise((b,c)=>{const d=document.createElement("link");d.onload=()=>b(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=a;document.head.appendChild(d)})}function Ra(a){return new Promise((b,c)=>{const d=new Image;d.onload=()=>b(d);d.onerror=e=>c(e);d.src=a})}async function Sa(a){a=URL.createObjectURL(a);try{return await Ra(a)}finally{URL.revokeObjectURL(a)}}
function Ta(a){return new Promise((b,c)=>{let d=new FileReader;d.onload=e=>b(e.target.result);d.onerror=e=>c(e);d.readAsText(a)})}
async function Ua(a,b,c){if(!/firefox/i.test(navigator.userAgent))return await Sa(a);var d=await Ta(a);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await Sa(a)}e.setAttribute("width",b+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);a=new Blob([d],{type:"image/svg+xml"});return await Sa(a)}
function Va(a){do{if(a.parentNode&&a.hasAttribute("contenteditable"))return!0;a=a.parentNode}while(a);return!1}const Wa=new Set(["input","textarea","datalist","select"]),Xa=new Set(["canvas","body","html"]);function I(a){a.target.tagName&&Xa.has(a.target.tagName.toLowerCase())&&a.preventDefault()}function Ya(a){(a.metaKey||a.ctrlKey)&&a.preventDefault()}
self.C3_GetSvgImageSize=async function(a){a=await Sa(a);if(0<a.width&&0<a.height)return[a.width,a.height];a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.visibility="hidden";document.body.appendChild(a);const b=a.getBoundingClientRect();document.body.removeChild(a);return[b.width,b.height]};self.C3_RasterSvgImageBlob=async function(a,b,c,d,e){a=await Ua(a,b,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(a,0,0,b,c);return f};
let Za=!1;document.addEventListener("pause",()=>Za=!0);document.addEventListener("resume",()=>Za=!1);function Ka(a){a.fd=!0;a.wc=a.D.ha();a.Ya=a.D.ca()}async function $a(a){await Promise.all(a.webfonts.map(async b=>{b=new FontFace(b.name,`url('${b.url}')`);document.fonts.add(b);await b.load()}))}
async function ab(a){var b=a.imageBitmapOpts;a=await self.C3_RasterSvgImageBlob(a.blob,a.imageWidth,a.imageHeight,a.surfaceWidth,a.surfaceHeight);b=b?await createImageBitmap(a,b):await createImageBitmap(a);return{imageBitmap:b,transferables:[b]}}async function bb(a){return await self.C3_GetSvgImageSize(a.blob)}function cb(a){window.c3_postToMessagePort&&(a.from="runtime",window.c3_postToMessagePort(a))}
function db(a){self.setTimeout(()=>{a.ed=!0},1E3);"cordova"===a.D.v?(document.addEventListener("pause",()=>eb(a,!0)),document.addEventListener("resume",()=>eb(a,!1))):document.addEventListener("visibilitychange",()=>eb(a,document.hidden));return{isSuspended:!(!document.hidden&&!Za)}}
function fb(a){a.ad||(a.ad=!0,window.addEventListener("deviceorientation",b=>{a.S||k(a,"deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},G)}),window.addEventListener("deviceorientationabsolute",b=>{a.S||k(a,"deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},G)}))}
function gb(a){a.$c||(a.$c=!0,window.addEventListener("devicemotion",b=>{if(!a.S){var c=null,d=b.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=b.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=b.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(a,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:b.interval,timeStamp:b.timeStamp},G)}}))}async function hb(a){await Qa(a.url)}
function ib(a,b){a.gd=b.message;-1===a.ic&&(a.ic=setTimeout(()=>{a.ic=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=a.gd)},250))}function jb(a){if(!a.S){var b=D.Na();b&&"any"!==a.Ic&&kb(a);k(a,"fullscreenchange",{isFullscreen:b,innerWidth:a.ha(),innerHeight:a.ca()})}}function lb(a,b){console.warn("[Construct] Fullscreen request failed: ",b);k(a,"fullscreenerror",{isFullscreen:D.Na(),innerWidth:a.ha(),innerHeight:a.ca()})}
function eb(a,b){b?a.D.Ud():a.D.ac();k(a,"visibilitychange",{hidden:b})}function mb(a,b,c){"Backspace"===c.key&&I(c);if(!a.S){var d=Na.get(c.code)||c.code;m(a,b,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},G)}}
function ob(a,b,c,d){a.S||Ma(c)||m(a,b,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+a.X,pageX:c.pageX,pageY:c.pageY+a.X,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function pb(a){window!==window.top&&window.focus();qb(a.target)&&document.activeElement&&!qb(document.activeElement)&&document.activeElement.blur()}
function rb(a,b,c){if(!a.S){var d=0;"mouse"===c.pointerType&&(d=a.$a);m(a,b,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+a.X,pageX:c.pageX,pageY:c.pageY+a.X,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},G);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===b?d="mousedown":"pointerup"===b&&(d="mouseup"),ob(a,d,c,Oa),a.$a=c.buttons)}}
function sb(a,b,c){if(!a.S&&!Ma(c)){var d=a.$a;"pointerdown"===b&&0!==d?b="pointermove":"pointerup"===b&&0!==c.buttons&&(b="pointermove");m(a,b,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+a.X,pageX:c.pageX,pageY:c.pageY+a.X,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},G);a.$a=c.buttons;ob(a,c.type,c,Oa)}}
function tb(a,b,c){if(!a.S)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];m(a,b,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+a.X,pageX:f.pageX,pageY:f.pageY+a.X,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
G)}}function ub(a,b,c){document.body.style.transform="";a.X=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),b=(d.top+d.bottom)/2-(b-c)/2,b>c&&(b=c),0>b&&(b=0),0<b&&(document.body.style.transform=`translateY(${-b}px)`,a.X=b))}}function vb(a,b,c,d){const e=a.ha(),f=a.ca();a.Ga=-1;e!=b||f!=c?k(a,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:D.Na()}):10>d&&wb(a,e,f,d+1)}
function wb(a,b,c,d){-1!==a.Ga&&clearTimeout(a.Ga);a.Ga=setTimeout(()=>vb(a,b,c,d),48)}
function kb(a){a=a.Ic;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(a).catch(b=>console.warn("[Construct] Failed to lock orientation: ",b));else try{let b=!1;screen.lockOrientation?b=screen.lockOrientation(a):screen.webkitLockOrientation?b=screen.webkitLockOrientation(a):screen.mozLockOrientation?b=screen.mozLockOrientation(a):screen.msLockOrientation&&(b=screen.msLockOrientation(a));b||console.warn("[Construct] Failed to lock orientation")}catch(b){console.warn("[Construct] Failed to lock orientation: ",
b)}}function qb(a){return!a||a===document||a===window||a===document.body||"canvas"===a.tagName.toLowerCase()}
D.Ma(class extends self.nb{constructor(a){super(a,"runtime");this.kd=!0;this.fd=!1;this.Ga=-1;this.Ic="any";this.$c=this.ad=!1;this.Bb=document.createElement("div");this.Bb.className="c3-screen-reader-text";this.Bb.setAttribute("aria-live","polite");document.body.appendChild(this.Bb);this.ua=null;this.S=!1;this.gd="";this.ic=-1;this.ed=!1;this.wc=a.ha();this.Ya=a.ca();this.X=this.kb=0;a.s("canvas","update-size",d=>{var e=this.D;e.jd||(e=e.N,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.kd&&(e.style.display="",this.kd=!1))});a.s("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});a.s("runtime","load-webfonts",d=>$a(d));a.s("runtime","raster-svg-image",d=>ab(d));a.s("runtime","get-svg-image-size",
d=>bb(d));a.s("runtime","set-target-orientation",d=>{this.Ic=d.targetOrientation});a.s("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});a.s("runtime","post-to-debugger",d=>cb(d));a.s("runtime","go-to-script",d=>cb(d));a.s("runtime","before-start-ticking",()=>db(this));a.s("runtime","debug-highlight",d=>{if(d.show){this.ua||(this.ua=document.createElement("div"),this.ua.id="inspectOutline",document.body.appendChild(this.ua));var e=this.ua;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.ua&&(this.ua.style.display="none")});a.s("runtime","enable-device-orientation",()=>fb(this));a.s("runtime","enable-device-motion",()=>gb(this));a.s("runtime","add-stylesheet",d=>hb(d));a.s("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});a.s("runtime","alert",d=>{alert(d.message)});
a.s("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.Bb.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
a.s("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});a.s("runtime","set-exporting-to-video",d=>{this.S=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.D.N.style.display="";this.D.Rd()});a.s("runtime","export-to-video-progress",d=>ib(this,d));a.s("runtime","exported-to-video",d=>{window.ve({type:"exported-video",
blob:d.blob,time:d.time})});a.s("runtime","exported-to-image-sequence",d=>{window.ve({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const b=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;b.has(e.tagName.toLowerCase())||Va(e)||d.preventDefault()});const c=a.N;window.addEventListener("selectstart",I);window.addEventListener("gesturehold",I);c.addEventListener("selectstart",I);c.addEventListener("gesturehold",I);window.addEventListener("touchstart",
I,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",I,{passive:!1}),c.addEventListener("pointerdown",I)):c.addEventListener("touchstart",I);this.$a=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ya,{passive:!1});window.addEventListener("wheel",Ya,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.S&&this.fd){var d=this.ha();var e=this.ca();if(this.D.Sc()){if(this.ed){if(this.wc===d&&
e<this.Ya){this.kb=this.Ya-e;ub(this,this.Ya,this.kb);d=void 0;break a}0<this.kb&&(this.kb=0,ub(this,e,this.kb))}this.wc=d;this.Ya=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:D.Na()});this.D.Sb()&&(-1!==this.Ga&&clearTimeout(this.Ga),vb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>jb(this));window.addEventListener("webkitfullscreenchange",()=>jb(this));window.addEventListener("mozfullscreenchange",()=>
jb(this));window.addEventListener("fullscreenerror",d=>lb(this,d));window.addEventListener("webkitfullscreenerror",d=>lb(this,d));window.addEventListener("mozfullscreenerror",d=>lb(this,d));if(a.Sb())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=
new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Va(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(D.Zc(!0),jb(this)):"exited-fullscreen"===d?(D.Zc(!1),jb(this)):console.warn("Unknown wrapper message: ",d)};this.yc=new Set;this.pe=new WeakSet;this.me=!1}Nc(){window.addEventListener("focus",()=>{k(this,"window-focus",null,Pa)});window.addEventListener("blur",
()=>{try{var b=window.parent&&window.parent.document.hasFocus()}catch(c){b=!1}k(this,"window-blur",{parentHasFocus:b},Pa);this.$a=0});window.addEventListener("focusin",b=>{b=b.target;(Wa.has(b.tagName.toLowerCase())||Va(b))&&k(this,"keyboard-blur",null,Pa)});window.addEventListener("keydown",b=>mb(this,"keydown",b));window.addEventListener("keyup",b=>mb(this,"keyup",b));window.addEventListener("dblclick",b=>ob(this,"dblclick",b,G));window.addEventListener("wheel",b=>{this.S||k(this,"wheel",{clientX:b.clientX,
clientY:b.clientY+this.X,pageX:b.pageX,pageY:b.pageY+this.X,deltaX:b.deltaX,deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,timeStamp:b.timeStamp},G)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",b=>{pb(b);rb(this,"pointerdown",b)}),this.D.ga&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",b=>{rb(this,"pointermove",b)}):window.addEventListener("pointermove",b=>rb(this,"pointermove",b)),window.addEventListener("pointerup",
b=>rb(this,"pointerup",b)),window.addEventListener("pointercancel",b=>rb(this,"pointercancel",b))):(window.addEventListener("mousedown",b=>{pb(b);sb(this,"pointerdown",b)}),window.addEventListener("mousemove",b=>sb(this,"pointermove",b)),window.addEventListener("mouseup",b=>sb(this,"pointerup",b)),window.addEventListener("touchstart",b=>{pb(b);tb(this,"pointerdown",b)}),window.addEventListener("touchmove",b=>tb(this,"pointermove",b)),window.addEventListener("touchend",b=>tb(this,"pointerup",b)),window.addEventListener("touchcancel",
b=>tb(this,"pointercancel",b)));const a=()=>this.$b();window.addEventListener("pointerup",a,!0);window.addEventListener("touchend",a,!0);window.addEventListener("click",a,!0);window.addEventListener("keydown",a,!0);window.addEventListener("gamepadconnected",a,!0);this.D.Md()&&!this.D.Sc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{ub(this,this.ca(),navigator.virtualKeyboard.boundingRect.height)}))}ha(){return this.D.ha()}ca(){return this.D.ca()}$b(){var a=
[...this.yc];this.yc.clear();if(!this.me)for(const b of a)(a=b.play())&&a.catch(()=>{this.pe.has(b)||this.yc.add(b)})}});"use strict";async function Ia(a){if(a.le)throw Error("already initialised");a.le=!0;var b=a.pa.Zb(("playable-ad"===a.pa.v?a.pa.Fa:"")+"dispatchworker.js");a.fc=await a.pa.Qb(b,a.Pa,{name:"DispatchWorker"});b=new MessageChannel;a.pc=b.port1;a.fc.postMessage({type:"_init","in-port":b.port2},[b.port2]);a.Bc=await La(a)}function Ja(a){return[a.pc,a.Bc]}
async function La(a){const b=a.ld.length;var c=a.pa.Zb(("playable-ad"===a.pa.v?a.pa.Fa:"")+"jobworker.js");c=await a.pa.Qb(c,a.Pa,{name:"JobWorker"+b});const d=new MessageChannel,e=new MessageChannel;a.fc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:b,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);a.ld.push(c);return e.port1}
self.Pd=class{constructor(a){this.pa=a;this.Pa=a.W;this.Pa="preview"===a.v?this.Pa+"workers/":this.Pa+a.Fa;this.ne=Math.min(navigator.hardwareConcurrency||2,16);this.fc=null;this.ld=[];this.Bc=this.pc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.za({Ge:!0,He:"workermain.js",Ka:["scripts/c3runtime.js"],Kb:[],Lc:"",De:"scripts/",Lb:[],sd:"html5"}));"use strict";function J(a){a.stopPropagation()}function xb(a){13!==a.which&&27!==a.which&&a.stopPropagation()}
self.za.Ma(class extends self.Pc{constructor(a){super(a,"text-input");ka(this,"scroll-to-bottom",b=>{b.scrollTop=b.scrollHeight})}Pb(a,b){let c;const d=b.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",J);c.addEventListener("pointermove",J);c.addEventListener("pointerrawupdate",J);c.addEventListener("pointerup",J);c.addEventListener("mousedown",
J);c.addEventListener("mouseup",J);c.addEventListener("keydown",xb);c.addEventListener("keyup",xb);c.addEventListener("click",e=>{e.stopPropagation();ma(this,"click",a)});c.addEventListener("dblclick",e=>{e.stopPropagation();ma(this,"dblclick",a)});c.addEventListener("input",()=>ja(this,"change",a,{text:c.value}));b.id&&(c.id=b.id);b.className&&(c.className=b.className);this.Oa(c,b);return c}Oa(a,b){a.value=b.text;a.placeholder=b.placeholder;a.title=b.title;a.disabled=!b.isEnabled;a.readOnly=b.isReadOnly;
a.spellcheck=b.spellCheck;b=b.maxLength;0>b?a.removeAttribute("maxlength"):a.setAttribute("maxlength",b)}});"use strict";function L(a){a.stopPropagation()}
self.za.Ma(class extends self.Pc{constructor(a){super(a,"button")}Pb(a,b){const c=document.createElement("input");var d=c;b.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",L);d.addEventListener("pointermove",
L);d.addEventListener("pointerrawupdate",L);d.addEventListener("pointerup",L);d.addEventListener("mousedown",L);d.addEventListener("mouseup",L);d.addEventListener("keydown",L);d.addEventListener("keyup",L);c.addEventListener("click",()=>ma(this,"click",a,{isChecked:c.checked}));b.id&&(c.id=b.id);b.className&&(c.className=b.className);this.Oa(d,b);return d}Yb(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}Oa(a,b){const c="input"===a.tagName.toLowerCase()?a:a.firstChild;c.checked=b.isChecked;
c.disabled=!b.isEnabled;a.title=b.title;a===c?c.value=b.text:a.lastChild.textContent=b.text}});"use strict";const yb=[],zb=2*Math.PI;function Ab(a){a%=zb;0>a&&(a+=zb);return a}function Bb(a,b){switch(a.oa){case 0:return b;case 1:return Math.fround(b);case 2:return 2===a.Ta&&(b=Ab(b),b/=Math.PI,b=32767*(b-1)),a=b|0,-32768>a?-32768:32767<a?32767:a;case 3:return 2===a.Ta&&(b=Ab(b),b/=zb,b*=255),a=b|0,0>a?0:255<a?255:a;default:return b}}
function Cb(a,b,c,d){switch(a.oa){case 0:b.setFloat64(c,d);c+=8;break;case 1:b.setFloat32(c,d);c+=4;break;case 2:b.setInt16(c,d);c+=2;break;case 3:b.setUint8(c,d);c+=1;break;default:b.setFloat32(c,d),c+=4}return c}function Db(a,b){if(2!==a.Ta)return b;2===a.oa?b=(b/32767+1)*Math.PI:3===a.oa&&(b=b/255*zb);return b}
function Eb(a,b,c,d,e){switch(a){case 0:return e?c:b;case 1:return b+d*(c-b);case 2:return b===c?a=0:(a=Math.sin(b)*Math.sin(c)+Math.cos(b)*Math.cos(c),a=1<=a?0:-1>=a?Math.PI:Math.acos(a)),0>=Math.cos(c)*Math.sin(b)-Math.sin(c)*Math.cos(b)?Ab(b+a*d):Ab(b-a*d);default:return e?c:b}}class Fb{constructor(a,b,c,d,e,f){this.hd=a;this.Ta=b;this.oa=c;this.jb=d;this.Fb=e;this.cd=f}ya(){return{tag:this.jb,interp:this.Ta,userData:this.Fb,cvt:this.cd}}la(){return this.Ta}}
class Gb{constructor(a,b){this.timestamp=a;this.data=b}}
class Hb{constructor(a,b,c){this.O=a;this.g=a.g;this.l=b;this.G=c;this.Ra=[];this.Ra.length=this.O.U.length;this.vc=this.xb=0;this.qc=this.Db=!1;this.I=[];this.B=this.j=this.aa=null}ya(){var a=[];for(let c=0,d=this.O.U.length;c<d;++c)a.push(this.la(this.O.Cb,c));a={id:this.l,nid:this.G,isTimedOut:0===this.I.length?!1:this.I[this.I.length-1].timestamp<this.O.Cb-3E3,interpValues:a,latestUpdate:null};const b=0===this.I.length?null:this.I[this.I.length-1];b&&(a.latestUpdate={timestamp:b.timestamp,data:b.data});
return a}Vb(a,b){a=a.netValues;var c=this.O.U;const d=c.length;this.Db=!1;for(let e=0;e<d;++e){const f=Bb(c[e],a[e]);this.Ra[e]!==f&&(this.Ra[e]=f,this.xb=b,this.O.xb=b)}a=b-this.xb;b-=this.vc;c=this.O.bd;(this.Db=100>a&&0===c?!0:1E3>a&&1>=c?95<=b:495<=b)&&this.O.cb++}Wb(a,b,c){const d=this.O.U;this.vc=c;a.setUint16(b,this.G);b+=2;for(let e=0,f=this.Ra.length;e<f;++e)b=Cb(d[e],a,b,this.Ra[e]);return b}Mb(a,b){for(let c=0,d=this.I.length;c<d;++c){const e=this.I[c];if(e.timestamp===a)return;if(e.timestamp>
a){this.I.splice(c,0,new Gb(a,b));return}}this.I.push(new Gb(a,b))}ma(){for(;2<this.I.length&&this.I[0]!==this.aa&&this.I[0]!==this.j&&this.I[0]!==this.B;)this.I.shift();const a=this.O.Cb;if(!(this.B&&this.B.timestamp>a&&this.j&&this.j.timestamp<a)){this.B=null;for(let b=0,c=this.I.length;b<c;++b){const d=this.I[b];if(d.timestamp<=a){if(!this.j||d.timestamp>this.j.timestamp)this.aa=this.j,this.j=d}else{this.B=d;break}}}}la(a,b){if(!this.B&&!this.j)return 0;if(this.B&&!this.j)return this.B.data[b];
const c=this.O.U;let d,e,f;if(!this.B&&this.j){if(this.aa){var g=this.aa.timestamp;d=this.aa.data[b];e=this.j.timestamp;f=this.j.data[b];a>this.j.timestamp+this.O.wb&&(a=this.j.timestamp+this.O.wb);g=g===e?0:(a-g)/(e-g);return Eb(c[b].la(),d,f,g,!0)}return this.j.data[b]}g=this.j.timestamp;d=this.j.data[b];e=this.B.timestamp;f=this.B.data[b];return Eb(c[b].la(),d,f,g===e?0:(a-g)/(e-g),!1)}}
function M(a,b,c,d,e,f){b=new Fb(a.U.length,b,c,d,e,f);switch(c){case 0:a.fa+=8;break;case 1:a.fa+=4;break;case 2:a.fa+=2;break;case 3:a.fa+=1}a.U.push(b)}function Ib(a,b){const c=b.l,d=b.G;a.g.h()&&!a.Ba&&a.tb.push(d);a.wa.delete(c);a.bb.delete(d);a.Ha.delete(d);b=a.$.indexOf(b);-1<b&&a.$.splice(b,1)}function Kb(a,b){(b=a.bb.get(b))&&Ib(a,b)}function Lb(a){return{roId:a.gb,sid:a.ib,netValues:a.U.map(b=>b.ya())}}
class Mb{constructor(a,b,c,d){this.g=a;this.gb=b;this.ib=c;this.G=this.g.qe++;this.bd=d;this.Fb={};this.fa=0;this.wb=250;switch(this.bd){case 1:this.wb=500;break;case 2:this.wb=2500}this.U=[];this.$=[];this.wa=new Map;this.Ha=new Set;this.cb=this.vc=this.xb=this.ab=0;this.Ba=!1;this.tb=[];this.bb=new Map;this.Cb=0;a=this.g;a.Y.push(this);a.fb.set(this.gb,this);a.Ea.set(this.G,this)}qa(a){this.G=a}Mb(a,b,c){{let d=this.bb.get(b);d||(d=new Hb(this,-1,b),this.bb.set(b,d),this.$.push(d));b=d}b.Mb(a,c)}ma(){this.Cb=
Nb(this.g);for(const a of this.$)a.ma()}Vb(a,b){this.cb=0;for(var c of this.$)c.qc=!1;for(let f=0,g=a.length;f<g;++f){c=a[f];var d=c.uid;var e=this.wa.get(d);if(!e){e=d;do this.ab++,65535<this.ab&&(this.ab=0);while(this.Ha.has(this.ab));const h=this.ab;this.Ha.add(h);e=new Hb(this,e,h);this.wa.set(d,e);this.$.push(e)}d=e;d.qc=!0;d.Vb(c,b)}for(const f of this.$)f.qc||yb.push(f);for(const f of yb)Ib(this,f);yb.length=0}Wb(a,b,c){a.setUint16(b,this.G);b+=2;let d=0;this.Ba&&(d=1);a.setUint8(b,d);b+=1;
a.setUint16(b,this.cb);b+=2;a.setUint16(b,this.fa);b+=2;for(const e of this.$)e.Db&&(b=e.Wb(a,b,c));return b}Ub(a){(a=this.wa.get(a))&&Ib(this,a)}ya(){return{hasOverriddenNids:this.Ba,netValues:this.U.map(a=>a.ya()),netInstances:this.$.map(a=>a.ya())}}}self.Gd=Fb;self.Fd=Gb;self.Id=Mb;"use strict";const Ob=self.Fd,Pb=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection;function Qb(a){if(a)try{a.close()}catch(b){}}const O=[];
function Rb(a){return new Promise(b=>setTimeout(b,a))}async function Sb(a){if(a.Cc.length&&!(a.bc>=a.oe)){a.bc++;var b=a.Cc.shift();try{const c=await b.ye();b.resolve(c)}catch(c){b.reject(c)}a.bc--;Sb(a)}}function Tb(a,b){return new Promise((c,d)=>{a.Cc.push({ye:b,resolve:c,reject:d});Sb(a)})}class Ub{constructor(){this.oe=1;this.Cc=[];this.bc=0}}async function Vb(a,b,c){const d=Wb(a,b,c.data);c=d;"o"===b&&(c=Tb(a.se,()=>d));(c=await c)&&Xb(a,b,c)}
function P(a,b,c){if(!a.Ia){a.Ia=!0;Yb(a,b);Q(a,"o",JSON.stringify({c:"disconnect",r:b,k:!!c}));var d=a.ra,e=a.sa,f=a.ta,g=a.o;setTimeout(()=>{Qb(d);Qb(e);Qb(f);Qb(g)},0);a.ra=null;a.sa=null;a.ta=null;a.o=null;a.Ua=!1;a.Va=!1;a.Wa=!1;Zb(a.g,a)}}
function $b(a,b,c){b.binaryType="arraybuffer";b.onopen=()=>{"o"===c?a.Ua=!0:"r"===c?a.Va=!0:"u"===c&&(a.Wa=!0);if(!a.na&&a.Va&&a.Wa&&a.Ua){a.tc=performance.now();if(a.g.h()){R(a.g,"o",JSON.stringify({c:"j",i:a.l,n:a.G,a:a.K}),0,a);var d=Q,e=JSON,f=e.stringify,g=a.g.C.G,h=a.G,l=a.g.Z,z=a.g.eb,t=a.g;var S={};for(const [q,p]of t.Ea.entries()){t=p.ib;var F=p;const H=[];for(var A of F.U)F={tag:A.jb,precision:A.oa,interp:A.la(),clientvaluetag:A.cd},"undefined"!==typeof A.Fb&&(F.userdata=A.Fb),H.push(F);
S[t]={nid:q,nvs:H}}A=a.g;t=[];for(const q of A.da)t.push({tag:q.jb,precision:q.oa,interp:q.la()});d(a,"o",f.call(e,{c:"hi",hn:g,n:h,d:l,u:z,objs:S,cvs:t,comp:ac}));for(const q of a.g.ea)!q.h()&&q!==a&&q.na&&!q.va&&Q(a,"o",JSON.stringify({c:"j",i:q.l,n:q.G,a:q.K}))}else a.mc=!0,a.h()&&bc(a,performance.now(),!0),Q(a,"o",JSON.stringify({c:"comp",comp:ac}));cc(a.g,a);a.na=!0;a.va=!1}};b.onmessage=d=>{Vb(a,c,d)};b.onerror=d=>{console.error("Peer '"+a.l+"' datachannel '"+c+"' error: ",d);T(a,d);a.g.h()&&
!a.h()&&P(a,"network error")};b.onclose=()=>{P(a,"disconnect")}}
function dc(a){if(a!==a.g.A){var b=a.g.h();a.Ua=!1;a.Va=!1;a.Wa=!1;a.na=!1;a.va=!1;a.dd=performance.now();a.o=new Pb({iceServers:a.g.oc});a.o.onicecandidate=d=>{d.candidate&&V(a.g,{message:"icecandidate",toclientid:a.l,icecandidate:d.candidate})};a.o.onsignalingstatechange=()=>{a.o&&"closed"===a.o.signalingState&&P(a,"disconnect")};a.o.oniceconnectionstatechange=()=>{a.o&&("failed"!==a.o.iceConnectionState&&"closed"!==a.o.iceConnectionState||P(a,"disconnect"))};a.o.onconnectionstatechange=()=>{if(a.o){var d=
a.o.connectionState;"failed"!==d&&"closed"!==d||P(a,"disconnect")}};var c=`c3mp_${a.g.jc}_${a.g.kc}_${a.g.F}`;b?(a.G=ec(a.g),a.ra=a.o.createDataChannel("o",{ordered:!0,protocol:c}),$b(a,a.ra,"o"),a.sa=a.o.createDataChannel("r",{ordered:!1,protocol:c}),$b(a,a.sa,"r"),a.ta=a.o.createDataChannel("u",{ordered:!1,maxRetransmits:0,protocol:c}),$b(a,a.ta,"u"),a.o.createOffer().then(d=>{a.o.setLocalDescription(d);V(a.g,{message:"offer",toclientid:a.l,offer:d})}).catch(d=>{console.error("Host error creating offer for peer '"+
a.l+"': ",d);T(a,"could not create offer for peer")})):a.o.ondatachannel=d=>{if(d.channel.protocol!==c)console.error("Unexpected datachannel protocol '"+d.channel.protocol+"', should be '"+c+"'"),T(a,"unexpected datachannel protocol '"+d.channel.protocol+"', should be '"+c+"'"),a.Ia||(P(a,"datachannel protocol error"),k(a.g,"peer-kicked"));else{var e=d.channel.label;"o"===e?a.ra=d.channel:"r"===e?a.sa=d.channel:"u"===e?a.ta=d.channel:(console.error("Unknown datachannel label: "+d.channel.label),T(a,
"unknown datachannel label '"+d.channel.label+"'"));$b(a,d.channel,e)}}}}async function fc(a,b){if(a.o)try{await a.o.addIceCandidate(b)}catch(c){console.warn("[Multiplayer] Error adding ICE candidate: ",c)}}async function Q(a,b,c,d=0){gc(a.g,c);const e=hc(a,b,c,d);c=e;"o"===b&&(c=Tb(a.te,()=>e));(c=await c)&&ic(a,b,c)}
function bc(a,b,c){a.Ia||(!c&&(!a.na||a.va)&&a.o&&25E3<b-a.dd?(console.warn("Timed out '"+a.K+"', could not establish connection after 25sec"),P(a,"timeout")):!c&&a.na&&!a.va&&2E4<b-a.tc?(console.warn("Timed out '"+a.K+"', not heard from for 20sec"),P(a,"timeout")):(a.md=b,a.dc=!0,a.uc++,Q(a,"u","ping:"+a.uc)))}function Yb(a,b){!a.va&&a.na&&(a.g.h()&&a!==a.g.A&&R(a.g,"o",JSON.stringify({c:"l",i:a.l,a:a.K,r:b}),0,a),a===a.g.A||jc(a.g,a,b),a.va=!0,a.na=!1)}
function kc(a,b){const c=ac;for(const d of b)c.includes(d)&&a.cc.push(d)}async function lc(a,b){if(0===a.cc.length)return{Gb:0,data:b};const c=new Blob([b]);if(64>c.size)return{Gb:0,data:b};a=a.cc[0];var d=new CompressionStream(a);d=c.stream().pipeThrough(d);d=await (new Response(d)).arrayBuffer();if(d.byteLength>=c.size)return{Gb:0,data:b};b=W.Nb.indexOf(a);if(0>b)throw Error("invalid compression type");return{Gb:b,data:d}}
async function hc(a,b,c,d=0){var e="string"===typeof c;const {Gb:f,data:g}=await lc(a,c);c=g;g instanceof ArrayBuffer&&(0!==f&&(d|=f<<4,e&&(d|=W.Rc)),c=new ArrayBuffer(g.byteLength+8),e=new DataView(c),e.setUint32(0,W.Tc),e.setUint32(4,d),(new Uint8Array(c,8)).set(new Uint8Array(g)));a.g.P.Mc++;d=a.g;d.P.Ib+=mc(c);d=a.g.Gc;e=a.g.Fc;a=a.g.Hc;if(0<d&&"u"===b&&Math.random()<d)return null;if(0!==e||0!==a){let h=1;"u"!==b&&Math.random()<d&&(h=3);await Rb((e+Math.random()*a)*h)}return c}
function ic(a,b,c){try{"o"===b?a.Ua&&a.ra&&a.ra.send(c):"r"===b?a.Va&&a.sa&&a.sa.send(c):"u"===b&&a.Wa&&a.ta&&a.ta.send(c)}catch(d){a.Ia||(a.g.h()?"o"===b||"r"===b?("string"===typeof c?(console.error("Error sending "+c.length+"-char string on '"+b+"' to '"+a.K+"', host kicking: ",d),console.log("String that failed to send from previous error was: "+c)):console.error("Error sending "+(c.length||c.byteLength)+"-byte binary on '"+b+"' to '"+a.K+"', host kicking: ",d),P(a,"network error")):(a.vb++,10<=
a.vb&&("string"===typeof c?(console.error("Too many errors ("+a.vb+") sending data on '"+b+"' to '"+a.K+"', kicking; last error was for sending "+c.length+"-char string: ",d),console.log("String that failed to send from previous error was: "+c)):console.error("Too many errors ("+a.vb+") sending data on '"+b+"' to '"+a.K+"', kicking; last error was for sending "+(c.length||c.byteLength)+"-byte binary: ",d),P(a,"network error"))):console.error("Error sending data on '"+b+"': ",d))}}
function nc(a,b){if(a.dc){var c=b.indexOf(":");if(-1<c){if(parseFloat(b.substr(c+1))===a.uc){c=performance.now();a.dc=!1;var d=(c-a.md)/2;a.yb.push(d);10<a.yb.length&&a.yb.shift();O.push(...a.yb);O.sort((h,l)=>h-l);a.rd=O[O.length-1]-O[0];var e=0,f=O.length;4<=O.length&&6>=O.length?(++e,--f):6<O.length&&(e+=2,f-=2);var g=0;for(let h=e;h<f;++h)g+=O[h];a.zb=g/(f-e);O.length=0;a.g.h()||(e=b.indexOf("/"),-1<e?(b=parseFloat(b.substr(e+1)),isFinite(b)?oc(a.g,b,c,d,a.zb):console.warn("Invalid host time from pong response")):
console.warn("Cannot parse off host time from pong response"))}}else console.warn("Cannot parse off ping ID from pong")}}async function Wb(a,b,c){a.g.P.Jc++;var d=a.g;d.P.Hb+=mc(c);d=a.g.Gc;const e=a.g.Fc;a=a.g.Hc;if(0<d&&"u"===b&&Math.random()<d)return null;if(0!==e||0!==a){let f=1;"u"!==b&&Math.random()<d&&(f=3);await Rb(e*f+Math.random()*a*f)}return c instanceof ArrayBuffer?await pc(c):c}
function Xb(a,b,c){if(!a.Ia)if(a.tc=performance.now(),"string"===typeof c){var d=a.g;d.P.La+=mc(c);if(!(""===c.trim()||4>c.length))if(d=c.substr(0,4),"ping"===d)d="pong:"+c.substr(5),a.g.h()&&(d=d+"/"+Math.round(performance.now()).toString()),Q(a,"u",d);else if("pong"===d)nc(a,c);else{try{var e=JSON.parse(c)}catch(n){T(a,n);a.g.h()?(console.error("Error parsing message as JSON for peer '"+a.l+"', host kicking: ",n),P(a,"data error")):console.error("Error parsing message as JSON for peer '"+a.l+"': ",
n);console.log("String that failed to parse from previous error: "+c);return}if(e)try{if(e.c&&"m"!==e.c){d=e;let n,v;switch(d.c){case "disconnect":d.k&&k(a.g,"peer-kicked");v=!a.g.h()&&!a.h();P(a,d.r);v&&qc(a.g);break;case "hi":if(!a.g.h()){a.g.C.qa(d.hn);a.g.A.qa(d.n);a.g.Z=d.d;a.g.eb=d.u;var f=a.g,g=d.objs;f.Ea.clear();for(const x of f.Y)if(g.hasOwnProperty(x.ib.toString())){const K=g[x.ib.toString()];x.qa(K.nid);f.Ea.set(K.nid,x);var h=x,l=K.nvs;h.U.length=0;h.fa=0;for(const E of l)M(h,E.interp,
E.precision,E.tag,E.userdata,E.clientvaluetag)}else console.warn("Could not map object SID '"+x.ib+"' - host did not send NID for it"),x.qa(-1);var z=a.g,t=d.cvs;z.rb.clear();z.da.length=0;for(let x=0,K=t.length;x<K;++x){const E=t[x],U=new rc(x,E.interp,E.precision,E.tag,null);z.rb.set(U.jb,U);z.da.push(U)}z.Ec=!0;d.hasOwnProperty("comp")&&kc(a,d.comp)}break;case "comp":kc(a,d.comp);break;case "j":a.g.h()||(n=new W(a.g,d.i,d.a),n.qa(d.n),cc(a.g,n));break;case "l":!a.g.h()&&(n=a.g.V.get(d.i)||null)&&
(n===n.g.A||jc(a.g,n,d.r),P(n,d.r));break;default:console.error("Unknown control message from peer '"+a.l+"': "+d.c),T(a,"unknown control message '"+d.c+"'")}}else{var S=a.g;d=e;const n=d.f||a.l;k(S,"peer-message",{tag:d.t,fromId:n,fromAlias:sc(S,n),transmissionMode:b,content:d.m,contentMode:d.cm||"e"})}}catch(n){T(a,n),a.g.h()?(console.error("Error handling message for peer '"+a.l+"', host kicking: ",n),P(a,"data error")):console.error("Error handling message for peer '"+a.l+"': ",n)}}}else{f=a.g;
f.P.La+=mc(c.data);!a.mc&&a.g.h()&&"u"===b&&(a.mc=!0,f=a.g,f.T&&f.h()&&V(f,{message:"confirm-peer",id:a.l}));try{var F=c.data,A=c.offset,q=c.flags;if(0===(q&W.Rb)){const n=new DataView(F,A);if(a.g.h()){h=n;var p=0,H=h.getFloat64(p);p+=8;H+=a.zb;if(!(3E3<=Math.abs(H-performance.now()))){var y=h.getUint8(p);p+=1;d=[];var la=a.g.da;for(var ba=0;ba<y;++ba)if(ba>=la.length)d.push(0);else{var ca=la[ba],N=void 0;switch(ca.oa){case 0:N=h.getFloat64(p);p+=8;break;case 1:N=h.getFloat32(p);p+=4;break;case 2:N=
Db(ca,h.getInt16(p));p+=2;break;case 3:N=Db(ca,h.getUint8(p));p+=1;break;default:N=h.getFloat32(p),p+=4}d.push(N)}a:{h=H;for(let v=0,x=a.R.length;v<x;++v){var r=a.R[v];if(r.timestamp===h)break a;if(r.timestamp>h){a.R.splice(v,0,new Ob(h,d));break a}}a.R.push(new Ob(h,d))}}}else if(r=n,0===(q&W.Qc))for(y=0,d=r.getFloat64(y),y+=8,h=r.getUint16(y),y+=2,la=0;la<h;++la){p=r.getUint16(y);y+=2;ba=r.getUint8(y);y+=1;H=null;ca=0;const v=a.g.Ea.get(p)||null;v?(H=v.U,ca=H.length,1===ba&&(v.Ba=!0)):console.warn("Don't know which object corresponds to NID "+
p);const x=r.getUint16(y);y+=2;const K=r.getUint16(y);y+=2;for(N=0;N<x;++N){const E=r.getUint16(y);y+=2;if(v){var ya=[],C=y;for(var da=0;da<ca;++da){const U=H[da];let ea;switch(U.oa){case 0:ea=r.getFloat64(C);C+=8;break;case 1:ea=r.getFloat32(C);C+=4;break;case 2:ea=Db(U,r.getInt16(C));C+=2;break;case 3:ea=Db(U,r.getUint8(C));C+=1;break;default:ea=r.getFloat32(C),C+=4}ya.push(ea)}v.Mb(d,E,ya)}y+=K}}else for(d=0,ya=r.getFloat64(d),d+=8,C=r.getUint16(d),d+=2,h=0;h<C;++h){da=r.getUint16(d);d+=2;const v=
a.g.Ea.get(da)||null;v||console.warn("Don't know which object corresponds to NID "+da);const x=r.getUint16(d);d+=2;for(p=0;p<x;++p){const K=r.getUint16(d);d+=2;v&&!v.Ba&&(k(a.g,"instance-destroyed",{roId:v.gb,nid:K,timestamp:ya}),Kb(v,K))}}}else{var Jb=a.g,Dc=0===A?F:F.slice(A);const n=a.l;k(Jb,"peer-message",{fromId:n,fromAlias:sc(Jb,n),transmissionMode:b,content:Dc,contentMode:"s"})}}catch(n){T(a,n),a.g.h()?(console.error("Error handling binary update for peer '"+a.l+"', host kicking: ",n),P(a,
"data error")):console.error("Error handling binary update for peer '"+a.l+"': ",n)}}}
async function pc(a){if(8>a.byteLength)return console.warn(`Rejected binary message as too small (only ${a.byteLength} bytes)`),null;var b=new DataView(a),c=b.getUint32(0);b=b.getUint32(4);if(c!==W.Tc)return console.warn(`Rejected binary message with invalid magic number (0x${c.toString(16)})`),null;c=(b&W.Kd)>>4;if(0===c)return{data:a,offset:8,flags:b};if(c>=W.Nb.length)throw Error("invalid compression type");c=W.Nb[c];a=new Blob([new Uint8Array(a,8)]);c=new DecompressionStream(c);a=a.stream().pipeThrough(c);
a=await (new Response(a)).arrayBuffer();return 0===(b&W.Rc)?{data:a,offset:0,flags:b}:(new TextDecoder).decode(a)}
function tc(a,b){b=b.hd;if(!a.B&&!a.j)return 0;if(a.B&&!a.j)return a=a.B.data,0>b||b>=a.length?0:a[b];var c=Nb(a.g);let d,e,f;if(!a.B&&a.j){if(a.aa){var g=a.aa.timestamp;d=a.aa.data[b];e=a.j.timestamp;f=a.j.data[b];c>a.j.timestamp+250&&(c=a.j.timestamp+250);g=g===e?0:(c-g)/(e-g);return Eb(a.g.da[b].la(),d,f,g,!0)}a=a.j.data;return 0>b||b>=a.length?0:a[b]}g=a.j.timestamp;d=a.j.data[b];e=a.B.timestamp;f=a.B.data[b];return Eb(a.g.da[b].la(),d,f,g===e?0:(c-g)/(e-g),!1)}
class W{constructor(a,b,c){this.g=a;this.l=b;this.G=0;this.K=c;this.ra=this.o=null;this.Ua=!1;this.sa=null;this.Va=!1;this.ta=null;this.Wa=!1;this.te=new Ub;this.se=new Ub;this.mc=this.Ia=this.va=this.na=!1;this.vb=this.dd=this.tc=0;this.cc=[];this.qd=[];this.od=this.nd=0;this.R=[];this.B=this.j=this.aa=null;this.md=0;this.dc=!1;this.uc=1;this.yb=[];this.rd=this.zb=0;a=this.g;a.ea.push(this);a.V.set(this.l,this);k(a,"add-peer",{id:this.l,alias:this.K})}qa(a){this.G=a}h(){return this===this.g.C}ma(a){if(0!==
this.R.length){for(;2<this.R.length&&this.R[0]!==this.aa&&this.R[0]!==this.j&&this.R[0]!==this.B;)this.R.shift();if(!(this.B&&this.B.timestamp>a&&this.j&&this.j.timestamp<a)){this.B=null;for(let b=0,c=this.R.length;b<c;++b){const d=this.R[b];if(d.timestamp<=a){if(!this.j||d.timestamp>this.j.timestamp)this.aa=this.j,this.j=d}else{this.B=d;break}}}}}}W.Tc=1664314736;W.Qc=1;W.Rc=2;W.Rb=4;W.Kd=240;W.Nb=["none","deflate","gzip"];self.Hd=W;"use strict";
const rc=self.Gd,uc=self.Hd,vc=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection,wc=window.RTCSessionDescription||window.webkitRTCSessionDescription||window.mozRTCSessionDescription||window.msRTCSessionDescription,xc=window.RTCIceCandidate||window.webkitRTCIceCandidate||window.mozRTCIceCandidate||window.msRTCIceCandidate,yc=window.RTCDataChannel||window.webkitRTCDataChannel||window.mozRTCDataChannel||window.msRTCDataChannel,zc=[{urls:"stun:stun.l.google.com:19302"}];
function Ac(a){if("undefined"===typeof CompressionStream||"function"!==typeof Blob.prototype.stream)return!1;try{return new CompressionStream(a),!0}catch(b){return!1}}function mc(a){if("number"===typeof a.byteLength)return a.byteLength;if("number"===typeof a.length)return a.length;console.warn("[Construct] Multiplayer: don't know how to measure size of data: ",a);return 0}const ac=[];Ac("deflate")&&ac.push("deflate");Ac("gzip")&&ac.push("gzip");let Bc=!1;const X=[];
function Nb(a){return a.h()?performance.now()-a.Z:performance.now()+a.J-a.M}function T(a,b){console.error(`[Multiplayer] Peer '${a.K}' (${a.l}) error: `,b)}function V(a,b){a.H&&a.ia&&a.H.send(JSON.stringify(b))}function ec(a){if(a.h()){do a.Ca++,65535<a.Ca&&(a.Ca=0);while(a.Eb.has(a.Ca));var b=a.Ca;a.Eb.add(b);return b}}function R(a,b,c,d=0,e=null){if(a.h()){var f=a.ea.slice(0);for(const g of f)g&&g!==a.A&&g!==e&&Q(g,b,c,d)}}function cc(a,b){k(a,"peer-open",{id:b.l,alias:b.K})}
function jc(a,b,c){k(a,"peer-close",{id:b.l,alias:b.K,reason:c||"unknown"})}function gc(a,b){a.P.Jb+=mc(b)}function oc(a,b,c,d,e){if(!a.h()){a.ka=e+a.Z;b=b+d-c;0===a.xa.length&&(a.J=b,a.M=a.ka);a.xa.push(b);30<a.xa.length&&a.xa.shift();X.push(...a.xa);X.sort((f,g)=>f-g);b=0;c=X.length;4<=X.length&&6>=X.length?(++b,--c):6<X.length&&19>=X.length?(b+=2,c-=2):19<X.length&&(b+=5,c-=5);d=0;for(e=b;e<c;++e)d+=X[e];a.ba=d/(c-b);X.length=0}}
function qc(a){if(a.T){var b=Y(a.L.wd);V(a,{message:"leave"});return b}}function Zb(a,b){k(a,"remove-peer",{id:b.l});a.h()&&a.h()&&a.Eb.delete(b.G);const c=a.ea.indexOf(b);-1<c&&a.ea.splice(c,1);a.V.delete(b.l);a.C===b&&(a.C=null,Cc(a,"host quit"));a.A===b&&(a.A=null,a.F="",Cc(a,"disconnect"))}function Ec(a,b){if(b)for(let c of b){"string"===typeof c&&(c={urls:c});a:{for(const d of a.oc)if(d.urls===c.urls){b=!0;break a}b=!1}b||(c.hasOwnProperty("url")||(c.url=c.urls),a.oc.push(c))}}
function Cc(a,b){if(!Bc){for(Bc=!0;a.ea.length;)P(a.ea[0],b);Bc=!1}}
function Fc(a,b){if(a.H||a.ia)return Promise.resolve();const c=Y(a.L.connect);try{a.H=new WebSocket(b,"c2multiplayer")}catch(d){return a.H=null,Z(a,d),c}a.H.onopen=()=>{-1===a.H.protocol.indexOf("c2multiplayer")?(Z(a,"server does not support 'c2multiplayer' protocol"),a.H.close(1002,"'c2multiplayer' protocol required"),a.H=null,a.ia=!1):a.ia=!0};a.H.onclose=()=>{k(a,"signalling-close");a.ia=!1;a.T=!1;a.H=null};a.H.onerror=d=>{console.error("Signalling server error: ",d);Z(a,d)};a.H.onmessage=d=>{a:{try{var e=
JSON.parse(d.data)}catch(f){Z(a,f);break a}switch(e.message){case "welcome":d=e;1>d.protocolrev||1<d.protocolrev?(Z(a,"signalling server protocol revision not supported"),Gc(a)):(a.Ac=d.clientid,a.F="",e=a.ue,e.Ed=d.protocolrev,e.version=d.version,e.name=d.name,e.Ad=d.operator,e.zd=d.motd,Ec(a,d.ice_servers),k(a,"signalling-welcome",{myid:a.Ac,sigservinfo:{protocolrev:e.Ed,version:e.version,name:e.name,operator:e.Ad,motd:e.zd}}),Hc(a.L.connect));break;case "login-ok":a.zc=e.alias;a.T=!0;k(a,"signalling-login-ok",
{myalias:a.zc});Hc(a.L.login);break;case "join-ok":d=e;Cc(a,"disconnect");a.jc=d.game;a.kc=d.instance;a.F=d.room;a.A=new uc(a,a.Ac,a.zc);d.host?(a.C=a.A,a.Ca=0,a.Eb.clear(),a.C.qa(ec(a))):(a.xa.length=0,a.ba=0,a.J=0,a.Z=80,a.nc=30,a.eb=30,a.ka=a.Z,a.M=a.Z,a.C=new uc(a,d.hostid,d.hostalias),dc(a.C));k(a,"signalling-join-ok",{isHost:!!d.host,hostId:a.C.l,hostAlias:a.C.K,game:a.jc,gameInstance:a.kc,room:a.F});Hc(a.L.Kc);break;case "leave-ok":a.F="";k(a,"signalling-leave-ok");Hc(a.L.wd);break;case "kicked":"host-left"===
e.reason?Gc(a):(Ic(a),a.F="",k(a,"signalling-kicked"));break;case "peer-joined":d=e;a.T&&a.F&&a.h()&&((e=a.V.get(d.peerid))&&P(e,"rejoin"),dc(new uc(a,d.peerid,d.peeralias)));break;case "peer-quit":d=e;a.T&&a.F&&a.h()&&(e=a.V.get(d.id))&&P(e,d.reason);break;case "icecandidate":d=e;a.T&&a.F&&(e=a.V.get(d.from))&&fc(e,new xc(d.icecandidate));break;case "offer":Jc(a,e);break;case "answer":Kc(a,e);break;case "instance-list":k(a,"signalling-instance-list",{list:e.list});Hc(a.L.xd);break;case "room-list":k(a,
"signalling-room-list",{list:e.list});Hc(a.L.yd);break;case "error":Z(a,e.details);break;default:Z(a,"received unknown signalling message")}}};return c}function Gc(a){a.H&&a.ia&&(a.H.close(),a.H=null,a.ia=!1)}function Ic(a,b){a.xa.length=0;a.ba=0;a.J=0;Cc(a,"disconnect");for(const d of a.Y){var c=d;c.tb.length=0;c.wa.clear();c.bb.clear();c.Ha.clear();c.$.length=0}b&&qc(a)}
function Lc(a,b,c){if(!a.h()&&a.A&&a.Ec&&(b=a.rb.get(b))){b=b.hd;var d=a.A.qd;d.length<b+1&&(d.length=b+1);d[b]!==c&&(d[b]=c,a.A.nd=performance.now())}}function Y(a){a.reject&&a.reject("overlapping signalling operation");return new Promise((b,c)=>{a.resolve=b;a.reject=c})}function Hc(a){a.resolve&&a.resolve(void 0);a.resolve=null;a.reject=null}
function Z(a,b){k(a,"signalling-error",{message:b?"string"===typeof b?b:"string"===typeof b.message?b.message:"string"===typeof b.details?b.details:"string"===typeof b.data?b.data:"string"===typeof b.type?b.type:"unknown error":"unknown error"});for(const c of Object.values(a.L))c.reject&&c.reject(b),c.resolve=null,c.reject=null}
function Jc(a,b){if(a.T&&a.F&&!a.h()&&a.A&&a.C&&a.C.o&&b.from===a.C.l){var c=a.C.o;c.setRemoteDescription(new wc(b.offer)).then(()=>{c.createAnswer().then(d=>{c.setLocalDescription(d);V(a,{message:"answer",toclientid:a.C.l,answer:d})}).catch(d=>{console.error("Peer error creating answer: ",d);T(a.A,"could not create answer to host offer")})}).catch(d=>{console.error("Peer error setting remote description: ",d);T(a.A,"could not set remote description")})}}
function Kc(a,b){a.T&&a.F&&a.h()&&(a=a.V.get(b.from))&&a.o.setRemoteDescription(new wc(b.answer)).catch(c=>{console.error("Host error setting remote description: ",c)})}function sc(a,b){return(a=a.V.get(b))?a.K:""}
async function Mc(a,b){if(a.h()){await Nc(a,b);const c=a.ec;let d=0,e=0;for(const f of a.Y)f.tb.length&&e++;if(0!==e){c.setFloat64(d,b);d+=8;c.setUint16(d,e);d+=2;for(const f of a.Y)if(b=f.tb,b.length){c.setUint16(d,f.G);d+=2;c.setUint16(d,b.length);d+=2;for(const g of b)c.setUint16(d,g),d+=2;b.length=0}R(a,"r",a.sb.slice(0,d),uc.Qc)}}else await Oc(a,b)}
async function Nc(a,b){const c=a.ec;let d=0,e=0;const f=await aa(a,"get-object-info",{ros:a.Y.map(g=>Lb(g))});for(const g of a.Y){const h=g.gb;f.hasOwnProperty(h)&&(g.Vb(f[h],b),0<g.cb&&e++)}if(0!==e){c.setFloat64(d,b);d+=8;c.setUint16(d,e);d+=2;for(const g of a.Y)0<g.cb&&(d=g.Wb(c,d,b));R(a,"u",a.sb.slice(0,d),0)}}
async function Oc(a,b){a.F&&(a.h()||0!==a.ba)&&await Qc(a);if(a.A&&a.Ec){var c=a.ec,d=0,e=a.da,f=a.A.qd,g=b-a.A.nd,h=b-a.A.od;if(100>g||(1E3>g?95<=h:495<=h)){c.setFloat64(d,b+a.J);d+=8;c.setUint8(d,e.length);d+=1;for(let l=0,z=e.length;l<z;++l)g=e[l],h=0,l<f.length&&(h=Bb(g,f[l])),d=Cb(g,c,d,h);a.A.od=b;Q(a.C,"u",a.sb.slice(0,d))}}}async function Qc(a){const b=await aa(a,"before-client-update");for(const c of b.clientStateUpdates)Lc(a,c.tag,c.value)}
self.za.Ma(class extends self.nb{constructor(a){super(a,"multiplayer");this.oc=[];this.H=null;this.T=this.ia=!1;this.ue={Ed:0,version:0,name:"",Ad:"",zd:""};this.F=this.kc=this.jc=this.zc=this.Ac="";this.ea=[];this.V=new Map;this.Ca=0;this.Eb=new Set;this.C=this.A=null;this.Z=80;this.eb=this.nc=30;this.pd=0;this.P={mb:0,Dd:0,Mc:0,Bd:0,Cd:0,Ib:0,Jb:0,vd:0,Jc:0,td:0,ud:0,Hb:0,La:0};this.sb=new ArrayBuffer(262144);this.ec=new DataView(this.sb);this.Y=[];this.qe=1;this.Ea=new Map;this.fb=new Map;this.Gc=
this.Hc=this.Fc=0;this.xa=[];this.J=this.ba=0;this.M=this.ka=this.Z;this.da=[];this.rb=new Map;this.Ec=!1;this.L={connect:{resolve:null,reject:null},login:{resolve:null,reject:null},Kc:{resolve:null,reject:null},wd:{resolve:null,reject:null},xd:{resolve:null,reject:null},yd:{resolve:null,reject:null}};Ec(this,zc);setInterval(()=>{const b=performance.now();if(this.h()){X.push(...this.ea);for(const c of X)c&&c!==this.A&&bc(c,b,!1);X.length=0}else this.C&&bc(this.C,b,!1)},2E3);window.addEventListener("unload",
()=>Cc(this,"quit"));u(this,"get-supported",()=>({isSupported:!(!vc||!yc)}));u(this,"add-ice-servers",b=>Ec(this,b.list));u(this,"simulate-latency",b=>{var c=b.pdv,d=b.loss;this.Fc=Math.max(b.latency,0);this.Hc=Math.max(c,0);this.Gc=Math.max(d,0)});u(this,"set-bandwidth-profile",b=>{var c=b.updateRate;b=b.delay;this.F||(this.eb=this.nc=c,this.Z=b)});u(this,"tick",b=>this.ma(b));u(this,"alert",b=>{alert(b.message)});u(this,"signalling-connect",b=>Fc(this,b.url));u(this,"signalling-disconnect",()=>
Gc(this));u(this,"signalling-login",b=>{b=b.alias;if(this.T)b=void 0;else{var c=Y(this.L.login);V(this,{message:"login",protocolrev:1,datachannelrev:2,compressionformats:ac,alias:b});b=c}return b});u(this,"signalling-join-room",b=>{var c=b.game;var d=b.instance,e=b.room;b=b.maxClients;if(this.T&&!this.F){var f=Y(this.L.Kc);V(this,{message:"join",game:c,instance:d,room:e,max_clients:b});c=f}else c=void 0;return c});u(this,"signalling-auto-join-room",b=>{var c=b.game;var d=b.instance,e=b.room,f=b.maxClients;
b=b.lock;if(this.T&&!this.F){var g=Y(this.L.Kc);V(this,{message:"auto-join",game:c,instance:d,room:e,max_clients:f,lock_when_full:b});c=g}else c=void 0;return c});u(this,"signalling-leave-room",()=>qc(this));u(this,"signalling-list-game-instances",b=>{b=b.game;if(this.H&&this.ia){var c=Y(this.L.xd);V(this,{message:"list-instances",game:b});b=c}else b=void 0;return b});u(this,"signalling-list-rooms",b=>{var c=b.game;var d=b.instance;b=b.which;if(this.H&&this.ia){var e=Y(this.L.yd);V(this,{message:"list-rooms",
game:c,instance:d,which:b});c=e}else c=void 0;return c});u(this,"disconnect-room",()=>Ic(this,!0));u(this,"peer-send-message",b=>{const c=b.tag;var d=b.message;const e=b.transmissionMode,f=b.contentMode;if(b=this.V.get(b.id)||null)"s"===f&&d instanceof ArrayBuffer?Q(b,e,d,uc.Rb):(d={c:"m",cm:f,m:d},"e"===f&&(d.t=c),Q(b,e,JSON.stringify(d)))});u(this,"host-broadcast",b=>{var c=b.fromId;const d=b.tag,e=b.message,f=b.transmissionMode;b=b.contentMode;const g=this.V.get(c)||null;"s"===b&&e instanceof ArrayBuffer?
R(this,f,e,uc.Rb,g):(c={c:"m",cm:b,f:c,m:e},"e"===b&&(c.t=d),R(this,f,JSON.stringify(c),0,g))});u(this,"kick-peer",b=>{if(this.h()){var c=b.reason;(b=this.V.get(b.id)||null)&&P(b,c,!0)}});u(this,"sync-object",b=>{const c=b.data,d=b.precision,e=b.bandwidth;for(const f of b.objectClasses)b=new self.Id(this,f.roId,f.sid,e),1===c?(M(b,1,d,"x"),M(b,1,d,"y")):2===c?M(b,2,d,"a"):3===c&&(M(b,1,d,"x"),M(b,1,d,"y"),M(b,2,d,"a"))});u(this,"sync-inst-var",b=>{const c=b.precision,d=b.interp,e=b.cvt;for(const f of b.syncData)M(this.fb.get(f.roId),
d,c,"iv",f.varIndex,e)});u(this,"associate-object",b=>{var c=b.peerId;const d=b.instUid;b=this.fb.get(b.roId);c=this.V.get(c);if(b&&c&&this.h())if(c=c.G,b.wa.has(d))console.warn("OverrideNid passed id "+d+" which is already in use and cannot be overridden");else if(b.Ha.has(c))console.warn("OverrideNid passed nid "+c+" which is already in use and cannot be overridden");else{var e=new Hb(b,d,c);b.wa.set(d,e);b.Ha.add(c);b.$.push(e);b.Ba=!0}});u(this,"remove-object-id",b=>this.Ub(b.uid));u(this,"remove-net-insts",
b=>{for(const [c,d]of Object.entries(b))if(b=this.fb.get(parseInt(c,10)))for(const e of d)Kb(b,e)});u(this,"remove-object-nid",b=>{const c=b.nid;(b=this.fb.get(b.roId))&&Kb(b,c)});u(this,"set-client-state",b=>Lc(this,b.tag,b.value));u(this,"add-client-input-value",b=>{var c=b.tag;b=new rc(this.da.length,b.interp,b.precision,c,null);this.rb.set(c,b);this.da.push(b)})}h(){return!!this.F&&this.A&&this.C===this.A}ma(a){if(!this.F)return null;a=a.dt;var b=performance.now();b-this.pd>=1E3/(this.h()?this.nc:
this.eb)-5&&(Mc(this,b),this.pd=b);var c=this.P;1E3<=b-c.mb&&(c.Dd=c.Mc,c.Bd=c.Ib,c.Cd=c.Jb,c.vd=c.Jc,c.td=c.Hb,c.ud=c.La,c.Mc=0,c.Ib=0,c.Jb=0,c.Jc=0,c.Hb=0,c.La=0,c.mb+=1E3,500<b-c.mb&&(c.mb=b),k(this,"stats",{stats:{outboundPerSec:c.Dd,outboundBandwidthPerSec:c.Bd,outboundDecompressedBandwidthPerSec:c.Cd,inboundPerSec:c.vd,inboundBandwidthPerSec:c.td,inboundDecompressedBandwidthPerSec:c.ud}}));this.h()||(this.J<this.ba?(this.J+=10*a,this.J>this.ba&&(this.J=this.ba)):this.J>this.ba&&(this.J-=10*
a,this.J<this.ba&&(this.J=this.ba)),this.M<this.ka?(this.M+=30*a,this.M>this.ka&&(this.M=this.ka)):this.M>this.ka&&(this.M-=30*a,this.M<this.ka&&(this.M=this.ka)));a=Nb(this);for(var d of this.ea)d.ma(a);for(var e of this.Y)e.ma();d=Nb(this);e=this.h()?performance.now():performance.now()+this.J+this.M;a=this.Z;b={};for(var f of this.ea){c={};for(const g of this.da)c[g.jb]=tc(f,g);b[f.l]={nid:f.G,latency:f.zb,pdv:f.rd,clientState:c}}f={};for(const g of this.Y)f[g.gb]=g.ya();return{simulationTime:d,
hostInputArrivalTime:e,clientDelay:a,peerData:b,roData:f,isReadyForInput:this.F?this.h()?!0:0!==this.ba:!1}}Ub(a){for(const b of this.Y)b.Ub(a)}});"use strict";async function Rc(a,b){b=b.type;let c=!0;0===b?c=await Sc():1===b&&(c=await Tc());k(a,"permission-result",{type:b,result:c})}
async function Sc(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(a){return console.warn("[Touch] Failed to request orientation permission: ",a),!1}}
async function Tc(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(a){return console.warn("[Touch] Failed to request motion permission: ",a),!1}}self.za.Ma(class extends self.nb{constructor(a){super(a,"touch");u(this,"request-permission",b=>Rc(this,b))}});
