'use strict';function w(f,a,b,d){f.u.uc(f.bb,a,b,d,void 0)}function E(f,a,b,d){f.u.ca?w(f,a,b,d):f.u.sf()._OnMessageFromDOM({type:"event",component:f.bb,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function J(f,a,b){f.u.C(f.bb,a,b)}function L(f,a){for(const [b,d]of a)J(f,b,d)}function M(f){f.Ub||(f.u.bf(f.ke),f.Ub=!0)}window.Ta=class{constructor(f,a){this.u=f;this.bb=a;this.Ub=!1;this.ke=()=>this.Da()}nd(){}Da(){}};function N(f){-1!==f.Qa&&(self.clearTimeout(f.Qa),f.Qa=-1)}
window.Te=class{constructor(f,a){this.Uc=f;this.Gg=a;this.Qa=-1;this.Vb=-Infinity;this.le=()=>{this.Qa=-1;this.Vb=Date.now();this.hb=!0;this.Uc();this.hb=!1};this.Td=this.hb=!1}f(){N(this);this.le=this.Uc=null}};"use strict";
function O(f,a){const b=a.elementId,d=f.rd(b,a);f.Y.set(b,d);d.style.boxSizing="border-box";a.isVisible||(d.style.display="none");d.addEventListener("focus",()=>{P(f,"elem-focused",b)});d.addEventListener("blur",()=>{P(f,"elem-blurred",b)});f.Pb&&document.body.appendChild(d)}function Q(f,a,b){J(f,a,d=>{const g=f.Y.get(d.elementId);return b(g,d)})}function P(f,a,b,d){d||(d={});d.elementId=b;w(f,a,d)}function R(f,a,b){var d;d||(d={});d.elementId=b;E(f,a,d)}
window.Ee=class extends self.Ta{constructor(f,a){super(f,a);this.Y=new Map;this.Pb=!0;L(this,[["create",b=>O(this,b)],["destroy",b=>{{b=b.elementId;const d=this.Y.get(b);this.Pb&&d.parentElement.removeChild(d);this.Y.delete(b)}}],["set-visible",b=>{this.Pb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Pb){var d=this.Y.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=b.height+"px";b=b.fontSize;
null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{{const d=this.Y.get(b.elementId);this.Ac(d,b)}}],["focus",b=>this.Oc(b)],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);Q(this,"get-element",b=>b)}rd(){throw Error("required override");}Ac(){throw Error("required override");}Oc(f){var a=this.Y.get(f.elementId);f.focus?a.focus():
a.blur()}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),a=/android/i.test(navigator.userAgent);let b=0;function d(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.Rg?new Promise(k=>{const l="c3_resolve_"+b;++b;self[l]=k;c.textContent=m.Vg+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let g=!1,n=!1;function p(){if(!g){try{new Worker("blob://",{get type(){n=
!0}})}catch(m){}g=!0}return n}let v=new Audio;const B={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};v=null;async function D(m){m=await x(m);return(new TextDecoder("utf-8")).decode(m)}
function x(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=q=>c(q.target.result);l.onerror=q=>k(q);l.readAsArrayBuffer(m)})}const y=[];let C=0;window.RealFile=window.File;const F=[],A=new Map,G=new Map;let I=0;const K=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");K.push(m)};const e=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.na=class m{constructor(c){this.ca=c.Xg;this.ra=null;this.F="";this.ic=c.Ug;
this.xb={};this.Ja=this.wb=null;this.Sb=[];this.kb=this.K=this.Oa=null;this.Na=-1;this.Lg=()=>this.Qf();this.Ma=[];this.s=c.me;this.ib="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&p()||(this.ca=!1);if("playable-ad"===this.s||"instant-games"===this.s)this.ca=!1;if("cordova"===this.s&&this.ca)if(a){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.ca=!1)}else this.ca=!1;this.Yb=this.ia=null;"html5"!==
this.s&&"playable-ad"!==this.s||!this.ib||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.s||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",k=>this.Af(k));this.C("runtime",
"create-job-worker",()=>this.Bf());"cordova"===this.s?document.addEventListener("deviceready",()=>this.Gd(c)):this.Gd(c)}f(){this.Bc();this.ra&&(this.ra=this.ra.onmessage=null);this.wb&&(this.wb.terminate(),this.wb=null);this.Ja&&(this.Ja.f(),this.Ja=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}Oe(){return f&&"cordova"===this.s}tc(){const c=navigator.userAgent;return f&&e.has(this.s)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}Me(){return a}vd(){return a&&e.has(this.s)}async Gd(c){"macos-wkwebview"===
this.s&&this.Sc({type:"ready"});if("playable-ad"===this.s){this.ia=self.c3_base64files;this.Yb={};await this.gf();for(let l=0,q=c.Ra.length;l<q;++l){var k=c.Ra[l].toLowerCase();this.Yb.hasOwnProperty(k)?c.Ra[l]={Rg:!0,Vg:this.Yb[k]}:this.ia.hasOwnProperty(k)&&(c.Ra[l]=URL.createObjectURL(this.ia[k]))}}c.Mg?this.F=c.Mg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.Zg&&(this.xb=c.Zg);k=new MessageChannel;this.ra=
k.port1;this.ra.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Mf(l));this.kb=new self.Pe(this);await S(this.kb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.vf(c,k.port2):await this.uf(c,k.port2)}Ec(c){c=this.xb.hasOwnProperty(c)?this.xb[c]:c.endsWith("/workermain.js")&&this.xb.hasOwnProperty("workermain.js")?
this.xb["workermain.js"]:"playable-ad"===this.s&&this.ia.hasOwnProperty(c.toLowerCase())?this.ia[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async nc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.s&&this.ib)return c=await this.yb(l.Qg?c:this.ic+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");
c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}pa(){return Math.max(window.innerWidth,1)}fa(){return Math.max(window.innerHeight,1)}Fd(c){var k=this.kb;return{baseUrl:this.F,windowInnerWidth:this.pa(),windowInnerHeight:this.fa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:m.Wa(),projectData:c.fh,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,
swClientId:window.dh||"",exportType:c.me,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.eh,jobScheduler:{inputPort:k.$c,outputPort:k.fd,maxNumWorkers:k.Ig},supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ic+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ic+"opus.wasm.wasm",isFileProtocol:this.ib,isiOSCordova:this.Oe(),isiOSWebView:this.tc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async vf(c,k){var l=this.Ec(c.Yg);this.wb=
await this.nc(l,this.F,{type:"module",name:"Runtime",Qg:!0});this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;let q=c.md||[],u=c.Ra;q=await Promise.all(q.map(r=>this.Ea(r)));u=await Promise.all(u.map(r=>this.Ea(r)));if("cordova"===this.s)for(let r=0,t=c.lc.length;r<t;++r){const z=c.lc[r],H=z[0];if(H===c.kd||"scriptsInEvents.js"===H||H.endsWith("/scriptsInEvents.js"))z[1]=await this.Ea(H)}this.wb.postMessage(Object.assign(this.Fd(c),
{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:q,engineScripts:u,projectScripts:c.lc,mainProjectScript:c.kd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...T(this.kb)]);this.Sb=F.map(r=>new r(this));this.Ed();self.c3_callFunction=(r,t)=>this.Oa.wf(r,t);"preview"===this.s&&(self.goToLastErrorScript=()=>this.uc("runtime","go-to-last-error-script"))}async uf(c,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);
window.c3canvas=this.K;this.Sb=F.map(r=>new r(this));this.Ed();var l=c.Ra.map(r=>"string"===typeof r?(new URL(r,this.F)).toString():r);Array.isArray(c.md)&&l.unshift(...c.md);l=await Promise.all(l.map(r=>this.Ea(r)));await Promise.all(l.map(r=>d(r)));l=self.C3_ProjectScriptsStatus;const q=c.kd,u=c.lc;for(let [r,t]of u)if(t||(t=r),r===q)try{t=await this.Ea(t),await d(t),"preview"!==this.s||l[r]||this.Od(r,"main script did not run to completion")}catch(z){this.Od(r,z)}else if("scriptsInEvents.js"===
r||r.endsWith("/scriptsInEvents.js"))t=await this.Ea(t),await d(t);"preview"===this.s&&"object"!==typeof self.$g.ah?(this.Kb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Fd(c),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:K}),this.Id(),this.Ja=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ja,
c))}Od(c,k){this.Kb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Id(){this.Kb()}Kb(){const c=window.Ng;c&&(c.parentElement.removeChild(c),window.Ng=null)}async Bf(){const c=await U(this.kb);return{outputPort:c,transferables:[c]}}sf(){if(this.ca)throw Error("not available in worker mode");return this.Ja}uc(c,k,l,q,u){this.ra.postMessage({type:"event",
component:c,handler:k,dispatchOpts:q||null,data:l,responseId:null},u)}xd(c,k,l,q,u){const r=I++,t=new Promise((z,H)=>{G.set(r,{resolve:z,reject:H})});this.ra.postMessage({type:"event",component:c,handler:k,dispatchOpts:q||null,data:l,responseId:r},u);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.Gf(c);if("result"===k)this.Tf(c);else if("runtime-ready"===k)this.Uf();else if("alert-error"===k)this.Kb(),alert(c.message);else if("creating-runtime"===k)this.Id();else throw Error(`unknown message '${k}'`);
}Gf(c){const k=c.component,l=c.handler,q=c.data,u=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(q)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==u&&this.Jb(u,!1,""+t);return}if(null===u)return r;r&&r.then?r.then(t=>this.Jb(u,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Jb(u,!1,""+t)}):this.Jb(u,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Jb(c,
k,l){let q;l&&l.transferables&&(q=l.transferables);this.ra.postMessage({type:"result",responseId:c,isOk:k,result:l},q)}Tf(c){const k=c.responseId,l=c.isOk;c=c.result;const q=G.get(k);l?q.resolve(c):q.reject(c);G.delete(k)}C(c,k,l){let q=A.get(c);q||(q=new Map,A.set(c,q));if(q.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);q.set(k,l)}static Sa(c){if(F.includes(c))throw Error("DOM handler already added");F.push(c)}Ed(){for(const c of this.Sb)if("runtime"===c.bb){this.Oa=c;return}throw Error("cannot find runtime DOM handler");
}Mf(c){this.uc("debugger","message",c)}Uf(){for(const c of this.Sb)c.nd()}static Wa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||h)}static Lb(c){h=!!c}bf(c){this.Ma.push(c);this.Rc()}gg(c){c=this.Ma.indexOf(c);if(-1===c)throw Error("invalid callback");this.Ma.splice(c,1);this.Ma.length||this.Bc()}Rc(){-1===this.Na&&this.Ma.length&&(this.Na=requestAnimationFrame(this.Lg))}Bc(){-1!==this.Na&&(cancelAnimationFrame(this.Na),this.Na=-1)}Qf(){this.Na=
-1;for(const c of this.Ma)c();this.Rc()}wa(c){this.Oa.wa(c)}Ca(c){this.Oa.Ca(c)}Qc(){this.Oa.Qc()}Eb(c){this.Oa.Eb(c)}Ne(){return!!B["audio/webm; codecs=opus"]}async Eg(c){c=await this.xd("runtime","opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}Le(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}wd(c){return!this.Le(c)}async Ea(c){return"cordova"===this.s&&(c.startsWith("file:")||this.ib&&this.wd(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),
c=await this.yb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async Af(c){const k=c.filename;switch(c.as){case "text":return await this.De(k);case "buffer":return await this.yb(k);default:throw Error("unsupported type");}}qd(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,q)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(l,q)},q)})}async De(c){c=await this.qd(c);return await D(c)}Cc(){if(y.length&&!(8<=C)){C++;var c=y.shift();
this.hf(c.filename,c.Wg,c.Pg)}}yb(c){return new Promise((k,l)=>{y.push({filename:c,Wg:q=>{C--;this.Cc();k(q)},Pg:q=>{C--;this.Cc();l(q)}});this.Cc()})}async hf(c,k,l){try{const q=await this.qd(c),u=await x(q);k(u)}catch(q){l(q)}}Sc(c){if("windows-webview2"===this.s)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.s)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async gf(){const c=[];for(const [k,
l]of Object.entries(this.ia))c.push(this.ff(k,l));await Promise.all(c)}async ff(c,k){if("object"===typeof k)this.ia[c]=new Blob([k.str],{type:k.type}),this.Yb[c]=k.str;else{let l=await this.qf(k);l||(l=this.kf(k));this.ia[c]=l}}async qf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}kf(c){c=this.ag(c);return this.ef(c.data,c.Sg)}ag(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||"";const q=k[2];l="base64"===k[1]||"base64"===q?atob(l):decodeURIComponent(l);return{Sg:c,data:l}}ef(c,k){var l=c.length;let q=l>>2,u=new Uint8Array(l),r=new Uint32Array(u.buffer,0,q),t,z;for(z=t=0;t<q;++t)r[t]=c.charCodeAt(z++)|c.charCodeAt(z++)<<8|c.charCodeAt(z++)<<16|c.charCodeAt(z++)<<24;for(l&=
3;l--;)u[z]=c.charCodeAt(z),++z;return new Blob([u],{type:k})}}}"use strict";
{const f=self.na;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function p(e){return new Promise((h,m)=>{const c=document.createElement("link");c.onload=()=>h(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=e;document.head.appendChild(c)})}function v(e){return new Promise((h,m)=>{const c=new Image;c.onload=()=>h(c);c.onerror=k=>m(k);c.src=e})}async function B(e){e=URL.createObjectURL(e);try{return await v(e)}finally{URL.revokeObjectURL(e)}}function D(e){return new Promise((h,m)=>{let c=new FileReader;c.onload=k=>h(k.target.result);c.onerror=k=>m(k);c.readAsText(e)})}async function x(e,h,m){if(!/firefox/i.test(navigator.userAgent))return await B(e);var c=await D(e);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),q=k.getAttribute("height");if(!l.includes("%")&&!q.includes("%"))return await B(e)}k.setAttribute("width",h+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);e=new Blob([c],{type:"image/svg+xml"});return await B(e)}function y(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),F=new Set(["canvas","body","html"]);function A(e){F.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function G(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await B(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,m,c,k){e=await x(e,h,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(e,0,0,h,m);return l};let I=!1;document.addEventListener("pause",()=>I=!0);document.addEventListener("resume",()=>I=!1);function K(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.Sa(class extends self.Ta{constructor(e){super(e,"runtime");this.Yd=!0;this.Pa=-1;this.hd="any";this.Pd=this.Qd=!1;this.Ia=
this.sb=this.ya=null;this.dc=this.cc=0;this.be=e.pa();this.Wb=e.fa();this.ub=0;e.C("canvas","update-size",c=>this.Yf(c));e.C("runtime","invoke-download",c=>this.Kf(c));e.C("runtime","raster-svg-image",c=>this.Rf(c));e.C("runtime","get-svg-image-size",c=>this.If(c));e.C("runtime","set-target-orientation",c=>this.Wf(c));e.C("runtime","register-sw",()=>this.Sf());e.C("runtime","post-to-debugger",c=>this.Kd(c));e.C("runtime","go-to-script",c=>this.Kd(c));e.C("runtime","before-start-ticking",()=>this.zf());
e.C("runtime","debug-highlight",c=>this.Cf(c));e.C("runtime","enable-device-orientation",()=>this.df());e.C("runtime","enable-device-motion",()=>this.cf());e.C("runtime","add-stylesheet",c=>this.yf(c));e.C("runtime","alert",c=>this.Ic(c));e.C("runtime","hide-cordova-splash",()=>this.Jf());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const k=c.target;h.has(k.tagName.toLowerCase())||y(k)||c.preventDefault()});const m=e.K;window.addEventListener("selectstart",
A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",A)):m.addEventListener("touchstart",A);this.pb=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",G,{passive:!1});window.addEventListener("wheel",G,
{passive:!1});window.addEventListener("resize",()=>this.Zf());window.addEventListener("fullscreenchange",()=>this.Ya());window.addEventListener("webkitfullscreenchange",()=>this.Ya());window.addEventListener("mozfullscreenchange",()=>this.Ya());window.addEventListener("fullscreenerror",c=>this.Lc(c));window.addEventListener("webkitfullscreenerror",c=>this.Lc(c));window.addEventListener("mozfullscreenerror",c=>this.Lc(c));e.tc()&&window.addEventListener("focusout",()=>{{const l=document.activeElement;
if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||"text"):y(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.$f(c);this.Ka=new Set;this.Zb=new WeakSet;this.qa=!1}zf(){"cordova"===this.u.s?(document.addEventListener("pause",()=>this.Pc(!0)),document.addEventListener("resume",()=>this.Pc(!1))):document.addEventListener("visibilitychange",()=>this.Pc(document.hidden));
return{isSuspended:!(!document.hidden&&!I)}}nd(){window.addEventListener("focus",()=>this.$a("window-focus"));window.addEventListener("blur",()=>{this.$a("window-blur",{parentHasFocus:K()});this.pb=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||y(h))&&this.$a("keyboard-blur")});window.addEventListener("keydown",h=>this.Jd("keydown",h));window.addEventListener("keyup",h=>this.Jd("keyup",h));window.addEventListener("dblclick",h=>this.Mc("dblclick",h,d));window.addEventListener("wheel",
h=>this.Of(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",h=>{this.Fc(h);this.Za("pointerdown",h)}),this.u.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.sb=new self.Te(()=>this.nf(),5),this.sb.Td=!0,window.addEventListener("pointerrawupdate",h=>this.Pf(h))):window.addEventListener("pointermove",h=>this.Za("pointermove",h)),window.addEventListener("pointerup",h=>this.Za("pointerup",h)),window.addEventListener("pointercancel",h=>this.Za("pointercancel",
h))):(window.addEventListener("mousedown",h=>{this.Fc(h);this.Nc("pointerdown",h)}),window.addEventListener("mousemove",h=>this.Nc("pointermove",h)),window.addEventListener("mouseup",h=>this.Nc("pointerup",h)),window.addEventListener("touchstart",h=>{this.Fc(h);this.Ib("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Ib("pointermove",h)),window.addEventListener("touchend",h=>this.Ib("pointerup",h)),window.addEventListener("touchcancel",h=>this.Ib("pointercancel",h)));const e=()=>this.Qc();
window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0);this.u.Me()&&!this.u.vd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this.Jc(this.fa(),navigator.virtualKeyboard.boundingRect.height)}))}Jc(e,h){document.body.style.transform="";if(0<h){var m=document.activeElement;
m&&(m=m.getBoundingClientRect(),e=(m.top+m.bottom)/2-(e-h)/2,e>h&&(e=h),0>e&&(e=0),0<e&&(document.body.style.transform=`translateY(${-e}px)`))}}$a(e,h){w(this,e,h||null,n)}pa(){return this.u.pa()}fa(){return this.u.fa()}Zf(){const e=this.pa(),h=this.fa();if(this.u.vd()){if(this.be===e&&h<this.Wb){this.ub=this.Wb-h;this.Jc(this.Wb,this.ub);return}0<this.ub&&(this.ub=0,this.Jc(h,this.ub));this.be=e;this.Wb=h}this.$a("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,
isFullscreen:f.Wa()});this.u.tc()&&(-1!==this.Pa&&clearTimeout(this.Pa),this.Ld(e,h,0))}hg(e,h,m){-1!==this.Pa&&clearTimeout(this.Pa);this.Pa=setTimeout(()=>this.Ld(e,h,m),48)}Ld(e,h,m){const c=this.pa(),k=this.fa();this.Pa=-1;c!=e||k!=h?this.$a("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Wa()}):10>m&&this.hg(c,k,m+1)}Wf(e){this.hd=e.targetOrientation}Ag(){const e=this.hd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>
console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Ya(){const e=f.Wa();e&&"any"!==this.hd&&this.Ag();w(this,"fullscreenchange",
{isFullscreen:e,innerWidth:this.pa(),innerHeight:this.fa()})}Lc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);w(this,"fullscreenerror",{isFullscreen:f.Wa(),innerWidth:this.pa(),innerHeight:this.fa()})}Pc(e){e?this.u.Bc():this.u.Rc();w(this,"visibilitychange",{hidden:e})}Jd(e,h){"Backspace"===h.key&&A(h);const m=b.get(h.code)||h.code;E(this,e,{code:m,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},
d)}Of(e){w(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},d)}Mc(e,h,m){a(h)||E(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,timeStamp:h.timeStamp},m)}Nc(e,h){if(!a(h)){var m=this.pb;"pointerdown"===e&&0!==m?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");
E(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.pb=h.buttons;this.Mc(h.type,h,g)}}Za(e,h){if(this.sb&&"pointermove"!==e){var m=this.sb;m.hb||(N(m),m.Vb=Date.now())}m=0;"mouse"===h.pointerType&&(m=this.pb);E(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,
button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:(h.movementX||0)+this.cc,movementY:(h.movementY||0)+this.dc,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);this.dc=this.cc=0;"mouse"===h.pointerType&&(m="mousemove","pointerdown"===e?m="mousedown":"pointerup"===e&&(m="mouseup"),this.Mc(m,h,g),this.pb=
h.buttons)}Pf(e){this.Ia&&(this.cc+=this.Ia.movementX||0,this.dc+=this.Ia.movementY||0);this.Ia=e;e=this.sb;if(-1===e.Qa){var h=Date.now(),m=h-e.Vb,c=e.Gg;m>=c&&e.Td?(e.Vb=h,e.hb=!0,e.Uc(),e.hb=!1):e.Qa=self.setTimeout(e.le,Math.max(c-m,4))}}nf(){this.Za("pointermove",this.Ia);this.Ia=null}Ib(e,h){for(let m=0,c=h.changedTouches.length;m<c;++m){const k=h.changedTouches[m];E(this,e,{pointerId:k.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,
pageY:k.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},d)}}Fc(e){window!==window.top&&window.focus();this.Hd(e.target)&&document.activeElement&&!this.Hd(document.activeElement)&&document.activeElement.blur()}Hd(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}df(){this.Qd||
(this.Qd=!0,window.addEventListener("deviceorientation",e=>this.Ef(e)),window.addEventListener("deviceorientationabsolute",e=>this.Ff(e)))}cf(){this.Pd||(this.Pd=!0,window.addEventListener("devicemotion",e=>this.Df(e)))}Ef(e){w(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}Ff(e){w(this,"deviceorientationabsolute",{absolute:!!e.absolute,
alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}Df(e){let h=null;var m=e.acceleration;m&&(h={x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=e.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;const k=e.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});w(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:m,rotationRate:c,interval:e.interval,timeStamp:e.timeStamp},d)}Yf(e){const h=this.u.K;h.style.width=e.styleWidth+"px";
h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";this.Yd&&(h.style.display="",this.Yd=!1)}Kf(e){const h=e.url;e=e.filename;const m=document.createElement("a"),c=document.body;m.textContent=e;m.href=h;m.download=e;c.appendChild(m);m.click();c.removeChild(m)}async Rf(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);h=h?await createImageBitmap(e,h):await createImageBitmap(e);
return{imageBitmap:h,transferables:[h]}}async If(e){return await self.C3_GetSvgImageSize(e.blob)}async yf(e){await p(e.url)}Qc(){var e=[...this.Ka];this.Ka.clear();if(!this.qa)for(const h of e)(e=h.play())&&e.catch(()=>{this.Zb.has(h)||this.Ka.add(h)})}wa(e){if("function"!==typeof e.play)throw Error("missing play function");this.Zb.delete(e);let h;try{h=e.play()}catch(m){this.Ka.add(e);return}h&&h.catch(()=>{this.Zb.has(e)||this.Ka.add(e)})}Ca(e){this.Ka.delete(e);this.Zb.add(e)}Eb(e){this.qa=!!e}Jf(){navigator.splashscreen&&
navigator.splashscreen.hide&&navigator.splashscreen.hide()}Cf(e){if(e.show){this.ya||(this.ya=document.createElement("div"),this.ya.id="inspectOutline",document.body.appendChild(this.ya));var h=this.ya;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.ya&&(this.ya.style.display="none")}Sf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Kd(e){window.c3_postToMessagePort&&(e.from="runtime",
window.c3_postToMessagePort(e))}wf(e,h){return this.u.xd(this.bb,"js-invoke-function",{name:e,params:h},void 0,void 0)}Ic(e){alert(e.message)}$f(e){"entered-fullscreen"===e?(f.Lb(!0),this.Ya()):"exited-fullscreen"===e?(f.Lb(!1),this.Ya()):console.warn("Unknown wrapper message: ",e)}})}"use strict";
async function S(f){if(f.Fg)throw Error("already initialised");f.Fg=!0;var a=f.hc.Ec("dispatchworker.js");f.Wc=await f.hc.nc(a,f.F,{name:"DispatchWorker"});a=new MessageChannel;f.$c=a.port1;f.Wc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.fd=await U(f)}function T(f){return[f.$c,f.fd]}
async function U(f){const a=f.Zd.length;var b=f.hc.Ec("jobworker.js");b=await f.hc.nc(b,f.F,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;f.Wc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);f.Zd.push(b);return g.port1}
self.Pe=class{constructor(f){this.hc=f;this.F=f.F;this.F="preview"===f.s?this.F+"workers/":this.F+f.ic;this.Ig=Math.min(navigator.hardwareConcurrency||2,16);this.Wc=null;this.Zd=[];this.fd=this.$c=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.na({Xg:!0,Yg:"workermain.js",Ra:["scripts/c3runtime.js"],lc:[],kd:"",Ug:"scripts/",md:[],me:"html5"}));"use strict";
async function V(f,a){a=a.type;let b=!0;0===a?b=await W():1===a&&(b=await X());w(f,"permission-result",{type:a,result:b})}async function W(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}
async function X(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}self.na.Sa(class extends self.Ta{constructor(f){super(f,"touch");J(this,"request-permission",a=>V(this,a))}});"use strict";
{const f=180/Math.PI;self.da=class extends self.Ta{constructor(a){super(a,"audio");this.Rb=this.c=null;this.Tb=this.Zc=!1;this.ta=()=>this.Bg();this.aa=[];this.D=[];this.ha=null;this.$d="";this.ae=-1;this.rb=new Map;this.cd=1;this.qa=!1;this.jd=0;this.jc=1;this.Xc=0;this.de="HRTF";this.Ud="inverse";this.ee=600;this.ce=1E4;this.ge=1;this.Wd=this.gd=!1;this.je=this.u.Ne();this.ba=new Map;this.Ga=new Set;this.ad=!1;this.dd="";this.za=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Nf(b,d);this.Qb=null;
self.C3Audio_GetOutputStream=()=>this.Hf();self.C3Audio_DOMInterface=this;L(this,[["create-audio-context",b=>this.jf(b)],["play",b=>this.bg(b)],["stop",b=>this.yg(b)],["stop-all",()=>this.zg()],["set-paused",b=>this.rg(b)],["set-volume",b=>this.wg(b)],["fade-volume",b=>this.pf(b)],["set-master-volume",b=>this.pg(b)],["set-muted",b=>this.qg(b)],["set-silent",b=>this.tg(b)],["set-looping",b=>this.og(b)],["set-playback-rate",b=>this.sg(b)],["seek",b=>this.ig(b)],["preload",b=>this.cg(b)],["unload",b=>
this.Cg(b)],["unload-all",()=>this.Dg()],["set-suspended",b=>this.ug(b)],["get-suspended",()=>this.tf()],["add-effect",b=>this.Cd(b)],["set-effect-param",b=>this.lg(b)],["remove-effects",b=>this.eg(b)],["tick",b=>this.Xf(b)],["load-state",b=>this.Lf(b)]])}async jf(a){a.isiOSCordova&&(this.gd=!0);this.jd=a.timeScaleMode;this.de=["equalpower","HRTF","soundfield"][a.panningModel];this.Ud=["linear","inverse","exponential"][a.distanceModel];this.ee=a.refDistance;this.ce=a.maxDistance;this.ge=a.rolloffFactor;
var b={latencyHint:a.latencyHint};this.je||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.c=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.c=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.Dd();this.c.onstatechange=()=>{"running"!==this.c.state&&this.Dd()};this.Rb=this.c.createGain();this.Rb.connect(this.c.destination);b=a.listenerPos;this.c.listener.setPosition(b[0],b[1],b[2]);this.c.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=
()=>this.oc();try{await Promise.all(a.preloadList.map(d=>this.Gb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.c.sampleRate}}Dd(){this.Tb||(this.Zc=!1,window.addEventListener("pointerup",this.ta,!0),window.addEventListener("touchend",this.ta,!0),window.addEventListener("click",this.ta,!0),window.addEventListener("keydown",this.ta,!0),this.Tb=!0)}lf(){this.Tb&&(this.Zc=!0,window.removeEventListener("pointerup",this.ta,!0),
window.removeEventListener("touchend",this.ta,!0),window.removeEventListener("click",this.ta,!0),window.removeEventListener("keydown",this.ta,!0),this.Tb=!1)}Bg(){if(!this.Zc){var a=this.c;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.lf()}}W(){return this.c}oc(){return this.c.currentTime}ua(){return this.Rb}td(a){return(a=this.ba.get(a.toLowerCase()))?a[0].P():this.ua()}ne(a,
b){a=a.toLowerCase();let d=this.ba.get(a);d||(d=[],this.ba.set(a,d));b.ng(d.length);b.vg(a);d.push(b);this.Nd(a)}Nd(a){let b=this.ua();const d=this.ba.get(a);if(d&&d.length){b=d[0].P();for(let g=0,n=d.length;g<n;++g){const p=d[g];g+1===n?p.S(this.ua()):p.S(d[g+1].P())}}for(const g of this.ma(a))g.Ue(b);this.za&&this.dd===a&&(this.za.disconnect(),this.za.connect(b))}Ab(){return this.cd}Bb(){return this.qa}mg(){this.Wd=!0}Ge(a,b){return b?this.u.Eg(a).then(d=>{const g=this.c.createBuffer(1,d.length,
48E3);g.getChannelData(0).set(d);return g}):new Promise((d,g)=>{this.c.decodeAudioData(a,d,g)})}wa(a){this.u.wa(a)}Ca(a){this.u.Ca(a)}yd(a){let b=0;for(let d=0,g=this.D.length;d<g;++d){const n=this.D[d];this.D[b]=n;n.L===a?n.f():++b}this.D.length=b}Ve(){let a=0;for(let b=0,d=this.aa.length;b<d;++b){const g=this.aa[b];this.aa[a]=g;g.va()?g.f():++a}this.aa.length=a}*ma(a){if(a)for(const b of this.D)self.da.He(b.Z,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Gb(a,b,d,g,n){for(const p of this.aa)if(p.Va()===
b)return await Y(p),p;if(n)return null;g&&(this.gd||this.Wd)&&this.Ve();n="audio/webm; codecs=opus"===d&&!this.je;g&&n&&this.mg();a=!g||this.gd||n?new self.Be(this,a,b,d,g,n):new self.ze(this,a,b,d,g);this.aa.push(a);await Y(a);return a}async Dc(a,b,d,g,n){for(const p of this.D)if(p.Va()===b&&(p.mc()||n))return p.Xe(g),p;a=await this.Gb(a,b,d,n);g="html5"===a.Tc?new self.Ae(a.i,a,g):new self.Ce(a.i,a,g);this.D.push(g);return g}af(a){let b=this.rb.get(a);if(!b){let d=null;b={ld:0,Tg:new Promise(g=>
d=g),resolve:d};this.rb.set(a,b)}b.ld++}fg(a){const b=this.rb.get(a);if(!b)throw Error("expected pending tag");b.ld--;0===b.ld&&(b.resolve(),this.rb.delete(a))}zc(a){a||(a=this.$d);return(a=this.rb.get(a))?a.Tg:Promise.resolve()}Hb(){if(0<this.Ga.size)M(this);else for(const a of this.D)if(a.ud()){M(this);break}}Da(){for(var a of this.Ga)a.Da();a=this.oc();for(var b of this.D)b.Da(a);b=this.D.filter(d=>d.ud()).map(d=>d.Ua());w(this,"state",{tickCount:this.ae,audioInstances:b,analysers:[...this.Ga].map(d=>
d.Je())});0===b.length&&0===this.Ga.size&&this.Ub&&(this.u.gg(this.ke),this.Ub=!1)}vc(a,b,d){w(this,"trigger",{type:a,tag:b,aiid:d})}async bg(a){const b=a.originalUrl,d=a.url,g=a.type,n=a.isMusic,p=a.tag,v=a.isLooping,B=a.vol,D=a.pos,x=a.panning;let y=a.off;0<y&&!a.trueClock&&(this.c.getOutputTimestamp?(a=this.c.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+this.c.currentTime);this.$d=p;this.af(p);try{this.ha=await this.Dc(b,d,g,p,n),x?(this.ha.Db(!0),this.ha.We(x.x,
x.y,x.angle,x.innerAngle,x.outerAngle,x.outerGain),x.hasOwnProperty("uid")&&this.ha.Ye(x.uid)):this.ha.Db(!1),this.ha.Play(v,B,D,y)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.fg(p)}M(this)}yg(a){a=a.tag;for(const b of this.ma(a))b.oa()}zg(){for(const a of this.D)a.oa()}rg(a){const b=a.tag;a=a.paused;for(const d of this.ma(b))a?d.Xa():d.Cb();this.Hb()}wg(a){const b=a.tag;a=a.vol;for(const d of this.ma(b))d.Fb(a)}async pf(a){const b=a.tag,d=a.vol,
g=a.duration;a=a.stopOnEnd;await this.zc(b);for(const n of this.ma(b))n.Ie(d,g,a);this.Hb()}pg(a){this.cd=a.vol;for(const b of this.D)b.Nb()}qg(a){const b=a.tag;a=a.isMuted;for(const d of this.ma(b))d.zd(a)}tg(a){this.qa=a.isSilent;this.u.Eb(this.qa);for(const b of this.D)b.Mb()}og(a){const b=a.tag;a=a.isLooping;for(const d of this.ma(b))d.xc(a)}async sg(a){const b=a.tag;a=a.rate;await this.zc(b);for(const d of this.ma(b))d.Bd(a)}async ig(a){const b=a.tag;a=a.pos;await this.zc(b);for(const d of this.ma(b))d.wc(a)}async cg(a){const b=
a.originalUrl,d=a.url,g=a.type;a=a.isMusic;try{await this.Dc(b,d,g,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async Cg(a){if(a=await this.Gb("",a.url,a.type,a.isMusic,!0))a.f(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}Dg(){for(const a of this.aa)a.f();this.aa.length=0}ug(a){a=a.isSuspended;!a&&this.c.resume&&this.c.resume();for(const b of this.D)b.yc(a);a&&this.c.suspend&&this.c.suspend()}tf(){return this.c?this.c.state:"suspended"}Xf(a){this.jc=a.timeScale;
this.Xc=a.gameTime;this.ae=a.tickCount;if(0!==this.jd)for(var b of this.D)b.Fa();(b=a.listenerPos)&&this.c.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.D)g.ga===a&&g.Ad(d.x,d.y,d.angle)}}async Cd(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.te(this,...g);else if("delay"===b)g=new self.re(this,...g);else if("convolution"===b){b=null;try{b=await this.Gb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",
n);return}g=new self.qe(this,b.$,...g);g.jg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.ue(this,...g);else if("phaser"===b)g=new self.we(this,...g);else if("gain"===b)g=new self.ve(this,...g);else if("tremolo"===b)g=new self.ye(this,...g);else if("ringmod"===b)g=new self.xe(this,...g);else if("distortion"===b)g=new self.se(this,...g);else if("compressor"===b)g=new self.pe(this,...g);else if("analyser"===b)g=new self.oe(this,...g);else throw Error("invalid effect type");this.ne(d,
g);this.Md()}lg(a){const b=a.index,d=a.param,g=a.value,n=a.ramp,p=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,g,n,p),this.Md())}eg(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const d of b)d.f();this.ba.delete(a);this.Nd(a)}}$e(a){this.Ga.add(a);this.Hb()}dg(a){this.Ga.delete(a)}Md(){this.ad||(this.ad=!0,Promise.resolve().then(()=>this.mf()))}mf(){const a={};for(const [b,d]of this.ba)a[b]=d.map(g=>g.Ua());w(this,"fxstate",{fxstate:a});this.ad=!1}async Lf(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.D)d.va()&&1===b||(d.va()||2!==b)&&d.oa();for(const g of this.ba.values())for(const n of g)n.f();this.ba.clear();this.jc=a.timeScale;this.Xc=a.gameTime;d=a.listenerPos;this.c.listener.setPosition(d[0],d[1],d[2]);this.qa=a.isSilent;this.u.Eb(this.qa);this.cd=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(n=>this.Cd(n))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.xf(g,b)));this.Hb()}async xf(a,b){if(3!==
b){var d=a.bufferOriginalUrl,g=a.bufferUrl,n=a.bufferType,p=a.isMusic,v=a.tag,B=a.isLooping,D=a.volume,x=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.Dc(d,g,n,v,p)}catch(y){console.error("[Construct 3] Audio: error loading audio state: ",y);return}b.Se(a.pan);b.Play(B,D,x,0);a.isPlaying||b.Xa();b.Hc(a)}}}Nf(a,b){this.za&&this.za.disconnect();this.dd=b.toLowerCase();this.za=this.c.createMediaStreamSource(a);this.za.connect(this.td(this.dd))}Hf(){this.Qb||(this.Qb=this.c.createMediaStreamDestination(),
this.Rb.connect(this.Qb));return this.Qb.stream}static He(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Ze(a){return a*f}static Fe(a){return Math.pow(10,a/20)}static sd(a){return Math.max(Math.min(self.da.Fe(a),1),0)}static Re(a){return Math.log(a)/Math.log(10)*20}static Qe(a){return self.da.Re(Math.max(Math.min(a,1),0))}static Og(a,b){return 1-Math.exp(-b*a)}};self.na.Sa(self.da)}"use strict";function Y(f){f.Xb||(f.Xb=f.Gc());return f.Xb}
self.od=class{constructor(f,a,b,d,g){this.i=f;this.Kg=a;this.Aa=b;this.R=d;this.Hg=g;this.Tc="";this.Xb=null}f(){this.Xb=this.i=null}Gc(){}W(){return this.i.W()}qc(){return this.Kg}Va(){return this.Aa}pc(){return this.R}va(){return this.Hg}ea(){}};"use strict";
self.ze=class extends self.od{constructor(f,a,b,d,g){super(f,a,b,d,g);this.Tc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.lb=this.mb=null;this.J.addEventListener("canplaythrough",()=>!0);this.qb=this.W().createGain();this.ob=null;this.J.addEventListener("canplay",()=>{this.mb&&(this.mb(),this.lb=this.mb=null);!this.ob&&this.J&&(this.ob=this.W().createMediaElementSource(this.J),this.ob.connect(this.qb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.Aa}' error: `,n);this.lb&&(this.lb(n),this.lb=this.mb=null)})}f(){this.i.yd(this);this.qb.disconnect();this.qb=null;this.ob.disconnect();this.ob=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.f()}Gc(){return new Promise((f,a)=>{this.mb=f;this.lb=a;this.J.src=this.Aa})}O(){return this.J}ea(){return this.J.duration}};"use strict";
async function aa(f){if(f.xa)return f.xa;var a=f.i.u;if("cordova"===a.s&&a.wd(f.Aa)&&a.ib)f.xa=await a.yb(f.Aa);else{a=await fetch(f.Aa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.xa=await a.arrayBuffer()}}async function ba(f){if(f.$)return f.$;f.$=await f.i.Ge(f.xa,f.Jg);f.xa=null}
self.Be=class extends self.od{constructor(f,a,b,d,g,n){super(f,a,b,d,g);this.Tc="webaudio";this.$=this.xa=null;this.Jg=!!n}f(){this.i.yd(this);this.$=this.xa=null;super.f()}async Gc(){try{await aa(this),await ba(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.Aa}': `,f)}}ea(){return this.$?this.$.duration:0}};"use strict";
{let f=0;self.pd=class{constructor(a,b,d){this.i=a;this.L=b;this.Z=d;this.Ob=f++;this.M=this.W().createGain();this.M.connect(this.ua());this.B=null;this.jb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.H=!0;this.V=this.la=this.G=!1;this.vb=1;this.Ha=!1;this.sa=1;a=this.i.jd;this.bd=1===a&&!this.va()||2===a;this.fb=this.ga=-1;this.ie=!1}f(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ua(){return this.i.td(this.Z)}Ab(){return this.i.Ab()}zb(){return this.bd?
this.i.Xc:performance.now()/1E3}qc(){return this.L.qc()}Va(){return this.L.Va()}pc(){return this.L.pc()}va(){return this.L.va()}Xe(a){this.Z=a}T(){}mc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}ud(){return!this.H&&!this.T()}Ba(){}ea(){return this.L.ea()}Play(){}oa(){}Xa(){}Cb(){}Fb(a){this.vb=a;this.M.gain.cancelScheduledValues(0);this.fb=-1;this.M.gain.value=this.rc()}Ie(a,b,d){if(!this.Ha){a*=this.Ab();var g=this.M.gain;g.cancelScheduledValues(0);var n=this.i.oc();b=n+b;g.setValueAtTime(g.value,
n);g.linearRampToValueAtTime(a,b);this.vb=a;this.fb=b;this.ie=d}}Nb(){this.Fb(this.vb)}Da(a){-1!==this.fb&&a>=this.fb&&(this.fb=-1,this.ie&&this.oa(),this.i.vc("fade-ended",this.Z,this.Ob))}rc(){const a=this.vb*this.Ab();return isFinite(a)?a:0}zd(a){a=!!a;this.Ha!==a&&(this.Ha=a,this.Mb())}Bb(){return this.i.Bb()}Mb(){}xc(){}Bd(a){this.sa!==a&&(this.sa=a,this.Fa())}Fa(){}wc(){}yc(){}Db(a){a=!!a;this.jb!==a&&((this.jb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.de,this.B.distanceModel=
this.i.Ud,this.B.refDistance=this.i.ee,this.B.maxDistance=this.i.ce,this.B.rolloffFactor=this.i.ge),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ua())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ua())))}We(a,b,d,g,n,p){this.jb&&(this.Ad(a,b,d),a=self.da.Ze,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=p)}Ad(a,b,d){this.jb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(d),this.ja[1]=Math.sin(d),this.ja[2]=0,this.B.setPosition(...this.ka),
this.B.setOrientation(...this.ja))}Ye(a){this.ga=a}sc(){}Ue(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ua(){return{aiid:this.Ob,tag:this.Z,duration:this.ea(),volume:this.vb,isPlaying:this.IsPlaying(),playbackTime:this.Ba(),playbackRate:this.sa,uid:this.ga,bufferOriginalUrl:this.qc(),bufferUrl:"",bufferType:this.pc(),isMusic:this.va(),isLooping:this.V,isMuted:this.Ha,resumePosition:this.sc(),pan:this.Ke()}}Hc(a){this.Bd(a.playbackRate);this.zd(a.isMuted)}Ke(){if(!this.B)return null;const a=
this.B;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Se(a){if(a){this.Db(!0);a=this.B;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.Db(!1)}}}"use strict";
self.Ae=class extends self.pd{constructor(f,a,b){super(f,a,b);this.L.qb.connect(this.M);this.L.onended=()=>this.Kc()}f(){this.oa();this.L.qb.disconnect();super.f()}O(){return this.L.O()}Kc(){this.H=!0;this.ga=-1;this.i.vc("ended",this.Z,this.Ob)}T(){return this.O().ended}mc(){return this.H?!0:this.T()}Ba(){let f=this.O().currentTime;this.V||(f=Math.min(f,this.ea()));return f}Play(f,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==f&&(d.loop=f);this.Fb(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Va()}' to position '${b}': `,g)}this.i.wa(d);this.G=this.H=!1;this.V=f;this.sa=1}oa(){const f=this.O();f.paused||f.pause();this.i.Ca(f);this.H=!0;this.G=!1;this.ga=-1}Xa(){if(!(this.G||this.H||this.T())){var f=this.O();f.paused||f.pause();this.i.Ca(f);this.G=!0}}Cb(){!this.G||this.H||this.T()||(this.i.wa(this.O()),this.G=!1)}Mb(){this.O().muted=this.Ha||this.Bb()}xc(f){f=!!f;this.V!==f&&
(this.V=f,this.O().loop=f)}Fa(){let f=this.sa;this.bd&&(f*=this.i.jc);try{this.O().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}wc(f){if(!this.H&&!this.T())try{this.O().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}sc(){return this.Ba()}yc(f){f?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.wa(this.O()),this.la=!1)}};"use strict";
function Z(f){f.j&&f.j.disconnect();f.j=null;f.ab=null}
self.Ce=class extends self.pd{constructor(f,a,b){super(f,a,b);this.j=null;this.$b=d=>this.Kc(d);this.Yc=!0;this.ab=null;this.N=this.ac=this.bc=0;this.ed=1}f(){this.oa();Z(this);this.$b=null;super.f()}Kc(f){this.G||this.la||f.target!==this.ab||(this.H=this.Yc=!0,this.ga=-1,Z(this),this.i.vc("ended",this.Z,this.Ob))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Yc}mc(){return!this.j||this.H?!0:this.T()}Ba(){let f;f=this.G?this.N:this.ac+(this.zb()-this.bc)*this.sa;this.V||(f=Math.min(f,this.ea()));
return f}Play(f,a,b,d){this.ed=1;this.Fb(a);Z(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.$;this.j.connect(this.M);this.ab=this.j;this.j.onended=this.$b;this.j.loop=f;this.j.start(d,b);this.G=this.H=this.Yc=!1;this.V=f;this.sa=1;this.bc=this.zb();this.ac=b}oa(){if(this.j)try{this.j.stop(0)}catch(f){}this.H=!0;this.G=!1;this.ga=-1}Xa(){this.G||this.H||this.T()||(this.N=this.Ba(),this.V&&(this.N%=this.ea()),this.G=!0,this.j.stop(0))}Cb(){!this.G||this.H||this.T()||(Z(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.$b,this.j.loop=this.V,this.Nb(),this.Fa(),this.j.start(0,this.N),this.bc=this.zb(),this.ac=this.N,this.G=!1)}rc(){return super.rc()*this.ed}Mb(){this.ed=this.Ha||this.Bb()?0:1;this.Nb()}xc(f){f=!!f;this.V!==f&&(this.V=f,this.j&&(this.j.loop=f))}Fa(){let f=this.sa;this.bd&&(f*=this.i.jc);this.j&&(this.j.playbackRate.value=f)}wc(f){this.H||this.T()||(this.G?this.N=f:(this.Xa(),this.N=f,this.Cb()))}sc(){return this.N}yc(f){f?
this.IsPlaying()?(this.la=!0,this.N=this.Ba(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.la=!1:this.la&&(Z(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.$b,this.j.loop=this.V,this.Nb(),this.Fa(),this.j.start(0,this.N),this.bc=this.zb(),this.ac=this.N,this.la=!1)}Hc(f){super.Hc(f);this.N=f.resumePosition}};"use strict";
{class f{constructor(a){this.i=a;this.c=a.W();this.Xd=-1;this.R=this.Z="";this.g=null}f(){this.c=null}ng(a){this.Xd=a}vg(a){this.Z=a}o(){return this.c.createGain()}P(){}S(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var n=this.c.currentTime;g+=n;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,g)}}}Ua(){return{type:this.R,tag:this.Z,params:this.g}}}
self.te=class extends f{constructor(a,b,d,g,n,p,v){super(a);this.R="filter";this.g=[b,d,g,n,p,v];this.l=this.o();this.b=this.o();this.b.gain.value=v;this.a=this.o();this.a.gain.value=1-v;this.A=this.c.createBiquadFilter();this.A.type=b;this.A.frequency.value=d;this.A.detune.value=g;this.A.Q.value=n;this.A.gain.vlaue=p;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b)}f(){this.l.disconnect();this.A.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.A.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.A.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.A.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.A.gain,b,d,g)}}};self.re=class extends f{constructor(a,b,d,g){super(a);this.R="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.nb=this.o();this.U=this.c.createDelay(b);this.U.delayTime.value=b;this.eb=this.o();this.eb.gain.value=d;this.l.connect(this.nb);this.l.connect(this.a);this.nb.connect(this.b);this.nb.connect(this.U);this.U.connect(this.eb);this.eb.connect(this.nb)}f(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.nb.disconnect();this.U.disconnect();this.eb.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){const n=self.da.sd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=n(b);this.m(this.eb.gain,n(b),d,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,g)}}};self.qe=class extends f{constructor(a,b,d,g){super(a);this.R="convolution";this.g=[d,g];this.Sd=this.Rd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.cb=this.c.createConvolver();this.cb.normalize=d;this.cb.buffer=b;this.l.connect(this.cb);this.l.connect(this.a);this.cb.connect(this.b)}f(){this.l.disconnect();this.cb.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}jg(a,b){this.Rd=a;this.Sd=b}Ua(){const a=
super.Ua();a.bufferOriginalUrl=this.Rd;a.bufferUrl="";a.bufferType=this.Sd;return a}};self.ue=class extends f{constructor(a,b,d,g,n,p){super(a);this.R="flanger";this.g=[b,d,g,n,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.gb=this.o();this.gb.gain.value=n;this.U=this.c.createDelay(b+d);this.U.delayTime.value=b;this.v=this.c.createOscillator();this.v.frequency.value=g;this.I=this.o();this.I.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.gb);this.gb.connect(this.U);this.v.connect(this.I);this.I.connect(this.U.delayTime);this.v.start(0)}f(){this.v.stop(0);this.l.disconnect();this.U.disconnect();this.v.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.gb.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.v.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.gb.gain,b/100,d,g)}}};self.we=class extends f{constructor(a,b,d,g,n,p,v){super(a);this.R="phaser";this.g=[b,d,g,n,p,v];this.l=this.o();this.a=this.o();this.a.gain.value=1-v/2;this.b=this.o();this.b.gain.value=v/2;this.A=this.c.createBiquadFilter();this.A.type="allpass";this.A.frequency.value=b;this.A.detune.value=
d;this.A.Q.value=g;this.v=this.c.createOscillator();this.v.frequency.value=p;this.I=this.o();this.I.gain.value=n;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b);this.v.connect(this.I);this.I.connect(this.A.frequency);this.v.start(0)}f(){this.v.stop(0);this.l.disconnect();this.A.disconnect();this.v.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.A.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.A.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.A.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.v.frequency,b,d,g)}}};self.ve=class extends f{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){const n=self.da.sd;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,g)}}};self.ye=class extends f{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.v=this.c.createOscillator();this.v.frequency.value=b;this.I=this.o();this.I.gain.value=d/2;this.v.connect(this.I);this.I.connect(this.h.gain);this.v.start(0)}f(){this.v.stop(0);this.v.disconnect();
this.I.disconnect();this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,g);this.m(this.I.gain,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.v.frequency,b,d,g)}}};self.xe=class extends f{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.tb=this.o();this.tb.gain.value=
0;this.v=this.c.createOscillator();this.v.frequency.value=b;this.v.connect(this.tb.gain);this.v.start(0);this.l.connect(this.tb);this.l.connect(this.a);this.tb.connect(this.b)}f(){this.v.stop(0);this.v.disconnect();this.tb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,g);
this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.v.frequency,b,d,g)}}};self.se=class extends f{constructor(a,b,d,g,n,p){super(a);this.R="distortion";this.g=[b,d,g,n,p];this.l=this.o();this.fc=this.o();this.ec=this.o();this.kg(g,n);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.kc=this.c.createWaveShaper();this.Vc=new Float32Array(65536);this.rf(b,d);this.kc.curve=this.Vc;this.l.connect(this.fc);this.l.connect(this.a);this.fc.connect(this.kc);this.kc.connect(this.ec);
this.ec.connect(this.b)}f(){this.l.disconnect();this.fc.disconnect();this.kc.disconnect();this.ec.disconnect();this.b.disconnect();this.a.disconnect();super.f()}kg(a,b){.01>a&&(a=.01);this.fc.gain.value=a;this.ec.gain.value=Math.pow(1/a,.6)*b}rf(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.xg(g,a,b);this.Vc[32768+d]=g;this.Vc[32768-d-1]=-g}}xg(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.da.Og(g-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.pe=class extends f{constructor(a,b,d,g,n,p){super(a);this.R="compressor";this.g=[b,d,g,n,p];this.h=this.c.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=n;this.h.release.value=p}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.oe=class extends f{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.c.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Vd=new Float32Array(this.h.frequencyBinCount);this.he=new Uint8Array(b);this.fe=this.La=0;this.i.$e(this)}f(){this.i.dg(this);this.h.disconnect();super.f()}Da(){this.h.getFloatFrequencyData(this.Vd);this.h.getByteTimeDomainData(this.he);const a=this.h.fftSize;let b=this.La=0;for(var d=0;d<a;++d){let g=(this.he[d]-128)/128;0>g&&(g=-g);
this.La<g&&(this.La=g);b+=g*g}d=self.da.Qe;this.La=d(this.La);this.fe=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Je(){return{tag:this.Z,index:this.Xd,peak:this.La,rms:this.fe,binCount:this.h.frequencyBinCount,freqBins:this.Vd}}}}"use strict";
{function f(b){b.stopPropagation()}function a(b){13!==b.which&&27!==b.which&&b.stopPropagation()}self.na.Sa(class extends self.Ee{constructor(b){super(b,"text-input");Q(this,"scroll-to-bottom",d=>this.Vf(d))}rd(b,d){let g;const n=d.type;"textarea"===n?(g=document.createElement("textarea"),g.style.resize="none"):(g=document.createElement("input"),g.type=n);g.style.position="absolute";g.autocomplete="off";g.addEventListener("touchstart",f);g.addEventListener("touchmove",f);g.addEventListener("touchend",
f);g.addEventListener("mousedown",f);g.addEventListener("mouseup",f);g.addEventListener("keydown",a);g.addEventListener("keyup",a);g.addEventListener("click",p=>{p.stopPropagation();R(this,"click",b)});g.addEventListener("dblclick",p=>{p.stopPropagation();R(this,"dblclick",b)});g.addEventListener("input",()=>P(this,"change",b,{text:g.value}));d.id&&(g.id=d.id);this.Ac(g,d);return g}Ac(b,d){b.value=d.text;b.placeholder=d.placeholder;b.title=d.title;b.disabled=!d.isEnabled;b.readOnly=d.isReadOnly;b.spellcheck=
d.spellCheck;d=d.maxLength;0>d?b.removeAttribute("maxlength"):b.setAttribute("maxlength",d)}Vf(b){b.scrollTop=b.scrollHeight}})}"use strict";function ca(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>w(f,"sw-message",a.data))}
function ea(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(f):screen.webkitLockOrientation?a=screen.webkitLockOrientation(f):screen.mozLockOrientation?a=screen.mozLockOrientation(f):screen.msLockOrientation&&(a=screen.msLockOrientation(f));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.na.Sa(class extends self.Ta{constructor(f){super(f,"browser");this.s="";L(this,[["get-initial-state",a=>{this.s=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>ca(this)],
["alert",a=>this.Ic(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Oc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ea(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===
a||"windows-webview2"===a?window.open(b,"_blank"):this.bh||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.s||"macos-wkwebview"===this.s)self.na.Lb(!0),this.u.Sc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":
2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.s||"macos-wkwebview"===this.s?(self.na.Lb(!1),this.u.Sc({type:"set-fullscreen",fullscreen:!1})):
document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{w(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{w(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{w(this,"hashchange",{location:location.toString()})});
document.addEventListener("backbutton",()=>{w(this,"backbutton")})}Ic(f){alert(f.message)}Oc(f){f=f.isFocus;if("nwjs"===this.s){const a="nwjs"===this.s?nw.Window.get():null;f?a.focus():a.blur()}else f?window.focus():window.blur()}});
