'use strict';function v(f,a,b,d){f.u.Fb(f.gb,a,b,d,void 0)}function H(f,a,b,d){f.u.da?v(f,a,b,d):f.u.Bf()._OnMessageFromDOM({type:"event",component:f.gb,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function J(f,a,b){f.u.C(f.gb,a,b)}function K(f,a){for(const [b,d]of a)J(f,b,d)}function M(f){f.Vb||(f.u.kf(f.se),f.Vb=!0)}window.Da=class{constructor(f,a){this.u=f;this.gb=a;this.Vb=!1;this.se=()=>this.Ga()}rd(){}Ga(){}};function N(f){-1!==f.Ua&&(self.clearTimeout(f.Ua),f.Ua=-1)}
window.$e=class{constructor(f,a){this.Yc=f;this.Tg=a;this.Ua=-1;this.Wb=-Infinity;this.te=()=>{this.Ua=-1;this.Wb=Date.now();this.lb=!0;this.Yc();this.lb=!1};this.Xd=this.lb=!1}f(){N(this);this.te=this.Yc=null}};"use strict";function P(f,a){J(f,"get-element",b=>{const d=f.ca.get(b.elementId);return a(d,b)})}
window.oh=class extends self.Da{constructor(f,a){super(f,a);this.ca=new Map;this.Xc=!0;K(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ca.get(b);this.Xc&&d.parentElement.removeChild(d);this.ca.delete(b)}}],["set-visible",b=>{this.Xc&&(this.ca.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Xc){var d=this.ca.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ca.get(b.elementId);throw Error("required override");}],["focus",b=>this.Qc(b)],["set-css-style",b=>{this.ca.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ca.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ca.get(b.elementId).removeAttribute(b.name)}]]);P(this,b=>b)}Qc(f){var a=this.ca.get(f.elementId);f.focus?a.focus():a.blur()}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),a=/android/i.test(navigator.userAgent);let b=0;function d(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.dh?new Promise(k=>{const l="c3_resolve_"+b;++b;self[l]=k;c.textContent=m.ih+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let h=!1,n=!1;function q(){if(!h){try{new Worker("blob://",{get type(){n=
!0}})}catch(m){}h=!0}return n}let w=new Audio;const B={"audio/webm; codecs=opus":!!w.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!w.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!w.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!w.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!w.canPlayType("audio/mp4"),"audio/mpeg":!!w.canPlayType("audio/mpeg")};w=null;async function E(m){m=await y(m);return(new TextDecoder("utf-8")).decode(m)}
function y(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=p=>c(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(m)})}const z=[];let C=0;window.RealFile=window.File;const F=[],A=new Map,G=new Map;let I=0;const L=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");L.push(m)};const e=new Set(["cordova","playable-ad","instant-games"]);let g=!1;window.oa=class m{constructor(c){this.da=c.kh;this.sa=null;this.Y="";this.lc=c.hh;
this.Bb={};this.Na=this.Ab=null;this.Tb=[];this.D=this.Sa=null;this.fd=!1;this.$d=0;this.ob=null;this.Ra=-1;this.Yg=()=>this.cg();this.Qa=[];this.s=c.ue;this.mb="file"===location.protocol.substr(0,4);!this.da||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&q()||(this.da=!1);if("playable-ad"===this.s||"instant-games"===this.s)this.da=!1;if("cordova"===this.s&&this.da)if(a){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.da=!1)}else this.da=!1;this.Zb=
this.ja=null;"html5"!==this.s&&"playable-ad"!==this.s||!this.mb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.s||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",
k=>this.If(k));this.C("runtime","create-job-worker",()=>this.Jf());"cordova"===this.s?document.addEventListener("deviceready",()=>this.Jd(c)):this.Jd(c)}f(){this.Cc();this.sa&&(this.sa=this.sa.onmessage=null);this.Ab&&(this.Ab.terminate(),this.Ab=null);this.Na&&(this.Na.f(),this.Na=null);this.D&&(this.D.parentElement.removeChild(this.D),this.D=null)}Ve(){return f&&"cordova"===this.s}wc(){const c=navigator.userAgent;return f&&e.has(this.s)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}Te(){return a}yd(){return a&&
e.has(this.s)}async Jd(c){"macos-wkwebview"===this.s&&this.Uc({type:"ready"});if("playable-ad"===this.s){this.ja=self.c3_base64files;this.Zb={};await this.qf();for(let l=0,p=c.Va.length;l<p;++l){var k=c.Va[l].toLowerCase();this.Zb.hasOwnProperty(k)?c.Va[l]={dh:!0,ih:this.Zb[k]}:this.ja.hasOwnProperty(k)&&(c.Va[l]=URL.createObjectURL(this.ja[k]))}}c.gh?this.Y=c.gh:(k=location.origin,this.Y=("null"===k?"file:///":k)+location.pathname,k=this.Y.lastIndexOf("/"),-1!==k&&(this.Y=this.Y.substr(0,k+1)));
c.mh&&(this.Bb=c.mh);k=new MessageChannel;this.sa=k.port1;this.sa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Wf(l));this.ob=new self.We(this);await Q(this.ob);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((l,p)=>{window.AndroidFullScreen.immersiveMode(l,p)})}catch(l){console.error("Failed to enter Android immersive mode: ",l)}this.da?await this.Df(c,
k.port2):await this.Cf(c,k.port2)}Fc(c){c=this.Bb.hasOwnProperty(c)?this.Bb[c]:c.endsWith("/workermain.js")&&this.Bb.hasOwnProperty("workermain.js")?this.Bb["workermain.js"]:"playable-ad"===this.s&&this.ja.hasOwnProperty(c.toLowerCase())?this.ja[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async qc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.s&&this.mb)return c=await this.Cb(l.bh?c:this.lc+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),
l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}qa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}Id(c){var k=this.Y,l=location.href,p=this.qa(),u=this.ga(),r=window.devicePixelRatio,t=m.Za(),x=c.uh,D=window.cr_previewImageBlobs||this.ja,V=window.cr_previewProjectFileBlobs,W=window.cr_previewProjectFiles,X=window.sh||
"";c=c.ue;var Y=(new URLSearchParams(self.location.search)).has("debug"),O=this.ob;return{runtimeBaseUrl:k,previewUrl:l,windowInnerWidth:p,windowInnerHeight:u,devicePixelRatio:r,isFullscreen:t,projectData:x,previewImageBlobs:D,previewProjectFileBlobs:V,previewProjectFileSWUrls:W,swClientId:X,exportType:c,isDebug:Y,ife:!!self.th,jobScheduler:{inputPort:O.ed,outputPort:O.ld,maxNumWorkers:O.Vg},supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.lc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.lc+"opus.wasm.wasm",isFileProtocol:this.mb,isiOSCordova:this.Ve(),isiOSWebView:this.wc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Df(c,k){var l=this.Fc(c.lh);this.Ab=await this.qc(l,this.Y,{type:"module",name:"Runtime",bh:!0});this.D=document.createElement("canvas");this.D.style.display="none";l=this.D.transferControlToOffscreen();document.body.appendChild(this.D);window.c3canvas=this.D;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let p=c.qd||[],u=c.Va;
p=await Promise.all(p.map(r=>this.Ha(r)));u=await Promise.all(u.map(r=>this.Ha(r)));if("cordova"===this.s)for(let r=0,t=c.oc.length;r<t;++r){const x=c.oc[r],D=x[0];if(D===c.od||"scriptsInEvents.js"===D||D.endsWith("/scriptsInEvents.js"))x[1]=await this.Ha(D)}this.Ab.postMessage(Object.assign(this.Id(c),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:p,engineScripts:u,projectScripts:c.oc,mainProjectScript:c.od,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,
l,...R(this.ob)]);this.Tb=F.map(r=>new r(this));this.Hd();self.c3_callFunction=(r,t)=>this.Sa.Ef(r,t);"preview"===this.s&&(self.goToLastErrorScript=()=>this.Fb("runtime","go-to-last-error-script"))}async Cf(c,k){this.D=document.createElement("canvas");this.D.style.display="none";document.body.appendChild(this.D);window.c3canvas=this.D;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Tb=F.map(r=>new r(this));this.Hd();var l=c.Va.map(r=>"string"===typeof r?(new URL(r,this.Y)).toString():
r);Array.isArray(c.qd)&&l.unshift(...c.qd);l=await Promise.all(l.map(r=>this.Ha(r)));await Promise.all(l.map(r=>d(r)));l=self.C3_ProjectScriptsStatus;const p=c.od,u=c.oc;for(let [r,t]of u)if(t||(t=r),r===p)try{t=await this.Ha(t),await d(t),"preview"!==this.s||l[r]||this.Sd(r,"main script did not run to completion")}catch(x){this.Sd(r,x)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))t=await this.Ha(t),await d(t);"preview"===this.s&&"object"!==typeof self.nh.ph?(this.Ob(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Id(c),{isInWorker:!1,messagePort:k,canvas:this.D,runOnStartupFunctions:L}),this.Ld(),this.Na=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Na,c))}Sd(c,k){this.Ob();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ld(){this.Ob()}Ob(){const c=
window.Zg;c&&(c.parentElement.removeChild(c),window.Zg=null)}async Jf(){const c=await S(this.ob);return{outputPort:c,transferables:[c]}}Bf(){if(this.da)throw Error("not available in worker mode");return this.Na}Fb(c,k,l,p,u){this.sa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:null},u)}Ad(c,k,l,p,u){const r=I++,t=new Promise((x,D)=>{G.set(r,{resolve:x,reject:D})});this.sa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:r},
u);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.Of(c);if("result"===k)this.fg(c);else if("runtime-ready"===k)this.gg();else if("alert-error"===k)this.Ob(),alert(c.message);else if("creating-runtime"===k)this.Ld();else throw Error(`unknown message '${k}'`);}Of(c){const k=c.component,l=c.handler,p=c.data,u=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(p)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==u&&this.Nb(u,!1,""+t);return}if(null===
u)return r;r&&r.then?r.then(t=>this.Nb(u,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Nb(u,!1,""+t)}):this.Nb(u,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Nb(c,k,l){let p;l&&l.transferables&&(p=l.transferables);this.sa.postMessage({type:"result",responseId:c,isOk:k,result:l},p)}fg(c){const k=c.responseId,l=c.isOk;c=c.result;const p=G.get(k);l?p.resolve(c):p.reject(c);G.delete(k)}C(c,
k,l){let p=A.get(c);p||(p=new Map,A.set(c,p));if(p.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);p.set(k,l)}static Wa(c){if(F.includes(c))throw Error("DOM handler already added");F.push(c)}Hd(){for(const c of this.Tb)if("runtime"===c.gb){this.Sa=c;return}throw Error("cannot find runtime DOM handler");}Wf(c){this.Fb("debugger","message",c)}gg(){for(const c of this.Tb)c.rd()}static Za(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
g)}static Pb(c){g=!!c}kf(c){this.Qa.push(c);this.Tc()}sg(c){c=this.Qa.indexOf(c);if(-1===c)throw Error("invalid callback");this.Qa.splice(c,1);this.Qa.length||this.Cc()}Tc(){-1===this.Ra&&this.Qa.length&&(this.Ra=requestAnimationFrame(this.Yg))}Cc(){-1!==this.Ra&&(cancelAnimationFrame(this.Ra),this.Ra=-1)}cg(){this.Ra=-1;for(const c of this.Qa)c();this.Tc()}xa(c){this.Sa.xa(c)}Fa(c){this.Sa.Fa(c)}Sc(){this.Sa.Sc()}Ib(c){this.Sa.Ib(c)}Ue(){return!!B["audio/webm; codecs=opus"]}async Rg(c){c=await this.Ad("runtime",
"opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}cf(c){this.fd=!0;this.$d=c}Se(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}zd(c){return!this.Se(c)}async Ha(c){return"cordova"===this.s&&(c.startsWith("file:")||this.mb&&this.zd(c))?(c.startsWith(this.Y)&&(c=c.substr(this.Y.length)),c=await this.Cb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async If(c){const k=c.filename;switch(c.as){case "text":return await this.Le(k);
case "buffer":return await this.Cb(k);default:throw Error("unsupported type");}}ud(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(l,p)},p)})}async Le(c){c=await this.ud(c);return await E(c)}Dc(){if(z.length&&!(8<=C)){C++;var c=z.shift();this.rf(c.filename,c.jh,c.ah)}}Cb(c){return new Promise((k,l)=>{z.push({filename:c,jh:p=>{C--;this.Dc();k(p)},ah:p=>{C--;this.Dc();l(p)}});this.Dc()})}async rf(c,k,
l){try{const p=await this.ud(c),u=await y(p);k(u)}catch(p){l(p)}}Uc(c){if("windows-webview2"===this.s)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.s)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async qf(){const c=[];for(const [k,l]of Object.entries(this.ja))c.push(this.pf(k,l));await Promise.all(c)}async pf(c,k){if("object"===typeof k)this.ja[c]=new Blob([k.str],{type:k.type}),this.Zb[c]=
k.str;else{let l=await this.zf(k);l||(l=this.tf(k));this.ja[c]=l}}async zf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}tf(c){c=this.mg(c);return this.nf(c.data,c.eh)}mg(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);
k=c.substring(5,k).split(";");c=k[0]||"";const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{eh:c,data:l}}nf(c,k){var l=c.length;let p=l>>2,u=new Uint8Array(l),r=new Uint32Array(u.buffer,0,p),t,x;for(x=t=0;t<p;++t)r[t]=c.charCodeAt(x++)|c.charCodeAt(x++)<<8|c.charCodeAt(x++)<<16|c.charCodeAt(x++)<<24;for(l&=3;l--;)u[x]=c.charCodeAt(x),++x;return new Blob([u],{type:k})}}}"use strict";
{const f=self.oa;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},h={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(e){return new Promise((g,m)=>{const c=document.createElement("link");c.onload=()=>g(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=e;document.head.appendChild(c)})}function w(e){return new Promise((g,m)=>{const c=new Image;c.onload=()=>g(c);c.onerror=k=>m(k);c.src=e})}async function B(e){e=URL.createObjectURL(e);try{return await w(e)}finally{URL.revokeObjectURL(e)}}function E(e){return new Promise((g,m)=>{let c=new FileReader;c.onload=k=>g(k.target.result);c.onerror=k=>m(k);c.readAsText(e)})}async function y(e,g,m){if(!/firefox/i.test(navigator.userAgent))return await B(e);var c=await E(e);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),p=k.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await B(e)}k.setAttribute("width",g+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);e=new Blob([c],{type:"image/svg+xml"});return await B(e)}function z(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),F=new Set(["canvas","body","html"]);function A(e){F.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function G(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await B(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const g=e.getBoundingClientRect();document.body.removeChild(e);return[g.width,
g.height]}};self.C3_RasterSvgImageBlob=async function(e,g,m,c,k){e=await y(e,g,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(e,0,0,g,m);return l};let I=!1;document.addEventListener("pause",()=>I=!0);document.addEventListener("resume",()=>I=!1);function L(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.Wa(class extends self.Da{constructor(e){super(e,"runtime");this.fe=!0;this.Ta=-1;this.md="any";this.Td=this.Ud=!1;this.za=
null;this.W=!1;this.ae="";this.ad=-1;this.Ma=this.wb=null;this.hc=this.fc=0;this.Zd=!1;this.je=e.qa();this.Xb=e.ga();this.yb=0;e.C("canvas","update-size",c=>this.jg(c));e.C("runtime","invoke-download",c=>this.Uf(c));e.C("runtime","raster-svg-image",c=>this.dg(c));e.C("runtime","get-svg-image-size",c=>this.Sf(c));e.C("runtime","set-target-orientation",c=>this.hg(c));e.C("runtime","register-sw",()=>this.eg());e.C("runtime","post-to-debugger",c=>this.Od(c));e.C("runtime","go-to-script",c=>this.Od(c));
e.C("runtime","before-start-ticking",()=>this.Hf());e.C("runtime","debug-highlight",c=>this.Kf(c));e.C("runtime","enable-device-orientation",()=>this.mf());e.C("runtime","enable-device-motion",()=>this.lf());e.C("runtime","add-stylesheet",c=>this.Gf(c));e.C("runtime","alert",c=>this.Jc(c));e.C("runtime","hide-cordova-splash",()=>this.Tf());e.C("runtime","set-exporting-to-video",c=>this.yg(c));e.C("runtime","export-to-video-progress",c=>this.Pf(c));e.C("runtime","exported-to-video",c=>this.Qf(c));
const g=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const k=c.target;g.has(k.tagName.toLowerCase())||z(k)||c.preventDefault()});const m=e.D;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",
A)):m.addEventListener("touchstart",A);this.tb=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",G,{passive:!1});window.addEventListener("wheel",G,{passive:!1});window.addEventListener("resize",()=>this.kg());window.addEventListener("fullscreenchange",()=>this.ab());window.addEventListener("webkitfullscreenchange",()=>this.ab());window.addEventListener("mozfullscreenchange",()=>this.ab());window.addEventListener("fullscreenerror",c=>
this.Mc(c));window.addEventListener("webkitfullscreenerror",c=>this.Mc(c));window.addEventListener("mozfullscreenerror",c=>this.Mc(c));if(e.wc())if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const k=window.visualViewport.height;k>c&&(document.scrollingElement.scrollTop=0);c=k})}else window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||"text"):z(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.lg(c);this.Oa=new Set;this.ac=new WeakSet;this.ra=!1}Hf(){self.setTimeout(()=>{this.Zd=!0},1E3);"cordova"===this.u.s?(document.addEventListener("pause",()=>this.Rc(!0)),document.addEventListener("resume",()=>this.Rc(!1))):document.addEventListener("visibilitychange",()=>this.Rc(document.hidden));return{isSuspended:!(!document.hidden&&!I)}}rd(){window.addEventListener("focus",
()=>this.cb("window-focus"));window.addEventListener("blur",()=>{this.cb("window-blur",{parentHasFocus:L()});this.tb=0});window.addEventListener("focusin",g=>{g=g.target;(C.has(g.tagName.toLowerCase())||z(g))&&this.cb("keyboard-blur")});window.addEventListener("keydown",g=>this.Md("keydown",g));window.addEventListener("keyup",g=>this.Md("keyup",g));window.addEventListener("dblclick",g=>this.Oc("dblclick",g,d));window.addEventListener("wheel",g=>this.Yf(g));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
g=>{this.Gc(g);this.bb("pointerdown",g)}),this.u.da&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.wb=new self.$e(()=>this.wf(),5),this.wb.Xd=!0,window.addEventListener("pointerrawupdate",g=>this.bg(g))):window.addEventListener("pointermove",g=>this.bb("pointermove",g)),window.addEventListener("pointerup",g=>this.bb("pointerup",g)),window.addEventListener("pointercancel",g=>this.bb("pointercancel",g))):(window.addEventListener("mousedown",g=>{this.Gc(g);this.Pc("pointerdown",
g)}),window.addEventListener("mousemove",g=>this.Pc("pointermove",g)),window.addEventListener("mouseup",g=>this.Pc("pointerup",g)),window.addEventListener("touchstart",g=>{this.Gc(g);this.Mb("pointerdown",g)}),window.addEventListener("touchmove",g=>this.Mb("pointermove",g)),window.addEventListener("touchend",g=>this.Mb("pointerup",g)),window.addEventListener("touchcancel",g=>this.Mb("pointercancel",g)));const e=()=>this.Sc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0);this.u.Te()&&!this.u.yd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this.Kc(this.ga(),navigator.virtualKeyboard.boundingRect.height)}))}Kc(e,g){document.body.style.transform="";if(0<g){var m=document.activeElement;m&&(m=m.getBoundingClientRect(),e=(m.top+m.bottom)/2-(e-g)/
2,e>g&&(e=g),0>e&&(e=0),0<e&&(document.body.style.transform=`translateY(${-e}px)`))}}cb(e,g){v(this,e,g||null,n)}qa(){return this.u.qa()}ga(){return this.u.ga()}kg(){if(!this.W){var e=this.qa(),g=this.ga();if(this.u.yd()){if(this.Zd){if(this.je===e&&g<this.Xb){this.yb=this.Xb-g;this.Kc(this.Xb,this.yb);return}0<this.yb&&(this.yb=0,this.Kc(g,this.yb))}this.je=e;this.Xb=g}this.cb("window-resize",{innerWidth:e,innerHeight:g,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Za()});this.u.wc()&&
(-1!==this.Ta&&clearTimeout(this.Ta),this.Pd(e,g,0))}}tg(e,g,m){-1!==this.Ta&&clearTimeout(this.Ta);this.Ta=setTimeout(()=>this.Pd(e,g,m),48)}Pd(e,g,m){const c=this.qa(),k=this.ga();this.Ta=-1;c!=e||k!=g?this.cb("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Za()}):10>m&&this.tg(c,k,m+1)}hg(e){this.md=e.targetOrientation}Ng(){const e=this.md;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(g=>console.warn("[Construct 3] Failed to lock orientation: ",
g));else try{let g=!1;screen.lockOrientation?g=screen.lockOrientation(e):screen.webkitLockOrientation?g=screen.webkitLockOrientation(e):screen.mozLockOrientation?g=screen.mozLockOrientation(e):screen.msLockOrientation&&(g=screen.msLockOrientation(e));g||console.warn("[Construct 3] Failed to lock orientation")}catch(g){console.warn("[Construct 3] Failed to lock orientation: ",g)}}ab(){if(!this.W){var e=f.Za();e&&"any"!==this.md&&this.Ng();v(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.qa(),
innerHeight:this.ga()})}}Mc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);v(this,"fullscreenerror",{isFullscreen:f.Za(),innerWidth:this.qa(),innerHeight:this.ga()})}Rc(e){e?this.u.Cc():this.u.Tc();v(this,"visibilitychange",{hidden:e})}Md(e,g){"Backspace"===g.key&&A(g);if(!this.W){var m=b.get(g.code)||g.code;H(this,e,{code:m,key:g.key,which:g.which,repeat:g.repeat,altKey:g.altKey,ctrlKey:g.ctrlKey,metaKey:g.metaKey,shiftKey:g.shiftKey,timeStamp:g.timeStamp},d)}}Yf(e){this.W||v(this,
"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},d)}Oc(e,g,m){this.W||a(g)||H(this,e,{button:g.button,buttons:g.buttons,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,movementX:g.movementX||0,movementY:g.movementY||0,timeStamp:g.timeStamp},m)}Pc(e,g){if(!this.W&&!a(g)){var m=this.tb;"pointerdown"===e&&0!==m?e="pointermove":"pointerup"===e&&0!==g.buttons&&(e="pointermove");
H(this,e,{pointerId:1,pointerType:"mouse",button:g.button,buttons:g.buttons,lastButtons:m,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,movementX:g.movementX||0,movementY:g.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:g.timeStamp},d);this.tb=g.buttons;this.Oc(g.type,g,h)}}bb(e,g){if(!this.W){if(this.wb&&"pointermove"!==e){var m=this.wb;m.lb||(N(m),m.Wb=Date.now())}m=0;"mouse"===g.pointerType&&(m=this.tb);H(this,e,{pointerId:g.pointerId,
pointerType:g.pointerType,button:g.button,buttons:g.buttons,lastButtons:m,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,movementX:(g.movementX||0)+this.fc,movementY:(g.movementY||0)+this.hc,width:g.width||0,height:g.height||0,pressure:g.pressure||0,tangentialPressure:g.tangentialPressure||0,tiltX:g.tiltX||0,tiltY:g.tiltY||0,twist:g.twist||0,timeStamp:g.timeStamp},d);this.hc=this.fc=0;"mouse"===g.pointerType&&(m="mousemove","pointerdown"===e?m="mousedown":"pointerup"===e&&(m="mouseup"),
this.Oc(m,g,h),this.tb=g.buttons)}}bg(e){this.Ma&&(this.fc+=this.Ma.movementX||0,this.hc+=this.Ma.movementY||0);this.Ma=e;e=this.wb;if(-1===e.Ua){var g=Date.now(),m=g-e.Wb,c=e.Tg;m>=c&&e.Xd?(e.Wb=g,e.lb=!0,e.Yc(),e.lb=!1):e.Ua=self.setTimeout(e.te,Math.max(c-m,4))}}wf(){this.bb("pointermove",this.Ma);this.Ma=null}Mb(e,g){if(!this.W)for(let m=0,c=g.changedTouches.length;m<c;++m){const k=g.changedTouches[m];H(this,e,{pointerId:k.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,
clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,movementX:g.movementX||0,movementY:g.movementY||0,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:g.timeStamp},d)}}Gc(e){window!==window.top&&window.focus();this.Kd(e.target)&&document.activeElement&&!this.Kd(document.activeElement)&&document.activeElement.blur()}Kd(e){return!e||e===document||e===window||e===document.body||
"canvas"===e.tagName.toLowerCase()}mf(){this.Ud||(this.Ud=!0,window.addEventListener("deviceorientation",e=>this.Mf(e)),window.addEventListener("deviceorientationabsolute",e=>this.Nf(e)))}lf(){this.Td||(this.Td=!0,window.addEventListener("devicemotion",e=>this.Lf(e)))}Mf(e){this.W||v(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}Nf(e){this.W||
v(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}Lf(e){if(!this.W){var g=null,m=e.acceleration;m&&(g={x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=e.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var k=e.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});v(this,"devicemotion",{acceleration:g,accelerationIncludingGravity:m,rotationRate:c,interval:e.interval,timeStamp:e.timeStamp},
d)}}jg(e){var g=this.u;g.fd||(g=g.D,g.style.width=e.styleWidth+"px",g.style.height=e.styleHeight+"px",g.style.marginLeft=e.marginLeft+"px",g.style.marginTop=e.marginTop+"px",this.fe&&(g.style.display="",this.fe=!1))}Uf(e){const g=e.url;e=e.filename;const m=document.createElement("a"),c=document.body;m.textContent=e;m.href=g;m.download=e;c.appendChild(m);m.click();c.removeChild(m)}async dg(e){var g=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,
e.surfaceHeight);g=g?await createImageBitmap(e,g):await createImageBitmap(e);return{imageBitmap:g,transferables:[g]}}async Sf(e){return await self.C3_GetSvgImageSize(e.blob)}async Gf(e){await q(e.url)}Sc(){var e=[...this.Oa];this.Oa.clear();if(!this.ra)for(const g of e)(e=g.play())&&e.catch(()=>{this.ac.has(g)||this.Oa.add(g)})}xa(e){if("function"!==typeof e.play)throw Error("missing play function");this.ac.delete(e);let g;try{g=e.play()}catch(m){this.Oa.add(e);return}g&&g.catch(()=>{this.ac.has(e)||
this.Oa.add(e)})}Fa(e){this.Oa.delete(e);this.ac.add(e)}Ib(e){this.ra=!!e}Tf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Kf(e){if(e.show){this.za||(this.za=document.createElement("div"),this.za.id="inspectOutline",document.body.appendChild(this.za));var g=this.za;g.style.display="";g.style.left=e.left-1+"px";g.style.top=e.top-1+"px";g.style.width=e.width+2+"px";g.style.height=e.height+2+"px";g.textContent=e.name}else this.za&&(this.za.style.display="none")}eg(){window.C3_RegisterSW&&
window.C3_RegisterSW()}Od(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}Ef(e,g){return this.u.Ad(this.gb,"js-invoke-function",{name:e,params:g},void 0,void 0)}Jc(e){alert(e.message)}lg(e){"entered-fullscreen"===e?(f.Pb(!0),this.ab()):"exited-fullscreen"===e?(f.Pb(!1),this.ab()):console.warn("Unknown wrapper message: ",e)}yg(e){this.W=!0;const g=document.createElement("h1");g.id="exportToVideoMessage";g.textContent=e.message;document.body.prepend(g);document.body.classList.add("exportingToVideo");
this.u.D.style.display="";this.u.cf(e.duration)}Pf(e){this.ae=e.message;-1===this.ad&&(this.ad=setTimeout(()=>this.xf(),250))}xf(){this.ad=-1;const e=document.getElementById("exportToVideoMessage");e&&(e.textContent=this.ae)}Qf(e){window.rh({type:"exported-video",blob:e.blob,time:e.time})}})}"use strict";
async function Q(f){if(f.Sg)throw Error("already initialised");f.Sg=!0;var a=f.kc.Fc("dispatchworker.js");f.$c=await f.kc.qc(a,f.fb,{name:"DispatchWorker"});a=new MessageChannel;f.ed=a.port1;f.$c.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.ld=await S(f)}function R(f){return[f.ed,f.ld]}
async function S(f){const a=f.ge.length;var b=f.kc.Fc("jobworker.js");b=await f.kc.qc(b,f.fb,{name:"JobWorker"+a});const d=new MessageChannel,h=new MessageChannel;f.$c.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":h.port2},[d.port2,h.port2]);f.ge.push(b);return h.port1}
self.We=class{constructor(f){this.kc=f;this.fb=f.Y;this.fb="preview"===f.s?this.fb+"workers/":this.fb+f.lc;this.Vg=Math.min(navigator.hardwareConcurrency||2,16);this.$c=null;this.ge=[];this.ld=this.ed=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.oa({kh:!1,lh:"workermain.js",Va:["scripts/c3runtime.js"],oc:[],od:"",hh:"scripts/",qd:[],ue:"html5"}));"use strict";
async function aa(f,a){a=a.type;let b=!0;0===a?b=await ba():1===a&&(b=await ca());v(f,"permission-result",{type:a,result:b})}async function ba(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}
async function ca(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}self.oa.Wa(class extends self.Da{constructor(f){super(f,"touch");J(this,"request-permission",a=>aa(this,a))}});"use strict";
function da(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>v(f,"sw-message",a.data))}
function fa(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(f):screen.webkitLockOrientation?a=screen.webkitLockOrientation(f):screen.mozLockOrientation?a=screen.mozLockOrientation(f):screen.msLockOrientation&&(a=screen.msLockOrientation(f));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.oa.Wa(class extends self.Da{constructor(f){super(f,"browser");this.s="";K(this,[["get-initial-state",a=>this.Nc(a)],["ready-for-sw-messages",()=>da(this)],["alert",a=>this.Jc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Qc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>fa(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===
b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.qh||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.s||"macos-wkwebview"===this.s)self.oa.Pb(!0),
this.u.Uc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",
()=>{"windows-webview2"===this.s||"macos-wkwebview"===this.s?(self.oa.Pb(!1),this.u.Uc({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{v(this,"online-state",{isOnline:!0})});window.addEventListener("offline",
()=>{v(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{v(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{v(this,"backbutton")})}Nc(f){this.s=f.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}Jc(f){alert(f.message)}Qc(f){f=f.isFocus;if("nwjs"===this.s){const a="nwjs"===this.s?nw.Window.get():null;f?a.focus():a.blur()}else f?window.focus():window.blur()}});"use strict";
async function ha(f){if(!f.Ba)try{f.Ba=await navigator.wakeLock.request("screen"),f.Ba.addEventListener("release",()=>{console.log("[Construct 3] Screen wake lock released");f.Ba=null;v(f,"wake-lock-released")}),console.log("[Construct 3] Screen wake lock acquired"),v(f,"wake-lock-acquired")}catch(a){console.warn("[Construct 3] Failed to acquire screen wake lock: ",a),v(f,"wake-lock-error")}}
function T(){var f=document.body;const a=f.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");f=getComputedStyle(f);f=[f.getPropertyValue("--temp-sai-top"),f.getPropertyValue("--temp-sai-right"),f.getPropertyValue("--temp-sai-bottom"),f.getPropertyValue("--temp-sai-left")].map(b=>{b=parseInt(b,10);
return isFinite(b)?b:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return f}
self.oa.Wa(class extends self.Da{constructor(f){super(f,"platform-info");K(this,[["get-initial-state",()=>this.Nc()],["request-wake-lock",()=>ha(this)],["release-wake-lock",()=>{this.Ba&&(this.Ba.release(),this.Ba=null)}]]);window.addEventListener("resize",()=>{v(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:T()})});this.Ba=null}Nc(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:T(),supportsWakeLock:!!navigator.wakeLock}}});"use strict";
{const f=180/Math.PI;self.ea=class extends self.Da{constructor(a){super(a,"audio");this.Ka=this.a=null;this.Ub=this.dd=!1;this.ua=()=>this.Og();this.aa=[];this.J=[];this.ia=null;this.he="";this.ie=-1;this.vb=new Map;this.$b=1;this.ra=!1;this.nd=0;this.mc=1;this.bd=0;this.le="HRTF";this.Yd="inverse";this.me=600;this.ke=1E4;this.oe=1;this.ce=this.dc=!1;this.re=this.u.Ue();this.ba=new Map;this.Ja=new Set;this.de=this.gd=!1;this.jd="";this.Aa=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Xf(b,d);this.Sb=
null;self.C3Audio_GetOutputStream=()=>this.Rf();self.C3Audio_DOMInterface=this;K(this,[["create-audio-context",b=>this.sf(b)],["play",b=>this.ng(b)],["stop",b=>this.Lg(b)],["stop-all",()=>this.Mg()],["set-paused",b=>this.Eg(b)],["set-volume",b=>this.Jg(b)],["fade-volume",b=>this.yf(b)],["set-master-volume",b=>this.Cg(b)],["set-muted",b=>this.Dg(b)],["set-silent",b=>this.Gg(b)],["set-looping",b=>this.Bg(b)],["set-playback-rate",b=>this.Fg(b)],["seek",b=>this.ug(b)],["preload",b=>this.og(b)],["unload",
b=>this.Pg(b)],["unload-all",()=>this.Qg()],["set-suspended",b=>this.Hg(b)],["add-effect",b=>this.Fd(b)],["set-effect-param",b=>this.xg(b)],["remove-effects",b=>this.qg(b)],["tick",b=>this.ig(b)],["load-state",b=>this.Vf(b)],["offline-render-audio",b=>this.Zf(b)],["offline-render-finish",()=>this.ag()]])}async sf(a){a.isiOSCordova&&(this.dc=!0);this.nd=a.timeScaleMode;this.le=["equalpower","HRTF","soundfield"][a.panningModel];this.Yd=["linear","inverse","exponential"][a.distanceModel];this.me=a.refDistance;
this.ke=a.maxDistance;this.oe=a.rolloffFactor;if(this.u.fd)this.dc=!0,this.a=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*this.u.$d)});else{var b={latencyHint:a.latencyHint};this.re||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.a=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.a=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.Gd();this.a.onstatechange=()=>{"running"!==this.a.state&&this.Gd();
v(this,"audiocontext-state",{audioContextState:this.a.state})}}this.Ka=this.a.createGain();this.Ka.connect(this.a.destination);b=a.listenerPos;this.a.listener.setPosition(b[0],b[1],b[2]);this.a.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.rc();try{await Promise.all(a.preloadList.map(d=>this.Kb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.a.sampleRate,audioContextState:this.a.state}}Gd(){this.Ub||
(this.dd=!1,window.addEventListener("pointerup",this.ua,!0),window.addEventListener("touchend",this.ua,!0),window.addEventListener("click",this.ua,!0),window.addEventListener("keydown",this.ua,!0),this.Ub=!0)}uf(){this.Ub&&(this.dd=!0,window.removeEventListener("pointerup",this.ua,!0),window.removeEventListener("touchend",this.ua,!0),window.removeEventListener("click",this.ua,!0),window.removeEventListener("keydown",this.ua,!0),this.Ub=!1)}Og(){if(!this.dd){var a=this.a;"suspended"===a.state&&a.resume&&
a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.uf()}}V(){return this.a}rc(){return this.a.currentTime}va(){return this.Ka}wd(a){return(a=this.ba.get(a.toLowerCase()))?a[0].O():this.va()}ve(a,b){a=a.toLowerCase();let d=this.ba.get(a);d||(d=[],this.ba.set(a,d));b.Ag(d.length);b.Ig(a);d.push(b);this.Rd(a)}Rd(a){let b=this.va();const d=this.ba.get(a);if(d&&d.length){b=d[0].O();for(let h=0,n=d.length;h<n;++h){const q=
d[h];h+1===n?q.R(this.va()):q.R(d[h+1].O())}}for(const h of this.na(a))h.af(b);this.Aa&&this.jd===a&&(this.Aa.disconnect(),this.Aa.connect(b))}Eb(){return this.ra}zg(){this.ce=!0}Ne(a,b){return b?this.u.Rg(a).then(d=>{const h=this.a.createBuffer(1,d.length,48E3);h.getChannelData(0).set(d);return h}):new Promise((d,h)=>{this.a.decodeAudioData(a,d,h)})}xa(a){this.u.xa(a)}Fa(a){this.u.Fa(a)}Bd(a){let b=0;for(let d=0,h=this.J.length;d<h;++d){const n=this.J[d];this.J[b]=n;n.K===a?n.f():++b}this.J.length=
b}bf(){let a=0;for(let b=0,d=this.aa.length;b<d;++b){const h=this.aa[b];this.aa[a]=h;h.wa()?h.f():++a}this.aa.length=a}*na(a){if(a)for(const b of this.J)self.ea.Oe(b.Z,a)&&(yield b);else this.ia&&!this.ia.S()&&(yield this.ia)}async Kb(a,b,d,h,n){for(const q of this.aa)if(q.Ya()===b)return await U(q),q;if(n)return null;h&&(this.dc||this.ce)&&this.bf();n="audio/webm; codecs=opus"===d&&!this.re;h&&n&&this.zg();a=!h||this.dc||n?new self.Je(this,a,b,d,h,n):new self.He(this,a,b,d,h);this.aa.push(a);await U(a);
return a}async Ec(a,b,d,h,n){for(const q of this.J)if(q.Ya()===b&&(q.pc()||n))return q.ef(h),q;a=await this.Kb(a,b,d,n);h="html5"===a.Wc?new self.Ie(a.j,a,h):new self.Ke(a.j,a,h);this.J.push(h);return h}jf(a){let b=this.vb.get(a);if(!b){let d=null;b={pd:0,fh:new Promise(h=>d=h),resolve:d};this.vb.set(a,b)}b.pd++}rg(a){const b=this.vb.get(a);if(!b)throw Error("expected pending tag");b.pd--;0===b.pd&&(b.resolve(),this.vb.delete(a))}Bc(a){a||(a=this.he);return(a=this.vb.get(a))?a.fh:Promise.resolve()}Lb(){if(0<
this.Ja.size)M(this);else for(const a of this.J)if(a.xd()){M(this);break}}Ga(){for(var a of this.Ja)a.Ga();a=this.rc();for(var b of this.J)b.Ga(a);b=this.J.filter(d=>d.xd()).map(d=>d.Xa());v(this,"state",{tickCount:this.ie,audioInstances:b,analysers:[...this.Ja].map(d=>d.Qe())});0===b.length&&0===this.Ja.size&&this.Vb&&(this.u.sg(this.se),this.Vb=!1)}xc(a,b,d){v(this,"trigger",{type:a,tag:b,aiid:d})}async ng(a){const b=a.originalUrl,d=a.url,h=a.type,n=a.isMusic,q=a.tag,w=a.isLooping,B=a.vol,E=a.pos,
y=a.panning;let z=a.off;0<z&&!a.trueClock&&(this.a.getOutputTimestamp?(a=this.a.getOutputTimestamp(),z=z-a.performanceTime/1E3+a.contextTime):z=z-performance.now()/1E3+this.a.currentTime);this.he=q;this.jf(q);try{this.ia=await this.Ec(b,d,h,q,n),y?(this.ia.Hb(!0),this.ia.df(y.x,y.y,y.angle,y.innerAngle,y.outerAngle,y.outerGain),y.hasOwnProperty("uid")&&this.ia.ff(y.uid)):this.ia.Hb(!1),this.ia.Play(w,B,E,z)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.rg(q)}M(this)}Lg(a){a=
a.tag;for(const b of this.na(a))b.pa()}Mg(){for(const a of this.J)a.pa()}Eg(a){const b=a.tag;a=a.paused;for(const d of this.na(b))a?d.$a():d.Gb();this.Lb()}Jg(a){const b=a.tag;a=a.vol;for(const d of this.na(b))d.Jb(a)}async yf(a){const b=a.tag,d=a.vol,h=a.duration;a=a.stopOnEnd;await this.Bc(b);for(const n of this.na(b))n.Pe(d,h,a);this.Lb()}Cg(a){this.$b=a.vol;this.Ka.gain.value=this.$b}Dg(a){const b=a.tag;a=a.isMuted;for(const d of this.na(b))d.Cd(a)}Gg(a){this.ra=a.isSilent;this.u.Ib(this.ra);
for(const b of this.J)b.Qb()}Bg(a){const b=a.tag;a=a.isLooping;for(const d of this.na(b))d.zc(a)}async Fg(a){const b=a.tag;a=a.rate;await this.Bc(b);for(const d of this.na(b))d.Ed(a)}async ug(a){const b=a.tag;a=a.pos;await this.Bc(b);for(const d of this.na(b))d.yc(a)}async og(a){const b=a.originalUrl,d=a.url,h=a.type;a=a.isMusic;try{await this.Ec(b,d,h,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async Pg(a){if(a=await this.Kb("",a.url,a.type,a.isMusic,!0))a.f(),a=this.aa.indexOf(a),
-1!==a&&this.aa.splice(a,1)}Qg(){for(const a of this.aa)a.f();this.aa.length=0}Hg(a){a=a.isSuspended;!a&&this.a.resume&&this.a.resume();for(const b of this.J)b.Ac(a);a&&this.a.suspend&&this.a.suspend()}ig(a){this.mc=a.timeScale;this.bd=a.gameTime;this.ie=a.tickCount;if(0!==this.nd)for(var b of this.J)b.Ia();(b=a.listenerPos)&&this.a.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const h of this.J)h.ha===a&&h.Dd(d.x,d.y,d.angle)}}async Fd(a){var b=a.type;const d=a.tag;
var h=a.params;if("filter"===b)h=new self.Be(this,...h);else if("delay"===b)h=new self.ze(this,...h);else if("convolution"===b){b=null;try{b=await this.Kb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",n);return}h=new self.ye(this,b.$,...h);h.vg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)h=new self.Ce(this,...h);else if("phaser"===b)h=new self.Ee(this,...h);else if("gain"===b)h=new self.De(this,...h);else if("tremolo"===
b)h=new self.Ge(this,...h);else if("ringmod"===b)h=new self.Fe(this,...h);else if("distortion"===b)h=new self.Ae(this,...h);else if("compressor"===b)h=new self.xe(this,...h);else if("analyser"===b)h=new self.we(this,...h);else throw Error("invalid effect type");this.ve(d,h);this.Qd()}xg(a){const b=a.index,d=a.param,h=a.value,n=a.ramp,q=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,h,n,q),this.Qd())}qg(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const d of b)d.f();
this.ba.delete(a);this.Rd(a)}}hf(a){this.Ja.add(a);this.Lb()}pg(a){this.Ja.delete(a)}Qd(){this.gd||(this.gd=!0,Promise.resolve().then(()=>this.vf()))}vf(){const a={};for(const [b,d]of this.ba)a[b]=d.map(h=>h.Xa());v(this,"fxstate",{fxstate:a});this.gd=!1}async Vf(a){const b=a.saveLoadMode;if(3!==b)for(var d of this.J)d.wa()&&1===b||(d.wa()||2!==b)&&d.pa();for(const h of this.ba.values())for(const n of h)n.f();this.ba.clear();this.mc=a.timeScale;this.bd=a.gameTime;d=a.listenerPos;this.a.listener.setPosition(d[0],
d[1],d[2]);this.ra=a.isSilent;this.u.Ib(this.ra);this.$b=a.masterVolume;this.Ka.gain.value=this.$b;d=[];for(const h of Object.values(a.effects))d.push(Promise.all(h.map(n=>this.Fd(n))));await Promise.all(d);await Promise.all(a.playing.map(h=>this.Ff(h,b)));this.Lb()}async Ff(a,b){if(3!==b){var d=a.bufferOriginalUrl,h=a.bufferUrl,n=a.bufferType,q=a.isMusic,w=a.tag,B=a.isLooping,E=a.volume,y=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.Ec(d,h,n,w,q)}catch(z){console.error("[Construct 3] Audio: error loading audio state: ",
z);return}b.Ze(a.pan);b.Play(B,E,y,0);a.isPlaying||b.$a();b.Ic(a)}}}Xf(a,b){this.Aa&&this.Aa.disconnect();this.jd=b.toLowerCase();this.Aa=this.a.createMediaStreamSource(a);this.Aa.connect(this.wd(this.jd))}Rf(){this.Sb||(this.Sb=this.a.createMediaStreamDestination(),this.Ka.connect(this.Sb));return this.Sb.stream}async Zf(a){try{const b=this.a.suspend(a.time);this.de?this.a.resume():(this.a.startRendering().then(d=>this.$f(d)).catch(d=>this.Nd(d)),this.de=!0);await b}catch(b){this.Nd(b)}}ag(){this.a.resume()}$f(a){const b=
[];for(let d=0,h=a.numberOfChannels;d<h;++d){const n=a.getChannelData(d);b.push(n.buffer)}this.u.Fb("runtime","offline-audio-render-completed",{duration:a.duration,length:a.length,numberOfChannels:a.numberOfChannels,sampleRate:a.sampleRate,channelData:b},null,b)}Nd(a){console.error("[Audio] Offline rendering error: ",a)}static Oe(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static gf(a){return a*f}static Me(a){return Math.pow(10,a/20)}static vd(a){return Math.max(Math.min(self.ea.Me(a),
1),0)}static Ye(a){return Math.log(a)/Math.log(10)*20}static Xe(a){return self.ea.Ye(Math.max(Math.min(a,1),0))}static $g(a,b){return 1-Math.exp(-b*a)}};self.oa.Wa(self.ea)}"use strict";function U(f){f.Yb||(f.Yb=f.Hc());return f.Yb}self.sd=class{constructor(f,a,b,d,h){this.j=f;this.Xg=a;this.Ca=b;this.P=d;this.Ug=h;this.Wc="";this.Yb=null}f(){this.Yb=this.j=null}Hc(){}V(){return this.j.V()}tc(){return this.Xg}Ya(){return this.Ca}sc(){return this.P}wa(){return this.Ug}fa(){}};"use strict";
self.He=class extends self.sd{constructor(f,a,b,d,h){super(f,a,b,d,h);this.Wc="html5";this.I=new Audio;this.I.crossOrigin="anonymous";this.I.autoplay=!1;this.I.preload="auto";this.pb=this.qb=null;this.I.addEventListener("canplaythrough",()=>!0);this.ub=this.V().createGain();this.sb=null;this.I.addEventListener("canplay",()=>{this.qb&&(this.qb(),this.pb=this.qb=null);!this.sb&&this.I&&(this.sb=this.V().createMediaElementSource(this.I),this.sb.connect(this.ub))});this.onended=null;this.I.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.I.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.Ca}' error: `,n);this.pb&&(this.pb(n),this.pb=this.qb=null)})}f(){this.j.Bd(this);this.ub.disconnect();this.ub=null;this.sb.disconnect();this.sb=null;this.I&&!this.I.paused&&this.I.pause();this.I=this.onended=null;super.f()}Hc(){return new Promise((f,a)=>{this.qb=f;this.pb=a;this.I.src=this.Ca})}N(){return this.I}fa(){return this.I.duration}};"use strict";
async function ia(f){if(f.ya)return f.ya;var a=f.j.u;if("cordova"===a.s&&a.zd(f.Ca)&&a.mb)f.ya=await a.Cb(f.Ca);else{a=await fetch(f.Ca);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.ya=await a.arrayBuffer()}}async function ja(f){if(f.$)return f.$;f.$=await f.j.Ne(f.ya,f.Wg);f.ya=null}
self.Je=class extends self.sd{constructor(f,a,b,d,h,n){super(f,a,b,d,h);this.Wc="webaudio";this.$=this.ya=null;this.Wg=!!n}f(){this.j.Bd(this);this.$=this.ya=null;super.f()}async Hc(){try{await ia(this),await ja(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.Ca}': `,f)}}fa(){return this.$?this.$.duration:0}};"use strict";
{let f=0;self.td=class{constructor(a,b,d){this.j=a;this.K=b;this.Z=d;this.Rb=f++;this.L=this.V().createGain();this.L.connect(this.va());this.B=null;this.nb=!1;this.la=[0,0,0];this.ka=[0,0,0];this.G=!0;this.U=this.ma=this.F=!1;this.zb=1;this.La=!1;this.ta=1;a=this.j.nd;this.hd=1===a&&!this.wa()||2===a;this.jb=this.ha=-1;this.qe=!1}f(){this.K=this.j=null;this.B&&(this.B.disconnect(),this.B=null);this.L.disconnect();this.L=null}V(){return this.j.V()}va(){return this.j.wd(this.Z)}Db(){return this.hd?
this.j.bd:performance.now()/1E3}tc(){return this.K.tc()}Ya(){return this.K.Ya()}sc(){return this.K.sc()}wa(){return this.K.wa()}ef(a){this.Z=a}S(){}pc(){}IsPlaying(){return!this.G&&!this.F&&!this.S()}xd(){return!this.G&&!this.S()}Ea(){}fa(){return this.K.fa()}Play(){}pa(){}$a(){}Gb(){}Jb(a){this.zb=a;this.L.gain.cancelScheduledValues(0);this.jb=-1;this.L.gain.value=this.uc()}Pe(a,b,d){if(!this.La){var h=this.L.gain;h.cancelScheduledValues(0);var n=this.j.rc();b=n+b;h.setValueAtTime(h.value,n);h.linearRampToValueAtTime(a,
b);this.zb=a;this.jb=b;this.qe=d}}Vc(){this.Jb(this.zb)}Ga(a){-1!==this.jb&&a>=this.jb&&(this.jb=-1,this.qe&&this.pa(),this.j.xc("fade-ended",this.Z,this.Rb))}uc(){const a=this.zb;return isFinite(a)?a:0}Cd(a){a=!!a;this.La!==a&&(this.La=a,this.Qb())}Eb(){return this.j.Eb()}Qb(){}zc(){}Ed(a){this.ta!==a&&(this.ta=a,this.Ia())}Ia(){}yc(){}Ac(){}Hb(a){a=!!a;this.nb!==a&&((this.nb=a)?(this.B||(this.B=this.V().createPanner(),this.B.panningModel=this.j.le,this.B.distanceModel=this.j.Yd,this.B.refDistance=
this.j.me,this.B.maxDistance=this.j.ke,this.B.rolloffFactor=this.j.oe),this.L.disconnect(),this.L.connect(this.B),this.B.connect(this.va())):(this.B.disconnect(),this.L.disconnect(),this.L.connect(this.va())))}df(a,b,d,h,n,q){this.nb&&(this.Dd(a,b,d),a=self.ea.gf,this.B.coneInnerAngle=a(h),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=q)}Dd(a,b,d){this.nb&&(this.la[0]=a,this.la[1]=b,this.la[2]=0,this.ka[0]=Math.cos(d),this.ka[1]=Math.sin(d),this.ka[2]=0,this.B.setPosition(...this.la),this.B.setOrientation(...this.ka))}ff(a){this.ha=
a}vc(){}af(a){const b=this.B||this.L;b.disconnect();b.connect(a)}Xa(){return{aiid:this.Rb,tag:this.Z,duration:this.fa(),volume:this.zb,isPlaying:this.IsPlaying(),playbackTime:this.Ea(),playbackRate:this.ta,uid:this.ha,bufferOriginalUrl:this.tc(),bufferUrl:"",bufferType:this.sc(),isMusic:this.wa(),isLooping:this.U,isMuted:this.La,resumePosition:this.vc(),pan:this.Re()}}Ic(a){this.Ed(a.playbackRate);this.Cd(a.isMuted)}Re(){if(!this.B)return null;const a=this.B;return{pos:this.la,orient:this.ka,cia:a.coneInnerAngle,
coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ha}}Ze(a){if(a){this.Hb(!0);a=this.B;var b=a.pos;this.la[0]=b[0];this.la[1]=b[1];this.la[2]=b[2];b=a.orient;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];a.setPosition(...this.la);a.setOrientation(...this.ka);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ha=a.uid}else this.Hb(!1)}}}"use strict";
self.Ie=class extends self.td{constructor(f,a,b){super(f,a,b);this.K.ub.connect(this.L);this.K.onended=()=>this.Lc()}f(){this.pa();this.K.ub.disconnect();super.f()}N(){return this.K.N()}Lc(){this.G=!0;this.ha=-1;this.j.xc("ended",this.Z,this.Rb)}S(){return this.N().ended}pc(){return this.G?!0:this.S()}Ea(){let f=this.N().currentTime;this.U||(f=Math.min(f,this.fa()));return f}Play(f,a,b){const d=this.N();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==f&&(d.loop=f);this.Jb(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(h){console.warn(`[Construct 3] Exception seeking audio '${this.K.Ya()}' to position '${b}': `,h)}this.j.xa(d);this.F=this.G=!1;this.U=f;this.ta=1}pa(){const f=this.N();f.paused||f.pause();this.j.Fa(f);this.G=!0;this.F=!1;this.ha=-1}$a(){if(!(this.F||this.G||this.S())){var f=this.N();f.paused||f.pause();this.j.Fa(f);this.F=!0}}Gb(){!this.F||this.G||this.S()||(this.j.xa(this.N()),this.F=!1)}Qb(){this.N().muted=this.La||this.Eb()}zc(f){f=!!f;this.U!==f&&
(this.U=f,this.N().loop=f)}Ia(){let f=this.ta;this.hd&&(f*=this.j.mc);try{this.N().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}yc(f){if(!this.G&&!this.S())try{this.N().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}vc(){return this.Ea()}Ac(f){f?this.IsPlaying()?(this.N().pause(),this.ma=!0):this.ma=!1:this.ma&&(this.j.xa(this.N()),this.ma=!1)}};"use strict";
function Z(f){f.i&&f.i.disconnect();f.i=null;f.eb=null}
self.Ke=class extends self.td{constructor(f,a,b){super(f,a,b);this.i=null;this.bc=d=>this.Lc(d);this.cd=!0;this.eb=null;this.M=this.cc=this.ec=0;this.kd=1}f(){this.pa();Z(this);this.bc=null;super.f()}Lc(f){this.F||this.ma||f.target!==this.eb||(this.G=this.cd=!0,this.ha=-1,Z(this),this.j.xc("ended",this.Z,this.Rb))}S(){return!this.G&&this.i&&this.i.loop||this.F?!1:this.cd}pc(){return!this.i||this.G?!0:this.S()}Ea(){let f;f=this.F?this.M:this.cc+(this.Db()-this.ec)*this.ta;this.U||(f=Math.min(f,this.fa()));
return f}Play(f,a,b,d){this.kd=1;this.Jb(a);Z(this);this.i=this.V().createBufferSource();this.i.buffer=this.K.$;this.i.connect(this.L);this.eb=this.i;this.i.onended=this.bc;this.i.loop=f;this.i.start(d,b);this.F=this.G=this.cd=!1;this.U=f;this.ta=1;this.ec=this.Db();this.cc=b}pa(){if(this.i)try{this.i.stop(0)}catch(f){}this.G=!0;this.F=!1;this.ha=-1}$a(){this.F||this.G||this.S()||(this.M=this.Ea(),this.U&&(this.M%=this.fa()),this.F=!0,this.i.stop(0))}Gb(){!this.F||this.G||this.S()||(Z(this),this.i=
this.V().createBufferSource(),this.i.buffer=this.K.$,this.i.connect(this.L),this.eb=this.i,this.i.onended=this.bc,this.i.loop=this.U,this.Vc(),this.Ia(),this.i.start(0,this.M),this.ec=this.Db(),this.cc=this.M,this.F=!1)}uc(){return super.uc()*this.kd}Qb(){this.kd=this.La||this.Eb()?0:1;this.Vc()}zc(f){f=!!f;this.U!==f&&(this.U=f,this.i&&(this.i.loop=f))}Ia(){let f=this.ta;this.hd&&(f*=this.j.mc);this.i&&(this.i.playbackRate.value=f)}yc(f){this.G||this.S()||(this.F?this.M=f:(this.$a(),this.M=f,this.Gb()))}vc(){return this.M}Ac(f){f?
this.IsPlaying()?(this.ma=!0,this.M=this.Ea(),this.U&&(this.M%=this.fa()),this.i.stop(0)):this.ma=!1:this.ma&&(Z(this),this.i=this.V().createBufferSource(),this.i.buffer=this.K.$,this.i.connect(this.L),this.eb=this.i,this.i.onended=this.bc,this.i.loop=this.U,this.Vc(),this.Ia(),this.i.start(0,this.M),this.ec=this.Db(),this.cc=this.M,this.ma=!1)}Ic(f){super.Ic(f);this.M=f.resumePosition}};"use strict";
{class f{constructor(a){this.j=a;this.a=a.V();this.ee=-1;this.P=this.Z="";this.g=null}f(){this.a=null}Ag(a){this.ee=a}Ig(a){this.Z=a}o(){return this.a.createGain()}O(){}R(){}m(a,b,d,h){a.cancelScheduledValues(0);if(0===h)a.value=b;else{var n=this.a.currentTime;h+=n;switch(d){case 0:a.setValueAtTime(b,h);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,h);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,h)}}}Xa(){return{type:this.P,tag:this.Z,params:this.g}}}
self.Be=class extends f{constructor(a,b,d,h,n,q,w){super(a);this.P="filter";this.g=[b,d,h,n,q,w];this.l=this.o();this.c=this.o();this.c.gain.value=w;this.b=this.o();this.b.gain.value=1-w;this.A=this.a.createBiquadFilter();this.A.type=b;this.A.frequency.value=d;this.A.detune.value=h;this.A.Q.value=n;this.A.gain.vlaue=q;this.l.connect(this.A);this.l.connect(this.b);this.A.connect(this.c)}f(){this.l.disconnect();this.A.disconnect();this.c.disconnect();this.b.disconnect();super.f()}R(a){this.c.disconnect();
this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.c.gain,b,d,h);this.m(this.b.gain,1-b,d,h);break;case 1:this.g[1]=b;this.m(this.A.frequency,b,d,h);break;case 2:this.g[2]=b;this.m(this.A.detune,b,d,h);break;case 3:this.g[3]=b;this.m(this.A.Q,b,d,h);break;case 4:this.g[4]=b,this.m(this.A.gain,b,d,h)}}};self.ze=class extends f{constructor(a,b,d,h){super(a);this.P="delay";this.g=[b,d,h];this.l=
this.o();this.c=this.o();this.c.gain.value=h;this.b=this.o();this.b.gain.value=1-h;this.rb=this.o();this.T=this.a.createDelay(b);this.T.delayTime.value=b;this.ib=this.o();this.ib.gain.value=d;this.l.connect(this.rb);this.l.connect(this.b);this.rb.connect(this.c);this.rb.connect(this.T);this.T.connect(this.ib);this.ib.connect(this.rb)}f(){this.l.disconnect();this.c.disconnect();this.b.disconnect();this.rb.disconnect();this.T.disconnect();this.ib.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);
this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,b,d,h){const n=self.ea.vd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.c.gain,b,d,h);this.m(this.b.gain,1-b,d,h);break;case 4:this.g[1]=n(b);this.m(this.ib.gain,n(b),d,h);break;case 5:this.g[0]=b,this.m(this.T.delayTime,b,d,h)}}};self.ye=class extends f{constructor(a,b,d,h){super(a);this.P="convolution";this.g=[d,h];this.Wd=this.Vd="";this.l=this.o();this.c=this.o();this.c.gain.value=h;this.b=this.o();this.b.gain.value=
1-h;this.hb=this.a.createConvolver();this.hb.normalize=d;this.hb.buffer=b;this.l.connect(this.hb);this.l.connect(this.b);this.hb.connect(this.c)}f(){this.l.disconnect();this.hb.disconnect();this.c.disconnect();this.b.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.c.gain,b,d,h),this.m(this.b.gain,1-b,d,h)}}vg(a,b){this.Vd=a;this.Wd=b}Xa(){const a=
super.Xa();a.bufferOriginalUrl=this.Vd;a.bufferUrl="";a.bufferType=this.Wd;return a}};self.Ce=class extends f{constructor(a,b,d,h,n,q){super(a);this.P="flanger";this.g=[b,d,h,n,q];this.l=this.o();this.b=this.o();this.b.gain.value=1-q/2;this.c=this.o();this.c.gain.value=q/2;this.kb=this.o();this.kb.gain.value=n;this.T=this.a.createDelay(b+d);this.T.delayTime.value=b;this.v=this.a.createOscillator();this.v.frequency.value=h;this.H=this.o();this.H.gain.value=d;this.l.connect(this.T);this.l.connect(this.b);
this.T.connect(this.c);this.T.connect(this.kb);this.kb.connect(this.T);this.v.connect(this.H);this.H.connect(this.T.delayTime);this.v.start(0)}f(){this.v.stop(0);this.l.disconnect();this.T.disconnect();this.v.disconnect();this.H.disconnect();this.b.disconnect();this.c.disconnect();this.kb.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.c.gain,
b/2,d,h);this.m(this.b.gain,1-b/2,d,h);break;case 6:this.g[1]=b/1E3;this.m(this.H.gain,b/1E3,d,h);break;case 7:this.g[2]=b;this.m(this.v.frequency,b,d,h);break;case 8:this.g[3]=b/100,this.m(this.kb.gain,b/100,d,h)}}};self.Ee=class extends f{constructor(a,b,d,h,n,q,w){super(a);this.P="phaser";this.g=[b,d,h,n,q,w];this.l=this.o();this.b=this.o();this.b.gain.value=1-w/2;this.c=this.o();this.c.gain.value=w/2;this.A=this.a.createBiquadFilter();this.A.type="allpass";this.A.frequency.value=b;this.A.detune.value=
d;this.A.Q.value=h;this.v=this.a.createOscillator();this.v.frequency.value=q;this.H=this.o();this.H.gain.value=n;this.l.connect(this.A);this.l.connect(this.b);this.A.connect(this.c);this.v.connect(this.H);this.H.connect(this.A.frequency);this.v.start(0)}f(){this.v.stop(0);this.l.disconnect();this.A.disconnect();this.v.disconnect();this.H.disconnect();this.b.disconnect();this.c.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,
b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.c.gain,b/2,d,h);this.m(this.b.gain,1-b/2,d,h);break;case 1:this.g[0]=b;this.m(this.A.frequency,b,d,h);break;case 2:this.g[1]=b;this.m(this.A.detune,b,d,h);break;case 3:this.g[2]=b;this.m(this.A.Q,b,d,h);break;case 6:this.g[3]=b;this.m(this.H.gain,b,d,h);break;case 7:this.g[4]=b,this.m(this.v.frequency,b,d,h)}}};self.De=class extends f{constructor(a,b){super(a);this.P="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}f(){this.h.disconnect();super.f()}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(a,b,d,h){const n=self.ea.vd;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,h)}}};self.Ge=class extends f{constructor(a,b,d){super(a);this.P="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.v=this.a.createOscillator();this.v.frequency.value=b;this.H=this.o();this.H.gain.value=d/2;this.v.connect(this.H);this.H.connect(this.h.gain);this.v.start(0)}f(){this.v.stop(0);this.v.disconnect();
this.H.disconnect();this.h.disconnect();super.f()}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,h);this.m(this.H.gain,b/2,d,h);break;case 7:this.g[0]=b,this.m(this.v.frequency,b,d,h)}}};self.Fe=class extends f{constructor(a,b,d){super(a);this.P="ringmod";this.g=[b,d];this.l=this.o();this.c=this.o();this.c.gain.value=d;this.b=this.o();this.b.gain.value=1-d;this.xb=this.o();this.xb.gain.value=
0;this.v=this.a.createOscillator();this.v.frequency.value=b;this.v.connect(this.xb.gain);this.v.start(0);this.l.connect(this.xb);this.l.connect(this.b);this.xb.connect(this.c)}f(){this.v.stop(0);this.v.disconnect();this.xb.disconnect();this.l.disconnect();this.c.disconnect();this.b.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.c.gain,b,d,h);
this.m(this.b.gain,1-b,d,h);break;case 7:this.g[0]=b,this.m(this.v.frequency,b,d,h)}}};self.Ae=class extends f{constructor(a,b,d,h,n,q){super(a);this.P="distortion";this.g=[b,d,h,n,q];this.l=this.o();this.jc=this.o();this.ic=this.o();this.wg(h,n);this.c=this.o();this.c.gain.value=q;this.b=this.o();this.b.gain.value=1-q;this.nc=this.a.createWaveShaper();this.Zc=new Float32Array(65536);this.Af(b,d);this.nc.curve=this.Zc;this.l.connect(this.jc);this.l.connect(this.b);this.jc.connect(this.nc);this.nc.connect(this.ic);
this.ic.connect(this.c)}f(){this.l.disconnect();this.jc.disconnect();this.nc.disconnect();this.ic.disconnect();this.c.disconnect();this.b.disconnect();super.f()}wg(a,b){.01>a&&(a=.01);this.jc.gain.value=a;this.ic.gain.value=Math.pow(1/a,.6)*b}Af(a,b){for(let d=0;32768>d;++d){let h=d/32768;h=this.Kg(h,a,b);this.Zc[32768+d]=h;this.Zc[32768-d-1]=-h}}Kg(a,b,d){d=1.05*d*b-b;const h=0>a?-a:a;return(h<b?h:b+d*self.ea.$g(h-b,1/d))*(0>a?-1:1)}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();
this.b.connect(a)}O(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.c.gain,b,d,h),this.m(this.b.gain,1-b,d,h)}}};self.xe=class extends f{constructor(a,b,d,h,n,q){super(a);this.P="compressor";this.g=[b,d,h,n,q];this.h=this.a.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=h;this.h.attack.value=n;this.h.release.value=q}f(){this.h.disconnect();super.f()}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(){}};
self.we=class extends f{constructor(a,b,d){super(a);this.P="analyser";this.g=[b,d];this.h=this.a.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.be=new Float32Array(this.h.frequencyBinCount);this.pe=new Uint8Array(b);this.ne=this.Pa=0;this.j.hf(this)}f(){this.j.pg(this);this.h.disconnect();super.f()}Ga(){this.h.getFloatFrequencyData(this.be);this.h.getByteTimeDomainData(this.pe);const a=this.h.fftSize;let b=this.Pa=0;for(var d=0;d<a;++d){let h=(this.pe[d]-128)/128;0>h&&(h=-h);
this.Pa<h&&(this.Pa=h);b+=h*h}d=self.ea.Xe;this.Pa=d(this.Pa);this.ne=d(Math.sqrt(b/a))}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(){}Qe(){return{tag:this.Z,index:this.ee,peak:this.Pa,rms:this.ne,binCount:this.h.frequencyBinCount,freqBins:this.be}}}};
