'use strict';function u(h,g,d,p){h.h.Z(h.B,g,d,p,void 0)}function x(h,g,d,p){h.h.s?u(h,g,d,p):h.h.mb()._OnMessageFromDOM({type:"event",component:h.B,handler:g,dispatchOpts:p||null,data:d,responseId:null})}function A(h,g,d){h.h.a(h.B,g,d)}function C(h,g){for(const [d,p]of g)A(h,d,p)}window.K=class{constructor(h,g){this.h=h;this.B=g}ta(){}};
window.ab=class{constructor(h,g){this.La=h;this.Sb=g;this.o=-1;this.U=-Infinity;this.Xb=()=>{this.o=-1;this.U=Date.now();this.C=!0;this.La();this.C=!1};this.Ma=this.C=!1}};"use strict";function D(h,g){const d=g.elementId,p=h.wa(d,g);h.f.set(d,p);g.isVisible||(p.style.display="none");p.addEventListener("focus",()=>{E(h,"elem-focused",d)});p.addEventListener("blur",()=>{E(h,"elem-blurred",d)});h.S&&document.body.appendChild(p)}
function F(h,g,d){A(h,g,p=>{const r=h.f.get(p.elementId);return d(r,p)})}function E(h,g,d,p){p||(p={});p.elementId=d;u(h,g,p)}function G(h,g,d){var p;p||(p={});p.elementId=d;x(h,g,p)}
window.Va=class extends self.K{constructor(h,g){super(h,g);this.f=new Map;this.S=!0;C(this,[["create",d=>D(this,d)],["destroy",d=>{{d=d.elementId;const p=this.f.get(d);this.S&&p.parentElement.removeChild(p);this.f.delete(d)}}],["set-visible",d=>{this.S&&(this.f.get(d.elementId).style.display=d.isVisible?"":"none")}],["update-position",d=>{if(this.S){var p=this.f.get(d.elementId);p.style.left=d.left+"px";p.style.top=d.top+"px";p.style.width=d.width+"px";p.style.height=d.height+"px";d=d.fontSize;null!==
d&&(p.style.fontSize=d+"em")}}],["update-state",d=>{{const p=this.f.get(d.elementId);this.$(p,d)}}],["focus",d=>{{const p=this.f.get(d.elementId);d.focus?p.focus():p.blur()}}],["set-css-style",d=>{this.f.get(d.elementId).style[d.prop]=d.val}],["set-attribute",d=>{this.f.get(d.elementId).setAttribute(d.name,d.val)}],["remove-attribute",d=>{this.f.get(d.elementId).removeAttribute(d.name)}]]);F(this,"get-element",d=>d)}wa(){throw Error("required override");}$(){throw Error("required override");}};"use strict";
{var H=function(n){return l.has(n)},I=function(n){return new Promise((b,e)=>{const f=new FileReader;f.onload=m=>b(m.target.result);f.onerror=m=>e(m);f.readAsArrayBuffer(n)})},J=async function(n){n=await I(n);return(new TextDecoder("utf-8")).decode(n)},L=function(n){if(n.$b){const b=document.createElement("script");b.async=!1;b.textContent=n.cc;document.head.appendChild(b)}else return new Promise((b,e)=>{const f=document.createElement("script");f.onload=b;f.onerror=e;f.async=!1;f.src=n;document.head.appendChild(f)})};
const h=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let g=new Audio;const d={"audio/webm; codecs=opus":!!g.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!g.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!g.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!g.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!g.canPlayType("audio/mp4"),"audio/mpeg":!!g.canPlayType("audio/mpeg")};g=null;const p=[];let r=0;window.RealFile=
window.File;const B=[],z=new Map,a=new Map;let c=0;const k=[];self.nc=function(n){if("function"!==typeof n)throw Error("runOnStartup called without a function");k.push(n)};const l=new Set(["cordova","playable-ad","instant-games"]);window.v=class n{constructor(b){this.s=b.ec;this.F=null;this.b="";this.qa=b.bc;this.I={};this.ma=this.Ra=null;this.T=[];this.D=this.c=this.pa=null;this.l=-1;this.Wb=()=>this.Fb();this.Pa=[];this.g=b.Sa;H(this.g)&&this.s&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this.s=!1);this.Qa=!1;this.V=this.i=null;"html5"!==this.g&&"playable-ad"!==this.g||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.a("runtime","cordova-fetch-local-file",e=>this.tb(e));this.a("runtime","create-job-worker",()=>this.ub());"cordova"===this.g?document.addEventListener("deviceready",()=>this.Ca(b)):this.Ca(b)}xa(){return h&&"cordova"===
this.g}L(){return h&&H(this.g)||navigator.standalone}async Ca(b){if("playable-ad"===this.g){this.i=self.c3_base64files;this.V={};await this.hb();for(let f=0,m=b.u.length;f<m;++f){var e=b.u[f].toLowerCase();this.V.hasOwnProperty(e)?b.u[f]={$b:!0,cc:this.V[e]}:this.i.hasOwnProperty(e)&&(b.u[f]=URL.createObjectURL(this.i[e]))}}b.Yb?this.b=b.Yb:(e=location.origin,this.b=("null"===e?"file:///":e)+location.pathname,e=this.b.lastIndexOf("/"),-1!==e&&(this.b=this.b.substr(0,e+1)));if(b.hc)for(const [f,m]of Object.entries(b.hc))this.I[f]=
URL.createObjectURL(m);e=new MessageChannel;this.F=e.port1;this.F.onmessage=f=>this._OnMessageFromRuntime(f.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(f=>this.Cb(f));this.D=new self.Za(this);await this.D.Ya();this.ya();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();await this.Pb();this.s?await this.ob(b,e.port2):await this.nb(b,e.port2)}ba(b){return this.I.hasOwnProperty(b)?
this.I[b]:b.endsWith("/workermain.js")&&this.I.hasOwnProperty("workermain.js")?this.I["workermain.js"]:"playable-ad"===this.g&&this.i.hasOwnProperty(b.toLowerCase())?URL.createObjectURL(this.i[b.toLowerCase()]):b}async X(b,e,f){if(b.startsWith("blob:"))return new Worker(b,f);if(this.xa()&&"file:"===location.protocol)return b=await this.va(this.qa+b),new Worker(URL.createObjectURL(new Blob([b],{type:"application/javascript"})),f);b=new URL(b,e);if(location.origin!==b.origin){b=await fetch(b);if(!b.ok)throw Error("failed to fetch worker script");
b=await b.blob();return new Worker(URL.createObjectURL(b),f)}return new Worker(b,f)}ya(){if(this.L()){const b=document.documentElement.style,e=document.body.style,f=window.innerWidth<window.innerHeight,m=f?window.screen.width:window.screen.height;e.height=b.height=(f?window.screen.height:window.screen.width)+"px";e.width=b.width=m+"px"}}Ba(b){return{baseUrl:this.b,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:n.Y(),projectData:b.mc,
previewImageBlobs:window.cr_previewImageBlobs||this.i,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:b.Sa,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.lc,jobScheduler:this.D.Wa(),supportedAudioFormats:d,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.qa+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.qa+"opus.wasm.wasm",isiOSCordova:this.xa(),isiOSWebView:this.L(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async ob(b,e){var f=
this.ba(b.fc);this.Ra=await this.X(f,this.b,{name:"Runtime"});this.c=document.createElement("canvas");this.c.style.display="none";f=this.c.transferControlToOffscreen();document.body.appendChild(this.c);window.c3canvas=this.c;this.Ra.postMessage(Object.assign(this.Ba(b),{type:"init-runtime",isInWorker:!0,messagePort:e,canvas:f,workerDependencyScripts:b.sa||[],engineScripts:b.u,projectScripts:window.kc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[e,f,...this.D.Xa()]);this.T=B.map(m=>new m(this));
this.Aa();self.c3_callFunction=(m,q)=>this.pa.pb(m,q);"preview"===this.g&&(self.goToLastErrorScript=()=>this.Z("runtime","go-to-last-error-script"))}async nb(b,e){this.c=document.createElement("canvas");this.c.style.display="none";document.body.appendChild(this.c);window.c3canvas=this.c;this.T=B.map(m=>new m(this));this.Aa();const f=b.u.map(m=>"string"===typeof m?(new URL(m,this.b)).toString():m);Array.isArray(b.sa)&&f.unshift(...b.sa);await Promise.all(f.map(m=>L(m)));if(b.Ta&&0<b.Ta.length){const m=
self.C3_ProjectScriptsStatus;try{if(await Promise.all(b.Ta.map(q=>L(q[1]))),Object.values(m).some(q=>!q)){self.setTimeout(()=>this.Ha(m),100);return}}catch(q){console.error("[Preview] Error loading project scripts: ",q);self.setTimeout(()=>this.Ha(m),100);return}}"preview"===this.g&&"object"!==typeof self.ic.jc?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):
(b=Object.assign(this.Ba(b),{isInWorker:!1,messagePort:e,canvas:this.c,runOnStartupFunctions:k}),this.ma=self.C3_CreateRuntime(b),await self.C3_InitRuntime(this.ma,b))}Ha(b){b=`Failed to load project script '${Object.entries(b).filter(e=>!e[1]).map(e=>e[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+b);alert(b)}async ub(){const b=await this.D.za();return{outputPort:b,transferables:[b]}}mb(){if(this.s)throw Error("not available in worker mode");return this.ma}Z(b,
e,f,m,q){this.F.postMessage({type:"event",component:b,handler:e,dispatchOpts:m||null,data:f,responseId:null},this.Qa?void 0:q)}$a(b,e){const f=c++,m=new Promise((q,w)=>{a.set(f,{resolve:q,reject:w})});this.F.postMessage({type:"event",component:b,handler:"js-invoke-function",dispatchOpts:null,data:e,responseId:f},void 0);return m}["_OnMessageFromRuntime"](b){const e=b.type;if("event"===e)return this.zb(b);if("result"===e)this.Ib(b);else if("runtime-ready"===e)this.Jb();else if("alert"===e)alert(b.message);
else throw Error(`unknown message '${e}'`);}zb(b){const e=b.component,f=b.handler,m=b.data,q=b.responseId;if(b=z.get(e))if(b=b.get(f)){var w=null;try{w=b(m)}catch(t){console.error(`Exception in '${e}' handler '${f}':`,t);null!==q&&this.P(q,!1,""+t);return}if(null===q)return w;w&&w.then?w.then(t=>this.P(q,!0,t)).catch(t=>{console.error(`Rejection from '${e}' handler '${f}':`,t);this.P(q,!1,""+t)}):this.P(q,!0,w)}else console.warn(`[DOM] No handler '${f}' for component '${e}'`);else console.warn(`[DOM] No event handlers for component '${e}'`)}P(b,
e,f){let m;f&&f.transferables&&(m=f.transferables);this.F.postMessage({type:"result",responseId:b,isOk:e,result:f},m)}Ib(b){const e=b.responseId,f=b.isOk;b=b.result;const m=a.get(e);f?m.resolve(b):m.reject(b);a.delete(e)}a(b,e,f){let m=z.get(b);m||(m=new Map,z.set(b,m));if(m.has(e))throw Error(`[DOM] Component '${b}' already has handler '${e}'`);m.set(e,f)}static J(b){if(B.includes(b))throw Error("DOM handler already added");B.push(b)}Aa(){for(const b of this.T)if("runtime"===b.B){this.pa=b;return}throw Error("cannot find runtime DOM handler");
}Cb(b){this.Z("debugger","message",b)}Jb(){for(const b of this.T)b.ta()}static Y(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Ia(){-1===this.l&&this.Pa.length&&(this.l=requestAnimationFrame(this.Wb))}fb(){-1!==this.l&&(cancelAnimationFrame(this.l),this.l=-1)}Fb(){this.l=-1;for(const b of this.Pa)b();this.Ia()}ia(){this.pa.ia()}async tb(b){const e=b.filename;switch(b.as){case "text":return await this.Ua(e);case "buffer":return await this.va(e);
default:throw Error("unsupported type");}}ua(b){const e=window.cordova.file.applicationDirectory+"www/"+b.toLowerCase();return new Promise((f,m)=>{window.resolveLocalFileSystemURL(e,q=>{q.file(f,m)},m)})}async Ua(b){b=await this.ua(b);return await J(b)}aa(){if(p.length&&!(8<=r)){r++;var b=p.shift();this.ib(b.filename,b.dc,b.Zb)}}va(b){return new Promise((e,f)=>{p.push({filename:b,dc:m=>{r--;this.aa();e(m)},Zb:m=>{r--;this.aa();f(m)}});this.aa()})}async ib(b,e,f){try{const m=await this.ua(b),q=await I(m);
e(q)}catch(m){f(m)}}async hb(){const b=[];for(const [e,f]of Object.entries(this.i))b.push(this.gb(e,f));await Promise.all(b)}async gb(b,e){if("object"===typeof e)this.i[b]=new Blob([e.str],{type:e.type}),this.V[b]=e.str;else{let f=await this.lb(e);f||(f=this.jb(e));this.i[b]=f}}async lb(b){try{return await (await fetch(b)).blob()}catch(e){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
e),null}}jb(b){b=this.Nb(b);return this.eb(b.data,b.ac)}Nb(b){var e=b.indexOf(",");if(0>e)throw new URIError("expected comma in data: uri");var f=b.substring(e+1);e=b.substring(5,e).split(";");b=e[0]||"";const m=e[2];f="base64"===e[1]||"base64"===m?atob(f):decodeURIComponent(f);return{ac:b,data:f}}eb(b,e){var f=b.length;let m=f>>2,q=new Uint8Array(f),w=new Uint32Array(q.buffer,0,m),t,y;for(y=t=0;t<m;++t)w[t]=b.charCodeAt(y++)|b.charCodeAt(y++)<<8|b.charCodeAt(y++)<<16|b.charCodeAt(y++)<<24;for(f&=
3;f--;)q[y]=b.charCodeAt(y),++y;return new Blob([q],{type:e})}Pb(){let b=null;const e=new Promise(q=>b=q),f=new ArrayBuffer(1),m=new MessageChannel;m.port2.onmessage=q=>{q.data&&q.data.arrayBuffer||(this.Qa=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));b()};m.port1.postMessage({arrayBuffer:f},[f]);return e}}}"use strict";
{var N=function(){const a=document.activeElement;if(!a)return!1;const c=a.tagName.toLowerCase(),k=new Set("email number password search tel text url".split(" "));return"textarea"===c?!0:"input"===c?k.has(a.type.toLowerCase()||"text"):M(a)},O=function(){try{return window.parent&&window.parent.document.hasFocus()}catch(a){return!1}},P=function(a){(a.metaKey||a.ctrlKey)&&a.preventDefault()},Q=function(a){B.has(a.target.tagName.toLowerCase())&&a.preventDefault()},M=function(a){do{if(a.parentNode&&a.hasAttribute("contenteditable"))return!0;
a=a.parentNode}while(a);return!1},T=async function(a,c,k){if(!/firefox/i.test(navigator.userAgent))return await R(a);var l=await S(a);l=(new DOMParser).parseFromString(l,"image/svg+xml");const n=l.documentElement;if(n.hasAttribute("width")&&n.hasAttribute("height")){const b=n.getAttribute("width"),e=n.getAttribute("height");if(!b.includes("%")&&!e.includes("%"))return await R(a)}n.setAttribute("width",c+"px");n.setAttribute("height",k+"px");l=(new XMLSerializer).serializeToString(l);a=new Blob([l],
{type:"image/svg+xml"});return await R(a)},S=function(a){return new Promise((c,k)=>{let l=new FileReader;l.onload=n=>c(n.target.result);l.onerror=n=>k(n);l.readAsText(a)})},R=async function(a){a=URL.createObjectURL(a);try{return await U(a)}finally{URL.revokeObjectURL(a)}},U=function(a){return new Promise((c,k)=>{const l=new Image;l.onload=()=>c(l);l.onerror=n=>k(n);l.src=a})},V=function(a){return new Promise((c,k)=>{const l=document.createElement("link");l.onload=()=>c(l);l.onerror=n=>k(n);l.rel=
"stylesheet";l.href=a;document.head.appendChild(l)})},W=function(a){return a.sourceCapabilities&&a.sourceCapabilities.firesTouchEvents||a.originalEvent&&a.originalEvent.sourceCapabilities&&a.originalEvent.sourceCapabilities.firesTouchEvents};const h=self.v,g=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},p={dispatchUserScriptEvent:!0},r={dispatchRuntimeEvent:!0},B=new Set(["canvas","body","html"]);self.C3_GetSvgImageSize=async function(a){a=
await R(a);if(0<a.width&&0<a.height)return[a.width,a.height];{a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.visibility="hidden";document.body.appendChild(a);const c=a.getBoundingClientRect();document.body.removeChild(a);return[c.width,c.height]}};self.C3_RasterSvgImageBlob=async function(a,c,k,l,n){a=await T(a,c,k);const b=document.createElement("canvas");b.width=l;b.height=n;b.getContext("2d").drawImage(a,0,0,c,k);return b};let z=!1;document.addEventListener("pause",()=>
z=!0);document.addEventListener("resume",()=>z=!1);h.J(class extends self.K{constructor(a){super(a,"runtime");this.Na=!0;this.m=-1;this.ra="any";this.Ja=this.Ka=!1;this.la=this.H=this.j=null;a.a("canvas","update-size",l=>this.Lb(l));a.a("runtime","invoke-download",l=>this.Bb(l));a.a("runtime","raster-svg-image",l=>this.Gb(l));a.a("runtime","get-svg-image-size",l=>this.Ab(l));a.a("runtime","set-target-orientation",l=>this.Kb(l));a.a("runtime","register-sw",()=>this.Hb());a.a("runtime","post-to-debugger",
l=>this.Fa(l));a.a("runtime","go-to-script",l=>this.Fa(l));a.a("runtime","before-start-ticking",()=>this.sb());a.a("runtime","debug-highlight",l=>this.vb(l));a.a("runtime","enable-device-orientation",()=>this.cb());a.a("runtime","enable-device-motion",()=>this.bb());a.a("runtime","add-stylesheet",l=>this.qb(l));a.a("runtime","alert",l=>this.rb(l));const c=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",l=>{const n=l.target;c.has(n.tagName.toLowerCase())||M(n)||l.preventDefault()});
const k=a.c;window.addEventListener("selectstart",Q);window.addEventListener("gesturehold",Q);k.addEventListener("selectstart",Q);k.addEventListener("gesturehold",Q);window.addEventListener("touchstart",Q,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",Q,{passive:!1}),k.addEventListener("pointerdown",Q)):k.addEventListener("touchstart",Q);this.G=0;window.addEventListener("mousedown",l=>{1===l.button&&l.preventDefault()});window.addEventListener("mousewheel",
P,{passive:!1});window.addEventListener("wheel",P,{passive:!1});window.addEventListener("resize",()=>this.Mb());a.L()&&window.addEventListener("focusout",()=>{N()||(document.scrollingElement.scrollTop=0)});this.na=new Set;this.Vb=new WeakSet;this.Tb=!1}sb(){"cordova"===this.h.g?(document.addEventListener("pause",()=>this.ha(!0)),document.addEventListener("resume",()=>this.ha(!1))):document.addEventListener("visibilitychange",()=>this.ha(document.hidden));return{isSuspended:!(!document.hidden&&!z)}}ta(){window.addEventListener("focus",
()=>this.R("window-focus"));window.addEventListener("blur",()=>{this.R("window-blur",{parentHasFocus:O()});this.G=0});window.addEventListener("fullscreenchange",()=>this.da());window.addEventListener("webkitfullscreenchange",()=>this.da());window.addEventListener("mozfullscreenchange",()=>this.da());window.addEventListener("fullscreenerror",c=>this.ea(c));window.addEventListener("webkitfullscreenerror",c=>this.ea(c));window.addEventListener("mozfullscreenerror",c=>this.ea(c));window.addEventListener("keydown",
c=>this.Ea("keydown",c));window.addEventListener("keyup",c=>this.Ea("keyup",c));window.addEventListener("dblclick",c=>this.fa("dblclick",c,d));window.addEventListener("wheel",c=>this.Db(c));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",c=>{this.ca(c);this.A("pointerdown",c)}),this.h.s&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.H=new self.ab(()=>this.kb(),5),this.H.Ma=!0,window.addEventListener("pointerrawupdate",c=>this.Eb(c))):window.addEventListener("pointermove",
c=>this.A("pointermove",c)),window.addEventListener("pointerup",c=>this.A("pointerup",c)),window.addEventListener("pointercancel",c=>this.A("pointercancel",c))):(window.addEventListener("mousedown",c=>{this.ca(c);this.ga("pointerdown",c)}),window.addEventListener("mousemove",c=>this.ga("pointermove",c)),window.addEventListener("mouseup",c=>this.ga("pointerup",c)),window.addEventListener("touchstart",c=>{this.ca(c);this.O("pointerdown",c)}),window.addEventListener("touchmove",c=>this.O("pointermove",
c)),window.addEventListener("touchend",c=>this.O("pointerup",c)),window.addEventListener("touchcancel",c=>this.O("pointercancel",c)));const a=()=>this.ia();window.addEventListener("pointerup",a,!0);window.addEventListener("touchend",a,!0);window.addEventListener("click",a,!0);window.addEventListener("keydown",a,!0);window.addEventListener("gamepadconnected",a,!0)}R(a,c){u(this,a,c||null,r)}N(){return Math.max(window.innerWidth,1)}M(){return Math.max(window.innerHeight,1)}Mb(){const a=this.N(),c=this.M();
this.R("window-resize",{innerWidth:a,innerHeight:c,devicePixelRatio:window.devicePixelRatio});this.h.L()&&(-1!==this.m&&clearTimeout(this.m),this.Ga(a,c,0))}Ob(a,c,k){-1!==this.m&&clearTimeout(this.m);this.m=setTimeout(()=>this.Ga(a,c,k),48)}Ga(a,c,k){const l=this.N(),n=this.M();this.m=-1;l!=a||n!=c?this.R("window-resize",{innerWidth:l,innerHeight:n,devicePixelRatio:window.devicePixelRatio}):10>k&&this.Ob(l,n,k+1)}Kb(a){this.ra=a.targetOrientation}Qb(){const a=this.ra;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(a).catch(c=>
console.warn("[Construct 3] Failed to lock orientation: ",c));else try{let c=!1;screen.lockOrientation?c=screen.lockOrientation(a):screen.webkitLockOrientation?c=screen.webkitLockOrientation(a):screen.mozLockOrientation?c=screen.mozLockOrientation(a):screen.msLockOrientation&&(c=screen.msLockOrientation(a));c||console.warn("[Construct 3] Failed to lock orientation")}catch(c){console.warn("[Construct 3] Failed to lock orientation: ",c)}}da(){const a=h.Y();a&&"any"!==this.ra&&this.Qb();u(this,"fullscreenchange",
{isFullscreen:a,innerWidth:this.N(),innerHeight:this.M()})}ea(a){console.warn("[Construct 3] Fullscreen request failed: ",a);u(this,"fullscreenerror",{isFullscreen:h.Y(),innerWidth:this.N(),innerHeight:this.M()})}ha(a){a?this.h.fb():this.h.Ia();u(this,"visibilitychange",{hidden:a})}Ea(a,c){"Backspace"===c.key&&Q(c);const k=g.get(c.code)||c.code;x(this,a,{code:k,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},d)}Db(a){u(this,
"wheel",{clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},d)}fa(a,c,k){W(c)||x(this,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,timeStamp:c.timeStamp},k)}ga(a,c){if(!W(c)){var k=this.G;"pointerdown"===a&&0!==k?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");x(this,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,
lastButtons:k,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},d);this.G=c.buttons;this.fa(c.type,c,p)}}A(a,c){if(this.H&&"pointermove"!==a){var k=this.H;k.C||(-1!==k.o&&(self.clearTimeout(k.o),k.o=-1),k.U=Date.now())}k=0;"mouse"===c.pointerType&&(k=this.G);x(this,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:k,clientX:c.clientX,clientY:c.clientY,
pageX:c.pageX,pageY:c.pageY,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},d);"mouse"===c.pointerType&&(k="mousemove","pointerdown"===a?k="mousedown":"pointerup"===a&&(k="pointerup"),this.fa(k,c,p),this.G=c.buttons)}Eb(a){this.la=a;a=this.H;if(-1===a.o){var c=Date.now(),k=c-a.U,l=a.Sb;k>=l&&a.Ma?(a.U=c,a.C=!0,a.La(),a.C=!1):a.o=self.setTimeout(a.Xb,Math.max(l-k,4))}}kb(){this.A("pointermove",
this.la);this.la=null}O(a,c){for(let k=0,l=c.changedTouches.length;k<l;++k){const n=c.changedTouches[k];x(this,a,{pointerId:n.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:n.clientX,clientY:n.clientY,pageX:n.pageX,pageY:n.pageY,width:2*(n.radiusX||n.webkitRadiusX||0),height:2*(n.radiusY||n.webkitRadiusY||0),pressure:n.force||n.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:n.rotationAngle||0,timeStamp:c.timeStamp},d)}}ca(a){window!==window.top&&window.focus();
this.Da(a.target)&&document.activeElement&&!this.Da(document.activeElement)&&document.activeElement.blur()}Da(a){return!a||a===document||a===window||a===document.body||"canvas"===a.tagName.toLowerCase()}cb(){this.Ka||(this.Ka=!0,window.addEventListener("deviceorientation",a=>this.xb(a)),window.addEventListener("deviceorientationabsolute",a=>this.yb(a)))}bb(){this.Ja||(this.Ja=!0,window.addEventListener("devicemotion",a=>this.wb(a)))}xb(a){u(this,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||
0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},d)}yb(a){u(this,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},d)}wb(a){let c=null;var k=a.acceleration;k&&(c={x:k.x||0,y:k.y||0,z:k.z||0});k=null;var l=a.accelerationIncludingGravity;l&&(k={x:l.x||0,y:l.y||0,z:l.z||0});l=null;const n=a.rotationRate;n&&(l={alpha:n.alpha||0,beta:n.beta||
0,gamma:n.gamma||0});u(this,"devicemotion",{acceleration:c,accelerationIncludingGravity:k,rotationRate:l,interval:a.interval,timeStamp:a.timeStamp},d)}Lb(a){const c=this.h,k=c.c;k.style.width=a.styleWidth+"px";k.style.height=a.styleHeight+"px";k.style.marginLeft=a.marginLeft+"px";k.style.marginTop=a.marginTop+"px";c.ya();this.Na&&(k.style.display="",this.Na=!1)}Bb(a){const c=a.url;a=a.filename;const k=document.createElement("a"),l=document.body;k.textContent=a;k.href=c;k.download=a;l.appendChild(k);
k.click();l.removeChild(k)}async Gb(a){var c=a.imageBitmapOpts;a=await self.C3_RasterSvgImageBlob(a.blob,a.imageWidth,a.imageHeight,a.surfaceWidth,a.surfaceHeight);c=c?await createImageBitmap(a,c):await createImageBitmap(a);return{imageBitmap:c,transferables:[c]}}async Ab(a){return await self.C3_GetSvgImageSize(a.blob)}async qb(a){await V(a.url)}ia(){var a=[...this.na];this.na.clear();if(!this.Tb)for(const c of a)(a=c.play())&&a.catch(()=>{this.Vb.has(c)||this.na.add(c)})}vb(a){if(a.show){this.j||
(this.j=document.createElement("div"),this.j.id="inspectOutline",document.body.appendChild(this.j));var c=this.j;c.style.display="";c.style.left=a.left-1+"px";c.style.top=a.top-1+"px";c.style.width=a.width+2+"px";c.style.height=a.height+2+"px";c.textContent=a.name}else this.j&&(this.j.style.display="none")}Hb(){window.C3_RegisterSW&&window.C3_RegisterSW()}Fa(a){window.c3_postToMessagePort&&(a.from="runtime",window.c3_postToMessagePort(a))}pb(a,c){return this.h.$a(this.B,{name:a,params:c})}rb(a){alert(a.message)}})}"use strict";
{const h=document.currentScript.src;self.Za=class{constructor(g){this.W=g;this.b=h?h.substr(0,h.lastIndexOf("/")+1):g.b;this.Ub=Math.min(navigator.hardwareConcurrency||2,16);this.ja=null;this.Oa=[];this.oa=this.ka=null}async Ya(){if(this.Rb)throw Error("already initialised");this.Rb=!0;var g=this.W.ba("dispatchworker.js");this.ja=await this.W.X(g,this.b,{name:"DispatchWorker"});g=new MessageChannel;this.ka=g.port1;this.ja.postMessage({type:"_init","in-port":g.port2},[g.port2]);this.oa=await this.za()}async za(){const g=
this.Oa.length;var d=this.W.ba("jobworker.js");d=await this.W.X(d,this.b,{name:"JobWorker"+g});const p=new MessageChannel,r=new MessageChannel;this.ja.postMessage({type:"_addJobWorker",port:p.port1},[p.port1]);d.postMessage({type:"init",number:g,"dispatch-port":p.port2,"output-port":r.port2},[p.port2,r.port2]);this.Oa.push(d);return r.port1}Wa(){return{inputPort:this.ka,outputPort:this.oa,maxNumWorkers:this.Ub}}Xa(){return[this.ka,this.oa]}}}"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.v({ec:"undefined"!==typeof OffscreenCanvas,fc:"workermain.js",u:["scripts/c3runtime.js"],bc:"scripts/",sa:[],Sa:"html5"}));"use strict";async function X(h,g){g=g.type;let d=!0;0===g?d=await aa():1===g&&(d=await ba());u(h,"permission-result",{type:g,result:d})}
async function aa(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(h){return console.warn("[Touch] Failed to request orientation permission: ",h),!1}}
async function ba(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(h){return console.warn("[Touch] Failed to request motion permission: ",h),!1}}self.v.J(class extends self.K{constructor(h){super(h,"touch");A(this,"request-permission",g=>X(this,g))}});"use strict";self.v.J(class extends self.K{constructor(h){super(h,"mouse");A(this,"cursor",g=>{document.documentElement.style.cursor=g})}});
"use strict";function Y(h){13!==h.which&&27!==h.which&&h.stopPropagation()}function Z(h){h.stopPropagation()}
self.v.J(class extends self.Va{constructor(h){super(h,"text-input");F(this,"scroll-to-bottom",g=>{g.scrollTop=g.scrollHeight})}wa(h,g){let d;const p=g.type;"textarea"===p?(d=document.createElement("textarea"),d.style.resize="none"):(d=document.createElement("input"),d.type=p);d.style.position="absolute";d.autocomplete="off";d.addEventListener("touchstart",Z);d.addEventListener("touchmove",Z);d.addEventListener("touchend",Z);d.addEventListener("mousedown",Z);d.addEventListener("mouseup",Z);d.addEventListener("keydown",
Y);d.addEventListener("keyup",Y);d.addEventListener("click",r=>{r.stopPropagation();G(this,"click",h)});d.addEventListener("dblclick",r=>{r.stopPropagation();G(this,"dblclick",h)});d.addEventListener("input",()=>E(this,"change",h,{text:d.value}));g.id&&(d.id=g.id);this.$(d,g);return d}$(h,g){h.value=g.text;h.placeholder=g.placeholder;h.title=g.title;h.disabled=!g.isEnabled;h.readOnly=g.isReadOnly;h.spellcheck=g.spellCheck;g=g.maxLength;0>g?h.removeAttribute("maxlength"):h.setAttribute("maxlength",
g)}});